// scripts/expand-economy.ts
// Phase 3: Economy 话题 — econ-001 ~ econ-100（100 个新词块）
// 频次分布: 超高(90-99)×40 + 高(70-89)×39 + 中(50-69)×21

import type { Chunk } from "../types/chunk";

export const ECONOMY_CHUNKS: Chunk[] = [
  // ═══ 超高頻 90-99 (40 个) ═══
  {
    id: "econ-001", word: "economic growth", translation: "经济增长", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 99, topics: ["economy"], modules: ["writing", "reading"],
    collocations: ["sustain economic growth", "drive economic growth", "rapid economic growth", "slowdown in economic growth"],
    example_sentence: "Sustained economic growth has lifted millions out of poverty in developing nations over the past two decades.",
    synonyms: ["economic expansion", "GDP growth", "economic development"],
    common_mistakes: ["economic growth 不等于 economic development; 后者包含生活质量等非经济指标"],
    ielts_context: "Writing Task 2: development / globalization; Reading: economics",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk ɡrəʊθ/",
    collocations_cn: ["维持经济增长", "推动经济增长", "快速经济增长", "经济增长放缓"],
    example_sentence_cn: "过去二十年，持续的经济增长使发展中国家数百万人摆脱了贫困。",
    synonyms_cn: ["经济扩张", "GDP增长", "经济发展"],
  },
  {
    id: "econ-002", word: "inflation rate", translation: "通货膨胀率", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 97, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["rising inflation rate", "control the inflation rate", "annual inflation rate", "high inflation rate"],
    example_sentence: "Central banks often raise interest rates to combat a rising inflation rate and stabilize the economy.",
    synonyms: ["price increase rate", "CPI growth", "cost-of-living increase"],
    common_mistakes: ["inflation rate 是比率; 不是绝对价格水平"],
    ielts_context: "Reading: economic reports; Listening Section 4: economics lectures",
    pronunciation: "/ɪnˈfleɪ.ʃən reɪt/",
    collocations_cn: ["上升的通货膨胀率", "控制通货膨胀率", "年通货膨胀率", "高通货膨胀率"],
    example_sentence_cn: "中央银行通常通过加息来应对上升的通货膨胀率并稳定经济。",
    synonyms_cn: ["物价上涨率", "CPI增长", "生活成本涨幅"],
  },
  {
    id: "econ-003", word: "stock market", translation: "股票市场", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 96, topics: ["economy"], modules: ["reading", "speaking"],
    collocations: ["invest in the stock market", "stock market crash", "stock market index", "volatile stock market"],
    example_sentence: "The stock market reflects investor confidence and serves as a barometer for the overall health of the economy.",
    synonyms: ["equity market", "share market", "securities exchange"],
    common_mistakes: ["stock market 交易股权; bond market 交易债券; 两者不同"],
    ielts_context: "Reading: business / finance; Speaking Part 3: investment / savings",
    pronunciation: "/stɒk ˈmɑː.kɪt/",
    collocations_cn: ["投资股票市场", "股市崩盘", "股票市场指数", "波动剧烈的股市"],
    example_sentence_cn: "股票市场反映了投资者信心，是经济整体健康状况的晴雨表。",
    synonyms_cn: ["股权市场", "股票交易市场", "证券交易所"],
  },
  {
    id: "econ-004", word: "supply chain", translation: "供应链", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 95, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["global supply chain", "disrupt the supply chain", "supply chain management", "streamline the supply chain"],
    example_sentence: "The pandemic exposed serious vulnerabilities in global supply chains, prompting many companies to diversify their suppliers.",
    synonyms: ["logistics network", "distribution chain", "procurement pipeline"],
    common_mistakes: ["supply chain 涵盖从原材料到消费者的全过程; 不仅限于物流"],
    ielts_context: "Reading: business / international trade; Writing Task 2: globalization",
    pronunciation: "/səˈplaɪ tʃeɪn/",
    collocations_cn: ["全球供应链", "中断供应链", "供应链管理", "优化供应链"],
    example_sentence_cn: "疫情暴露了全球供应链中的严重脆弱性，促使许多公司多元化其供应商。",
    synonyms_cn: ["物流网络", "分销链", "采购管道"],
  },
  {
    id: "econ-005", word: "consumer spending", translation: "消费者支出", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 95, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["boost consumer spending", "decline in consumer spending", "consumer spending habits", "drive consumer spending"],
    example_sentence: "Consumer spending accounts for approximately two-thirds of GDP in many developed economies.",
    synonyms: ["household expenditure", "personal consumption", "retail spending"],
    common_mistakes: ["consumer spending 是个人/家庭消费; government spending 是政府支出"],
    ielts_context: "Reading: economic indicators; Writing Task 2: consumer behavior",
    pronunciation: "/kənˈsjuː.mə ˈspen.dɪŋ/",
    collocations_cn: ["提振消费者支出", "消费者支出下降", "消费者支出习惯", "推动消费者支出"],
    example_sentence_cn: "在许多发达经济体中，消费者支出约占GDP的三分之二。",
    synonyms_cn: ["家庭支出", "个人消费", "零售支出"],
  },
  {
    id: "econ-006", word: "monetary policy", translation: "货币政策", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 94, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["tighten monetary policy", "loose monetary policy", "implement monetary policy", "monetary policy committee"],
    example_sentence: "The central bank's monetary policy decisions directly influence interest rates, inflation, and overall economic activity.",
    synonyms: ["central bank strategy", "interest rate policy", "money supply regulation"],
    common_mistakes: ["monetary policy 由央行制定（控制货币供给/利率）; fiscal policy 由政府制定（税收/支出）"],
    ielts_context: "Reading: financial news / economics; Listening Section 4: economics",
    pronunciation: "/ˈmʌn.ɪ.tər.i ˈpɒl.ə.si/",
    collocations_cn: ["收紧货币政策", "宽松货币政策", "实施货币政策", "货币政策委员会"],
    example_sentence_cn: "央行的货币政策决策直接影响利率、通胀和整体经济活动。",
    synonyms_cn: ["央行策略", "利率政策", "货币供给调控"],
  },
  {
    id: "econ-007", word: "fiscal policy", translation: "财政政策", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 93, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["expansionary fiscal policy", "government fiscal policy", "fiscal policy measures", "countercyclical fiscal policy"],
    example_sentence: "Governments use fiscal policy, including taxation and public spending, to influence economic growth and stabilize the business cycle.",
    synonyms: ["government budgetary policy", "public finance strategy", "tax-and-spend policy"],
    common_mistakes: ["fiscal policy 不是金融政策; 是财政政策（政府税收和支出）"],
    ielts_context: "Reading: economics / government; Writing Task 2: government spending",
    pronunciation: "/ˈfɪs.kəl ˈpɒl.ə.si/",
    collocations_cn: ["扩张性财政政策", "政府财政政策", "财政政策措施", "逆周期财政政策"],
    example_sentence_cn: "政府使用财政政策，包括税收和公共支出，来影响经济增长并稳定商业周期。",
    synonyms_cn: ["政府预算政策", "公共财政策略", "税收与支出政策"],
  },
  {
    id: "econ-008", word: "foreign investment", translation: "外国投资", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 93, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["attract foreign investment", "foreign direct investment", "foreign investment inflow", "restrict foreign investment"],
    example_sentence: "Many developing countries offer tax incentives to attract foreign investment and stimulate domestic job creation.",
    synonyms: ["international capital", "overseas investment", "cross-border investment"],
    common_mistakes: ["FDI (Foreign Direct Investment) 是长期控股; FPI (Foreign Portfolio Investment) 是证券投资"],
    ielts_context: "Reading: international economics; Writing Task 2: globalization / development",
    pronunciation: "/ˈfɒr.ɪn ɪnˈvest.mənt/",
    collocations_cn: ["吸引外国投资", "外国直接投资", "外国投资流入", "限制外国投资"],
    example_sentence_cn: "许多发展中国家提供税收优惠来吸引外国投资并刺激国内就业创造。",
    synonyms_cn: ["国际资本", "海外投资", "跨境投资"],
  },
  {
    id: "econ-009", word: "exchange rate", translation: "汇率", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 94, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["fluctuating exchange rate", "fixed exchange rate", "exchange rate mechanism", "exchange rate volatility"],
    example_sentence: "A weaker exchange rate can boost exports by making domestically produced goods cheaper for foreign buyers.",
    synonyms: ["currency rate", "forex rate", "foreign exchange quotation"],
    common_mistakes: ["exchange rate 是两种货币之间的兑换比率; 不是单一货币的价值"],
    ielts_context: "Reading: international trade / finance; Listening Section 3: business discussions",
    pronunciation: "/ɪksˈtʃeɪndʒ reɪt/",
    collocations_cn: ["波动的汇率", "固定汇率", "汇率机制", "汇率波动性"],
    example_sentence_cn: "较弱的汇率可以通过使国内生产的商品对外国买家更便宜来促进出口。",
    synonyms_cn: ["货币汇率", "外汇汇率", "外汇牌价"],
  },
  {
    id: "econ-010", word: "market economy", translation: "市场经济", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["transition to a market economy", "free market economy", "market economy principles", "emerging market economy"],
    example_sentence: "China's transition from a planned economy to a market economy has been one of the most significant economic transformations in modern history.",
    synonyms: ["free enterprise system", "capitalist economy", "laissez-faire system"],
    common_mistakes: ["market economy 由供需决定价格; planned economy 由政府决定"],
    ielts_context: "Reading: economic systems; Writing Task 2: government vs market",
    pronunciation: "/ˈmɑː.kɪt ɪˈkɒn.ə.mi/",
    collocations_cn: ["向市场经济转型", "自由市场经济", "市场经济原则", "新兴市场经济"],
    example_sentence_cn: "中国从计划经济向市场经济的转型是现代历史上最重大的经济变革之一。",
    synonyms_cn: ["自由企业制度", "资本主义经济", "自由放任体制"],
  },
  {
    id: "econ-011", word: "unemployment rate", translation: "失业率", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 96, topics: ["economy"], modules: ["writing", "reading"],
    collocations: ["rising unemployment rate", "reduce the unemployment rate", "youth unemployment rate", "official unemployment rate"],
    example_sentence: "The unemployment rate is a key economic indicator reflecting the percentage of the labor force that is actively seeking work but unable to find it.",
    synonyms: ["jobless rate", "employment gap", "labor underutilization rate"],
    common_mistakes: ["unemployment rate 只计算正在找工作的人; 不包括已放弃找工的人"],
    ielts_context: "Writing Task 1: line graph / bar chart; Reading: economic indicators",
    pronunciation: "/ˌʌn.ɪmˈplɔɪ.mənt reɪt/",
    collocations_cn: ["上升的失业率", "降低失业率", "青年失业率", "官方失业率"],
    example_sentence_cn: "失业率是一个关键经济指标，反映劳动力中积极寻找工作但无法找到的人口百分比。",
    synonyms_cn: ["无业率", "就业缺口", "劳动力未充分利用率"],
  },
  {
    id: "econ-012", word: "income inequality", translation: "收入不平等", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 93, topics: ["economy"], modules: ["writing", "reading"],
    collocations: ["growing income inequality", "address income inequality", "reduce income inequality", "income inequality gap"],
    example_sentence: "Rising income inequality has become a pressing concern for policymakers worldwide, as it threatens social cohesion and economic stability.",
    synonyms: ["wealth disparity", "income gap", "economic inequality"],
    common_mistakes: ["income inequality 是收入差距; wealth inequality 是财富差距（包括资产）; 两者不同"],
    ielts_context: "Writing Task 2: social issues / economy; Reading: sociology / economics",
    pronunciation: "/ˈɪn.kʌm ˌɪn.ɪˈkwɒl.ə.ti/",
    collocations_cn: ["日益加剧的收入不平等", "解决收入不平等", "减少收入不平等", "收入不平等差距"],
    example_sentence_cn: "日益加剧的收入不平等已成为全球政策制定者的紧迫关切，因为它威胁到社会凝聚力和经济稳定。",
    synonyms_cn: ["财富差距", "收入差距", "经济不平等"],
  },
  {
    id: "econ-013", word: "tax revenue", translation: "税收收入", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 92, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["generate tax revenue", "loss of tax revenue", "increase tax revenue", "government tax revenue"],
    example_sentence: "Tax revenue is the primary source of funding for public services such as education, healthcare, and infrastructure development.",
    synonyms: ["fiscal income", "government tax receipts", "public revenue"],
    common_mistakes: ["tax revenue 是政府收到的税款总额; tax rate 是税率百分比"],
    ielts_context: "Reading: public finance / government reports; Writing Task 2: taxation",
    pronunciation: "/tæks ˈrev.ən.juː/",
    collocations_cn: ["产生税收收入", "税收收入损失", "增加税收收入", "政府税收收入"],
    example_sentence_cn: "税收收入是教育、医疗和基础设施发展等公共服务的主要资金来源。",
    synonyms_cn: ["财政收入", "政府税收", "公共收入"],
  },
  {
    id: "econ-014", word: "global trade", translation: "全球贸易", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 92, topics: ["economy"], modules: ["writing", "reading"],
    collocations: ["facilitate global trade", "global trade agreement", "expansion of global trade", "global trade volume"],
    example_sentence: "The reduction of trade barriers has led to an unprecedented expansion of global trade over the past half-century.",
    synonyms: ["international commerce", "world trade", "cross-border exchange"],
    common_mistakes: ["global trade 涉及商品和服务跨境流动; global supply chain 关注生产的全球分工"],
    ielts_context: "Writing Task 2: globalization / international cooperation; Reading: trade / economics",
    pronunciation: "/ˈɡləʊ.bəl treɪd/",
    collocations_cn: ["促进全球贸易", "全球贸易协议", "全球贸易扩张", "全球贸易额"],
    example_sentence_cn: "贸易壁垒的减少导致了过去半个世纪全球贸易前所未有的扩张。",
    synonyms_cn: ["国际商业", "世界贸易", "跨境交流"],
  },
  {
    id: "econ-015", word: "interest rate", translation: "利率", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 98, topics: ["economy"], modules: ["listening", "reading"],
    collocations: ["raise interest rates", "cut interest rates", "low interest rate environment", "benchmark interest rate"],
    example_sentence: "When the central bank raises interest rates, borrowing becomes more expensive, which typically slows down consumer spending and inflation.",
    synonyms: ["base rate", "lending rate", "bank rate"],
    common_mistakes: ["interest rate 可以是借款利率或存款利率; 注意上下文区分"],
    ielts_context: "Listening Section 3/4: economics / finance; Reading: financial news",
    pronunciation: "/ˈɪn.trəst reɪt/",
    collocations_cn: ["提高利率", "降低利率", "低利率环境", "基准利率"],
    example_sentence_cn: "当央行提高利率时，借贷变得更昂贵，这通常会减缓消费者支出和通胀。",
    synonyms_cn: ["基准利率", "贷款利率", "银行利率"],
  },
  {
    id: "econ-016", word: "economic recession", translation: "经济衰退", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 94, topics: ["economy"], modules: ["writing", "reading"],
    collocations: ["fall into economic recession", "recover from economic recession", "trigger an economic recession", "deep economic recession"],
    example_sentence: "An economic recession is typically defined as two consecutive quarters of negative GDP growth.",
    synonyms: ["economic downturn", "economic contraction", "economic slump"],
    common_mistakes: ["recession 是经济衰退; depression 是更严重和持久的萧条"],
    ielts_context: "Writing Task 2: economic cycles / government policy; Reading: economics",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk rɪˈseʃ.ən/",
    collocations_cn: ["陷入经济衰退", "从经济衰退中复苏", "触发经济衰退", "深度经济衰退"],
    example_sentence_cn: "经济衰退通常被定义为连续两个季度GDP负增长。",
    synonyms_cn: ["经济下行", "经济收缩", "经济萧条"],
  },
  {
    id: "econ-017", word: "purchasing power", translation: "购买力", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["erode purchasing power", "increase purchasing power", "loss of purchasing power", "consumer purchasing power"],
    example_sentence: "High inflation erodes the purchasing power of consumers, reducing their ability to afford goods and services.",
    synonyms: ["buying power", "spending capacity", "real income value"],
    common_mistakes: ["purchasing power 受通胀影响; 同样金额在高通胀时购买力降低"],
    ielts_context: "Reading: economic reports; Writing Task 1: data interpretation",
    pronunciation: "/ˈpɜː.tʃə.sɪŋ ˈpaʊ.ər/",
    collocations_cn: ["侵蚀购买力", "提高购买力", "购买力下降", "消费者购买力"],
    example_sentence_cn: "高通胀侵蚀了消费者的购买力，降低了他们购买商品和服务的能力。",
    synonyms_cn: ["购买能力", "支出能力", "实际收入价值"],
  },
  {
    id: "econ-018", word: "banking system", translation: "银行体系", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["regulate the banking system", "commercial banking system", "stability of the banking system", "shadow banking system"],
    example_sentence: "A stable banking system is essential for economic growth as it channels savings into productive investments.",
    synonyms: ["financial system", "banking sector", "financial institutions"],
    common_mistakes: ["banking system 包括央行、商业银行等; 不是单一的银行"],
    ielts_context: "Reading: finance / economics; Listening Section 4: finance lectures",
    pronunciation: "/ˈbæŋ.kɪŋ ˈsɪs.təm/",
    collocations_cn: ["监管银行体系", "商业银行体系", "银行体系的稳定性", "影子银行体系"],
    example_sentence_cn: "稳定的银行体系对经济增长至关重要，因为它将储蓄引导至生产性投资。",
    synonyms_cn: ["金融体系", "银行业", "金融机构"],
  },
  {
    id: "econ-019", word: "trade deficit", translation: "贸易逆差", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 92, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["reduce the trade deficit", "widening trade deficit", "run a trade deficit", "persistent trade deficit"],
    example_sentence: "A trade deficit occurs when a country's imports exceed its exports over a given period, leading to a net outflow of domestic currency.",
    synonyms: ["trade gap", "negative trade balance", "import surplus"],
    common_mistakes: ["trade deficit 不一定是坏事; 可能反映强劲的国内消费需求"],
    ielts_context: "Reading: international trade / economics; Writing Task 2: trade policy",
    pronunciation: "/treɪd ˈdef.ɪ.sɪt/",
    collocations_cn: ["减少贸易逆差", "扩大的贸易逆差", "持续贸易逆差", "长期贸易逆差"],
    example_sentence_cn: "当一国进口超过出口时就会出现贸易逆差，导致国内货币净流出。",
    synonyms_cn: ["贸易缺口", "负贸易差额", "进口盈余"],
  },
  {
    id: "econ-020", word: "venture capital", translation: "风险投资", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["economy"], modules: ["reading", "speaking"],
    collocations: ["raise venture capital", "venture capital firm", "venture capital funding", "venture capital investment"],
    example_sentence: "Venture capital plays a crucial role in funding innovative startups that may be too risky for traditional bank loans.",
    synonyms: ["risk capital", "startup funding", "equity investment"],
    common_mistakes: ["venture capital 投资早期高风险创业公司; private equity 通常投资成熟企业"],
    ielts_context: "Reading: business / finance; Speaking Part 3: entrepreneurship",
    pronunciation: "/ˈven.tʃə ˈkæp.ɪ.təl/",
    collocations_cn: ["筹集风险投资", "风险投资公司", "风险投资基金", "风险投资"],
    example_sentence_cn: "风险投资在为那些对传统银行贷款来说风险过高的创新创业公司提供资金方面发挥着关键作用。",
    synonyms_cn: ["风险资本", "创业资金", "股权投资"],
  },
  {
    id: "econ-021", word: "labor market", translation: "劳动力市场", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 93, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["tight labor market", "flexible labor market", "enter the labor market", "labor market conditions"],
    example_sentence: "A tight labor market with low unemployment gives workers greater bargaining power to demand higher wages and better conditions.",
    synonyms: ["job market", "employment market", "workforce market"],
    common_mistakes: ["labor market 关注劳动力的供给和需求; goods market 关注商品"],
    ielts_context: "Reading: labor economics / employment; Writing Task 2: employment / policy",
    pronunciation: "/ˈleɪ.bə ˈmɑː.kɪt/",
    collocations_cn: ["紧张的劳动力市场", "灵活的劳动力市场", "进入劳动力市场", "劳动力市场状况"],
    example_sentence_cn: "低失业率下的紧张劳动力市场赋予工人更大的议价能力来要求更高工资和更好条件。",
    synonyms_cn: ["就业市场", "人力市场", "用工市场"],
  },
  {
    id: "econ-022", word: "economic recovery", translation: "经济复苏", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 93, topics: ["economy"], modules: ["writing", "reading"],
    collocations: ["support economic recovery", "fragile economic recovery", "pace of economic recovery", "post-crisis economic recovery"],
    example_sentence: "Government stimulus packages played a vital role in supporting economic recovery following the global financial crisis.",
    synonyms: ["economic rebound", "economic revival", "economic resurgence"],
    common_mistakes: ["economic recovery 后经济回到衰退前水平; economic boom 是超常高速增长"],
    ielts_context: "Writing Task 2: government policy / crisis management; Reading: economic analysis",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk rɪˈkʌv.ər.i/",
    collocations_cn: ["支持经济复苏", "脆弱的经济复苏", "经济复苏步伐", "危机后经济复苏"],
    example_sentence_cn: "政府刺激计划在支持全球金融危机后的经济复苏中发挥了重要作用。",
    synonyms_cn: ["经济反弹", "经济复兴", "经济回升"],
  },
  {
    id: "econ-023", word: "trade agreement", translation: "贸易协定", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 91, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["negotiate a trade agreement", "free trade agreement", "bilateral trade agreement", "sign a trade agreement"],
    example_sentence: "Free trade agreements reduce tariffs and other barriers, facilitating the flow of goods and services between signatory nations.",
    synonyms: ["trade pact", "commercial treaty", "trade deal"],
    common_mistakes: ["FTA (Free Trade Agreement) 不是取消所有海关手续; 只降低/取消关税"],
    ielts_context: "Reading: international relations / economics; Writing Task 2: globalization",
    pronunciation: "/treɪd əˈɡriː.mənt/",
    collocations_cn: ["谈判贸易协定", "自由贸易协定", "双边贸易协定", "签署贸易协定"],
    example_sentence_cn: "自由贸易协定降低关税和其他壁垒，促进商品和服务在签署国之间的流动。",
    synonyms_cn: ["贸易条约", "商业条约", "贸易协议"],
  },
  {
    id: "econ-024", word: "government subsidy", translation: "政府补贴", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["economy"], modules: ["writing", "reading"],
    collocations: ["provide government subsidies", "agricultural government subsidy", "cut government subsidies", "government subsidy program"],
    example_sentence: "Government subsidies for renewable energy have accelerated the transition away from fossil fuels in many countries.",
    synonyms: ["state aid", "public subsidy", "government grant"],
    common_mistakes: ["subsidy 是政府给特定行业/企业的资金; welfare 是给个人的福利"],
    ielts_context: "Writing Task 2: government spending / environment; Reading: policy analysis",
    pronunciation: "/ˈɡʌv.ən.mənt ˈsʌb.sɪ.di/",
    collocations_cn: ["提供政府补贴", "农业政府补贴", "削减政府补贴", "政府补贴计划"],
    example_sentence_cn: "政府对可再生能源的补贴加速了许多国家从化石燃料的转型。",
    synonyms_cn: ["国家援助", "公共补贴", "政府拨款"],
  },
  {
    id: "econ-025", word: "budget deficit", translation: "预算赤字", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 92, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["reduce the budget deficit", "run a budget deficit", "widening budget deficit", "federal budget deficit"],
    example_sentence: "Persistent budget deficits can lead to rising national debt and eventually undermine investor confidence in the economy.",
    synonyms: ["fiscal deficit", "government shortfall", "revenue gap"],
    common_mistakes: ["budget deficit 是某一年支出>收入; national debt 是多年赤字累积的债务总额"],
    ielts_context: "Reading: public finance / economics; Writing Task 2: government policy",
    pronunciation: "/ˈbʌdʒ.ɪt ˈdef.ɪ.sɪt/",
    collocations_cn: ["减少预算赤字", "持续预算赤字", "扩大的预算赤字", "联邦预算赤字"],
    example_sentence_cn: "持续的预算赤字可能导致国债上升，并最终削弱投资者对经济的信心。",
    synonyms_cn: ["财政赤字", "政府收支缺口", "收入缺口"],
  },
  {
    id: "econ-026", word: "sovereign debt", translation: "主权债务", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 90, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["sovereign debt crisis", "restructure sovereign debt", "sovereign debt default", "rising sovereign debt"],
    example_sentence: "A sovereign debt crisis occurs when a government is unable or unwilling to repay its outstanding obligations to international creditors.",
    synonyms: ["national debt", "government debt", "public debt"],
    common_mistakes: ["sovereign debt 特指中央政府的外币债务; 不包括地方政府借款"],
    ielts_context: "Reading: international finance / economics; Listening Section 4: global economy",
    pronunciation: "/ˈsɒv.ər.ɪn det/",
    collocations_cn: ["主权债务危机", "重组主权债务", "主权债务违约", "不断上升的主权债务"],
    example_sentence_cn: "主权债务危机是指政府无力或不愿偿还对国际债权人的未偿债务。",
    synonyms_cn: ["国债", "政府债务", "公共债务"],
  },
  {
    id: "econ-027", word: "consumer confidence", translation: "消费者信心", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 91, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["boost consumer confidence", "decline in consumer confidence", "consumer confidence index", "measure consumer confidence"],
    example_sentence: "Consumer confidence indexes measure how optimistic or pessimistic households feel about the economy, which in turn affects their spending decisions.",
    synonyms: ["consumer sentiment", "household optimism", "buyer confidence"],
    common_mistakes: ["consumer confidence 影响消费支出; 是经济先行指标"],
    ielts_context: "Reading: economic indicators; Listening Section 3: business news",
    pronunciation: "/kənˈsjuː.mə ˈkɒn.fɪ.dəns/",
    collocations_cn: ["提振消费者信心", "消费者信心下降", "消费者信心指数", "衡量消费者信心"],
    example_sentence_cn: "消费者信心指数衡量家庭对经济感到乐观或悲观的程度，这反过来影响他们的支出决策。",
    synonyms_cn: ["消费者情绪", "家庭乐观指数", "买家信心"],
  },
  {
    id: "econ-028", word: "minimum wage", translation: "最低工资", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 92, topics: ["economy"], modules: ["writing", "speaking"],
    collocations: ["raise the minimum wage", "statutory minimum wage", "minimum wage legislation", "minimum wage increase"],
    example_sentence: "Debates over raising the minimum wage center on the trade-off between higher earnings for low-income workers and potential job losses.",
    synonyms: ["base pay", "wage floor", "statutory pay minimum"],
    common_mistakes: ["minimum wage 是法定最低时薪; living wage 是基于生活成本计算的更高标准"],
    ielts_context: "Writing Task 2: employment / inequality; Speaking Part 3: work / policy",
    pronunciation: "/ˈmɪn.ɪ.məm weɪdʒ/",
    collocations_cn: ["提高最低工资", "法定最低工资", "最低工资立法", "最低工资增长"],
    example_sentence_cn: "关于提高最低工资的辩论集中在低收入工人更高收入与潜在失业之间的权衡。",
    synonyms_cn: ["基本工资", "工资底线", "法定最低薪酬"],
  },
  {
    id: "econ-029", word: "gross domestic product", translation: "国内生产总值", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 98, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["GDP growth rate", "nominal gross domestic product", "GDP per capita", "calculate gross domestic product"],
    example_sentence: "Gross domestic product measures the total value of goods and services produced within a country's borders in a given period.",
    synonyms: ["GDP", "national output", "economic output"],
    common_mistakes: ["GDP 计算一国境内生产; GNP 计算一国国民生产（无论地点）"],
    ielts_context: "Writing Task 1: economic data; Reading: economic reports",
    pronunciation: "/ɡrəʊs dəˈmes.tɪk ˈprɒd.ʌkt/",
    collocations_cn: ["GDP增长率", "名义国内生产总值", "人均GDP", "计算国内生产总值"],
    example_sentence_cn: "国内生产总值衡量特定时期内一国境内生产的商品和服务的总价值。",
    synonyms_cn: ["GDP", "国民产出", "经济总产出"],
  },
  {
    id: "econ-030", word: "foreign exchange reserve", translation: "外汇储备", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["accumulate foreign exchange reserves", "deplete foreign exchange reserves", "foreign exchange reserve holdings", "adequate foreign exchange reserves"],
    example_sentence: "Countries maintain foreign exchange reserves to manage exchange rate volatility and provide a buffer against external economic shocks.",
    synonyms: ["forex reserves", "currency reserves", "international reserves"],
    common_mistakes: ["外汇储备主要用于稳定本币、偿付外债和国际贸易支付"],
    ielts_context: "Reading: international finance / economics; Listening Section 4: global economics",
    pronunciation: "/ˈfɒr.ɪn ɪksˈtʃeɪndʒ rɪˈzɜːv/",
    collocations_cn: ["积累外汇储备", "消耗外汇储备", "外汇储备持有量", "充足的外汇储备"],
    example_sentence_cn: "各国维持外汇储备以管理汇率波动并为外部经济冲击提供缓冲。",
    synonyms_cn: ["外汇存底", "货币储备", "国际储备"],
  },
  {
    id: "econ-031", word: "cost of living", translation: "生活成本", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 94, topics: ["economy"], modules: ["speaking", "writing"],
    collocations: ["rising cost of living", "high cost of living", "cost of living index", "cost of living adjustment"],
    example_sentence: "The cost of living varies dramatically between urban and rural areas, particularly in terms of housing, transportation, and food expenses.",
    synonyms: ["living expenses", "subsistence cost", "household expenditure level"],
    common_mistakes: ["cost of living 是一揽子商品/服务价格; 不仅限于房租"],
    ielts_context: "Speaking Part 3: urban vs rural life; Writing Task 2: housing / economy",
    pronunciation: "/kɒst əv ˈlɪv.ɪŋ/",
    collocations_cn: ["上涨的生活成本", "高生活成本", "生活成本指数", "生活成本调整"],
    example_sentence_cn: "城市和农村地区的生活成本差异巨大，尤其在住房、交通和食品开支方面。",
    synonyms_cn: ["生活开支", "生存成本", "家庭支出水平"],
  },
  {
    id: "econ-032", word: "economic indicator", translation: "经济指标", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 93, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["key economic indicator", "leading economic indicator", "publish economic indicators", "economic indicator data"],
    example_sentence: "Key economic indicators such as GDP growth, inflation, and unemployment rates provide crucial insights into the health of an economy.",
    synonyms: ["economic metric", "macroeconomic gauge", "economic bellwether"],
    common_mistakes: ["leading indicators 预测未来趋势; lagging indicators 确认已发生的趋势"],
    ielts_context: "Writing Task 1: data analysis / charts; Reading: economic reports",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk ˈɪn.dɪ.keɪ.tər/",
    collocations_cn: ["关键经济指标", "先行经济指标", "发布经济指标", "经济指标数据"],
    example_sentence_cn: "GDP增长、通胀和失业率等关键经济指标提供了对经济健康状况的关键洞察。",
    synonyms_cn: ["经济度量", "宏观指标", "经济风向标"],
  },
  {
    id: "econ-033", word: "emerging market", translation: "新兴市场", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["economy"], modules: ["reading", "speaking"],
    collocations: ["invest in emerging markets", "emerging market economy", "emerging market growth", "emerging market fund"],
    example_sentence: "Emerging markets offer higher growth potential than developed economies but also carry greater political and currency risks.",
    synonyms: ["developing economy", "newly industrialized country", "growth market"],
    common_mistakes: ["emerging market 不等于 frontier market; 后者更小、流动性更差"],
    ielts_context: "Reading: global investment / economics; Speaking Part 3: global economy",
    pronunciation: "/ɪˈmɜː.dʒɪŋ ˈmɑː.kɪt/",
    collocations_cn: ["投资新兴市场", "新兴市场经济体", "新兴市场增长", "新兴市场基金"],
    example_sentence_cn: "新兴市场提供比发达经济体更高的增长潜力，但也伴随更大的政治和货币风险。",
    synonyms_cn: ["发展中经济体", "新兴工业化国家", "增长市场"],
  },
  {
    id: "econ-034", word: "public debt", translation: "公共债务", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["reduce public debt", "public debt burden", "sustainable public debt", "public debt level"],
    example_sentence: "High levels of public debt can limit a government's ability to respond to economic crises and invest in long-term growth.",
    synonyms: ["national debt", "government borrowing", "state debt"],
    common_mistakes: ["public debt 包括中央和地方政府债务; sovereign debt 仅指中央政府"],
    ielts_context: "Reading: public finance / economics; Writing Task 2: fiscal policy",
    pronunciation: "/ˈpʌb.lɪk det/",
    collocations_cn: ["减少公共债务", "公共债务负担", "可持续的公共债务", "公共债务水平"],
    example_sentence_cn: "高水平的公共债务可能限制政府应对经济危机和投资长期增长的能力。",
    synonyms_cn: ["国债", "政府借款", "国家债务"],
  },
  {
    id: "econ-035", word: "commodity price", translation: "大宗商品价格", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["fluctuating commodity prices", "commodity price index", "volatile commodity prices", "rising commodity prices"],
    example_sentence: "Fluctuations in commodity prices can have profound effects on the economies of resource-dependent developing nations.",
    synonyms: ["raw material price", "bulk goods price", "primary resource price"],
    common_mistakes: ["commodity 指标准化大宗商品（石油、铜、小麦等）; 不是一般商品"],
    ielts_context: "Reading: international trade / economics; Listening Section 4: global markets",
    pronunciation: "/kəˈmɒd.ə.ti praɪs/",
    collocations_cn: ["波动的大宗商品价格", "大宗商品价格指数", "剧烈波动的大宗商品价格", "上涨的大宗商品价格"],
    example_sentence_cn: "大宗商品价格的波动可能对依赖资源的发展中国家经济产生深远影响。",
    synonyms_cn: ["原材料价格", "大宗货物价格", "初级资源价格"],
  },
  {
    id: "econ-036", word: "wage growth", translation: "工资增长", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 92, topics: ["economy"], modules: ["writing", "reading"],
    collocations: ["slow wage growth", "real wage growth", "stagnant wage growth", "accelerate wage growth"],
    example_sentence: "Despite strong economic growth, many developed countries have experienced stagnant wage growth for middle and low-income workers.",
    synonyms: ["salary increase", "earnings growth", "pay rise trend"],
    common_mistakes: ["real wage growth 已扣除通胀; nominal wage growth 未扣除通胀"],
    ielts_context: "Writing Task 1: economic trends / graphs; Reading: labor economics",
    pronunciation: "/weɪdʒ ɡrəʊθ/",
    collocations_cn: ["缓慢的工资增长", "实际工资增长", "停滞的工资增长", "加速工资增长"],
    example_sentence_cn: "尽管经济增长强劲，许多发达国家的中低收入工人经历了停滞的工资增长。",
    synonyms_cn: ["薪资增长", "收入增长", "加薪趋势"],
  },
  {
    id: "econ-037", word: "economic inequality", translation: "经济不平等", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 92, topics: ["economy"], modules: ["writing", "reading"],
    collocations: ["worsening economic inequality", "address economic inequality", "reduce economic inequality", "persistent economic inequality"],
    example_sentence: "Economic inequality within countries has been linked to reduced social mobility, poorer health outcomes, and increased political polarization.",
    synonyms: ["wealth gap", "income disparity", "economic injustice"],
    common_mistakes: ["economic inequality 涵盖收入、财富和机会的不平等; 是多维度概念"],
    ielts_context: "Writing Task 2: social issues / globalization; Reading: sociology / economics",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk ˌɪn.ɪˈkwɒl.ə.ti/",
    collocations_cn: ["恶化的经济不平等", "解决经济不平等", "减少经济不平等", "持续的经济不平等"],
    example_sentence_cn: "国家内部的经济不平等已与社会流动性降低、健康结果恶化和政治极化加剧相关联。",
    synonyms_cn: ["贫富差距", "收入差距", "经济不公"],
  },
  {
    id: "econ-038", word: "corporate tax", translation: "公司税", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 91, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["cut corporate tax", "corporate tax rate", "corporate tax avoidance", "corporate tax revenue"],
    example_sentence: "Many multinational corporations have been criticized for shifting profits to low-tax jurisdictions to minimize their corporate tax obligations.",
    synonyms: ["business tax", "enterprise levy", "corporate income tax"],
    common_mistakes: ["corporate tax 是利润税; VAT/GST 是消费税; 不同税种"],
    ielts_context: "Reading: business / public finance; Writing Task 2: taxation / regulation",
    pronunciation: "/ˈkɔː.pər.ət tæks/",
    collocations_cn: ["削减公司税", "公司税率", "公司避税", "公司税收入"],
    example_sentence_cn: "许多跨国公司因将利润转移到低税率管辖区以最小化公司税义务而受到批评。",
    synonyms_cn: ["营业税", "企业税", "企业所得税"],
  },
  {
    id: "econ-039", word: "financial crisis", translation: "金融危机", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 94, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["trigger a financial crisis", "global financial crisis", "weather the financial crisis", "aftermath of the financial crisis"],
    example_sentence: "The 2008 global financial crisis highlighted the dangers of excessive risk-taking in the banking sector and inadequate regulatory oversight.",
    synonyms: ["economic meltdown", "banking crisis", "market crash"],
    common_mistakes: ["financial crisis 源自金融体系; economic recession 是其可能导致的经济结果"],
    ielts_context: "Reading: economic history / finance; Writing Task 2: regulation / economy",
    pronunciation: "/faɪˈnæn.ʃəl ˈkraɪ.sɪs/",
    collocations_cn: ["触发金融危机", "全球金融危机", "渡过金融危机", "金融危机余波"],
    example_sentence_cn: "2008年全球金融危机突显了银行业过度冒险和监管不力的危险。",
    synonyms_cn: ["经济崩溃", "银行危机", "市场崩盘"],
  },
  {
    id: "econ-040", word: "economic sanction", translation: "经济制裁", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["impose economic sanctions", "lift economic sanctions", "comprehensive economic sanctions", "targeted economic sanctions"],
    example_sentence: "Economic sanctions are often used as a foreign policy tool to pressure governments without resorting to military intervention.",
    synonyms: ["trade embargo", "economic penalty", "financial restriction"],
    common_mistakes: ["sanctions 是政治经济惩罚措施; tariffs 是贸易税收"],
    ielts_context: "Reading: international relations / economics; Writing Task 2: foreign policy",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk ˈsæŋk.ʃən/",
    collocations_cn: ["实施经济制裁", "解除经济制裁", "全面经济制裁", "有针对性的经济制裁"],
    example_sentence_cn: "经济制裁经常被用作外交政策工具，在不诉诸军事干预的情况下向政府施压。",
    synonyms_cn: ["贸易禁运", "经济处罚", "金融限制"],
  },
  // ═══ 高頻 70-89 (39 个) ═══
  {
    id: "econ-041", word: "retail sales", translation: "零售额", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 85, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["boost retail sales", "decline in retail sales", "monthly retail sales", "retail sales growth"],
    example_sentence: "Monthly retail sales figures are closely watched as an indicator of consumer spending and overall economic health.",
    synonyms: ["consumer spending data", "shop sales", "retail turnover"],
    common_mistakes: ["retail sales 只计实体店+网店零售额; 不包括批发和商业采购"],
    ielts_context: "Reading: economic indicators / business; Listening Section 3: market reports",
    pronunciation: "/ˈriː.teɪl seɪlz/",
    collocations_cn: ["提振零售额", "零售额下降", "月度零售额", "零售额增长"],
    example_sentence_cn: "月度零售额数据作为消费者支出和整体经济健康状况的指标受到密切关注。",
    synonyms_cn: ["消费支出数据", "商店销售额", "零售营业额"],
  },
  {
    id: "econ-042", word: "export-oriented", translation: "出口导向型", part_of_speech: "adjective", band_level: "6.5", frequency_score: 84, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["export-oriented industry", "export-oriented economy", "export-oriented growth strategy", "export-oriented manufacturing"],
    example_sentence: "Many East Asian economies adopted export-oriented growth strategies that propelled them from low-income to high-income status within a few decades.",
    synonyms: ["export-led", "trade-focused", "externally driven"],
    common_mistakes: ["export-oriented 不等于 free trade; 也可能包括产业政策扶持出口"],
    ielts_context: "Reading: development economics / trade; Writing Task 2: economic development",
    pronunciation: "/ˈek.spɔːt ˈɔː.ri.en.tɪd/",
    collocations_cn: ["出口导向型产业", "出口导向型经济", "出口导向型增长策略", "出口导向型制造业"],
    example_sentence_cn: "许多东亚经济体采取了出口导向型增长策略，在几十年内从低收入迈入高收入行列。",
    synonyms_cn: ["出口主导型", "贸易导向型", "外部驱动型"],
  },
  {
    id: "econ-043", word: "import tariff", translation: "进口关税", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 86, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["impose import tariffs", "raise import tariffs", "reduce import tariffs", "punitive import tariff"],
    example_sentence: "Import tariffs protect domestic industries from foreign competition but can lead to higher prices for consumers.",
    synonyms: ["customs duty", "import tax", "border levy"],
    common_mistakes: ["tariff 是进口税的一种; quota 是数量限制"],
    ielts_context: "Reading: international trade; Writing Task 2: protectionism vs free trade",
    pronunciation: "/ˈɪm.pɔːt ˈtær.ɪf/",
    collocations_cn: ["征收进口关税", "提高进口关税", "降低进口关税", "惩罚性进口关税"],
    example_sentence_cn: "进口关税保护国内产业免受外国竞争，但可能导致消费者面临更高价格。",
    synonyms_cn: ["海关税", "进口税", "边境税"],
  },
  {
    id: "econ-044", word: "currency fluctuation", translation: "货币波动", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 82, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["currency fluctuation risk", "hedge against currency fluctuations", "unpredictable currency fluctuations", "currency fluctuation impact"],
    example_sentence: "Exporters often use financial instruments to hedge against currency fluctuations that could erode their profit margins.",
    synonyms: ["exchange rate volatility", "forex movement", "currency swing"],
    common_mistakes: ["currency fluctuation 是双向的（升或贬）; currency depreciation 只是贬值"],
    ielts_context: "Reading: international finance; Listening Section 4: global business",
    pronunciation: "/ˈkʌr.ən.si ˌflʌk.tʃuˈeɪ.ʃən/",
    collocations_cn: ["货币波动风险", "对冲货币波动", "不可预测的货币波动", "货币波动影响"],
    example_sentence_cn: "出口商经常使用金融工具来对冲可能侵蚀其利润率的货币波动。",
    synonyms_cn: ["汇率波动", "外汇波动", "货币震荡"],
  },
  {
    id: "econ-045", word: "tax haven", translation: "避税天堂", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 83, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["offshore tax haven", "tax haven jurisdiction", "use a tax haven", "crack down on tax havens"],
    example_sentence: "International efforts to combat tax avoidance have focused on increasing transparency and closing loopholes that allow companies to exploit tax havens.",
    synonyms: ["offshore financial center", "low-tax jurisdiction", "secrecy jurisdiction"],
    common_mistakes: ["tax haven 不等于 tax evasion; haven 合法（利用低税率）; evasion 非法"],
    ielts_context: "Reading: global finance / regulation; Writing Task 2: corporate responsibility",
    pronunciation: "/tæks ˈheɪ.vən/",
    collocations_cn: ["离岸避税天堂", "避税管辖区", "利用避税天堂", "打击避税天堂"],
    example_sentence_cn: "打击避税的国际努力集中在提高透明度和堵住允许公司利用避税天堂的漏洞上。",
    synonyms_cn: ["离岸金融中心", "低税管辖区", "保密管辖区"],
  },
  {
    id: "econ-046", word: "housing market", translation: "房地产市场", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 88, topics: ["economy"], modules: ["speaking", "reading"],
    collocations: ["booming housing market", "housing market crash", "overheated housing market", "regulate the housing market"],
    example_sentence: "An overheated housing market can create affordability crises and increase the risk of a financial bubble.",
    synonyms: ["property market", "real estate market", "residential market"],
    common_mistakes: ["housing market 仅指住宅; real estate market 还包括商业地产"],
    ielts_context: "Speaking Part 3: housing / cost of living; Reading: real estate / economics",
    pronunciation: "/ˈhaʊ.zɪŋ ˈmɑː.kɪt/",
    collocations_cn: ["繁荣的房地产市场", "房地产市场崩盘", "过热的房地产市场", "调控房地产市场"],
    example_sentence_cn: "过热的房地产市场可能造成负担能力危机并增加金融泡沫的风险。",
    synonyms_cn: ["房产市场", "地产市场", "住宅市场"],
  },
  {
    id: "econ-047", word: "pension fund", translation: "养老基金", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 84, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["invest pension funds", "manage a pension fund", "pension fund deficit", "public pension fund"],
    example_sentence: "Pension funds are among the largest institutional investors in the world, managing trillions of dollars in retirement savings.",
    synonyms: ["retirement fund", "superannuation fund", "old-age provision fund"],
    common_mistakes: ["pension fund 管理养老金的机构; pension 是退休者收到的养老金"],
    ielts_context: "Reading: finance / retirement; Listening Section 4: aging population / economics",
    pronunciation: "/ˈpen.ʃən fʌnd/",
    collocations_cn: ["投资养老基金", "管理养老基金", "养老基金缺口", "公共养老基金"],
    example_sentence_cn: "养老基金是世界上最大的机构投资者之一，管理着数万亿美元的退休储蓄。",
    synonyms_cn: ["退休基金", "公积金基金", "养老储备基金"],
  },
  {
    id: "econ-048", word: "central bank", translation: "中央银行", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 89, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["central bank governor", "central bank policy", "independent central bank", "central bank intervention"],
    example_sentence: "An independent central bank can make difficult monetary policy decisions without political interference, enhancing economic stability.",
    synonyms: ["national bank", "monetary authority", "reserve bank"],
    common_mistakes: ["central bank 制定货币政策; commercial banks 提供存贷款等日常服务"],
    ielts_context: "Reading: monetary policy / finance; Listening Section 4: economics lectures",
    pronunciation: "/ˈsen.trəl bæŋk/",
    collocations_cn: ["中央银行行长", "中央银行政策", "独立的中央银行", "中央银行干预"],
    example_sentence_cn: "独立的中央银行可以在不受政治干预的情况下做出艰难的货币政策决策，增强经济稳定性。",
    synonyms_cn: ["国家银行", "货币当局", "储备银行"],
  },
  {
    id: "econ-049", word: "trade surplus", translation: "贸易顺差", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 87, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["run a trade surplus", "large trade surplus", "persistent trade surplus", "trade surplus with"],
    example_sentence: "A trade surplus indicates that a country exports more than it imports, which can contribute to currency appreciation over time.",
    synonyms: ["positive trade balance", "trade excess", "export surplus"],
    common_mistakes: ["trade surplus 不等于经济健康; 可能是国内需求疲软的表现"],
    ielts_context: "Reading: international trade / economics; Writing Task 2: trade policy",
    pronunciation: "/treɪd ˈsɜː.pləs/",
    collocations_cn: ["保持贸易顺差", "巨额贸易顺差", "持续贸易顺差", "对某国贸易顺差"],
    example_sentence_cn: "贸易顺差表明一国出口多于进口，这可能导致货币随时间升值。",
    synonyms_cn: ["正贸易差额", "贸易盈余", "出口顺差"],
  },
  {
    id: "econ-050", word: "subsidy program", translation: "补贴计划", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 85, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["provide a subsidy program", "government subsidy program", "federal subsidy program", "phase out subsidy programs"],
    example_sentence: "Government subsidy programs for agricultural producers help stabilize food prices and protect farmers from market volatility.",
    synonyms: ["financial aid scheme", "state assistance program", "public support initiative"],
    common_mistakes: ["subsidy 是补贴特定行业/活动; welfare 是对个人的福利救助"],
    ielts_context: "Reading: public policy / economics; Writing Task 2: government spending",
    pronunciation: "/ˈsʌb.sɪ.di ˈprəʊ.ɡræm/",
    collocations_cn: ["提供补贴计划", "政府补贴计划", "联邦补贴计划", "逐步取消补贴计划"],
    example_sentence_cn: "政府对农业生产者的补贴计划有助于稳定粮食价格并保护农民免受市场波动的冲击。",
    synonyms_cn: ["财政援助计划", "国家援助计划", "公共支持倡议"],
  },
  {
    id: "econ-051", word: "economic output", translation: "经济产出", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 86, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["measure economic output", "total economic output", "boost economic output", "decline in economic output"],
    example_sentence: "Manufacturing and services each account for a substantial share of total economic output in most developed nations.",
    synonyms: ["GDP", "production value", "national product"],
    common_mistakes: ["economic output = GDP; input 是劳动力、资本等生产要素"],
    ielts_context: "Reading: macroeconomics; Writing Task 1: economic data",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk ˈaʊt.pʊt/",
    collocations_cn: ["衡量经济产出", "经济总产出", "提高经济产出", "经济产出下滑"],
    example_sentence_cn: "在大多数发达国家，制造业和服务业各占总经济产出的相当大份额。",
    synonyms_cn: ["GDP", "生产价值", "国民产品"],
  },
  {
    id: "econ-052", word: "capital market", translation: "资本市场", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 86, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["access the capital market", "deepen capital markets", "capital market financing", "capital market regulation"],
    example_sentence: "Well-functioning capital markets channel funds from savers to businesses, facilitating long-term investment and economic growth.",
    synonyms: ["financial market", "securities market", "investment market"],
    common_mistakes: ["capital market 交易长期证券（股票/债券）; money market 交易短期债务工具（<1年）"],
    ielts_context: "Reading: finance / economics; Writing Task 2: financial development",
    pronunciation: "/ˈkæp.ɪ.təl ˈmɑː.kɪt/",
    collocations_cn: ["进入资本市场", "深化资本市场", "资本市场融资", "资本市场监管"],
    example_sentence_cn: "运作良好的资本市场将资金从储蓄者引导至企业，促进长期投资和经济增长。",
    synonyms_cn: ["金融市场", "证券市场", "投资市场"],
  },
  {
    id: "econ-053", word: "consumer debt", translation: "消费者债务", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 83, topics: ["economy"], modules: ["reading", "speaking"],
    collocations: ["rising consumer debt", "pay off consumer debt", "consumer debt burden", "household consumer debt"],
    example_sentence: "Rising consumer debt levels can signal strong economic confidence in the short term but may pose risks to financial stability over time.",
    synonyms: ["household borrowing", "personal indebtedness", "consumer credit"],
    common_mistakes: ["consumer debt 是个人/家庭借款消费; national debt 是国家借款"],
    ielts_context: "Reading: personal finance / economics; Speaking Part 3: money / consumption",
    pronunciation: "/kənˈsjuː.mə det/",
    collocations_cn: ["不断上升的消费者债务", "偿还消费者债务", "消费者债务负担", "家庭消费者债务"],
    example_sentence_cn: "不断上升的消费者债务水平在短期内可能表明经济信心强劲，但随时间推移可能对金融稳定构成风险。",
    synonyms_cn: ["家庭借贷", "个人负债", "消费信贷"],
  },
  {
    id: "econ-054", word: "manufacturing sector", translation: "制造业", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 85, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["boost the manufacturing sector", "declining manufacturing sector", "manufacturing sector output", "advanced manufacturing sector"],
    example_sentence: "The manufacturing sector remains a key driver of employment and export earnings in many developing economies.",
    synonyms: ["industrial sector", "production industry", "factory sector"],
    common_mistakes: ["manufacturing sector 生产有形商品; service sector 提供无形服务"],
    ielts_context: "Reading: industry / economics; Writing Task 2: industrial policy",
    pronunciation: "/ˌmæn.jʊˈfæk.tʃə.rɪŋ ˈsek.tər/",
    collocations_cn: ["提振制造业", "衰退的制造业", "制造业产出", "先进制造业"],
    example_sentence_cn: "制造业仍然是许多发展中经济体就业和出口收入的关键驱动力。",
    synonyms_cn: ["工业部门", "生产行业", "工厂行业"],
  },
  {
    id: "econ-055", word: "wealth gap", translation: "贫富差距", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 87, topics: ["economy"], modules: ["writing", "reading"],
    collocations: ["widen the wealth gap", "narrow the wealth gap", "growing wealth gap", "address the wealth gap"],
    example_sentence: "The widening wealth gap between the richest and poorest segments of society has sparked debates about tax reform and social welfare policies.",
    synonyms: ["wealth disparity", "asset inequality", "rich-poor divide"],
    common_mistakes: ["wealth gap 指资产（房产、股票等）差距; income gap 指收入差距; 两者相关但不同"],
    ielts_context: "Writing Task 2: social inequality / policy; Reading: sociology / economics",
    pronunciation: "/welθ ɡæp/",
    collocations_cn: ["扩大贫富差距", "缩小贫富差距", "日益加大的贫富差距", "解决贫富差距"],
    example_sentence_cn: "社会最富有与最贫困阶层之间日益扩大的贫富差距引发了关于税制改革和社会福利政策的辩论。",
    synonyms_cn: ["财富差距", "资产不平等", "贫富分化"],
  },
  {
    id: "econ-056", word: "service sector", translation: "服务业", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 84, topics: ["economy"], modules: ["reading", "speaking"],
    collocations: ["expand the service sector", "growing service sector", "service sector employment", "service sector productivity"],
    example_sentence: "The service sector now accounts for over 70 percent of GDP in many advanced economies, reflecting a long-term shift away from manufacturing.",
    synonyms: ["tertiary sector", "service industry", "services economy"],
    common_mistakes: ["service sector 涵盖零售、金融、教育、医疗等; 不是单一行业"],
    ielts_context: "Reading: economic trends / employment; Speaking Part 3: jobs / economy",
    pronunciation: "/ˈsɜː.vɪs ˈsek.tər/",
    collocations_cn: ["扩大服务业", "不断增长的服务业", "服务业就业", "服务业生产率"],
    example_sentence_cn: "服务业现在占许多发达经济体GDP的70%以上，反映了从制造业的长期转移。",
    synonyms_cn: ["第三产业", "服务行业", "服务经济体"],
  },
  {
    id: "econ-057", word: "economic boom", translation: "经济繁荣", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 83, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["fuel an economic boom", "postwar economic boom", "unsustainable economic boom", "economic boom period"],
    example_sentence: "The postwar economic boom of the 1950s and 1960s delivered unprecedented prosperity to many industrialized nations.",
    synonyms: ["economic prosperity", "economic surge", "boom times"],
    common_mistakes: ["economic boom 是高速扩张期; economic growth 是持续增长; boom 隐含不可持续的可能"],
    ielts_context: "Reading: economic history; Writing Task 2: economic cycles",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk buːm/",
    collocations_cn: ["推动经济繁荣", "战后经济繁荣", "不可持续的经济繁荣", "经济繁荣期"],
    example_sentence_cn: "20世纪50年代和60年代的战后经济繁荣为许多工业化国家带来了前所未有的繁荣。",
    synonyms_cn: ["经济景气", "经济高涨", "繁荣时代"],
  },
  {
    id: "econ-058", word: "trade protectionism", translation: "贸易保护主义", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 82, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["rising trade protectionism", "resort to trade protectionism", "combat trade protectionism", "unilateral trade protectionism"],
    example_sentence: "Trade protectionism, through tariffs and quotas, may shield domestic jobs in the short run but often leads to higher consumer prices and trade retaliation.",
    synonyms: ["economic nationalism", "trade barriers", "protectionist policy"],
    common_mistakes: ["protectionism 通过关税/配额限制进口; free trade 主张消除壁垒"],
    ielts_context: "Reading: international trade / economics; Writing Task 2: globalization / trade policy",
    pronunciation: "/treɪd prəˈtek.ʃə.nɪ.zəm/",
    collocations_cn: ["日益加剧的贸易保护主义", "诉诸贸易保护主义", "反对贸易保护主义", "单边贸易保护主义"],
    example_sentence_cn: "通过关税和配额实施的贸易保护主义可能在短期内保护国内就业，但通常导致更高的消费价格和贸易报复。",
    synonyms_cn: ["经济民族主义", "贸易壁垒", "保护主义政策"],
  },
  {
    id: "econ-059", word: "financial inclusion", translation: "金融包容", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 78, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["promote financial inclusion", "digital financial inclusion", "achieving financial inclusion", "financial inclusion initiatives"],
    example_sentence: "Mobile banking has revolutionized financial inclusion in developing countries, giving millions of unbanked individuals access to savings and credit.",
    synonyms: ["inclusive finance", "broad-based banking", "universal financial access"],
    common_mistakes: ["financial inclusion 指让所有人都能获得基本金融服务; 不仅限于银行贷款"],
    ielts_context: "Reading: development economics / fintech; Writing Task 2: technology / development",
    pronunciation: "/faɪˈnæn.ʃəl ɪnˈkluː.ʒən/",
    collocations_cn: ["促进金融包容", "数字金融包容", "实现金融包容", "金融包容倡议"],
    example_sentence_cn: "移动银行已经彻底改变了发展中国家的金融包容，使数百万无银行账户的个人能够获得储蓄和信贷服务。",
    synonyms_cn: ["普惠金融", "广泛银行服务", "全民金融准入"],
  },
  {
    id: "econ-060", word: "remittance", translation: "汇款", part_of_speech: "noun", band_level: "6.0", frequency_score: 80, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["send remittances", "remittance flows", "migrant remittance", "remittance service"],
    example_sentence: "Remittances from overseas workers exceed foreign direct investment as the largest source of external finance for many low-income countries.",
    synonyms: ["money transfer", "migrant earnings transfer", "cross-border payment"],
    common_mistakes: ["remittance 是移民汇回国外的钱; payment 是一般交易付款"],
    ielts_context: "Reading: development economics / migration; Listening Section 3: global finance discussions",
    pronunciation: "/rɪˈmɪt.əns/",
    collocations_cn: ["汇款回国", "汇款流动", "移民汇款", "汇款服务"],
    example_sentence_cn: "海外工人的汇款超过外国直接投资，成为许多低收入国家最大的外部资金来源。",
    synonyms_cn: ["汇款转账", "移民收入转移", "跨境汇款"],
  },
  {
    id: "econ-061", word: "privatization", translation: "私有化", part_of_speech: "noun", band_level: "6.5", frequency_score: 82, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["state enterprise privatization", "partial privatization", "privatization of public services", "privatization program"],
    example_sentence: "Privatization of state-owned enterprises was a cornerstone of economic reform in many transition economies during the 1990s.",
    synonyms: ["denationalization", "private ownership transfer", "marketization"],
    common_mistakes: ["privatization 是国有资产转给私人; nationalization 是私产收归国有"],
    ielts_context: "Reading: economic reform / public policy; Writing Task 2: government role in economy",
    pronunciation: "/ˌpraɪ.və.taɪˈzeɪ.ʃən/",
    collocations_cn: ["国有企业私有化", "部分私有化", "公共服务私有化", "私有化计划"],
    example_sentence_cn: "国有企业私有化是20世纪90年代许多转型经济体经济改革的基石。",
    synonyms_cn: ["去国有化", "私有产权转移", "市场化"],
  },
  {
    id: "econ-062", word: "balance of trade", translation: "贸易差额", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 84, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["favorable balance of trade", "negative balance of trade", "balance of trade deficit", "improve the balance of trade"],
    example_sentence: "The balance of trade measures the difference between the monetary value of a nation's exports and imports over a specific period.",
    synonyms: ["trade balance", "net exports", "commercial balance"],
    common_mistakes: ["balance of trade 仅计商品贸易; balance of payments 还包括服务和资本流动"],
    ielts_context: "Reading: international economics / trade; Writing Task 2: trade policy",
    pronunciation: "/ˈbæl.əns əv treɪd/",
    collocations_cn: ["有利的贸易差额", "负贸易差额", "贸易逆差", "改善贸易差额"],
    example_sentence_cn: "贸易差额衡量特定时期内一国出口与进口货币价值之间的差异。",
    synonyms_cn: ["贸易收支", "净出口", "商业差额"],
  },
  {
    id: "econ-063", word: "economic integration", translation: "经济一体化", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 81, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["regional economic integration", "deepen economic integration", "global economic integration", "economic integration process"],
    example_sentence: "Regional economic integration, such as the European Union, eliminates trade barriers between member states and coordinates economic policies.",
    synonyms: ["economic unification", "market integration", "economic convergence"],
    common_mistakes: ["economic integration 不仅指贸易自由化; 还包括政策协调和要素自由流动"],
    ielts_context: "Reading: international relations / economics; Writing Task 2: regional cooperation",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk ˌɪn.tɪˈɡreɪ.ʃən/",
    collocations_cn: ["区域经济一体化", "深化经济一体化", "全球经济一体化", "经济一体化进程"],
    example_sentence_cn: "区域经济一体化，如欧盟，消除了成员国之间的贸易壁垒并协调经济政策。",
    synonyms_cn: ["经济统一", "市场一体化", "经济趋同"],
  },
  {
    id: "econ-064", word: "self-sufficient economy", translation: "自给经济", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 77, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["pursue a self-sufficient economy", "self-sufficient economy model", "relatively self-sufficient economy", "strive for a self-sufficient economy"],
    example_sentence: "A self-sufficient economy minimizes dependence on external trade by producing nearly all goods and services needed domestically.",
    synonyms: ["autarky", "closed economy", "self-reliant system"],
    common_mistakes: ["self-sufficient economy 不是完全封闭经济; 多数国家仅在特定领域追求自给自足"],
    ielts_context: "Reading: economic systems / development; Writing Task 2: food security / energy",
    pronunciation: "/self səˈfɪʃ.ənt ɪˈkɒn.ə.mi/",
    collocations_cn: ["追求自给经济", "自给经济模式", "相对自给自足的经济", "努力实现自给经济"],
    example_sentence_cn: "自给经济通过在国内生产几乎所有所需商品和服务来最大限度地减少对外部贸易的依赖。",
    synonyms_cn: ["自给自足制", "封闭经济", "自力更生体系"],
  },
  {
    id: "econ-065", word: "digital economy", translation: "数字经济", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 85, topics: ["economy"], modules: ["reading", "speaking"],
    collocations: ["expand the digital economy", "digital economy sector", "digital economy transformation", "digital economy platform"],
    example_sentence: "The rise of the digital economy has reshaped traditional business models, creating new opportunities in e-commerce, fintech, and remote work.",
    synonyms: ["internet economy", "online economy", "knowledge-based economy"],
    common_mistakes: ["digital economy 不仅指电商; 涵盖所有数字化的经济活动"],
    ielts_context: "Reading: technology / business; Speaking Part 3: technology and work",
    pronunciation: "/ˈdɪdʒ.ɪ.təl ɪˈkɒn.ə.mi/",
    collocations_cn: ["扩展数字经济", "数字经济部门", "数字经济转型", "数字经济平台"],
    example_sentence_cn: "数字经济的崛起重塑了传统商业模式，在电商、金融科技和远程工作中创造了新的机会。",
    synonyms_cn: ["互联网经济", "网络经济", "知识经济"],
  },
  {
    id: "econ-066", word: "antitrust law", translation: "反垄断法", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 79, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["enforce antitrust laws", "violate antitrust law", "antitrust law investigation", "strengthen antitrust laws"],
    example_sentence: "Antitrust laws aim to promote fair competition by preventing monopolistic practices such as price-fixing and market allocation agreements.",
    synonyms: ["competition law", "anti-monopoly legislation", "fair trade regulation"],
    common_mistakes: ["antitrust law 针对反竞争行为; 大公司本身不违法，滥用市场支配地位才违法"],
    ielts_context: "Reading: business regulation / law; Writing Task 2: corporate regulation",
    pronunciation: "/ˌæn.tiˈtrʌst lɔː/",
    collocations_cn: ["执行反垄断法", "违反反垄断法", "反垄断法调查", "加强反垄断法"],
    example_sentence_cn: "反垄断法旨在通过防止价格操纵和市场分配协议等垄断行为来促进公平竞争。",
    synonyms_cn: ["竞争法", "反垄断立法", "公平贸易法规"],
  },
  {
    id: "econ-067", word: "deflation", translation: "通货紧缩", part_of_speech: "noun", band_level: "6.5", frequency_score: 82, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["fight deflation", "persistent deflation", "spiral of deflation", "fall into deflation"],
    example_sentence: "Deflation can be more damaging than inflation, as falling prices encourage consumers to delay purchases, further depressing economic activity.",
    synonyms: ["negative inflation", "price decline", "falling price level"],
    common_mistakes: ["deflation 是物价普遍持续下跌; disinflation 是通胀率下降但仍为正"],
    ielts_context: "Reading: macroeconomics / monetary policy; Listening Section 4: economics lectures",
    pronunciation: "/dɪˈfleɪ.ʃən/",
    collocations_cn: ["抗击通货紧缩", "持续通货紧缩", "通缩螺旋", "陷入通货紧缩"],
    example_sentence_cn: "通缩可能比通胀更具破坏性，因为价格下降鼓励消费者推迟购买，进一步压抑经济活动。",
    synonyms_cn: ["负通胀", "物价下跌", "价格水平下降"],
  },
  {
    id: "econ-068", word: "bond market", translation: "债券市场", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 83, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["issue in the bond market", "government bond market", "corporate bond market", "bond market yield"],
    example_sentence: "The bond market plays a critical role in determining long-term interest rates and providing governments with a stable source of financing.",
    synonyms: ["debt market", "fixed-income market", "credit market"],
    common_mistakes: ["bond market 交易债务工具; stock market 交易股权; 两者是金融市场的两大支柱"],
    ielts_context: "Reading: finance / economics; Listening Section 4: financial markets",
    pronunciation: "/bɒnd ˈmɑː.kɪt/",
    collocations_cn: ["在债券市场发行", "政府债券市场", "公司债券市场", "债券市场收益率"],
    example_sentence_cn: "债券市场在决定长期利率和为政府提供稳定融资来源方面发挥着关键作用。",
    synonyms_cn: ["债务市场", "固定收益市场", "信贷市场"],
  },
  {
    id: "econ-069", word: "outsourcing", translation: "外包", part_of_speech: "noun", band_level: "6.0", frequency_score: 84, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["offshore outsourcing", "outsourcing of production", "benefits of outsourcing", "outsourcing jobs overseas"],
    example_sentence: "Outsourcing production to countries with lower labor costs has allowed companies to reduce expenses but has also raised concerns about domestic job losses.",
    synonyms: ["contracting out", "offshoring", "externalization"],
    common_mistakes: ["outsourcing 是外包给第三方; offshoring 是将业务移到海外（可能仍属本公司）"],
    ielts_context: "Reading: business / globalization; Writing Task 2: globalization / employment",
    pronunciation: "/ˈaʊt.sɔː.sɪŋ/",
    collocations_cn: ["离岸外包", "生产外包", "外包的好处", "将工作外包到海外"],
    example_sentence_cn: "将生产外包到劳动力成本较低的国家使公司能够降低开支，但也引发了对国内就业损失的担忧。",
    synonyms_cn: ["合同外包", "离岸经营", "外部化"],
  },
  {
    id: "econ-070", word: "macroeconomic stability", translation: "宏观经济稳定", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 80, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["maintain macroeconomic stability", "ensure macroeconomic stability", "macroeconomic stability framework", "undermine macroeconomic stability"],
    example_sentence: "Maintaining macroeconomic stability through sound fiscal and monetary policies is a primary objective of most governments and central banks.",
    synonyms: ["economic stability", "macro-level balance", "overall economic equilibrium"],
    common_mistakes: ["macroeconomic 关注国家整体经济（通胀/GDP/就业）; microeconomic 关注个体市场行为"],
    ielts_context: "Reading: economics / public policy; Writing Task 2: economic management",
    pronunciation: "/ˌmæk.rəʊ.iː.kəˈnɒm.ɪk stəˈbɪl.ə.ti/",
    collocations_cn: ["维持宏观经济稳定", "确保宏观经济稳定", "宏观经济稳定框架", "破坏宏观经济稳定"],
    example_sentence_cn: "通过健全的财政和货币政策维持宏观经济稳定是大多数政府和中央银行的首要目标。",
    synonyms_cn: ["经济稳定", "宏观平衡", "整体经济均衡"],
  },
  {
    id: "econ-071", word: "purchasing power parity", translation: "购买力平价", part_of_speech: "noun phrase", band_level: "7.5", frequency_score: 78, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["purchasing power parity adjustment", "PPP exchange rate", "assess purchasing power parity", "purchasing power parity comparison"],
    example_sentence: "Purchasing power parity provides a more accurate comparison of living standards across countries by accounting for differences in local price levels.",
    synonyms: ["PPP", "cost-of-living equivalence", "relative price parity"],
    common_mistakes: ["PPP 用于比较不同国家生活水平; 不同于市场汇率（market exchange rate）"],
    ielts_context: "Reading: international economics / development; Listening Section 4: global economy",
    pronunciation: "/ˈpɜː.tʃə.sɪŋ ˈpaʊ.ər ˈpær.ə.ti/",
    collocations_cn: ["购买力平价调整", "PPP汇率", "评估购买力平价", "购买力平价比较"],
    example_sentence_cn: "购买力平价通过考虑当地价格水平的差异，提供了更准确的各国生活水平比较。",
    synonyms_cn: ["PPP", "生活成本等值", "相对价格平价"],
  },
  {
    id: "econ-072", word: "circular economy", translation: "循环经济", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 79, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["transition to a circular economy", "circular economy model", "circular economy principles", "promote the circular economy"],
    example_sentence: "A circular economy aims to eliminate waste by keeping products and materials in use through recycling, reuse, and remanufacturing.",
    synonyms: ["closed-loop economy", "regenerative economy", "zero-waste economy"],
    common_mistakes: ["circular economy 不是简单的回收利用; 是从设计阶段就考虑全生命周期的系统"],
    ielts_context: "Reading: environment / sustainability; Writing Task 2: environment / sustainable development",
    pronunciation: "/ˈsɜː.kjʊ.lər ɪˈkɒn.ə.mi/",
    collocations_cn: ["向循环经济转型", "循环经济模式", "循环经济原则", "促进循环经济"],
    example_sentence_cn: "循环经济旨在通过回收、再利用和再制造来保持产品和材料在使用中，从而消除浪费。",
    synonyms_cn: ["闭环经济", "再生经济", "零废弃经济"],
  },
  {
    id: "econ-073", word: "economic diversification", translation: "经济多元化", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 81, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["pursue economic diversification", "achieve economic diversification", "lack of economic diversification", "economic diversification strategy"],
    example_sentence: "Economic diversification is essential for resource-dependent countries to reduce their vulnerability to commodity price fluctuations.",
    synonyms: ["economic broadening", "sectoral diversity", "multi-industry development"],
    common_mistakes: ["economic diversification 是发展多种产业; 不是各产业平均发展"],
    ielts_context: "Reading: development economics; Writing Task 2: resource curse / development",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk daɪˌvɜː.sɪ.fɪˈkeɪ.ʃən/",
    collocations_cn: ["追求经济多元化", "实现经济多元化", "缺乏经济多元化", "经济多元化战略"],
    example_sentence_cn: "经济多元化对于依赖资源的国家至关重要，以减少其对大宗商品价格波动的脆弱性。",
    synonyms_cn: ["经济拓宽", "产业多样性", "多产业发展"],
  },
  {
    id: "econ-074", word: "human capital", translation: "人力资本", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 82, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["invest in human capital", "human capital development", "accumulate human capital", "human capital formation"],
    example_sentence: "Investing in human capital through education and training is widely regarded as one of the most effective strategies for long-term economic growth.",
    synonyms: ["workforce skills", "talent pool", "labor quality"],
    common_mistakes: ["human capital 指劳动者的知识技能和经验; physical capital 指机器设备等有形资产"],
    ielts_context: "Reading: labor economics / education; Writing Task 2: education / development",
    pronunciation: "/ˈhjuː.mən ˈkæp.ɪ.təl/",
    collocations_cn: ["投资人力资本", "人力资本开发", "积累人力资本", "人力资本形成"],
    example_sentence_cn: "通过教育和培训投资人力资本被广泛认为是实现长期经济增长最有效的策略之一。",
    synonyms_cn: ["劳动力技能", "人才库", "劳动质量"],
  },
  {
    id: "econ-075", word: "shareholder", translation: "股东", part_of_speech: "noun", band_level: "6.0", frequency_score: 83, topics: ["economy"], modules: ["reading", "speaking"],
    collocations: ["protect shareholder interests", "maximize shareholder value", "shareholder meeting", "majority shareholder"],
    example_sentence: "Companies are legally obligated to act in the best interests of their shareholders, though broader stakeholder concerns are increasingly recognized.",
    synonyms: ["stockholder", "equity holder", "investor"],
    common_mistakes: ["shareholder 是持有股票的所有者; stakeholder 包括员工、社区等更广泛的利益相关者"],
    ielts_context: "Reading: business / corporate governance; Speaking Part 3: investment / business ethics",
    pronunciation: "/ˈʃeə.həʊl.dər/",
    collocations_cn: ["保护股东利益", "最大化股东价值", "股东大会", "大股东"],
    example_sentence_cn: "公司在法律上有义务为股东的最佳利益行事，尽管更广泛的利益相关者关切正日益受到认可。",
    synonyms_cn: ["股票持有者", "股权人", "投资者"],
  },
  {
    id: "econ-076", word: "gig economy", translation: "零工经济", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 81, topics: ["economy"], modules: ["reading", "speaking"],
    collocations: ["participate in the gig economy", "rise of the gig economy", "gig economy worker", "gig economy platform"],
    example_sentence: "The gig economy offers workers flexibility but often lacks the employment protections and benefits associated with traditional full-time jobs.",
    synonyms: ["freelance economy", "on-demand economy", "platform economy"],
    common_mistakes: ["gig economy 工人通常是独立承包商而非雇员; 缺少医保、退休金等保障"],
    ielts_context: "Reading: labor trends / technology; Speaking Part 3: work / future of employment",
    pronunciation: "/ɡɪɡ ɪˈkɒn.ə.mi/",
    collocations_cn: ["参与零工经济", "零工经济的兴起", "零工经济工作者", "零工经济平台"],
    example_sentence_cn: "零工经济为工作者提供了灵活性，但往往缺乏与传统全职工作相关的就业保护和福利。",
    synonyms_cn: ["自由职业经济", "按需经济", "平台经济"],
  },
  {
    id: "econ-077", word: "austerity measures", translation: "紧缩措施", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 80, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["impose austerity measures", "implement austerity measures", "austerity measures package", "harsh austerity measures"],
    example_sentence: "Austerity measures adopted during the debt crisis involved deep cuts to public spending, which critics argue prolonged the economic downturn.",
    synonyms: ["spending cuts", "fiscal tightening", "budgetary restraint"],
    common_mistakes: ["austerity measures 是政府削减开支/增税来减少赤字; stimulus 是增加支出来刺激经济"],
    ielts_context: "Reading: public policy / economics; Writing Task 2: government spending / economic policy",
    pronunciation: "/ɒˈster.ə.ti ˈmeʒ.ərz/",
    collocations_cn: ["施加紧缩措施", "实施紧缩措施", "一揽子紧缩措施", "严厉的紧缩措施"],
    example_sentence_cn: "债务危机期间采取的紧缩措施涉及大幅削减公共支出，批评者认为这延长了经济衰退。",
    synonyms_cn: ["支出削减", "财政紧缩", "预算节制"],
  },
  {
    id: "econ-078", word: "currency depreciation", translation: "货币贬值", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 82, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["sharp currency depreciation", "managed currency depreciation", "currency depreciation risk", "benefit from currency depreciation"],
    example_sentence: "Currency depreciation can boost a country's export competitiveness but also makes imported goods more expensive for domestic consumers.",
    synonyms: ["currency devaluation", "exchange rate decline", "currency weakening"],
    common_mistakes: ["depreciation 是市场驱动的贬值; devaluation 是政府主动下调固定汇率"],
    ielts_context: "Reading: international finance / economics; Writing Task 2: trade / monetary policy",
    pronunciation: "/ˈkʌr.ən.si dɪˌpriː.ʃiˈeɪ.ʃən/",
    collocations_cn: ["急剧的货币贬值", "有管理的货币贬值", "货币贬值风险", "从货币贬值中受益"],
    example_sentence_cn: "货币贬值可以提升一国的出口竞争力，但也使进口商品对国内消费者更加昂贵。",
    synonyms_cn: ["货币跌值", "汇率下跌", "货币走弱"],
  },
  {
    id: "econ-079", word: "quantitative easing", translation: "量化宽松", part_of_speech: "noun phrase", band_level: "7.5", frequency_score: 81, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["launch quantitative easing", "quantitative easing program", "end quantitative easing", "quantitative easing policy"],
    example_sentence: "Quantitative easing involves central banks purchasing government bonds and other financial assets to inject liquidity into the economy during severe downturns.",
    synonyms: ["QE", "asset purchase program", "monetary expansion"],
    common_mistakes: ["QE 是央行购买资产来增加货币供给; 不是直接印钞发给公众"],
    ielts_context: "Reading: monetary policy / financial crisis; Listening Section 4: central banking",
    pronunciation: "/ˈkwɒn.tɪ.tə.tɪv ˈiː.zɪŋ/",
    collocations_cn: ["启动量化宽松", "量化宽松计划", "结束量化宽松", "量化宽松政策"],
    example_sentence_cn: "量化宽松涉及中央银行在严重衰退期间购买政府债券和其他金融资产以向经济注入流动性。",
    synonyms_cn: ["QE", "资产购买计划", "货币扩张"],
  },
  // ═══ 中頻 50-69 (21 个) ═══
  {
    id: "econ-080", word: "Gini coefficient", translation: "基尼系数", part_of_speech: "noun phrase", band_level: "7.5", frequency_score: 65, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["measure the Gini coefficient", "rising Gini coefficient", "Gini coefficient value", "Gini coefficient calculation"],
    example_sentence: "The Gini coefficient is a widely used measure of income inequality, ranging from zero for perfect equality to one for maximum inequality.",
    synonyms: ["inequality index", "income dispersion measure", "Lorenz-based metric"],
    common_mistakes: ["基尼系数 0=完全平等，1=完全不平等; 数值越小越平等"],
    ielts_context: "Reading: development economics / sociology; Writing Task 2: inequality / social policy",
    pronunciation: "/ˈdʒiː.ni ˌkəʊ.ɪˈfɪʃ.ənt/",
    collocations_cn: ["衡量基尼系数", "上升的基尼系数", "基尼系数值", "基尼系数计算"],
    example_sentence_cn: "基尼系数是广泛使用的收入不平等衡量指标，范围从零（完全平等）到一（完全不平等）。",
    synonyms_cn: ["不平等指数", "收入离散度指标", "洛伦兹度量"],
  },
  {
    id: "econ-081", word: "economic bubble", translation: "经济泡沫", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 68, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["create an economic bubble", "burst of the economic bubble", "housing economic bubble", "speculative economic bubble"],
    example_sentence: "An economic bubble forms when asset prices rise far above their intrinsic value due to speculative buying, eventually leading to a market crash.",
    synonyms: ["speculative bubble", "asset price bubble", "market mania"],
    common_mistakes: ["economic bubble 是资产价格远超基本面价值; bubble burst 是泡沫破裂"],
    ielts_context: "Reading: financial history / economics; Writing Task 2: financial regulation",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk ˈbʌb.əl/",
    collocations_cn: ["制造经济泡沫", "经济泡沫破裂", "房地产经济泡沫", "投机性经济泡沫"],
    example_sentence_cn: "当资产价格因投机性购买而远高于其内在价值时就会形成经济泡沫，最终导致市场崩盘。",
    synonyms_cn: ["投机泡沫", "资产价格泡沫", "市场狂热"],
  },
  {
    id: "econ-082", word: "free port", translation: "自由港", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 62, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["establish a free port", "free port zone", "free port status", "major free port"],
    example_sentence: "Free ports allow goods to be imported, stored, and re-exported without customs duties, making them hubs for international trade and logistics.",
    synonyms: ["free trade zone", "duty-free port", "special economic zone"],
    common_mistakes: ["free port 免关税但仍有海关监管; 不是完全无法治地带"],
    ielts_context: "Reading: international trade / logistics; Listening Section 4: global trade infrastructure",
    pronunciation: "/friː pɔːt/",
    collocations_cn: ["建立自由港", "自由港区", "自由港地位", "主要自由港"],
    example_sentence_cn: "自由港允许货物在免关税的情况下进口、存储和再出口，使其成为国际贸易和物流的枢纽。",
    synonyms_cn: ["自由贸易区", "免税港", "经济特区"],
  },
  {
    id: "econ-083", word: "import substitution", translation: "进口替代", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 64, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["import substitution policy", "import substitution industrialization", "pursue import substitution", "import substitution strategy"],
    example_sentence: "Import substitution industrialization was widely adopted by developing countries in the mid-20th century to reduce dependence on foreign manufactured goods.",
    synonyms: ["domestic replacement", "local production strategy", "self-sufficiency policy"],
    common_mistakes: ["import substitution 用国内生产替代进口; export orientation 则侧重出口"],
    ielts_context: "Reading: development economics; Writing Task 2: trade policy / development strategies",
    pronunciation: "/ˈɪm.pɔːt ˌsʌb.stɪˈtjuː.ʃən/",
    collocations_cn: ["进口替代政策", "进口替代工业化", "推行进口替代", "进口替代战略"],
    example_sentence_cn: "进口替代工业化在20世纪中期被发展中国家广泛采用，以减少对外国制成品的依赖。",
    synonyms_cn: ["国产替代", "本地生产策略", "自给自足政策"],
  },
  {
    id: "econ-084", word: "credit rating", translation: "信用评级", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 68, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["downgrade the credit rating", "sovereign credit rating", "credit rating agency", "maintain a credit rating"],
    example_sentence: "A sovereign credit rating downgrade can increase a country's borrowing costs and deter foreign investors from holding its debt.",
    synonyms: ["credit score", "debt rating", "creditworthiness assessment"],
    common_mistakes: ["credit rating 评估的是信用风险/违约概率; 不是经济增长前景"],
    ielts_context: "Reading: finance / international economics; Listening Section 3: financial analysis",
    pronunciation: "/ˈkred.ɪt ˈreɪ.tɪŋ/",
    collocations_cn: ["下调信用评级", "主权信用评级", "信用评级机构", "维持信用评级"],
    example_sentence_cn: "主权信用评级被下调可能增加一国的借贷成本并阻止外国投资者持有其债务。",
    synonyms_cn: ["信用评分", "债务评级", "信用评估"],
  },
  {
    id: "econ-085", word: "industrial structure", translation: "产业结构", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 66, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["upgrade the industrial structure", "optimize industrial structure", "shift in industrial structure", "traditional industrial structure"],
    example_sentence: "The transformation of a country's industrial structure from agriculture to manufacturing and services is a hallmark of economic development.",
    synonyms: ["industry composition", "sectoral framework", "production structure"],
    common_mistakes: ["industrial structure 指各产业的比重和关系; 不仅是制造业"],
    ielts_context: "Reading: development economics / industry; Writing Task 2: economic transformation",
    pronunciation: "/ɪnˈdʌs.tri.əl ˈstrʌk.tʃər/",
    collocations_cn: ["升级产业结构", "优化产业结构", "产业结构转变", "传统产业结构"],
    example_sentence_cn: "一国产业结构从农业向制造业和服务业的转型是经济发展的标志。",
    synonyms_cn: ["产业构成", "部门框架", "生产结构"],
  },
  {
    id: "econ-086", word: "gold standard", translation: "金本位", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 63, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["abandon the gold standard", "return to the gold standard", "gold standard era", "adopt the gold standard"],
    example_sentence: "The gold standard, which pegged currencies to a fixed quantity of gold, was progressively abandoned by most countries during the 20th century.",
    synonyms: ["gold-backed currency system", "bullion standard", "gold parity system"],
    common_mistakes: ["gold standard 货币与黄金挂钩; fiat money 是现代不挂钩的法定货币"],
    ielts_context: "Reading: economic history / monetary systems; Listening Section 4: history of money",
    pronunciation: "/ɡəʊld ˈstæn.dəd/",
    collocations_cn: ["放弃金本位", "恢复金本位", "金本位时代", "采用金本位"],
    example_sentence_cn: "将货币与固定数量的黄金挂钩的金本位制度在20世纪被大多数国家逐步放弃。",
    synonyms_cn: ["黄金支持货币体系", "金块本位", "黄金平价体系"],
  },
  {
    id: "econ-087", word: "economic sanctions relief", translation: "经济制裁解除", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 60, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["grant economic sanctions relief", "seek economic sanctions relief", "partial sanctions relief", "conditions for sanctions relief"],
    example_sentence: "Economic sanctions relief is often negotiated as part of diplomatic agreements, providing incentives for countries to comply with international demands.",
    synonyms: ["sanctions removal", "embargo lifting", "restriction easing"],
    common_mistakes: ["sanctions relief 是解除制裁; sanctions evasion 是规避制裁（非法）"],
    ielts_context: "Reading: international relations / diplomacy; Writing Task 2: foreign policy / conflict resolution",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk ˈsæŋk.ʃənz rɪˈliːf/",
    collocations_cn: ["给予经济制裁解除", "寻求经济制裁解除", "部分制裁解除", "制裁解除条件"],
    example_sentence_cn: "经济制裁解除通常作为外交协议的一部分进行谈判，为各国遵守国际要求提供激励。",
    synonyms_cn: ["制裁取消", "禁运解除", "限制放宽"],
  },
  {
    id: "econ-088", word: "green bond", translation: "绿色债券", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 65, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["issue green bonds", "green bond market", "green bond investment", "certified green bond"],
    example_sentence: "Green bonds are fixed-income instruments specifically earmarked to raise funds for climate and environmental projects.",
    synonyms: ["climate bond", "environmental bond", "sustainable debt instrument"],
    common_mistakes: ["green bond 资金必须用于环保项目; 普通债券无此限制"],
    ielts_context: "Reading: sustainable finance / environment; Writing Task 2: climate change / green investment",
    pronunciation: "/ɡriːn bɒnd/",
    collocations_cn: ["发行绿色债券", "绿色债券市场", "绿色债券投资", "认证绿色债券"],
    example_sentence_cn: "绿色债券是专门用于为气候和环境项目筹集资金的固定收益工具。",
    synonyms_cn: ["气候债券", "环境债券", "可持续债务工具"],
  },
  {
    id: "econ-089", word: "microfinance", translation: "微型金融", part_of_speech: "noun", band_level: "6.5", frequency_score: 67, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["provide microfinance", "microfinance institution", "microfinance loan", "microfinance services"],
    example_sentence: "Microfinance provides small loans and financial services to entrepreneurs in impoverished communities who lack access to traditional banking.",
    synonyms: ["microcredit", "small-scale lending", "grassroots finance"],
    common_mistakes: ["microfinance 不只有贷款; 还包括储蓄、保险等基本金融服务"],
    ielts_context: "Reading: development economics / poverty reduction; Writing Task 2: economic empowerment",
    pronunciation: "/ˈmaɪ.krəʊ.faɪ.næns/",
    collocations_cn: ["提供微型金融", "微型金融机构", "微型金融贷款", "微型金融服务"],
    example_sentence_cn: "微型金融向贫困社区中无法获得传统银行服务的企业家提供小额贷款和金融服务。",
    synonyms_cn: ["小额信贷", "小规模贷款", "基层金融"],
  },
  {
    id: "econ-090", word: "fiscal discipline", translation: "财政纪律", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 66, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["maintain fiscal discipline", "enforce fiscal discipline", "lack of fiscal discipline", "strict fiscal discipline"],
    example_sentence: "Fiscal discipline requires governments to balance spending with revenue over the long term, avoiding excessive borrowing that could destabilize the economy.",
    synonyms: ["budgetary restraint", "public finance prudence", "spending control"],
    common_mistakes: ["fiscal discipline 不等于 austerity; 前者强调长期自律，后者是短期紧缩"],
    ielts_context: "Reading: public finance / economics; Writing Task 2: government budgeting",
    pronunciation: "/ˈfɪs.kəl ˈdɪs.ə.plɪn/",
    collocations_cn: ["保持财政纪律", "执行财政纪律", "缺乏财政纪律", "严格财政纪律"],
    example_sentence_cn: "财政纪律要求政府在长期内平衡支出与收入，避免可能破坏经济稳定的过度借贷。",
    synonyms_cn: ["预算节制", "公共财政审慎", "支出控制"],
  },
  {
    id: "econ-091", word: "transfer payment", translation: "转移支付", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 64, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["government transfer payments", "receive transfer payments", "social transfer payments", "central-to-local transfer payment"],
    example_sentence: "Transfer payments, including pensions and unemployment benefits, redistribute income from taxpayers to vulnerable groups in society.",
    synonyms: ["welfare payment", "income transfer", "social benefit disbursement"],
    common_mistakes: ["transfer payment 是单向的资金转移; 政府购买则获得商品或服务作为回报"],
    ielts_context: "Reading: public finance / social policy; Writing Task 2: social welfare / inequality",
    pronunciation: "/ˈtræns.fɜː ˈpeɪ.mənt/",
    collocations_cn: ["政府转移支付", "接受转移支付", "社会转移支付", "中央对地方转移支付"],
    example_sentence_cn: "包括养老金和失业救济金在内的转移支付将收入从纳税人重新分配给社会中的弱势群体。",
    synonyms_cn: ["福利支付", "收入转移", "社会福利发放"],
  },
  {
    id: "econ-092", word: "competition policy", translation: "竞争政策", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 63, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["enforce competition policy", "competition policy framework", "effective competition policy", "competition policy authority"],
    example_sentence: "Competition policy ensures that firms operate in a fair market environment, preventing cartels, abuse of dominance, and anti-competitive mergers.",
    synonyms: ["antitrust policy", "market regulation", "fair competition framework"],
    common_mistakes: ["competition policy 旨在保护市场竞争; industrial policy 旨在扶持特定产业"],
    ielts_context: "Reading: business regulation / economics; Writing Task 2: market regulation / consumer protection",
    pronunciation: "/ˌkɒm.pəˈtɪʃ.ən ˈpɒl.ə.si/",
    collocations_cn: ["执行竞争政策", "竞争政策框架", "有效的竞争政策", "竞争政策主管机构"],
    example_sentence_cn: "竞争政策确保企业在公平的市场环境中运作，防止卡特尔、滥用支配地位和反竞争并购。",
    synonyms_cn: ["反垄断政策", "市场规制", "公平竞争框架"],
  },
  {
    id: "econ-093", word: "income tax", translation: "所得税", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 69, topics: ["economy"], modules: ["listening", "speaking"],
    collocations: ["pay income tax", "progressive income tax", "income tax rate", "file income tax return"],
    example_sentence: "Progressive income tax systems impose higher tax rates on higher income brackets, which helps to redistribute wealth across society.",
    synonyms: ["earnings tax", "personal tax", "revenue tax"],
    common_mistakes: ["income tax 是对个人/公司收入征税; VAT 是对消费征税"],
    ielts_context: "Listening Section 1/2: everyday finance; Speaking Part 3: taxation / public services",
    pronunciation: "/ˈɪn.kʌm tæks/",
    collocations_cn: ["缴纳所得税", "累进所得税", "所得税税率", "申报所得税"],
    example_sentence_cn: "累进所得税制度对高收入层级征收更高税率，有助于在社会中重新分配财富。",
    synonyms_cn: ["收入税", "个人税", "收益税"],
  },
  {
    id: "econ-094", word: "economic forecast", translation: "经济预测", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 68, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["revise the economic forecast", "bleak economic forecast", "economic forecast report", "downgrade the economic forecast"],
    example_sentence: "Economic forecasts by international institutions influence government policy decisions and investor expectations around the world.",
    synonyms: ["economic projection", "GDP outlook", "growth prediction"],
    common_mistakes: ["economic forecast 是基于模型的预测; 不是确定性的预言"],
    ielts_context: "Reading: economic analysis / reports; Listening Section 3: economic briefings",
    pronunciation: "/ˌiː.kəˈnɒm.ɪk ˈfɔː.kɑːst/",
    collocations_cn: ["修正经济预测", "黯淡的经济预测", "经济预测报告", "下调经济预测"],
    example_sentence_cn: "国际机构的经济预测影响全球的政府政策决策和投资者预期。",
    synonyms_cn: ["经济预判", "GDP展望", "增长预测"],
  },
  {
    id: "econ-095", word: "startup", translation: "初创企业", part_of_speech: "noun", band_level: "5.5", frequency_score: 67, topics: ["economy"], modules: ["reading", "speaking"],
    collocations: ["launch a startup", "tech startup", "startup ecosystem", "startup funding round"],
    example_sentence: "Startups play a vital role in driving innovation and job creation, though a significant proportion fail within the first few years of operation.",
    synonyms: ["new venture", "fledgling company", "early-stage enterprise"],
    common_mistakes: ["startup 是快速成长的新公司; small business 可能是传统小店，不一定追求高增长"],
    ielts_context: "Reading: business / entrepreneurship; Speaking Part 3: innovation / career choices",
    pronunciation: "/ˈstɑːt.ʌp/",
    collocations_cn: ["创办初创企业", "科技初创企业", "初创企业生态系统", "初创企业融资轮"],
    example_sentence_cn: "初创企业在推动创新和创造就业方面发挥着关键作用，尽管相当大比例在运营的头几年内失败。",
    synonyms_cn: ["新创企业", "初生公司", "早期企业"],
  },
  {
    id: "econ-096", word: "risk aversion", translation: "风险规避", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 62, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["investor risk aversion", "high risk aversion", "increase in risk aversion", "degree of risk aversion"],
    example_sentence: "During periods of economic uncertainty, heightened risk aversion among investors leads to capital flight from emerging markets to safe-haven assets.",
    synonyms: ["risk avoidance", "cautionary investing", "conservative stance"],
    common_mistakes: ["risk aversion 是避免风险的行为倾向; risk management 是管理风险的策略"],
    ielts_context: "Reading: behavioral economics / finance; Listening Section 4: investment psychology",
    pronunciation: "/rɪsk əˈvɜː.ʃən/",
    collocations_cn: ["投资者风险规避", "高风险规避", "风险规避上升", "风险规避程度"],
    example_sentence_cn: "在经济不确定时期，投资者加剧的风险规避导致资本从新兴市场逃向避险资产。",
    synonyms_cn: ["风险回避", "谨慎投资", "保守立场"],
  },
  {
    id: "econ-097", word: "cost-benefit analysis", translation: "成本效益分析", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 66, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["conduct a cost-benefit analysis", "cost-benefit analysis framework", "thorough cost-benefit analysis", "cost-benefit analysis results"],
    example_sentence: "Cost-benefit analysis is a systematic approach used by policymakers to evaluate whether the economic benefits of a project outweigh its costs.",
    synonyms: ["CBA", "economic appraisal", "benefit-cost assessment"],
    common_mistakes: ["cost-benefit analysis 量化所有成本和收益; 有些非经济因素难以量化"],
    ielts_context: "Reading: public policy / project evaluation; Writing Task 2: government investment decisions",
    pronunciation: "/kɒst ˈben.ɪ.fɪt əˈnæl.ə.sɪs/",
    collocations_cn: ["进行成本效益分析", "成本效益分析框架", "彻底的成本效益分析", "成本效益分析结果"],
    example_sentence_cn: "成本效益分析是政策制定者用来评估项目的经济效益是否超过其成本的系统性方法。",
    synonyms_cn: ["CBA", "经济评估", "效益成本评估"],
  },
  {
    id: "econ-098", word: "natural resource rent", translation: "自然资源租金", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 61, topics: ["economy"], modules: ["reading", "listening"],
    collocations: ["extract natural resource rent", "natural resource rent distribution", "dependence on natural resource rent", "capture natural resource rent"],
    example_sentence: "Natural resource rent refers to the excess revenue generated from resource extraction beyond the cost of production, which can lead to governance challenges.",
    synonyms: ["resource windfall", "commodity surplus", "extractive revenue"],
    common_mistakes: ["natural resource rent 是超额收益; 不是租金的字面含义"],
    ielts_context: "Reading: resource economics / governance; Listening Section 4: resource curse",
    pronunciation: "/ˈnætʃ.ər.əl rɪˈsɔːs rent/",
    collocations_cn: ["获取自然资源租金", "自然资源租金分配", "对自然资源租金的依赖", "占有自然资源租金"],
    example_sentence_cn: "自然资源租金是指资源开采产生的超过生产成本的超额收入，这可能导致治理挑战。",
    synonyms_cn: ["资源暴利", "大宗商品盈余", "采掘收入"],
  },
  {
    id: "econ-099", word: "underground economy", translation: "地下经济", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 64, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["size of the underground economy", "participate in the underground economy", "underground economy activities", "curb the underground economy"],
    example_sentence: "The underground economy encompasses unreported income from legal activities and illicit trade, making it difficult for governments to collect accurate tax revenue.",
    synonyms: ["shadow economy", "informal sector", "black market"],
    common_mistakes: ["underground economy 包括合法但未报税活动+非法活动; black market 仅指非法交易"],
    ielts_context: "Reading: economics / governance; Writing Task 2: taxation / informal employment",
    pronunciation: "/ˌʌn.dəˈɡraʊnd ɪˈkɒn.ə.mi/",
    collocations_cn: ["地下经济规模", "参与地下经济", "地下经济活动", "遏制地下经济"],
    example_sentence_cn: "地下经济包括合法活动的未申报收入和非法贸易，使政府难以获得准确的税收收入。",
    synonyms_cn: ["影子经济", "非正规部门", "黑市"],
  },
  {
    id: "econ-100", word: "trade facilitation", translation: "贸易便利化", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 63, topics: ["economy"], modules: ["reading", "writing"],
    collocations: ["promote trade facilitation", "trade facilitation agreement", "trade facilitation measures", "enhance trade facilitation"],
    example_sentence: "Trade facilitation focuses on simplifying customs procedures and reducing administrative barriers to speed up the cross-border movement of goods.",
    synonyms: ["customs modernization", "border efficiency improvement", "trade streamlining"],
    common_mistakes: ["trade facilitation 是简化贸易程序; trade liberalization 是降低/取消关税"],
    ielts_context: "Reading: international trade / logistics; Writing Task 2: global commerce / development",
    pronunciation: "/treɪd fəˌsɪl.ɪˈteɪ.ʃən/",
    collocations_cn: ["促进贸易便利化", "贸易便利化协定", "贸易便利化措施", "加强贸易便利化"],
    example_sentence_cn: "贸易便利化侧重于简化海关程序和减少行政壁垒，以加快货物的跨境流动。",
    synonyms_cn: ["海关现代化", "边境效率提升", "贸易流程简化"],
  },
];