// scripts/expand-city.ts
// Phase 2: City 话题扩展 — city-051 ~ city-100（50 个新词块）
// 频次分布: 超高(90-99)×20 + 高(70-89)×18 + 中(50-69)×12

import type { Chunk } from "../types/chunk";

export const CITY_EXPANSION: Chunk[] = [
  // ═══ 超高頻 90-99 (20 个) ═══
  {
    id: "city-051", word: "affordable housing", translation: "经济适用房", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 97, topics: ["city"], modules: ["writing", "reading"],
    collocations: ["provide affordable housing", "lack of affordable housing", "affordable housing scheme", "develop affordable housing"],
    example_sentence: "The shortage of affordable housing in major cities has forced many low-income families to relocate to distant suburbs.",
    synonyms: ["low-cost housing", "subsidized accommodation", "budget-friendly homes"],
    common_mistakes: ["affordable housing 不仅是政府补贴住房; 也包括市场价格下的可负担住房"],
    ielts_context: "Writing Task 2: urbanization / housing; Reading: city planning",
    pronunciation: "/əˈfɔː.də.bəl ˈhaʊ.zɪŋ/",
    collocations_cn: ["提供经济适用房", "缺乏经济适用房", "经济适用房计划", "开发经济适用房"],
    example_sentence_cn: "主要城市经济适用房短缺迫使许多低收入家庭迁移到远郊。",
    synonyms_cn: ["低成本住房", "补贴住房", "价格亲民的住房"],
  },
  {
    id: "city-052", word: "building code", translation: "建筑规范", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["city"], modules: ["reading", "listening"],
    collocations: ["comply with building codes", "enforce building codes", "update building codes", "strict building codes"],
    example_sentence: "Building codes establish minimum safety standards for construction, including structural integrity, fire protection, and accessibility.",
    synonyms: ["construction regulation", "structural safety standard", "building ordinance"],
    common_mistakes: ["building code 是法律要求的最低标准; 不是建筑设计建议"],
    ielts_context: "Reading: urban planning / construction; Listening: property / planning",
    pronunciation: "/ˈbɪl.dɪŋ kəʊd/",
    collocations_cn: ["遵守建筑规范", "执行建筑规范", "更新建筑规范", "严格的建筑规范"],
    example_sentence_cn: "建筑规范为施工设立了最低安全标准，包括结构完整性、消防和可及性。",
    synonyms_cn: ["建筑法规", "结构安全标准", "建筑条例"],
  },
  {
    id: "city-053", word: "property value", translation: "房产价值", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 91, topics: ["city"], modules: ["reading", "speaking"],
    collocations: ["increase property values", "declining property values", "assess property values", "boost property values"],
    example_sentence: "The construction of a new metro line typically leads to a significant increase in nearby property values.",
    synonyms: ["real estate price", "housing worth", "land valuation"],
    common_mistakes: ["property value 受位置、交通、学区、设施等多重因素影响"],
    ielts_context: "Reading: real estate / economics; Speaking Part 3: housing / investment",
    pronunciation: "/ˈprɒp.ə.ti ˈvæl.juː/",
    collocations_cn: ["提高房产价值", "房产价值下降", "评估房产价值", "提升房产价值"],
    example_sentence_cn: "新地铁线路的建设通常会导致周边房产价值显著增加。",
    synonyms_cn: ["房地产价格", "房屋价值", "土地估值"],
  },
  {
    id: "city-054", word: "community center", translation: "社区中心", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["city"], modules: ["speaking", "listening"],
    collocations: ["local community center", "visit the community center", "community center activities", "build a community center"],
    example_sentence: "Community centers play a vital role in bringing residents together through recreational programs, educational classes, and social events.",
    synonyms: ["neighborhood hub", "recreation center", "civic center"],
    common_mistakes: ["community center 是社区公共设施; community hall 通常指可租借的室内活动场所"],
    ielts_context: "Speaking Part 2: local facility; Listening Section 2: community announcement",
    pronunciation: "/kəˈmjuː.nə.ti ˈsen.tər/",
    collocations_cn: ["当地社区中心", "参观社区中心", "社区中心活动", "建设社区中心"],
    example_sentence_cn: "社区中心通过娱乐活动、教育课程和社交活动在凝聚居民方面发挥着关键作用。",
    synonyms_cn: ["邻里中心", "文娱中心", "市民中心"],
  },
  {
    id: "city-055", word: "high-rise building", translation: "高层建筑", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 92, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["live in a high-rise building", "modern high-rise building", "glass high-rise building", "high-rise building complex"],
    example_sentence: "High-rise buildings have become the dominant architectural form in densely populated cities where land is scarce and expensive.",
    synonyms: ["skyscraper", "tower block", "multi-story structure"],
    common_mistakes: ["high-rise 有连字符; 通常指12层以上的建筑"],
    ielts_context: "Speaking Part 3: city living / architecture; Reading: urban development",
    pronunciation: "/haɪ raɪz ˈbɪl.dɪŋ/",
    collocations_cn: ["住在高层建筑中", "现代高层建筑", "玻璃幕墙高层建筑", "高层建筑群"],
    example_sentence_cn: "在土地稀缺且昂贵的人口密集城市，高层建筑已成为主导的建筑形式。",
    synonyms_cn: ["摩天大楼", "塔楼", "多层结构"],
  },
  {
    id: "city-056", word: "zoning regulation", translation: "分区规划法规", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["enforce zoning regulations", "change zoning regulations", "local zoning regulations", "comply with zoning regulations"],
    example_sentence: "Zoning regulations determine whether land can be used for residential, commercial, or industrial purposes, shaping the character of urban neighborhoods.",
    synonyms: ["land-use control", "urban division rules", "planning restrictions"],
    common_mistakes: ["zoning regulations 决定土地用途; building codes 决定建筑如何建造"],
    ielts_context: "Reading: urban planning / law; Writing Task 2: city development",
    pronunciation: "/ˈzəʊ.nɪŋ ˌreɡ.jʊˈleɪ.ʃən/",
    collocations_cn: ["执行分区规划法规", "更改分区规划法规", "当地分区规划法规", "遵守分区规划法规"],
    example_sentence_cn: "分区规划法规决定土地可用于住宅、商业还是工业用途，塑造着城市社区的特征。",
    synonyms_cn: ["土地使用管制", "城市规划规则", "规划限制"],
  },
  {
    id: "city-057", word: "emergency service", translation: "应急服务", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["city"], modules: ["listening", "reading"],
    collocations: ["call emergency services", "emergency service response", "coordinate emergency services", "emergency service personnel"],
    example_sentence: "Well-funded emergency services including police, fire departments, and ambulance networks are essential for urban safety and crisis management.",
    synonyms: ["first responders", "rescue services", "crisis response teams"],
    common_mistakes: ["emergency services 指警察、消防、急救等的总称; emergency room 只是医院的一个部门"],
    ielts_context: "Listening Section 2: public safety announcement; Reading: city governance",
    pronunciation: "/ɪˈmɜː.dʒən.si ˈsɜː.vɪs/",
    collocations_cn: ["呼叫应急服务", "应急服务响应", "协调应急服务", "应急服务人员"],
    example_sentence_cn: "资金充足的应急服务，包括警察、消防部门和救护网络，对于城市安全和危机管理至关重要。",
    synonyms_cn: ["第一响应者", "救援服务", "危机响应团队"],
  },
  {
    id: "city-058", word: "cultural venue", translation: "文化场所", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["visit cultural venues", "popular cultural venue", "cultural venue district", "historic cultural venue"],
    example_sentence: "Cities with vibrant cultural venues such as museums, theaters, and concert halls tend to attract more tourists and creative professionals.",
    synonyms: ["cultural institution", "arts facility", "heritage site"],
    common_mistakes: ["cultural venue 不仅包括博物馆，也包括音乐厅、剧院、画廊等"],
    ielts_context: "Speaking Part 2: cultural visit; Reading: tourism / city guide",
    pronunciation: "/ˈkʌl.tʃər.əl ˈven.juː/",
    collocations_cn: ["参观文化场所", "受欢迎的文化场所", "文化场所区", "历史性文化场所"],
    example_sentence_cn: "拥有博物馆、剧院和音乐厅等充满活力的文化场所的城市往往吸引更多游客和创意专业人士。",
    synonyms_cn: ["文化机构", "艺术设施", "文物古迹"],
  },
  {
    id: "city-059", word: "urban heat island", translation: "城市热岛效应", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["mitigate the urban heat island effect", "contribute to the urban heat island", "urban heat island phenomenon", "reduce urban heat island effects"],
    example_sentence: "The urban heat island effect causes city temperatures to be several degrees higher than surrounding rural areas due to heat-absorbing surfaces like asphalt and concrete.",
    synonyms: ["city heat retention", "metropolitan warming", "thermal island effect"],
    common_mistakes: ["urban heat island 是一个气象术语，不是一个真正的「岛」"],
    ielts_context: "Reading: environmental science / urban planning; Writing Task 2: city environment",
    pronunciation: "/ˈɜː.bən hiːt ˈaɪ.lənd/",
    collocations_cn: ["缓解城市热岛效应", "加剧城市热岛效应", "城市热岛现象", "减少城市热岛效应"],
    example_sentence_cn: "城市热岛效应导致城市温度比周围农村地区高出几度，这是因为沥青和混凝土等吸热表面所致。",
    synonyms_cn: ["城市蓄热效应", "都市变暖", "热岛现象"],
  },
  {
    id: "city-060", word: "public library", translation: "公共图书馆", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 91, topics: ["city"], modules: ["speaking", "listening"],
    collocations: ["visit the public library", "local public library", "public library services", "digital public library"],
    example_sentence: "Public libraries have evolved beyond book lending to become community hubs offering digital resources, workshops, and social services.",
    synonyms: ["municipal library", "community library", "free public archive"],
    common_mistakes: ["public library 是免费向公众开放的; university library 可能有限制"],
    ielts_context: "Speaking Part 2: favorite place; Listening Section 1: library information",
    pronunciation: "/ˈpʌb.lɪk ˈlaɪ.brər.i/",
    collocations_cn: ["访问公共图书馆", "当地公共图书馆", "公共图书馆服务", "数字公共图书馆"],
    example_sentence_cn: "公共图书馆已超越借书的范畴，转变为提供数字资源、工作坊和社会服务的社区中心。",
    synonyms_cn: ["市立图书馆", "社区图书馆", "免费公共档案馆"],
  },
  {
    id: "city-061", word: "city skyline", translation: "城市天际线", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["iconic city skyline", "dominate the city skyline", "transform the city skyline", "view the city skyline"],
    example_sentence: "The construction of several new skyscrapers has dramatically transformed the city skyline over the past decade.",
    synonyms: ["urban skyline", "metropolitan profile", "city silhouette"],
    common_mistakes: ["skyline 一个词; 不要写为 sky line"],
    ielts_context: "Speaking Part 2: describe a city view; Reading: architecture / travel",
    pronunciation: "/ˈsɪt.i ˈskaɪ.laɪn/",
    collocations_cn: ["标志性的城市天际线", "主宰城市天际线", "改变城市天际线", "观赏城市天际线"],
    example_sentence_cn: "过去十年间，几座新摩天大楼的建设极大地改变了城市天际线。",
    synonyms_cn: ["都市轮廓", "城市剪影", "城市全景"],
  },
  {
    id: "city-062", word: "construction permit", translation: "建筑许可证", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["city"], modules: ["reading", "listening"],
    collocations: ["apply for a construction permit", "obtain a construction permit", "require a construction permit", "issue a construction permit"],
    example_sentence: "Before any major renovation or new build can begin, property owners must obtain a construction permit from the local planning authority.",
    synonyms: ["building permit", "development approval", "planning permission"],
    common_mistakes: ["construction permit 是政府发放的合法施工许可; 不是 contractor 的报价单"],
    ielts_context: "Reading: property development / law; Listening: planning / construction",
    pronunciation: "/kənˈstrʌk.ʃən ˈpɜː.mɪt/",
    collocations_cn: ["申请建筑许可证", "获得建筑许可证", "需要建筑许可证", "发放建筑许可证"],
    example_sentence_cn: "在进行任何重大装修或新建之前，业主必须从当地规划部门获得建筑许可证。",
    synonyms_cn: ["建设许可", "开发批准", "规划许可"],
  },
  {
    id: "city-063", word: "neighborhood safety", translation: "社区安全", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 93, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["ensure neighborhood safety", "concerned about neighborhood safety", "improve neighborhood safety", "neighborhood safety measures"],
    example_sentence: "Neighborhood safety is consistently ranked as one of the most important factors when families choose where to live.",
    synonyms: ["community security", "residential area safety", "local public safety"],
    common_mistakes: ["neighborhood safety 不仅指低犯罪率; 还包括交通安全、照明和邻里关系"],
    ielts_context: "Speaking Part 3: urban living / crime; Reading: city planning / sociology",
    pronunciation: "/ˈneɪ.bə.hʊd ˈseɪf.ti/",
    collocations_cn: ["确保社区安全", "担心社区安全", "改善社区安全", "社区安全措施"],
    example_sentence_cn: "社区安全一直被认为是家庭选择居住地时最重要的因素之一。",
    synonyms_cn: ["社区治安", "住宅区安全", "地方公共安全"],
  },
  {
    id: "city-064", word: "waste management system", translation: "垃圾管理系统", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 92, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["improve waste management systems", "efficient waste management system", "implement a waste management system", "integrated waste management system"],
    example_sentence: "An efficient waste management system encompassing collection, sorting, recycling, and disposal is critical for maintaining urban hygiene.",
    synonyms: ["refuse management infrastructure", "solid waste system", "waste disposal network"],
    common_mistakes: ["waste management 包括减少、再利用、回收、处理和最终处置的全过程"],
    ielts_context: "Reading: urban infrastructure / environment; Writing Task 2: city services",
    pronunciation: "/weɪst ˈmæn.ɪdʒ.mənt ˈsɪs.təm/",
    collocations_cn: ["改善垃圾管理系统", "高效的垃圾管理系统", "实施垃圾管理系统", "综合性垃圾管理系统"],
    example_sentence_cn: "一个涵盖收集、分类、回收和处置的高效垃圾管理系统对维护城市卫生至关重要。",
    synonyms_cn: ["垃圾管理基础设施", "固体废物系统", "废物处理网络"],
  },
  {
    id: "city-065", word: "real estate market", translation: "房地产市场", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 94, topics: ["city"], modules: ["reading", "speaking"],
    collocations: ["booming real estate market", "real estate market crash", "regulate the real estate market", "competitive real estate market"],
    example_sentence: "The real estate market in major global cities has seen unprecedented price growth, making home ownership increasingly unattainable for young people.",
    synonyms: ["property market", "housing market sector", "land and building trade"],
    common_mistakes: ["real estate (房地产) 包括土地及其上的建筑物; housing market 侧重住宅"],
    ielts_context: "Reading: economics / business; Speaking Part 3: housing / investment",
    pronunciation: "/rɪəl ɪˈsteɪt ˈmɑː.kɪt/",
    collocations_cn: ["繁荣的房地产市场", "房地产市场崩盘", "监管房地产市场", "竞争激烈的房地产市场"],
    example_sentence_cn: "全球主要城市的房地产市场经历了前所未有的价格增长，使购房对年轻人来说越来越难以实现。",
    synonyms_cn: ["房产市场", "住房市场部门", "土地与建筑交易"],
  },
  {
    id: "city-066", word: "urban congestion", translation: "城市拥堵", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 94, topics: ["city"], modules: ["writing", "speaking"],
    collocations: ["reduce urban congestion", "worsening urban congestion", "alleviate urban congestion", "urban congestion charge"],
    example_sentence: "Urban congestion not only wastes commuters' time but also increases fuel consumption and worsens air quality.",
    synonyms: ["traffic gridlock", "city overcrowding", "metropolitan bottleneck"],
    common_mistakes: ["congestion 是不可数名词; 可以 severe congestion 但不 a congestion"],
    ielts_context: "Writing Task 2: transport / city planning; Speaking Part 3: city life",
    pronunciation: "/ˈɜː.bən kənˈdʒes.tʃən/",
    collocations_cn: ["减少城市拥堵", "日益严重的城市拥堵", "缓解城市拥堵", "城市拥堵费"],
    example_sentence_cn: "城市拥堵不仅浪费通勤者的时间，还增加燃料消耗并恶化空气质量。",
    synonyms_cn: ["交通堵死", "城市过度拥挤", "都市瓶颈"],
  },
  {
    id: "city-067", word: "urban design", translation: "城市设计", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["principles of urban design", "sustainable urban design", "urban design project", "human-centered urban design"],
    example_sentence: "Good urban design prioritizes walkability, public spaces, and human-scale environments over car-centric infrastructure.",
    synonyms: ["city design", "town planning aesthetics", "urban layout design"],
    common_mistakes: ["urban design 关注城市空间的物理形态和美学; urban planning 更关注政策、法规和功能分区"],
    ielts_context: "Reading: architecture / city planning; Writing Task 2: city development",
    pronunciation: "/ˈɜː.bən dɪˈzaɪn/",
    collocations_cn: ["城市设计原则", "可持续城市设计", "城市设计项目", "以人为本的城市设计"],
    example_sentence_cn: "好的城市设计优先考虑步行性、公共空间和人性化尺度环境，而非以汽车为中心的基础设施。",
    synonyms_cn: ["城市规划", "市镇美学布局", "都市布局设计"],
  },
  {
    id: "city-068", word: "parking facility", translation: "停车设施", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["city"], modules: ["listening", "speaking"],
    collocations: ["provide parking facilities", "underground parking facility", "lack of parking facilities", "public parking facility"],
    example_sentence: "Many cities are reducing surface parking facilities in their centers and replacing them with pedestrian-friendly plazas and green spaces.",
    synonyms: ["car park", "parking structure", "vehicle storage area"],
    common_mistakes: ["parking facility 可以指地面停车场、地下停车场或多层停车楼"],
    ielts_context: "Listening Section 1: city travel / directions; Speaking Part 3: driving / transport",
    pronunciation: "/ˈpɑː.kɪŋ fəˈsɪl.ɪ.ti/",
    collocations_cn: ["提供停车设施", "地下停车设施", "缺乏停车设施", "公共停车设施"],
    example_sentence_cn: "许多城市正在减少中心的露天停车设施，用适合步行的广场和绿地取而代之。",
    synonyms_cn: ["停车场", "停车楼", "车辆存放区"],
  },
  {
    id: "city-069", word: "public space", translation: "公共空间", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 93, topics: ["city"], modules: ["speaking", "writing"],
    collocations: ["create public spaces", "vibrant public space", "access to public spaces", "well-designed public space"],
    example_sentence: "Well-designed public spaces such as parks, plazas, and pedestrian streets foster social interaction and strengthen community bonds.",
    synonyms: ["civic area", "common space", "open-access urban area"],
    common_mistakes: ["public space 指所有人都可自由出入的区域; 商场是 privately owned public space"],
    ielts_context: "Writing Task 2: urban life / community; Speaking Part 3: city quality",
    pronunciation: "/ˈpʌb.lɪk speɪs/",
    collocations_cn: ["创造公共空间", "充满活力的公共空间", "获取公共空间", "精心设计的公共空间"],
    example_sentence_cn: "精心设计的公共空间，如公园、广场和步行街，促进社会互动并加强社区纽带。",
    synonyms_cn: ["市民区域", "公共用地", "开放城市空间"],
  },
  {
    id: "city-070", word: "infrastructure maintenance", translation: "基础设施维护", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 91, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["fund infrastructure maintenance", "neglect infrastructure maintenance", "routine infrastructure maintenance", "infrastructure maintenance backlog"],
    example_sentence: "Chronic underfunding of infrastructure maintenance has left many cities with crumbling roads, leaking water pipes, and unreliable power grids.",
    synonyms: ["civil works upkeep", "public works repair", "facility management"],
    common_mistakes: ["maintenance 是持续性的维护; construction 是一次性的建设"],
    ielts_context: "Reading: public finance / urban management; Writing Task 2: government spending",
    pronunciation: "/ˈɪn.frəˌstrʌk.tʃər ˈmeɪn.tɪ.nəns/",
    collocations_cn: ["为基础设施维护拨款", "忽视基础设施维护", "常规基础设施维护", "基础设施维护积压"],
    example_sentence_cn: "长期对基础设施维护拨款不足导致许多城市道路破损、水管渗漏和电网不可靠。",
    synonyms_cn: ["土建维护", "公共工程修缮", "设施管理"],
  },
  // ═══ 高頻 70-89 (18 个) ═══
  {
    id: "city-071", word: "suburban sprawl", translation: "郊区蔓延", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 85, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["control suburban sprawl", "low-density suburban sprawl", "limit suburban sprawl", "consequences of suburban sprawl"],
    example_sentence: "Suburban sprawl has consumed vast areas of farmland and natural habitat while increasing car dependency and commute times.",
    synonyms: ["urban expansion", "metropolitan spread", "outward city growth"],
    common_mistakes: ["sprawl 表示无序、低密度的蔓延，通常带有负面含义"],
    ielts_context: "Reading: urban studies / environment; Writing Task 2: city growth",
    pronunciation: "/səˈbɜː.bən sprɔːl/",
    collocations_cn: ["控制郊区蔓延", "低密度郊区蔓延", "限制郊区蔓延", "郊区蔓延的后果"],
    example_sentence_cn: "郊区蔓延消耗了大量农田和自然栖息地，同时增加了汽车依赖和通勤时间。",
    synonyms_cn: ["城市扩张", "都市蔓延", "城区向外扩展"],
  },
  {
    id: "city-072", word: "public transit", translation: "公共交通", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 87, topics: ["city"], modules: ["speaking", "listening"],
    collocations: ["use public transit", "reliable public transit", "expand public transit", "invest in public transit"],
    example_sentence: "Expanding reliable public transit is one of the most effective strategies for reducing traffic congestion and carbon emissions in cities.",
    synonyms: ["mass transit", "public conveyance", "communal transport"],
    common_mistakes: ["public transit 通常指 buses, trains, subways, trams; 不包括 taxis"],
    ielts_context: "Speaking Part 3: city transport; Listening Section 2: travel information",
    pronunciation: "/ˈpʌb.lɪk ˈtræn.zɪt/",
    collocations_cn: ["使用公共交通", "可靠的公共交通", "扩展公共交通", "投资公共交通"],
    example_sentence_cn: "扩展可靠的公共交通是减少城市交通拥堵和碳排放最有效的策略之一。",
    synonyms_cn: ["大众运输", "公共运载", "公共交通工具"],
  },
  {
    id: "city-073", word: "property development", translation: "房地产开发", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 82, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["engage in property development", "large-scale property development", "property development company", "residential property development"],
    example_sentence: "Rapid property development in urban fringe areas has transformed former industrial sites into sought-after residential neighborhoods.",
    synonyms: ["real estate development", "land development", "construction project"],
    common_mistakes: ["property development 包括从土地收购、融资到设计、施工、销售的全过程"],
    ielts_context: "Reading: business / real estate; Writing Task 2: urban growth",
    pronunciation: "/ˈprɒp.ə.ti dɪˈvel.əp.mənt/",
    collocations_cn: ["从事房地产开发", "大规模房地产开发", "房地产开发公司", "住宅房地产开发"],
    example_sentence_cn: "城市边缘地区的快速房地产开发已将前工业用地转变为抢手的住宅社区。",
    synonyms_cn: ["房地产发展", "土地开发", "建设项目"],
  },
  {
    id: "city-074", word: "rural-urban migration", translation: "农村向城市迁移", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 83, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["mass urban migration", "drive urban migration", "rural-to-urban migration", "rapid urban migration"],
    example_sentence: "Rural-to-urban migration continues to reshape the demographic landscape of developing countries at an unprecedented pace.",
    synonyms: ["cityward movement", "urbanization trend", "metropolitan influx"],
    common_mistakes: ["urban migration 是从乡村到城市的大规模人口流入; emigration 是跨国迁移"],
    ielts_context: "Reading: demography / sociology; Writing Task 2: urbanization",
    pronunciation: "/ˈrʊə.rəl ˈɜː.bən maɪˈɡreɪ.ʃən/",
    collocations_cn: ["大规模城镇化迁移", "推动城镇化迁移", "农村向城市迁移", "快速的城镇化迁移"],
    example_sentence_cn: "农村向城市的迁移继续以前所未有的速度重塑发展中国家的人口格局。",
    synonyms_cn: ["向城市迁移", "城镇化趋势", "都市人口涌入"],
  },
  {
    id: "city-075", word: "tourist attraction", translation: "旅游景点", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 80, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["visit a tourist attraction", "major tourist attraction", "popular tourist attraction", "iconic tourist attraction"],
    example_sentence: "The city's historic district has become a major tourist attraction, drawing millions of visitors annually and supporting the local economy.",
    synonyms: ["visitor destination", "sightseeing spot", "point of interest"],
    common_mistakes: ["tourist attraction 可以是自然景观、历史建筑或文化活动"],
    ielts_context: "Speaking Part 2: travel / city visit; Reading: travel guides",
    pronunciation: "/ˈtʊə.rɪst əˈtræk.ʃən/",
    collocations_cn: ["参观旅游景点", "主要旅游景点", "热门旅游景点", "标志性旅游景点"],
    example_sentence_cn: "该市的历史街区已成为一个主要旅游景点，每年吸引数百万游客并支撑当地经济。",
    synonyms_cn: ["旅游目的地", "观光景点", "兴趣点"],
  },
  {
    id: "city-076", word: "social housing", translation: "社会住房", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 84, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["provide social housing", "social housing project", "access to social housing", "social housing waiting list"],
    example_sentence: "Social housing programs aim to ensure that low-income families and vulnerable individuals have access to safe and decent accommodation.",
    synonyms: ["public housing", "council housing", "affordable housing scheme"],
    common_mistakes: ["social housing 是政府或非营利组织为低收入群体提供的补贴住房"],
    ielts_context: "Reading: social policy / urban planning; Writing Task 2: housing / inequality",
    pronunciation: "/ˈsəʊ.ʃəl ˈhaʊ.zɪŋ/",
    collocations_cn: ["提供社会住房", "社会住房项目", "获取社会住房", "社会住房等候名单"],
    example_sentence_cn: "社会住房项目旨在确保低收入家庭和弱势群体能够获得安全和体面的住所。",
    synonyms_cn: ["公共住房", "市建住房", "经济适用房计划"],
  },
  {
    id: "city-077", word: "heritage conservation", translation: "遗产保护", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 80, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["promote heritage conservation", "architectural heritage conservation", "heritage conservation area", "support heritage conservation"],
    example_sentence: "Heritage conservation strikes a delicate balance between preserving historical character and accommodating modern urban needs.",
    synonyms: ["historical preservation", "cultural heritage protection", "architectural conservation"],
    common_mistakes: ["conservation 是保护和管理以保持其价值; preservation 是完全保持原样不变"],
    ielts_context: "Reading: architecture / culture; Writing Task 2: development vs preservation",
    pronunciation: "/ˈher.ɪ.tɪdʒ ˌkɒn.səˈveɪ.ʃən/",
    collocations_cn: ["促进遗产保护", "建筑遗产保护", "遗产保护区", "支持遗产保护"],
    example_sentence_cn: "遗产保护在保留历史特色和满足现代城市需求之间取得了微妙的平衡。",
    synonyms_cn: ["历史保护", "文化遗产保护", "建筑保护"],
  },
  {
    id: "city-078", word: "street hawker", translation: "街头小贩", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 78, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["buy from a street vendor", "licensed street vendor", "street vendor market", "illegal street vendor"],
    example_sentence: "Street vendors contribute to a city's informal economy and cultural vibrancy, but their presence raises questions about regulation and public space.",
    synonyms: ["hawker", "peddler", "informal trader"],
    common_mistakes: ["street vendor 和 food stall 不同; vendor 可以是移动的推车，stall 通常是固定的摊位"],
    ielts_context: "Speaking Part 2: city experience / food; Reading: urban studies / economics",
    pronunciation: "/striːt ˈhɔː.kər/",
    collocations_cn: ["从街头小贩购买", "持牌街头小贩", "街头小贩市场", "非法街头小贩"],
    example_sentence_cn: "街头小贩为城市的非正规经济和文化活力做出贡献，但他们的存在引发了关于监管和公共空间的问题。",
    synonyms_cn: ["小贩", "摊贩", "非正规商贩"],
  },
  {
    id: "city-079", word: "disaster preparedness", translation: "灾害准备", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 79, topics: ["city"], modules: ["reading", "listening"],
    collocations: ["improve disaster preparedness", "disaster preparedness plan", "invest in disaster preparedness", "lack of disaster preparedness"],
    example_sentence: "Cities in earthquake-prone regions must invest heavily in disaster preparedness, including early warning systems and evacuation infrastructure.",
    synonyms: ["emergency readiness", "crisis anticipation", "catastrophe planning"],
    common_mistakes: ["disaster preparedness 是灾害发生前的准备和规划; disaster response 是灾害发生后的应对"],
    ielts_context: "Reading: urban safety / resilience; Listening: public safety announcement",
    pronunciation: "/dɪˈzɑː.stər prɪˈpeə.rɪd.nəs/",
    collocations_cn: ["改善灾害准备", "灾害准备计划", "投资灾害准备", "缺乏灾害准备"],
    example_sentence_cn: "地震多发地区的城市必须大量投资灾害准备，包括预警系统和疏散基础设施。",
    synonyms_cn: ["应急准备", "危机预防", "灾难规划"],
  },
  {
    id: "city-080", word: "urban agriculture", translation: "城市农业", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 76, topics: ["city"], modules: ["reading", "speaking"],
    collocations: ["practice urban agriculture", "urban agriculture initiative", "rooftop urban agriculture", "promote urban agriculture"],
    example_sentence: "Urban agriculture on vacant lots and rooftops can improve food security, reduce food miles, and strengthen community connections.",
    synonyms: ["city farming", "metropolitan cultivation", "intra-urban food production"],
    common_mistakes: ["urban agriculture 包括个人菜园到商业城市农场; 不限于 community garden"],
    ielts_context: "Reading: sustainable cities / food systems; Speaking Part 3: city living",
    pronunciation: "/ˈɜː.bən ˈæɡ.rɪ.kʌl.tʃər/",
    collocations_cn: ["进行城市农业", "城市农业倡议", "屋顶城市农业", "推广城市农业"],
    example_sentence_cn: "在闲置土地和屋顶上的城市农业可以改善食品安全、减少食物运输里程并加强社区联系。",
    synonyms_cn: ["城市耕作", "都市种植", "城区粮食生产"],
  },
  {
    id: "city-081", word: "public sanitation", translation: "公共环境卫生", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 83, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["maintain public sanitation", "improve public sanitation", "public sanitation services", "lack of public sanitation"],
    example_sentence: "Investments in public sanitation, including clean water supply and sewage treatment, were foundational to the dramatic health improvements in 19th-century cities.",
    synonyms: ["municipal hygiene", "communal cleanliness", "urban health infrastructure"],
    common_mistakes: ["sanitation 不只是卫生; 包括清洁饮水、污水和垃圾处理、公共卫生设施"],
    ielts_context: "Reading: public health history / infrastructure; Writing Task 2: city services",
    pronunciation: "/ˈpʌb.lɪk ˌsæn.ɪˈteɪ.ʃən/",
    collocations_cn: ["维护公共环境卫生", "改善公共环境卫生", "公共环境卫生服务", "缺乏公共环境卫生"],
    example_sentence_cn: "对公共环境卫生的投资，包括清洁供水和污水处理，是19世纪城市健康状况显著改善的基础。",
    synonyms_cn: ["市政卫生", "公共清洁", "城市健康基础设施"],
  },
  {
    id: "city-082", word: "retail district", translation: "商业零售区", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 78, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["bustling retail district", "downtown retail district", "pedestrian retail district", "major retail district"],
    example_sentence: "The city's main retail district has seen a decline in foot traffic as more consumers shift to online shopping.",
    synonyms: ["shopping quarter", "commercial strip", "market area"],
    common_mistakes: ["retail district 包括商店、餐厅和娱乐场所; 不仅是购物 mall"],
    ielts_context: "Speaking Part 2: city area description; Reading: urban economics",
    pronunciation: "/ˈriː.teɪl ˈdɪs.trɪkt/",
    collocations_cn: ["繁华的商业零售区", "市中心商业零售区", "步行商业零售区", "主要商业零售区"],
    example_sentence_cn: "随着更多消费者转向在线购物，该市的主要商业零售区人流量出现下降。",
    synonyms_cn: ["购物区", "商业街", "市场区域"],
  },
  {
    id: "city-083", word: "pedestrian infrastructure", translation: "行人基础设施", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 81, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["improve pedestrian infrastructure", "invest in pedestrian infrastructure", "accessible pedestrian infrastructure", "safe pedestrian infrastructure"],
    example_sentence: "Investing in pedestrian infrastructure such as wide sidewalks, safe crossings, and pedestrian bridges makes cities more walkable and livable.",
    synonyms: ["walkway system", "footpath network", "non-motorized infrastructure"],
    common_mistakes: ["pedestrian infrastructure 不等于 sidewalk; 还包括 crosswalks, overpasses, underpasses, pedestrian zones"],
    ielts_context: "Reading: urban planning / transport; Writing Task 2: city design",
    pronunciation: "/pɪˈdes.tri.ən ˈɪn.frəˌstrʌk.tʃər/",
    collocations_cn: ["改善行人基础设施", "投资行人基础设施", "便捷的行人基础设施", "安全的行人基础设施"],
    example_sentence_cn: "投资行人基础设施，如宽阔的人行道、安全的过街设施和人行天桥，使城市更适合步行和居住。",
    synonyms_cn: ["步行系统", "人行道网络", "非机动化设施"],
  },
  {
    id: "city-084", word: "sports stadium", translation: "体育场馆", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 76, topics: ["city"], modules: ["speaking", "listening"],
    collocations: ["attend a sports stadium", "build a sports stadium", "modern sports stadium", "sports stadium event"],
    example_sentence: "The construction of a new sports stadium can revitalize a neighborhood but often comes with high public costs and displacement concerns.",
    synonyms: ["arena", "athletic venue", "sporting ground"],
    common_mistakes: ["stadium 通常有观众看台和无顶或可开合顶棚; arena 通常是室内场馆"],
    ielts_context: "Speaking Part 2: city venue / event; Listening Section 2: event information",
    pronunciation: "/spɔːts ˈsteɪ.di.əm/",
    collocations_cn: ["前往体育场馆", "建设体育场馆", "现代体育场馆", "体育场馆活动"],
    example_sentence_cn: "建设新体育场馆可以振兴一个街区，但通常伴随着高昂的公共成本和搬迁问题。",
    synonyms_cn: ["竞技场", "运动场馆", "体育场地"],
  },
  {
    id: "city-085", word: "local government budget", translation: "地方政府预算", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 80, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["allocate local government budget", "stretched local government budget", "local government budget cuts", "manage the local government budget"],
    example_sentence: "Local government budgets have come under increasing pressure as demand for public services grows while tax revenues stagnate.",
    synonyms: ["municipal budget", "city council finances", "regional authority spending"],
    common_mistakes: ["local government budget 包括财政收入和支出两个方面; 不只是支出"],
    ielts_context: "Reading: public administration / finance; Writing Task 2: government spending",
    pronunciation: "/ˈləʊ.kəl ˈɡʌv.ən.mənt ˈbʌdʒ.ɪt/",
    collocations_cn: ["分配地方政府预算", "紧张的地方政府预算", "地方政府预算削减", "管理地方政府预算"],
    example_sentence_cn: "随着公共服务需求增长而税收收入停滞不前，地方政府预算面临越来越大的压力。",
    synonyms_cn: ["市政预算", "市议会财政", "地方当局支出"],
  },
  {
    id: "city-086", word: "civic participation", translation: "公民参与", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 77, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["encourage civic participation", "increase civic participation", "civic participation in local government", "promote civic participation"],
    example_sentence: "Higher levels of civic participation lead to more responsive local governance and better outcomes for community development.",
    synonyms: ["community engagement", "public involvement", "citizen participation"],
    common_mistakes: ["civic participation 指参与社区公共事务; political participation 特指选举和政治活动"],
    ielts_context: "Reading: sociology / governance; Writing Task 2: community / democracy",
    pronunciation: "/ˈsɪv.ɪk pɑːˌtɪs.ɪˈpeɪ.ʃən/",
    collocations_cn: ["鼓励公民参与", "增加公民参与", "地方政府中的公民参与", "促进公民参与"],
    example_sentence_cn: "更高水平的公民参与带来更具响应性的地方治理和更好的社区发展成果。",
    synonyms_cn: ["社区参与", "公众参与", "市民参与"],
  },
  {
    id: "city-087", word: "urban renewal project", translation: "城市更新项目", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 82, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["implement an urban renewal project", "large-scale urban renewal project", "controversial urban renewal project", "urban renewal project area"],
    example_sentence: "Urban renewal projects aim to revitalize declining areas through infrastructure upgrades, housing improvements, and economic development initiatives.",
    synonyms: ["city regeneration scheme", "neighborhood revitalization", "urban rehabilitation program"],
    common_mistakes: ["urban renewal 在实际中有时导致 gentrification (绅士化); 即原有居民被迫迁出而受益的是高收入群体"],
    ielts_context: "Reading: urban studies / sociology; Writing Task 2: city development",
    pronunciation: "/ˈɜː.bən rɪˈnjuː.əl ˈprɒdʒ.ekt/",
    collocations_cn: ["实施城市更新项目", "大规模城市更新项目", "有争议的城市更新项目", "城市更新项目区"],
    example_sentence_cn: "城市更新项目旨在通过基础设施升级、住房改善和经济发展举措来振兴衰落地区。",
    synonyms_cn: ["城市再生计划", "社区振兴", "城市改建计划"],
  },
  {
    id: "city-088", word: "fire safety regulation", translation: "消防安全规定", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 78, topics: ["city"], modules: ["reading", "listening"],
    collocations: ["comply with fire safety regulations", "enforce fire safety regulations", "violate fire safety regulations", "strict fire safety regulations"],
    example_sentence: "After the tragic high-rise fire, the city introduced stricter fire safety regulations including mandatory sprinkler systems and regular inspections.",
    synonyms: ["fire code", "blaze prevention standard", "combustion safety rules"],
    common_mistakes: ["fire safety regulations 包括 sprinkler systems, fire alarms, emergency exits 和 evacuation plans"],
    ielts_context: "Reading: building safety / law; Listening: safety briefing",
    pronunciation: "/faɪə ˈseɪf.ti ˌreɡ.jʊˈleɪ.ʃən/",
    collocations_cn: ["遵守消防安全规定", "执行消防安全规定", "违反消防安全规定", "严格的消防安全规定"],
    example_sentence_cn: "在悲剧性高层火灾后，该市推出了更严格的消防安全规定，包括强制性自动喷水灭火系统和定期检查。",
    synonyms_cn: ["消防法规", "防火标准", "燃烧安全规则"],
  },
  // ═══ 中頻 50-69 (12 个) ═══
  {
    id: "city-089", word: "community garden", translation: "社区花园", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 65, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["join a community garden", "tend a community garden", "create a community garden", "community garden plot"],
    example_sentence: "Community gardens transform vacant urban lots into productive green spaces where residents grow fresh produce and build social connections.",
    synonyms: ["neighborhood garden", "allotment garden", "shared urban farm"],
    common_mistakes: ["community garden 是居民共同管理的; private garden 是私人的"],
    ielts_context: "Speaking Part 2: outdoor activity / community; Reading: urban greening",
    pronunciation: "/kəˈmjuː.nə.ti ˈɡɑː.dən/",
    collocations_cn: ["加入社区花园", "照料社区花园", "创建社区花园", "社区花园地块"],
    example_sentence_cn: "社区花园将城市空地转变为生产性绿地，供居民种植新鲜农产品并建立社交联系。",
    synonyms_cn: ["邻里花园", "分配菜园", "共享城市农园"],
  },
  {
    id: "city-090", word: "flood control system", translation: "防洪系统", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 68, topics: ["city"], modules: ["reading", "listening"],
    collocations: ["build a flood control system", "flood control system failure", "improve the flood control system", "urban flood control system"],
    example_sentence: "Climate change has forced many coastal cities to invest billions in upgrading their flood control systems against rising sea levels.",
    synonyms: ["flood defense infrastructure", "stormwater management system", "inundation prevention works"],
    common_mistakes: ["flood control 包括堤坝、排水系统、水库、海绵城市等综合措施"],
    ielts_context: "Reading: climate adaptation / infrastructure; Listening: city council meeting",
    pronunciation: "/flʌd kənˈtrəʊl ˈsɪs.təm/",
    collocations_cn: ["建设防洪系统", "防洪系统失效", "改善防洪系统", "城市防洪系统"],
    example_sentence_cn: "气候变化迫使许多沿海城市投资数十亿美元升级防洪系统以应对海平面上升。",
    synonyms_cn: ["防洪基础设施", "雨水管理系统", "防汛工程"],
  },
  {
    id: "city-091", word: "noise pollution ordinance", translation: "噪音污染法规", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 62, topics: ["city"], modules: ["reading", "listening"],
    collocations: ["enforce a noise pollution ordinance", "violate a noise pollution ordinance", "noise pollution ordinance limit", "local noise pollution ordinance"],
    example_sentence: "The city council passed a new noise pollution ordinance restricting construction activities to daytime hours and setting decibel limits for entertainment venues.",
    synonyms: ["noise regulation", "sound nuisance law", "acoustic pollution control"],
    common_mistakes: ["ordinance (条例) 是地方性法律; 注意与 ordnance (军械) 的区别"],
    ielts_context: "Reading: city governance / living; Listening: community complaint",
    pronunciation: "/nɔɪz pəˈluː.ʃən ˈɔː.dɪ.nəns/",
    collocations_cn: ["执行噪音污染法规", "违反噪音污染法规", "噪音污染法规限值", "当地噪音污染法规"],
    example_sentence_cn: "市议会通过了新的噪音污染法规，将施工活动限制在白天时段，并为娱乐场所设定分贝限值。",
    synonyms_cn: ["噪音管制", "声音滋扰法", "声污染控制"],
  },
  {
    id: "city-092", word: "urban forestry", translation: "城市林业", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 63, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["promote urban forestry", "urban forestry program", "invest in urban forestry", "urban forestry management"],
    example_sentence: "Urban forestry programs increase tree canopy coverage, which helps reduce the urban heat island effect and improves air quality.",
    synonyms: ["city tree management", "municipal arboriculture", "urban greening"],
    common_mistakes: ["urban forestry 不仅仅是种树; 包括街道、公园和私人土地上树木的规划、种植和养护"],
    ielts_context: "Reading: environmental planning / city sustainability; Writing Task 2: city environment",
    pronunciation: "/ˈɜː.bən ˈfɒr.ɪ.stri/",
    collocations_cn: ["推广城市林业", "城市林业项目", "投资城市林业", "城市林业管理"],
    example_sentence_cn: "城市林业项目增加树冠覆盖率，有助于降低城市热岛效应并改善空气质量。",
    synonyms_cn: ["城市树木管理", "市政树木栽培", "城市绿化"],
  },
  {
    id: "city-093", word: "building inspection", translation: "建筑检查", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 64, topics: ["city"], modules: ["reading", "listening"],
    collocations: ["conduct a building inspection", "pass a building inspection", "fail a building inspection", "regular building inspection"],
    example_sentence: "Building inspections ensure that construction work meets all applicable safety codes and approved plans before occupancy is permitted.",
    synonyms: ["structural safety audit", "construction compliance review", "property examination"],
    common_mistakes: ["building inspection 由政府或专业机构进行; home inspection 是购房前的私人检查"],
    ielts_context: "Reading: construction / regulation; Listening: property discussion",
    pronunciation: "/ˈbɪl.dɪŋ ɪnˈspek.ʃən/",
    collocations_cn: ["进行建筑检查", "通过建筑检查", "未通过建筑检查", "定期建筑检查"],
    example_sentence_cn: "建筑检查确保施工工作满足所有适用的安全规范和批准的方案，之后才允许入住。",
    synonyms_cn: ["结构安全审计", "建筑合规审查", "房产检验"],
  },
  {
    id: "city-094", word: "historic district", translation: "历史街区", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 66, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["preserve the historic district", "walk through the historic district", "designated historic district", "charming historic district"],
    example_sentence: "Many cities have designated historic districts where building modifications are strictly regulated to preserve architectural heritage.",
    synonyms: ["heritage quarter", "old town area", "conservation zone"],
    common_mistakes: ["historic district 是官方指定的保护区域; old area 是笼统的说法"],
    ielts_context: "Speaking Part 2: city visit / favorite area; Reading: architecture / tourism",
    pronunciation: "/hɪˈstɒr.ɪk ˈdɪs.trɪkt/",
    collocations_cn: ["保护历史街区", "漫步历史街区", "被划定为历史街区", "迷人的历史街区"],
    example_sentence_cn: "许多城市划定了历史街区，这些区域内的建筑改造受到严格监管，以保护建筑遗产。",
    synonyms_cn: ["文化遗产区", "老城区", "保护区"],
  },
  {
    id: "city-095", word: "recycling facility", translation: "回收处理设施", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 67, topics: ["city"], modules: ["reading", "speaking"],
    collocations: ["sort waste at a recycling facility", "modern recycling facility", "send to a recycling facility", "local recycling facility"],
    example_sentence: "Advanced recycling facilities use automated sorting technology to separate different types of materials, increasing recycling efficiency and reducing landfill waste.",
    synonyms: ["waste recovery center", "materials recovery facility", "reprocessing plant"],
    common_mistakes: ["recycling facility 处理可回收物; landfill 是填埋不可回收垃圾"],
    ielts_context: "Reading: waste management / environment; Speaking Part 3: recycling / sustainability",
    pronunciation: "/ˌriːˈsaɪ.klɪŋ fəˈsɪl.ɪ.ti/",
    collocations_cn: ["在回收处理设施进行分拣", "现代回收处理设施", "送往回收处理设施", "当地回收处理设施"],
    example_sentence_cn: "先进的回收处理设施使用自动化分拣技术分离不同类型材料，提高回收效率并减少填埋废物。",
    synonyms_cn: ["废品回收中心", "材料回收设施", "再加工厂"],
  },
  {
    id: "city-096", word: "urban exploration", translation: "城市探索", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 60, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["go urban exploration", "urban exploration photography", "fascination with urban exploration", "urban exploration community"],
    example_sentence: "Urban exploration, the practice of investigating abandoned buildings and hidden spaces, has gained a worldwide following through social media.",
    synonyms: ["urbex", "city exploration", "metropolitan discovery"],
    common_mistakes: ["urbex 是 urban exploration 的口语缩写; 常涉及未经许可进入私人领地"],
    ielts_context: "Speaking Part 2: hobby / adventure; Reading: subculture / photography",
    pronunciation: "/ˈɜː.bən ˌek.spləˈreɪ.ʃən/",
    collocations_cn: ["进行城市探索", "城市探索摄影", "对城市探索的热爱", "城市探索社区"],
    example_sentence_cn: "城市探索，即调查废弃建筑和隐藏空间的实践，已通过社交媒体在全球范围内获得追随者。",
    synonyms_cn: ["城市探险", "都市发现", "废墟探索"],
  },
  {
    id: "city-097", word: "municipal court", translation: "市法院", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 61, topics: ["city"], modules: ["reading", "listening"],
    collocations: ["appear in municipal court", "file a case in municipal court", "municipal court judge", "municipal court hearing"],
    example_sentence: "Municipal courts handle minor criminal offenses, traffic violations, and local ordinance disputes within city limits.",
    synonyms: ["city court", "local judiciary", "magistrate's court"],
    common_mistakes: ["municipal court 处理轻微案件; higher court 处理重罪和重大民事诉讼"],
    ielts_context: "Reading: law / local governance; Listening: legal / city services",
    pronunciation: "/mjuːˈnɪs.ɪ.pəl kɔːt/",
    collocations_cn: ["在市法院出庭", "向市法院提起诉讼", "市法院法官", "市法院听证会"],
    example_sentence_cn: "市法院处理轻微刑事犯罪、交通违章和市区范围内的地方法规纠纷。",
    synonyms_cn: ["城市法院", "地方法院", "治安法院"],
  },
  {
    id: "city-098", word: "botanical garden", translation: "植物园", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 63, topics: ["city"], modules: ["speaking", "reading"],
    collocations: ["visit a botanical garden", "city botanical garden", "botanical garden collection", "historic botanical garden"],
    example_sentence: "Botanical gardens serve as both recreational attractions and important centers for plant conservation, research, and environmental education.",
    synonyms: ["plant conservatory", "horticultural park", "flora sanctuary"],
    common_mistakes: ["botanical garden 以科研和教育为目的; park 主要是休闲娱乐场所"],
    ielts_context: "Speaking Part 2: city attraction / outdoor activity; Reading: travel / science",
    pronunciation: "/bəˈtæn.ɪ.kəl ˈɡɑː.dən/",
    collocations_cn: ["参观植物园", "城市植物园", "植物园收藏", "历史植物园"],
    example_sentence_cn: "植物园既是休闲景点，也是植物保护、研究和环境教育的重要中心。",
    synonyms_cn: ["植物保护区", "园艺公园", "植物庇护所"],
  },
  {
    id: "city-099", word: "traffic calming measure", translation: "交通稳静化措施", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 64, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["implement traffic calming measures", "traffic calming measure design", "effective traffic calming measures", "install traffic calming measures"],
    example_sentence: "Traffic calming measures such as speed bumps, raised crosswalks, and narrowed lanes have been shown to significantly reduce pedestrian accidents.",
    synonyms: ["speed reduction design", "road safety intervention", "vehicle slowing infrastructure"],
    common_mistakes: ["traffic calming 旨在降低车速和改善步行/骑行安全; 不是减少交通流量"],
    ielts_context: "Reading: urban planning / transport safety; Writing Task 2: road safety",
    pronunciation: "/ˈtræf.ɪk ˈkɑː.mɪŋ ˈmeʒ.ər/",
    collocations_cn: ["实施交通稳静化措施", "交通稳静化措施设计", "有效的交通稳静化措施", "安装交通稳静化措施"],
    example_sentence_cn: "交通稳静化措施，如减速带、抬高的人行横道和缩窄的车道，已被证明能显著减少行人事故。",
    synonyms_cn: ["减速设计", "道路安全干预", "车辆减速设施"],
  },
  {
    id: "city-100", word: "compact city model", translation: "紧凑城市模式", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 65, topics: ["city"], modules: ["reading", "writing"],
    collocations: ["adopt a compact city model", "compact city model of development", "advocate the compact city model", "principles of the compact city model"],
    example_sentence: "The compact city model promotes high-density, mixed-use development to reduce sprawl, shorten commutes, and preserve surrounding natural areas.",
    synonyms: ["dense urban form", "concentrated settlement pattern", "high-density urban design"],
    common_mistakes: ["compact city 不是拥挤城市; 而是通过合理密度减少资源消耗和交通需求的规划理念"],
    ielts_context: "Reading: sustainable urbanism / planning; Writing Task 2: city development / environment",
    pronunciation: "/ˈkɒm.pækt ˈsɪt.i ˈmɒd.əl/",
    collocations_cn: ["采用紧凑城市模式", "紧凑城市开发模式", "倡导紧凑城市模式", "紧凑城市模式原则"],
    example_sentence_cn: "紧凑城市模式推广高密度、混合用途的开发，以减少城市蔓延、缩短通勤距离，并保护周边的自然区域。",
    synonyms_cn: ["高密度城市形态", "集中式住区格局", "高密度城市设计"],
  },
];
