// scripts/expand-health.ts
// Phase 2: Health 话题扩展 — health-051 ~ health-100（50 个新词块）
// 频次分布: 超高(90-99)×20 + 高(70-89)×18 + 中(50-69)×12

import type { Chunk } from "../types/chunk";

export const HEALTH_EXPANSION: Chunk[] = [
  // ═══ 超高頻 90-99 (20 个) ═══
  {
    id: "health-051", word: "mental health awareness", translation: "心理健康意识", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 97, topics: ["health"], modules: ["writing", "speaking"],
    collocations: ["raise mental health awareness", "promote mental health awareness", "mental health awareness campaign", "increase mental health awareness"],
    example_sentence: "Schools are increasingly incorporating mental health awareness into their curriculum to help students recognize and manage emotional challenges.",
    synonyms: ["psychological well-being awareness", "emotional health understanding", "mental wellness education"],
    common_mistakes: ["mental health 不仅是缺少 mental illness; 还包括积极的心理状态"],
    ielts_context: "Writing Task 2: public health / education; Speaking Part 3: well-being",
    pronunciation: "/ˈmen.təl helθ əˈweə.nəs/",
    collocations_cn: ["提高心理健康意识", "促进心理健康意识", "心理健康宣传活动", "增强心理健康意识"],
    example_sentence_cn: "学校越来越多地将心理健康意识纳入课程，帮助学生识别和管理情绪挑战。",
    synonyms_cn: ["心理福祉意识", "情绪健康认知", "心理健康教育"],
  },
  {
    id: "health-052", word: "antibiotic resistance", translation: "抗生素耐药性", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 93, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["combat antibiotic resistance", "growing antibiotic resistance", "antibiotic resistance crisis", "spread of antibiotic resistance"],
    example_sentence: "The World Health Organization has identified antibiotic resistance as one of the top ten global health threats facing humanity.",
    synonyms: ["antimicrobial resistance", "drug resistance", "superbug crisis"],
    common_mistakes: ["antibiotic resistance 是细菌对抗生素产生耐药性，不是人体对抗生素产生耐药"],
    ielts_context: "Reading: medical science / public health; Writing Task 2: global health",
    pronunciation: "/ˌæn.ti.baɪˈɒt.ɪk rɪˈzɪs.təns/",
    collocations_cn: ["抗击抗生素耐药性", "日益增长的抗生素耐药性", "抗生素耐药性危机", "抗生素耐药性的传播"],
    example_sentence_cn: "世界卫生组织已将抗生素耐药性确定为人类面临的十大全球健康威胁之一。",
    synonyms_cn: ["抗微生物耐药性", "药物耐药性", "超级细菌危机"],
  },
  {
    id: "health-053", word: "clinical trial", translation: "临床试验", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 94, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["conduct a clinical trial", "participate in a clinical trial", "randomized clinical trial", "clinical trial results"],
    example_sentence: "Before any new drug can be approved for public use, it must undergo rigorous clinical trials to demonstrate safety and efficacy.",
    synonyms: ["medical trial", "human trial", "pharmaceutical study"],
    common_mistakes: ["clinical trial 在人身上测试; preclinical study 在实验室和动物身上"],
    ielts_context: "Reading: medical research / pharmacology; Writing Task 2: medical innovation",
    pronunciation: "/ˈklɪn.ɪ.kəl ˈtraɪ.əl/",
    collocations_cn: ["进行临床试验", "参与临床试验", "随机对照临床试验", "临床试验结果"],
    example_sentence_cn: "任何新药在获准用于公众之前，必须经过严格的临床试验以证明其安全性和有效性。",
    synonyms_cn: ["医学试验", "人体试验", "药物研究"],
  },
  {
    id: "health-054", word: "vaccine development", translation: "疫苗开发", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 95, topics: ["health"], modules: ["reading", "speaking"],
    collocations: ["accelerate vaccine development", "rapid vaccine development", "vaccine development process", "invest in vaccine development"],
    example_sentence: "The COVID-19 pandemic demonstrated that global collaboration can dramatically accelerate vaccine development without compromising safety.",
    synonyms: ["immunization research", "vaccine research and development", "inoculation advancement"],
    common_mistakes: ["vaccine development 包括 discovery, preclinical, clinical trials, regulatory review 多个阶段"],
    ielts_context: "Reading: medical science / global health; Speaking Part 3: public health",
    pronunciation: "/ˈvæk.siːn dɪˈvel.əp.mənt/",
    collocations_cn: ["加速疫苗开发", "快速疫苗开发", "疫苗开发流程", "投资疫苗开发"],
    example_sentence_cn: "新冠大流行表明，全球合作可以大幅加快疫苗开发而不牺牲安全性。",
    synonyms_cn: ["免疫研究", "疫苗研发", "接种研究"],
  },
  {
    id: "health-055", word: "sedentary behavior", translation: "久坐行为", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 93, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["reduce sedentary behavior", "prolonged sedentary behavior", "risks of sedentary behavior", "combat sedentary behavior"],
    example_sentence: "Prolonged sedentary behavior, such as sitting at a desk for hours, has been linked to an increased risk of heart disease and diabetes.",
    synonyms: ["physical inactivity", "prolonged sitting", "inactive lifestyle pattern"],
    common_mistakes: ["sedentary behavior 不等于 lack of exercise; 是长时间低能量消耗的状态"],
    ielts_context: "Reading: public health / occupational health; Writing Task 2: lifestyle / health",
    pronunciation: "/ˈsed.ən.tər.i bɪˈheɪ.vjər/",
    collocations_cn: ["减少久坐行为", "长时间久坐行为", "久坐行为的风险", "对抗久坐行为"],
    example_sentence_cn: "长时间久坐行为，如数小时坐在桌前，已与心脏病和糖尿病风险增加相关联。",
    synonyms_cn: ["身体活动不足", "长时间坐着", "缺乏运动的生活方式"],
  },
  {
    id: "health-056", word: "pandemic response", translation: "疫情应对", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 96, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["coordinate pandemic response", "strengthen pandemic response", "global pandemic response", "pandemic response strategy"],
    example_sentence: "Effective pandemic response requires rapid testing deployment, robust contact tracing systems, and clear public communication.",
    synonyms: ["outbreak management", "epidemic response", "public health emergency response"],
    common_mistakes: ["pandemic (全球性大流行) 比 epidemic (局部性流行) 范围更广、影响更大"],
    ielts_context: "Reading: public health / global policy; Writing Task 2: government / health",
    pronunciation: "/pænˈdem.ɪk rɪˈspɒns/",
    collocations_cn: ["协调疫情应对", "加强疫情应对", "全球疫情应对", "疫情应对策略"],
    example_sentence_cn: "有效的疫情应对需要快速部署检测、强大的接触者追踪系统和清晰的公众沟通。",
    synonyms_cn: ["疫情管理", "流行病应对", "公共卫生紧急响应"],
  },
  {
    id: "health-057", word: "health screening program", translation: "健康筛查计划", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 91, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["implement a health screening program", "national health screening program", "free health screening program", "regular health screening program"],
    example_sentence: "National health screening programs for cancers such as breast and cervical have saved countless lives through early detection and treatment.",
    synonyms: ["medical screening initiative", "preventive check-up scheme", "diagnostic screening campaign"],
    common_mistakes: ["screening 是针对无症状人群的检测; diagnosis 是对有症状患者的确认"],
    ielts_context: "Reading: public health policy; Writing Task 2: preventive healthcare",
    pronunciation: "/helθ ˈskriː.nɪŋ ˈprəʊ.ɡræm/",
    collocations_cn: ["实施健康筛查计划", "国家健康筛查计划", "免费健康筛查计划", "定期健康筛查计划"],
    example_sentence_cn: "针对乳腺癌和宫颈癌等的国家健康筛查计划通过早期发现和治疗挽救了无数生命。",
    synonyms_cn: ["医学筛查项目", "预防检查计划", "诊断筛查活动"],
  },
  {
    id: "health-058", word: "emergency room", translation: "急诊室", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["health"], modules: ["listening", "speaking"],
    collocations: ["visit the emergency room", "rushed to the emergency room", "emergency room doctor", "overcrowded emergency room"],
    example_sentence: "Overcrowded emergency rooms often result in long waiting times for patients with non-life-threatening conditions.",
    synonyms: ["ER", "accident and emergency department", "casualty ward"],
    common_mistakes: ["emergency room 处理危及生命的紧急情况; urgent care 处理不需要急救但也需尽快处理的情况"],
    ielts_context: "Listening Section 1: hospital visit; Speaking Part 2: medical experience",
    pronunciation: "/ɪˈmɜː.dʒən.si ruːm/",
    collocations_cn: ["去急诊室", "被紧急送往急诊室", "急诊科医生", "过度拥挤的急诊室"],
    example_sentence_cn: "过度拥挤的急诊室常常导致非危及生命情况的患者长时间等待。",
    synonyms_cn: ["急诊", "意外及急救部", "伤病室"],
  },
  {
    id: "health-059", word: "blood pressure", translation: "血压", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 92, topics: ["health"], modules: ["listening", "reading"],
    collocations: ["check blood pressure", "high blood pressure", "normal blood pressure", "lower blood pressure"],
    example_sentence: "Regularly monitoring your blood pressure is important because hypertension often has no noticeable symptoms until serious damage occurs.",
    synonyms: ["arterial pressure", "hypertension (high)", "hypotension (low)"],
    common_mistakes: ["high blood pressure 也称 hypertension; low blood pressure 是 hypotension"],
    ielts_context: "Listening Section 1: doctor's appointment; Reading: health / wellness",
    pronunciation: "/blʌd ˈpreʃ.ər/",
    collocations_cn: ["检查血压", "高血压", "正常血压", "降低血压"],
    example_sentence_cn: "定期监测血压很重要，因为高血压在造成严重损害之前通常没有明显症状。",
    synonyms_cn: ["动脉压力", "高血压（高压）", "低血压（低压）"],
  },
  {
    id: "health-060", word: "surgical procedure", translation: "外科手术", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["health"], modules: ["reading", "listening"],
    collocations: ["undergo a surgical procedure", "minimally invasive surgical procedure", "complex surgical procedure", "routine surgical procedure"],
    example_sentence: "Advances in robotic technology have made surgical procedures less invasive, reducing recovery time and post-operative complications.",
    synonyms: ["operation", "surgery", "medical procedure"],
    common_mistakes: ["surgery (不可数) 泛指外科; a surgical procedure 指一次具体的手术"],
    ielts_context: "Reading: medical technology; Listening Section 3: health consultation",
    pronunciation: "/ˈsɜː.dʒɪ.kəl prəˈsiː.dʒər/",
    collocations_cn: ["接受外科手术", "微创外科手术", "复杂的外科手术", "常规外科手术"],
    example_sentence_cn: "机器人技术的进步使外科手术变得不那么侵入性，减少了恢复时间和术后并发症。",
    synonyms_cn: ["手术", "外科", "医疗手段"],
  },
  {
    id: "health-061", word: "chronic pain", translation: "慢性疼痛", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 91, topics: ["health"], modules: ["reading", "speaking"],
    collocations: ["suffer from chronic pain", "manage chronic pain", "live with chronic pain", "chronic pain relief"],
    example_sentence: "Chronic pain affects millions of people worldwide and can significantly impair quality of life and mental well-being.",
    synonyms: ["persistent pain", "long-term pain", "intractable pain"],
    common_mistakes: ["chronic (持续超过3个月的) 不同于 acute (急性、短期、突然的)"],
    ielts_context: "Reading: medical conditions / public health; Speaking Part 3: health challenges",
    pronunciation: "/ˈkrɒn.ɪk peɪn/",
    collocations_cn: ["遭受慢性疼痛", "管理慢性疼痛", "与慢性疼痛共存", "缓解慢性疼痛"],
    example_sentence_cn: "慢性疼痛影响着全球数百万人，并可能显著损害生活质量和心理健康。",
    synonyms_cn: ["持续性疼痛", "长期疼痛", "难治性疼痛"],
  },
  {
    id: "health-062", word: "intensive care unit", translation: "重症监护室", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["health"], modules: ["reading", "listening"],
    collocations: ["admitted to the intensive care unit", "intensive care unit bed", "in the intensive care unit", "discharged from the intensive care unit"],
    example_sentence: "During the peak of the pandemic, hospitals struggled with a critical shortage of intensive care unit beds and ventilators.",
    synonyms: ["ICU", "critical care unit", "intensive treatment unit"],
    common_mistakes: ["ICU / Intensive Care Unit 针对有生命危险的患者; 不要和 general ward (普通病房) 混淆"],
    ielts_context: "Reading: healthcare capacity / hospital management; Listening: hospital scenario",
    pronunciation: "/ɪnˈten.sɪv keə ˈjuː.nɪt/",
    collocations_cn: ["被送进重症监护室", "重症监护床位", "在重症监护室", "从重症监护室出院"],
    example_sentence_cn: "在疫情高峰期，医院面临着重症监护床位和呼吸机的严重短缺。",
    synonyms_cn: ["ICU", "重症监护", "严症监护室"],
  },
  {
    id: "health-063", word: "primary care physician", translation: "初级保健医生", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["health"], modules: ["listening", "speaking"],
    collocations: ["visit a primary care physician", "regular primary care physician", "referral from a primary care physician", "consult a primary care physician"],
    example_sentence: "A primary care physician serves as the first point of contact for patients and coordinates referrals to specialists when needed.",
    synonyms: ["general practitioner", "family doctor", "GP"],
    common_mistakes: ["primary care 是基础医疗服务; secondary care 是专科医疗服务"],
    ielts_context: "Listening Section 1: making an appointment; Speaking Part 1: health / doctor visits",
    pronunciation: "/ˈpraɪ.mər.i keə fɪˈzɪʃ.ən/",
    collocations_cn: ["看初级保健医生", "固定的初级保健医生", "初级保健医生转诊", "咨询初级保健医生"],
    example_sentence_cn: "初级保健医生是患者的第一接触点，并在需要时协调转诊给专科医生。",
    synonyms_cn: ["全科医生", "家庭医生", "GP"],
  },
  {
    id: "health-064", word: "diagnostic test", translation: "诊断检测", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 92, topics: ["health"], modules: ["reading", "listening"],
    collocations: ["undergo a diagnostic test", "order a diagnostic test", "diagnostic test result", "rapid diagnostic test"],
    example_sentence: "Diagnostic tests such as blood work, X-rays, and biopsies help physicians determine the underlying cause of a patient's symptoms.",
    synonyms: ["medical test", "diagnostic assessment", "clinical examination"],
    common_mistakes: ["diagnostic test (诊断检测) 不同于 screening test (筛查); 前者针对有症状者，后者针对无症状人群"],
    ielts_context: "Reading: medical reports; Listening: doctor consultation",
    pronunciation: "/ˌdaɪ.əɡˈnɒs.tɪk test/",
    collocations_cn: ["接受诊断检测", "开具诊断检测", "诊断检测结果", "快速诊断检测"],
    example_sentence_cn: "血液检查、X光和活检等诊断检测帮助医生确定患者症状的潜在原因。",
    synonyms_cn: ["医学检测", "诊断评估", "临床检查"],
  },
  {
    id: "health-065", word: "palliative care", translation: "姑息治疗", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 90, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["provide palliative care", "receive palliative care", "access to palliative care", "palliative care services"],
    example_sentence: "Palliative care focuses on improving quality of life for patients with serious illnesses by managing pain and other distressing symptoms.",
    synonyms: ["comfort care", "end-of-life support", "symptom management care"],
    common_mistakes: ["palliative care 不等于 hospice care; 前者可在疾病任何阶段开始，后者主要用于生命末期"],
    ielts_context: "Reading: healthcare / ethics; Writing Task 2: healthcare access",
    pronunciation: "/ˈpæl.i.ə.tɪv keə/",
    collocations_cn: ["提供姑息治疗", "接受姑息治疗", "获取姑息治疗", "姑息治疗服务"],
    example_sentence_cn: "姑息治疗侧重于通过管理疼痛和其他痛苦症状来改善严重疾病患者的生活质量。",
    synonyms_cn: ["缓解性照护", "生命末期支持", "症状管理护理"],
  },
  {
    id: "health-066", word: "physical therapy", translation: "物理治疗", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["health"], modules: ["listening", "speaking"],
    collocations: ["undergo physical therapy", "physical therapy session", "prescribe physical therapy", "physical therapy exercises"],
    example_sentence: "After knee surgery, patients typically undergo several weeks of physical therapy to regain strength and mobility.",
    synonyms: ["physiotherapy", "rehabilitation exercise", "therapeutic exercise"],
    common_mistakes: ["physical therapy 侧重于通过运动恢复功能; occupational therapy 帮助恢复日常活动能力"],
    ielts_context: "Listening Section 3: health / recovery; Speaking Part 2: injury experience",
    pronunciation: "/ˈfɪz.ɪ.kəl ˈθer.ə.pi/",
    collocations_cn: ["接受物理治疗", "物理治疗疗程", "开具物理治疗处方", "物理治疗练习"],
    example_sentence_cn: "膝关节手术后，患者通常需要接受数周的物理治疗以恢复力量和活动能力。",
    synonyms_cn: ["物理治疗", "康复运动", "治疗性运动"],
  },
  {
    id: "health-067", word: "health literacy", translation: "健康素养", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["improve health literacy", "low health literacy", "promote health literacy", "health literacy skills"],
    example_sentence: "Low health literacy is associated with poorer health outcomes, higher hospitalization rates, and less effective use of preventive services.",
    synonyms: ["medical literacy", "health knowledge", "healthcare understanding"],
    common_mistakes: ["health literacy 不仅是读懂医学信息，还包括理解并据此做出健康决策的能力"],
    ielts_context: "Reading: public health / education; Writing Task 2: health policy",
    pronunciation: "/helθ ˈlɪt.ər.ə.si/",
    collocations_cn: ["提高健康素养", "低健康素养", "促进健康素养", "健康素养技能"],
    example_sentence_cn: "低健康素养与较差的健康结果、较高的住院率和较低的预防性服务使用效果相关。",
    synonyms_cn: ["医学素养", "健康知识", "医疗理解能力"],
  },
  {
    id: "health-068", word: "infectious disease", translation: "传染病", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 93, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["prevent infectious diseases", "control infectious diseases", "outbreak of infectious disease", "spread of infectious diseases"],
    example_sentence: "Improved sanitation and vaccination programs have dramatically reduced the burden of infectious diseases in many parts of the world.",
    synonyms: ["communicable disease", "transmissible illness", "contagious condition"],
    common_mistakes: ["infectious (由病原体引起) 不等于 contagious (通过接触传播); 所有 contagious 病都是 infectious 的，反之不然"],
    ielts_context: "Reading: public health / epidemiology; Writing Task 2: global health",
    pronunciation: "/ɪnˈfek.ʃəs dɪˈziːz/",
    collocations_cn: ["预防传染病", "控制传染病", "传染病暴发", "传染病的传播"],
    example_sentence_cn: "改善的卫生条件和疫苗接种计划已大幅减少了许多地区的传染病负担。",
    synonyms_cn: ["传染病", "可传播疾病", "接触传染性疾病"],
  },
  {
    id: "health-069", word: "cognitive decline", translation: "认知能力下降", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["prevent cognitive decline", "age-related cognitive decline", "slow cognitive decline", "signs of cognitive decline"],
    example_sentence: "Regular physical exercise and mentally stimulating activities can help slow age-related cognitive decline.",
    synonyms: ["mental deterioration", "cognitive impairment", "intellectual decline"],
    common_mistakes: ["cognitive decline 是认知功能的逐渐减退; dementia (痴呆) 是严重的认知障碍综合征"],
    ielts_context: "Reading: aging / neuroscience; Writing Task 2: elderly care / health",
    pronunciation: "/ˈkɒɡ.nə.tɪv dɪˈklaɪn/",
    collocations_cn: ["预防认知能力下降", "与年龄相关的认知能力下降", "减缓认知能力下降", "认知能力下降的迹象"],
    example_sentence_cn: "定期体育锻炼和脑力刺激活动有助于减缓与年龄相关的认知能力下降。",
    synonyms_cn: ["心理衰退", "认知障碍", "智力下降"],
  },
  {
    id: "health-070", word: "nutritional deficiency", translation: "营养缺乏", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["suffer from nutritional deficiency", "address nutritional deficiency", "iron nutritional deficiency", "severe nutritional deficiency"],
    example_sentence: "Nutritional deficiencies are most prevalent in low-income communities where access to diverse, nutrient-rich foods is limited.",
    synonyms: ["micronutrient deficiency", "dietary insufficiency", "malnutrition"],
    common_mistakes: ["deficiency 表示缺乏特定营养素; malnutrition (营养不良) 更广义，也包括营养过剩"],
    ielts_context: "Reading: global health / nutrition; Writing Task 2: food / poverty",
    pronunciation: "/njuːˈtrɪʃ.ən.əl dɪˈfɪʃ.ən.si/",
    collocations_cn: ["患有营养缺乏", "解决营养缺乏", "铁营养缺乏", "严重营养缺乏"],
    example_sentence_cn: "营养缺乏在低收入社区中最为普遍，那里获得多样化、营养丰富的食物的机会有限。",
    synonyms_cn: ["微量营养素缺乏", "膳食不足", "营养不良"],
  },
  // ═══ 高頻 70-89 (18 个) ═══
  {
    id: "health-071", word: "organ donation", translation: "器官捐献", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 84, topics: ["health"], modules: ["reading", "speaking"],
    collocations: ["register for organ donation", "promote organ donation", "voluntary organ donation", "organ donation system"],
    example_sentence: "Many countries have adopted opt-out organ donation systems to address the chronic shortage of organs available for transplant.",
    synonyms: ["tissue donation", "transplant donation", "anatomical gift"],
    common_mistakes: ["opt-out system (默认同意) 和 opt-in system (主动登记) 是两种不同的器官捐献制度"],
    ielts_context: "Reading: medical ethics / healthcare; Speaking Part 3: healthcare / society",
    pronunciation: "/ˈɔː.ɡən dəʊˈneɪ.ʃən/",
    collocations_cn: ["登记器官捐献", "推广器官捐献", "自愿器官捐献", "器官捐献系统"],
    example_sentence_cn: "许多国家已采用选择退出器官捐献制度，以解决可供移植器官的长期短缺问题。",
    synonyms_cn: ["组织捐献", "移植捐献", "解剖捐献"],
  },
  {
    id: "health-072", word: "herd immunity", translation: "群体免疫", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 86, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["achieve herd immunity", "reach herd immunity", "herd immunity threshold", "concept of herd immunity"],
    example_sentence: "Herd immunity occurs when a sufficiently high percentage of a population becomes immune to a disease, making its spread unlikely.",
    synonyms: ["population immunity", "community immunity", "collective protection"],
    common_mistakes: ["herd immunity 可以通过接种疫苗或自然感染获得; 通过接种疫苗获得更安全"],
    ielts_context: "Reading: epidemiology / public health; Writing Task 2: vaccination policy",
    pronunciation: "/hɜːd ɪˈmjuː.nə.ti/",
    collocations_cn: ["实现群体免疫", "达到群体免疫", "群体免疫阈值", "群体免疫的概念"],
    example_sentence_cn: "当人群中足够高比例的人对某种疾病产生免疫力时，就会出现群体免疫，使该疾病不太可能传播。",
    synonyms_cn: ["人口免疫", "社区免疫", "集体保护"],
  },
  {
    id: "health-073", word: "cancer screening", translation: "癌症筛查", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 85, topics: ["health"], modules: ["reading", "listening"],
    collocations: ["undergo cancer screening", "regular cancer screening", "cancer screening programme", "recommend cancer screening"],
    example_sentence: "Early detection through routine cancer screening dramatically improves survival rates for breast, cervical, and colorectal cancers.",
    synonyms: ["oncology screening", "tumor detection program", "malignancy screening"],
    common_mistakes: ["screening 不能诊断癌症，只能发现异常; 确诊需要 biopsy (活检)"],
    ielts_context: "Reading: preventive medicine / public health; Listening: doctor's recommendation",
    pronunciation: "/ˈkæn.sər ˈskriː.nɪŋ/",
    collocations_cn: ["接受癌症筛查", "定期癌症筛查", "癌症筛查计划", "建议进行癌症筛查"],
    example_sentence_cn: "通过常规癌症筛查实现早期发现能显著提高乳腺癌、宫颈癌和结直肠癌的生存率。",
    synonyms_cn: ["肿瘤筛查", "肿瘤检测计划", "恶性肿瘤筛查"],
  },
  {
    id: "health-074", word: "anxiety disorder", translation: "焦虑障碍", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 88, topics: ["health"], modules: ["reading", "speaking"],
    collocations: ["diagnosed with an anxiety disorder", "suffer from an anxiety disorder", "treat anxiety disorders", "generalized anxiety disorder"],
    example_sentence: "Anxiety disorders are among the most common mental health conditions, affecting millions of people of all ages worldwide.",
    synonyms: ["generalized anxiety", "panic disorder", "social anxiety condition"],
    common_mistakes: ["anxiety disorder 是临床诊断的持续焦虑状态; everyday anxiety 是正常的压力反应"],
    ielts_context: "Reading: mental health / psychology; Speaking Part 3: modern life / stress",
    pronunciation: "/æŋˈzaɪ.ə.ti dɪˈsɔː.dər/",
    collocations_cn: ["被诊断患有焦虑障碍", "患有焦虑障碍", "治疗焦虑障碍", "广泛性焦虑障碍"],
    example_sentence_cn: "焦虑障碍是最常见的心理健康状况之一，影响着全球各年龄段的数百万人。",
    synonyms_cn: ["广泛性焦虑", "惊恐障碍", "社交焦虑症"],
  },
  {
    id: "health-075", word: "exercise routine", translation: "锻炼计划", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 82, topics: ["health"], modules: ["speaking", "listening"],
    collocations: ["maintain an exercise routine", "establish an exercise routine", "daily exercise routine", "stick to an exercise routine"],
    example_sentence: "Establishing a consistent exercise routine is one of the most effective strategies for improving both physical and mental health.",
    synonyms: ["fitness regimen", "workout plan", "physical training schedule"],
    common_mistakes: ["routine 强调「规律性」和「可坚持性」; 不是一次性或偶发运动"],
    ielts_context: "Speaking Part 2: healthy habit; Listening Section 1: gym / fitness",
    pronunciation: "/ˈek.sər.saɪz ruːˈtiːn/",
    collocations_cn: ["保持锻炼计划", "建立锻炼计划", "日常锻炼计划", "坚持锻炼计划"],
    example_sentence_cn: "建立持续的锻炼计划是改善身体和心理健康最有效的策略之一。",
    synonyms_cn: ["健身计划", "训练方案", "体能训练安排"],
  },
  {
    id: "health-076", word: "food safety standard", translation: "食品安全标准", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 80, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["comply with food safety standards", "enforce food safety standards", "improve food safety standards", "international food safety standards"],
    example_sentence: "Stringent food safety standards are essential for preventing foodborne illnesses and protecting public health.",
    synonyms: ["food hygiene regulation", "alimentary safety protocol", "food quality standard"],
    common_mistakes: ["food safety 关注防止食品污染和食源性疾病; food quality 关注口味、外观、营养价值"],
    ielts_context: "Reading: public health / regulation; Writing Task 2: consumer protection",
    pronunciation: "/fuːd ˈseɪf.ti ˈstæn.dəd/",
    collocations_cn: ["遵守食品安全标准", "执行食品安全标准", "提高食品安全标准", "国际食品安全标准"],
    example_sentence_cn: "严格的食品安全标准对于预防食源性疾病和保护公众健康至关重要。",
    synonyms_cn: ["食品卫生法规", "食品安全规程", "食品质量标准"],
  },
  {
    id: "health-077", word: "rehabilitation program", translation: "康复计划", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 79, topics: ["health"], modules: ["reading", "listening"],
    collocations: ["enroll in a rehabilitation program", "complete a rehabilitation program", "drug rehabilitation program", "cardiac rehabilitation program"],
    example_sentence: "Comprehensive rehabilitation programs help patients recovering from strokes, surgeries, or substance addiction regain independence and quality of life.",
    synonyms: ["recovery program", "rehab scheme", "restoration treatment"],
    common_mistakes: ["rehabilitation 不仅是毒品康复; 也用于心脏、神经、外科等康复"],
    ielts_context: "Reading: healthcare / social services; Listening: healthcare referral",
    pronunciation: "/ˌriː.əˌbɪl.ɪˈteɪ.ʃən ˈprəʊ.ɡræm/",
    collocations_cn: ["参加康复计划", "完成康复计划", "戒毒康复计划", "心脏康复计划"],
    example_sentence_cn: "全面的康复计划帮助从中风、手术或物质成瘾中恢复的患者重获独立和生活质量。",
    synonyms_cn: ["恢复计划", "康复方案", "恢复性治疗"],
  },
  {
    id: "health-078", word: "tobacco consumption", translation: "烟草消费", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 83, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["reduce tobacco consumption", "curb tobacco consumption", "tobacco consumption rate", "excessive tobacco consumption"],
    example_sentence: "Higher taxes on cigarettes and plain packaging laws have been effective in reducing tobacco consumption in many nations.",
    synonyms: ["smoking prevalence", "cigarette use", "nicotine consumption"],
    common_mistakes: ["tobacco 包括香烟、雪茄、烟斗烟等; 不限于 cigarette"],
    ielts_context: "Reading: public health policy; Writing Task 2: health / government regulation",
    pronunciation: "/təˈbæk.əʊ kənˈsʌmp.ʃən/",
    collocations_cn: ["减少烟草消费", "抑制烟草消费", "烟草消费率", "过度烟草消费"],
    example_sentence_cn: "较高的烟草税和素面包装法在许多国家有效减少了烟草消费。",
    synonyms_cn: ["吸烟率", "香烟使用", "尼古丁消费"],
  },
  {
    id: "health-079", word: "sleep quality", translation: "睡眠质量", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 84, topics: ["health"], modules: ["speaking", "reading"],
    collocations: ["improve sleep quality", "poor sleep quality", "affect sleep quality", "assess sleep quality"],
    example_sentence: "Reducing screen time before bed and maintaining a consistent sleep schedule can significantly improve sleep quality.",
    synonyms: ["rest quality", "sleep adequacy", "nocturnal restfulness"],
    common_mistakes: ["sleep quality 不仅包括 sleep duration (时长); 还包括深度、连续性和醒来后的感觉"],
    ielts_context: "Speaking Part 1: daily routine / health; Reading: sleep science",
    pronunciation: "/sliːp ˈkwɒl.ə.ti/",
    collocations_cn: ["改善睡眠质量", "睡眠质量差", "影响睡眠质量", "评估睡眠质量"],
    example_sentence_cn: "减少睡前屏幕使用时间并保持一致的睡眠时间表可以显著改善睡眠质量。",
    synonyms_cn: ["休息质量", "睡眠充分度", "夜间安宁度"],
  },
  {
    id: "health-080", word: "diabetes management", translation: "糖尿病管理", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 82, topics: ["health"], modules: ["reading", "listening"],
    collocations: ["improve diabetes management", "self diabetes management", "diabetes management plan", "diabetes management program"],
    example_sentence: "Effective diabetes management involves regular blood sugar monitoring, a balanced diet, exercise, and medication adherence.",
    synonyms: ["glycemic control", "blood sugar regulation", "diabetes care"],
    common_mistakes: ["type 1 diabetes 是自身免疫性疾病; type 2 diabetes 通常与生活方式相关"],
    ielts_context: "Reading: chronic disease / healthcare; Listening: health consultation",
    pronunciation: "/ˌdaɪ.əˈbiː.tiːz ˈmæn.ɪdʒ.mənt/",
    collocations_cn: ["改善糖尿病管理", "自我糖尿病管理", "糖尿病管理计划", "糖尿病管理项目"],
    example_sentence_cn: "有效的糖尿病管理涉及定期血糖监测、均衡饮食、锻炼和坚持用药。",
    synonyms_cn: ["血糖控制", "血糖调节", "糖尿病护理"],
  },
  {
    id: "health-081", word: "alcohol abuse", translation: "酒精滥用", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 85, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["combat alcohol abuse", "alcohol abuse treatment", "consequences of alcohol abuse", "alcohol abuse problem"],
    example_sentence: "Alcohol abuse contributes to a wide range of health problems, including liver disease, cardiovascular conditions, and mental health disorders.",
    synonyms: ["excessive drinking", "alcohol misuse", "problem drinking"],
    common_mistakes: ["alcohol abuse (滥用) 不同于 alcohol dependence (依赖); 后者是更严重的成瘾状态"],
    ielts_context: "Reading: public health / social issues; Writing Task 2: health / regulation",
    pronunciation: "/ˈæl.kə.hɒl əˈbjuːs/",
    collocations_cn: ["打击酒精滥用", "酒精滥用治疗", "酒精滥用的后果", "酒精滥用问题"],
    example_sentence_cn: "酒精滥用导致一系列健康问题，包括肝病、心血管疾病和心理健康障碍。",
    synonyms_cn: ["过度饮酒", "酒精误用", "问题饮酒"],
  },
  {
    id: "health-082", word: "meditation practice", translation: "冥想练习", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 78, topics: ["health"], modules: ["speaking", "reading"],
    collocations: ["develop a meditation practice", "daily meditation practice", "mindfulness meditation practice", "benefit from meditation practice"],
    example_sentence: "Regular meditation practice has been scientifically shown to reduce stress, improve concentration, and enhance emotional well-being.",
    synonyms: ["mindfulness exercise", "contemplation routine", "mental training"],
    common_mistakes: ["meditation 是一种训练注意力和觉知的心智练习; 不必然与宗教相关"],
    ielts_context: "Speaking Part 2: relaxation method; Reading: wellness / neuroscience",
    pronunciation: "/ˌmed.ɪˈteɪ.ʃən ˈpræk.tɪs/",
    collocations_cn: ["培养冥想练习", "每日冥想练习", "正念冥想练习", "受益于冥想练习"],
    example_sentence_cn: "科学研究表明，定期冥想练习可以减少压力、提高注意力并增强情绪健康。",
    synonyms_cn: ["正念练习", "内观练习", "心智训练"],
  },
  {
    id: "health-083", word: "healthcare expenditure", translation: "医疗支出", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 80, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["rising healthcare expenditure", "control healthcare expenditure", "public healthcare expenditure", "healthcare expenditure per capita"],
    example_sentence: "Healthcare expenditure has been growing faster than GDP in most developed nations, raising concerns about long-term fiscal sustainability.",
    synonyms: ["medical spending", "health budget", "healthcare costs"],
    common_mistakes: ["healthcare expenditure 包括政府、保险公司和个人三方面的支出总和"],
    ielts_context: "Reading: health economics / policy; Writing Task 2: government spending",
    pronunciation: "/ˈhelθ.keə ɪkˈspen.dɪ.tʃər/",
    collocations_cn: ["不断增长的医疗支出", "控制医疗支出", "公共医疗支出", "人均医疗支出"],
    example_sentence_cn: "大多数发达国家的医疗支出增长速度超过了GDP，引发了对长期财政可持续性的担忧。",
    synonyms_cn: ["医疗开支", "卫生预算", "医疗费用"],
  },
  {
    id: "health-084", word: "immune system function", translation: "免疫系统功能", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 81, topics: ["health"], modules: ["reading", "speaking"],
    collocations: ["boost immune system function", "support immune system function", "weaken immune system function", "optimal immune system function"],
    example_sentence: "A balanced diet rich in vitamins and minerals is essential for maintaining optimal immune system function.",
    synonyms: ["immunological defense", "body's defense mechanism", "immune response capacity"],
    common_mistakes: ["immune system 保护身体免受病原体侵害; 可以 strengthened/supported，但不是 overnight"],
    ielts_context: "Reading: nutrition / biology; Speaking Part 3: health / lifestyle",
    pronunciation: "/ɪˈmjuːn ˈsɪs.təm ˈfʌŋk.ʃən/",
    collocations_cn: ["增强免疫系统功能", "支持免疫系统功能", "削弱免疫系统功能", "最佳免疫系统功能"],
    example_sentence_cn: "富含维生素和矿物质的均衡饮食对于维持最佳的免疫系统功能至关重要。",
    synonyms_cn: ["免疫防御", "身体防御机制", "免疫反应能力"],
  },
  {
    id: "health-085", word: "healthcare professional", translation: "医疗专业人员", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 82, topics: ["health"], modules: ["listening", "speaking"],
    collocations: ["consult a healthcare professional", "trained healthcare professional", "qualified healthcare professional", "seek advice from a healthcare professional"],
    example_sentence: "People should always consult a qualified healthcare professional before starting any new treatment or making significant dietary changes.",
    synonyms: ["medical professional", "health worker", "clinician"],
    common_mistakes: ["healthcare professional 是广义术语，包括医生、护士、药剂师等"],
    ielts_context: "Listening Section 1: health advice; Speaking Part 1: health habits",
    pronunciation: "/ˈhelθ.keə prəˈfeʃ.ən.əl/",
    collocations_cn: ["咨询医疗专业人员", "经过培训的医疗专业人员", "合格的医疗专业人员", "向医疗专业人员寻求建议"],
    example_sentence_cn: "在开始任何新的治疗或进行重大饮食改变之前，人们应始终咨询合格的医疗专业人员。",
    synonyms_cn: ["医学专业人员", "卫生工作者", "临床医生"],
  },
  {
    id: "health-086", word: "sports injury", translation: "运动损伤", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 78, topics: ["health"], modules: ["speaking", "reading"],
    collocations: ["suffer a sports injury", "prevent sports injuries", "treat a sports injury", "recover from a sports injury"],
    example_sentence: "Proper warm-up exercises and correct technique are essential for preventing common sports injuries such as sprains and strains.",
    synonyms: ["athletic injury", "exercise-related trauma", "sporting damage"],
    common_mistakes: ["sports injury 用复数 sports 作形容词; 不是 sport injury"],
    ielts_context: "Speaking Part 2: injury / accident experience; Reading: sports medicine",
    pronunciation: "/spɔːts ˈɪn.dʒər.i/",
    collocations_cn: ["遭受运动损伤", "预防运动损伤", "治疗运动损伤", "从运动损伤中恢复"],
    example_sentence_cn: "适当的热身运动和正确的技术对于预防扭伤和拉伤等常见运动损伤至关重要。",
    synonyms_cn: ["竞技损伤", "运动相关外伤", "体育损伤"],
  },
  {
    id: "health-087", word: "opioid crisis", translation: "阿片类药物危机", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 84, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["tackle the opioid crisis", "address the opioid crisis", "opioid crisis epidemic", "devastating opioid crisis"],
    example_sentence: "The opioid crisis has claimed hundreds of thousands of lives, prompting governments to tighten prescription regulations and expand addiction treatment.",
    synonyms: ["opioid epidemic", "prescription drug crisis", "narcotic painkiller epidemic"],
    common_mistakes: ["opioid (阿片类药物) 包括 prescription painkillers 和 illegal drugs like heroin"],
    ielts_context: "Reading: public health / policy; Writing Task 2: health crisis / government action",
    pronunciation: "/ˈəʊ.pi.ɔɪd ˈkraɪ.sɪs/",
    collocations_cn: ["应对阿片类药物危机", "解决阿片类药物危机", "阿片类药物危机流行病", "毁灭性的阿片类药物危机"],
    example_sentence_cn: "阿片类药物危机已夺走数十万人的生命，促使政府加强处方监管并扩大成瘾治疗。",
    synonyms_cn: ["阿片类流行病", "处方药危机", "麻醉止痛药泛滥"],
  },
  {
    id: "health-088", word: "dietary guideline", translation: "膳食指南", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 79, topics: ["health"], modules: ["reading", "speaking"],
    collocations: ["follow dietary guidelines", "national dietary guidelines", "update dietary guidelines", "recommend in dietary guidelines"],
    example_sentence: "National dietary guidelines recommend consuming at least five portions of fruits and vegetables per day for optimal health.",
    synonyms: ["nutrition recommendation", "eating guideline", "food consumption advice"],
    common_mistakes: ["dietary guidelines 是国家层面基于科学的饮食建议; 不是个人膳食计划"],
    ielts_context: "Reading: nutrition / public health; Speaking Part 3: healthy eating",
    pronunciation: "/ˈdaɪ.ə.tər.i ˈɡaɪd.laɪn/",
    collocations_cn: ["遵循膳食指南", "国家膳食指南", "更新膳食指南", "膳食指南推荐"],
    example_sentence_cn: "国家膳食指南建议每天至少摄入五份水果和蔬菜以获得最佳健康。",
    synonyms_cn: ["营养建议", "饮食指导", "食品消费建议"],
  },
  // ═══ 中頻 50-69 (12 个) ═══
  {
    id: "health-089", word: "medical ethics", translation: "医学伦理", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 67, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["uphold medical ethics", "violate medical ethics", "principles of medical ethics", "medical ethics committee"],
    example_sentence: "Medical ethics requires healthcare providers to balance patient autonomy, beneficence, non-maleficence, and justice in clinical decision-making.",
    synonyms: ["bioethics", "clinical ethics", "healthcare morality"],
    common_mistakes: ["medical ethics 指临床实践中医生对患者的伦理义务; bioethics 范围更广，包括生物研究伦理"],
    ielts_context: "Reading: medicine / philosophy; Writing Task 2: healthcare / ethics",
    pronunciation: "/ˈmed.ɪ.kəl ˈeθ.ɪks/",
    collocations_cn: ["维护医学伦理", "违反医学伦理", "医学伦理原则", "医学伦理委员会"],
    example_sentence_cn: "医学伦理要求医疗提供者在临床决策中平衡患者自主权、有利原则、不伤害原则和公正原则。",
    synonyms_cn: ["生物伦理", "临床伦理", "医疗道德"],
  },
  {
    id: "health-090", word: "contact tracing", translation: "接触者追踪", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 65, topics: ["health"], modules: ["reading", "listening"],
    collocations: ["implement contact tracing", "digital contact tracing", "contact tracing app", "effective contact tracing"],
    example_sentence: "Contact tracing is a fundamental public health tool used to identify and notify individuals who may have been exposed to an infectious disease.",
    synonyms: ["exposure notification", "epidemiological tracing", "infection chain mapping"],
    common_mistakes: ["contact tracing 是公共卫生术语，指追踪感染者接触过的人"],
    ielts_context: "Reading: public health / epidemiology; Listening: health authority briefing",
    pronunciation: "/ˈkɒn.tækt ˈtreɪ.sɪŋ/",
    collocations_cn: ["实施接触者追踪", "数字接触者追踪", "接触者追踪应用", "有效的接触者追踪"],
    example_sentence_cn: "接触者追踪是用于识别和通知可能接触过传染病的个人的基本公共卫生工具。",
    synonyms_cn: ["曝露通知", "流行病学追踪", "感染链映射"],
  },
  {
    id: "health-091", word: "outpatient clinic", translation: "门诊诊所", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 64, topics: ["health"], modules: ["listening", "reading"],
    collocations: ["visit an outpatient clinic", "hospital outpatient clinic", "outpatient clinic appointment", "specialist outpatient clinic"],
    example_sentence: "Outpatient clinics provide medical consultations and minor procedures without requiring patients to stay overnight in hospital.",
    synonyms: ["ambulatory care center", "day clinic", "community health clinic"],
    common_mistakes: ["outpatient (门诊) 不需要过夜; inpatient (住院) 需要留院观察治疗"],
    ielts_context: "Listening Section 1: medical appointment; Reading: healthcare services",
    pronunciation: "/ˈaʊt.peɪ.ʃənt ˈklɪn.ɪk/",
    collocations_cn: ["前往门诊诊所", "医院门诊诊所", "门诊诊所预约", "专科门诊诊所"],
    example_sentence_cn: "门诊诊所提供医疗咨询和小型手术，患者无需在医院过夜。",
    synonyms_cn: ["日间诊所", "社区卫生中心", "流动护理中心"],
  },
  {
    id: "health-092", word: "sanitation facility", translation: "卫生设施", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 66, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["access to sanitation facilities", "lack of sanitation facilities", "improve sanitation facilities", "basic sanitation facilities"],
    example_sentence: "Access to clean water and adequate sanitation facilities is a fundamental human right recognized by the United Nations.",
    synonyms: ["hygiene infrastructure", "waste disposal system", "public health amenities"],
    common_mistakes: ["sanitation 包括安全处理人类排泄物、垃圾处理和清洁饮水; 不只是厕所"],
    ielts_context: "Reading: global development / public health; Writing Task 2: infrastructure / poverty",
    pronunciation: "/ˌsæn.ɪˈteɪ.ʃən fəˈsɪl.ɪ.ti/",
    collocations_cn: ["获得卫生设施", "缺乏卫生设施", "改善卫生设施", "基本卫生设施"],
    example_sentence_cn: "获得清洁水和充足的卫生设施是联合国承认的一项基本人权。",
    synonyms_cn: ["卫生基础设施", "废物处理系统", "公共卫生设施"],
  },
  {
    id: "health-093", word: "yoga and mindfulness", translation: "瑜伽与正念", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 62, topics: ["health"], modules: ["speaking", "reading"],
    collocations: ["practice yoga and mindfulness", "yoga and mindfulness techniques", "benefits of yoga and mindfulness", "incorporate yoga and mindfulness"],
    example_sentence: "Many corporations now offer yoga and mindfulness sessions to help employees manage stress and improve focus at work.",
    synonyms: ["meditative movement", "mind-body practice", "holistic wellness routine"],
    common_mistakes: ["yoga 是印度传统的身心练习; mindfulness 是佛教冥想的一部分，两者结合使用但并非同一事物"],
    ielts_context: "Speaking Part 2: relaxation / healthy habit; Reading: wellness / workplace",
    pronunciation: "/ˈjəʊ.ɡə ənd ˈmaɪnd.fəl.nəs/",
    collocations_cn: ["练习瑜伽与正念", "瑜伽与正念技巧", "瑜伽与正念的好处", "融入瑜伽与正念"],
    example_sentence_cn: "许多企业现在提供瑜伽与正念课程，帮助员工管理压力并提高工作中的专注力。",
    synonyms_cn: ["冥想运动", "身心练习", "整体健康习惯"],
  },
  {
    id: "health-094", word: "life support system", translation: "生命支持系统", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 65, topics: ["health"], modules: ["reading", "listening"],
    collocations: ["placed on a life support system", "remove from life support system", "advanced life support system", "connected to a life support system"],
    example_sentence: "The patient was placed on a life support system to maintain breathing and circulation until his condition stabilized.",
    synonyms: ["mechanical ventilation", "critical care apparatus", "organ support equipment"],
    common_mistakes: ["life support 特指维持生命的机械设备; 不泛指 life-saving treatment"],
    ielts_context: "Reading: medical technology / end-of-life care; Listening: hospital scenario",
    pronunciation: "/laɪf səˈpɔːt ˈsɪs.təm/",
    collocations_cn: ["被连接生命支持系统", "撤除生命支持系统", "先进的生命支持系统", "连接了生命支持系统"],
    example_sentence_cn: "患者被接上生命支持系统以维持呼吸和循环，直到其病情稳定。",
    synonyms_cn: ["机械通风", "危重护理设备", "器官支持设备"],
  },
  {
    id: "health-095", word: "clinical diagnosis", translation: "临床诊断", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 64, topics: ["health"], modules: ["reading", "listening"],
    collocations: ["make a clinical diagnosis", "confirm a clinical diagnosis", "accurate clinical diagnosis", "clinical diagnosis criteria"],
    example_sentence: "A clinical diagnosis is based on the patient's reported symptoms, physical examination findings, and relevant test results.",
    synonyms: ["medical diagnosis", "professional assessment", "clinical evaluation"],
    common_mistakes: ["diagnosis 是基于证据的医学判断，不仅仅是对症状的描述"],
    ielts_context: "Reading: medical case studies; Listening: doctor consultation",
    pronunciation: "/ˈklɪn.ɪ.kəl ˌdaɪ.əɡˈnəʊ.sɪs/",
    collocations_cn: ["做出临床诊断", "确认临床诊断", "准确的临床诊断", "临床诊断标准"],
    example_sentence_cn: "临床诊断基于患者报告的症状、体格检查结果和相关检测结果。",
    synonyms_cn: ["医学诊断", "专业评估", "临床评价"],
  },
  {
    id: "health-096", word: "generic drug", translation: "仿制药", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 63, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["prescribe a generic drug", "switch to generic drugs", "generic drug manufacturer", "approve a generic drug"],
    example_sentence: "Generic drugs contain the same active ingredients as brand-name medications but are typically sold at a fraction of the cost.",
    synonyms: ["off-brand medication", "unbranded pharmaceutical", "bioequivalent drug"],
    common_mistakes: ["generic drug 与原研药在有效成分、剂量、安全性上相同; 不是低质药品"],
    ielts_context: "Reading: pharmaceuticals / healthcare costs; Writing Task 2: healthcare affordability",
    pronunciation: "/dʒəˈner.ɪk drʌɡ/",
    collocations_cn: ["开具仿制药处方", "改用仿制药", "仿制药生产商", "批准仿制药"],
    example_sentence_cn: "仿制药含有与品牌药相同的有效成分，但通常以远低于品牌药的价格出售。",
    synonyms_cn: ["非品牌药品", "非专利药", "生物等效药"],
  },
  {
    id: "health-097", word: "health complaint", translation: "健康问题/主诉", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 66, topics: ["health"], modules: ["listening", "speaking"],
    collocations: ["present a health complaint", "common health complaint", "minor health complaint", "report a health complaint"],
    example_sentence: "The doctor asked the patient to describe their health complaint in detail, including when the symptoms first appeared.",
    synonyms: ["medical issue", "ailment", "symptom presentation"],
    common_mistakes: ["health complaint 在此不是投诉，而是描述疾病症状的主诉"],
    ielts_context: "Listening Section 1: doctor's appointment; Speaking Part 2: illness experience",
    pronunciation: "/helθ kəmˈpleɪnt/",
    collocations_cn: ["陈述健康问题", "常见的健康问题", "轻微的健康不适", "报告健康问题"],
    example_sentence_cn: "医生请患者详细描述其健康问题，包括症状首次出现的时间。",
    synonyms_cn: ["医疗问题", "小病痛", "症状表现"],
  },
  {
    id: "health-098", word: "nutrition label", translation: "营养标签", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 63, topics: ["health"], modules: ["reading", "speaking"],
    collocations: ["read the nutrition label", "check the nutrition label", "clear nutrition label", "nutrition label information"],
    example_sentence: "Consumers are encouraged to read nutrition labels carefully to make informed choices about the food they purchase.",
    synonyms: ["food label", "nutritional fact panel", "dietary information label"],
    common_mistakes: ["nutrition label 包含卡路里、脂肪、糖、蛋白质等信息; ingredient list 是按含量排列的配料表"],
    ielts_context: "Reading: health / consumer information; Speaking Part 3: healthy eating",
    pronunciation: "/njuːˈtrɪʃ.ən ˈleɪ.bəl/",
    collocations_cn: ["阅读营养标签", "查看营养标签", "清晰的营养标签", "营养标签信息"],
    example_sentence_cn: "鼓励消费者仔细阅读营养标签，以便对所购食品做出明智的选择。",
    synonyms_cn: ["食品标签", "营养成分表", "膳食信息标签"],
  },
  {
    id: "health-099", word: "chemical exposure", translation: "化学物质暴露", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 62, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["limit chemical exposure", "harmful chemical exposure", "occupational chemical exposure", "long-term chemical exposure"],
    example_sentence: "Long-term chemical exposure in industrial workplaces can lead to serious respiratory conditions and increased cancer risk.",
    synonyms: ["toxic contact", "hazardous substance exposure", "chemical contamination risk"],
    common_mistakes: ["chemical exposure 可以发生在吃、呼吸和皮肤接触等多种途径上"],
    ielts_context: "Reading: occupational health / environmental health; Writing Task 2: safety regulation",
    pronunciation: "/ˈkem.ɪ.kəl ɪkˈspəʊ.ʒər/",
    collocations_cn: ["限制化学物质暴露", "有害化学物质暴露", "职业性化学物质暴露", "长期化学物质暴露"],
    example_sentence_cn: "工业工作场所的长期化学物质暴露可能导致严重的呼吸系统疾病并增加癌症风险。",
    synonyms_cn: ["有毒接触", "有害物质暴露", "化学污染风险"],
  },
  {
    id: "health-100", word: "preventive medicine", translation: "预防医学", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 68, topics: ["health"], modules: ["reading", "writing"],
    collocations: ["practice preventive medicine", "importance of preventive medicine", "invest in preventive medicine", "preventive medicine approach"],
    example_sentence: "Preventive medicine focuses on maintaining health and preventing disease before it occurs, rather than treating illness after it develops.",
    synonyms: ["prophylactic care", "preventive healthcare", "health protection"],
    common_mistakes: ["preventive medicine 是针对整个人群; clinical medicine 是针对患病个体"],
    ielts_context: "Reading: public health / healthcare strategy; Writing Task 2: healthcare investment",
    pronunciation: "/prɪˈven.tɪv ˈmed.ɪ.sɪn/",
    collocations_cn: ["践行预防医学", "预防医学的重要性", "投资预防医学", "预防医学方法"],
    example_sentence_cn: "预防医学侧重于在疾病发生之前保持健康和预防疾病，而不是在疾病发展后进行治疗。",
    synonyms_cn: ["预防性护理", "预防性医疗", "健康保护"],
  },
];
