// scripts/expand-environment.ts
// Phase 2: Environment 话题扩展 — env-051 ~ env-100（50 个新词块）
// 频次分布: 超高(90-99)×20 + 高(70-89)×18 + 中(50-69)×12

import type { Chunk } from "../types/chunk";

export const ENV_EXPANSION: Chunk[] = [
  // ═══ 超高頻 90-99 (20 个) ═══
  {
    id: "env-051", word: "climate crisis", translation: "气候危机", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 97, topics: ["environment"], modules: ["writing", "speaking"],
    collocations: ["address the climate crisis", "escalating climate crisis", "tackle the climate crisis", "climate crisis awareness"],
    example_sentence: "The climate crisis is widely regarded as the most pressing challenge facing humanity in the 21st century.",
    synonyms: ["climate emergency", "global climate threat", "environmental crisis"],
    common_mistakes: ["climate crisis 强调紧迫性; climate change 更为中性"],
    ielts_context: "Writing Task 2: environment / global issues; Speaking Part 3: climate topics",
    pronunciation: "/ˈklaɪ.mət ˈkraɪ.sɪs/",
    collocations_cn: ["应对气候危机", "不断升级的气候危机", "解决气候危机", "气候危机意识"],
    example_sentence_cn: "气候危机被广泛认为是21世纪人类面临的最紧迫挑战。",
    synonyms_cn: ["气候紧急状态", "全球气候威胁", "环境危机"],
  },
  {
    id: "env-052", word: "carbon neutrality", translation: "碳中和", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 96, topics: ["environment"], modules: ["writing", "reading"],
    collocations: ["achieve carbon neutrality", "commit to carbon neutrality", "path to carbon neutrality", "carbon neutrality target"],
    example_sentence: "Many countries have pledged to achieve carbon neutrality by 2050 to mitigate the worst effects of global warming.",
    synonyms: ["net-zero emissions", "carbon balance", "zero-carbon status"],
    common_mistakes: ["carbon neutral 是形容词形式; carbon neutrality 是名词形式"],
    ielts_context: "Writing Task 2: climate policy; Reading: environmental reports",
    pronunciation: "/ˈkɑː.bən njuːˈtræl.ə.ti/",
    collocations_cn: ["实现碳中和", "承诺碳中和", "碳中和之路", "碳中和目标"],
    example_sentence_cn: "许多国家已承诺到2050年实现碳中和，以缓解全球变暖的最严重影响。",
    synonyms_cn: ["净零排放", "碳平衡", "零碳状态"],
  },
  {
    id: "env-053", word: "environmental regulation", translation: "环境监管", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 94, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["enforce environmental regulations", "stricter environmental regulations", "comply with environmental regulations", "environmental regulation framework"],
    example_sentence: "Stronger environmental regulations are needed to hold corporations accountable for their ecological impact.",
    synonyms: ["environmental legislation", "green laws", "ecological governance"],
    common_mistakes: ["regulation 常用复数 regulations 表示具体法规条文"],
    ielts_context: "Writing Task 2: government / environment; Reading: policy documents",
    pronunciation: "/ɪnˌvaɪ.rənˈmen.təl ˌreɡ.jʊˈleɪ.ʃən/",
    collocations_cn: ["执行环境法规", "更严格的环境法规", "遵守环境法规", "环境监管框架"],
    example_sentence_cn: "需要更有力的环境法规来让企业对其生态影响负责。",
    synonyms_cn: ["环境立法", "绿色法律", "生态治理"],
  },
  {
    id: "env-054", word: "green technology", translation: "绿色技术", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 95, topics: ["environment"], modules: ["writing", "speaking"],
    collocations: ["invest in green technology", "adopt green technology", "green technology innovation", "green technology sector"],
    example_sentence: "Investment in green technology has surged as governments and businesses seek sustainable alternatives to fossil fuels.",
    synonyms: ["clean technology", "sustainable technology", "eco-technology"],
    common_mistakes: ["green tech 是口语中的缩略形式; 正式写作用 green technology"],
    ielts_context: "Writing Task 2: technology / environment; Speaking Part 3: clean energy",
    pronunciation: "/ɡriːn tekˈnɒl.ə.dʒi/",
    collocations_cn: ["投资绿色技术", "采用绿色技术", "绿色技术创新", "绿色技术行业"],
    example_sentence_cn: "随着政府和企业寻求化石燃料的可持续替代方案，对绿色技术的投资大幅增长。",
    synonyms_cn: ["清洁技术", "可持续技术", "生态技术"],
  },
  {
    id: "env-055", word: "sustainable agriculture", translation: "可持续农业", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 92, topics: ["environment"], modules: ["writing", "reading"],
    collocations: ["promote sustainable agriculture", "practice sustainable agriculture", "transition to sustainable agriculture", "sustainable agriculture methods"],
    example_sentence: "Sustainable agriculture aims to meet society's food needs while preserving environmental quality for future generations.",
    synonyms: ["eco-farming", "regenerative agriculture", "agroecology"],
    common_mistakes: ["sustainable 强调长期性; organic 只是 sustainable agriculture 的一个方面"],
    ielts_context: "Writing Task 2: food production / environment; Reading: agricultural science",
    pronunciation: "/səˈsteɪ.nə.bəl ˈæɡ.rɪ.kʌl.tʃər/",
    collocations_cn: ["推广可持续农业", "实行可持续农业", "向可持续农业转型", "可持续农业方法"],
    example_sentence_cn: "可持续农业旨在满足社会的粮食需求，同时为子孙后代保护环境质量。",
    synonyms_cn: ["生态农业", "再生农业", "生态耕作"],
  },
  {
    id: "env-056", word: "plastic pollution", translation: "塑料污染", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 96, topics: ["environment"], modules: ["speaking", "writing"],
    collocations: ["combat plastic pollution", "tackle plastic pollution", "marine plastic pollution", "plastic pollution crisis"],
    example_sentence: "Plastic pollution has reached alarming levels in the world's oceans, threatening marine life and human health.",
    synonyms: ["plastic waste crisis", "plastic contamination", "synthetic waste pollution"],
    common_mistakes: ["pollution 是不可数名词; plastic 是形容词修饰名词"],
    ielts_context: "Writing Task 2: pollution / waste; Speaking Part 3: environmental issues",
    pronunciation: "/ˈplæs.tɪk pəˈluː.ʃən/",
    collocations_cn: ["对抗塑料污染", "解决塑料污染", "海洋塑料污染", "塑料污染危机"],
    example_sentence_cn: "塑料污染在全球海洋中已达到惊人水平，威胁着海洋生物和人类健康。",
    synonyms_cn: ["塑料废物危机", "塑料污染", "合成废物污染"],
  },
  {
    id: "env-057", word: "energy transition", translation: "能源转型", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 93, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["accelerate the energy transition", "global energy transition", "renewable energy transition", "just energy transition"],
    example_sentence: "The energy transition from fossil fuels to renewable sources is essential for achieving long-term climate goals.",
    synonyms: ["energy transformation", "clean energy shift", "decarbonization"],
    common_mistakes: ["energy transition 特指能源体系转型; energy conservation 是节约能源"],
    ielts_context: "Writing Task 2: energy policy; Reading: energy economics",
    pronunciation: "/ˈen.ə.dʒi trænˈzɪʃ.ən/",
    collocations_cn: ["加速能源转型", "全球能源转型", "可再生能源转型", "公正的能源转型"],
    example_sentence_cn: "从化石燃料向可再生能源的能源转型对于实现长期气候目标至关重要。",
    synonyms_cn: ["能源转型", "清洁能源转变", "去碳化"],
  },
  {
    id: "env-058", word: "water conservation", translation: "水资源保护", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["environment"], modules: ["speaking", "reading"],
    collocations: ["practice water conservation", "water conservation measures", "promote water conservation", "water conservation strategy"],
    example_sentence: "Water conservation has become increasingly important as many regions face prolonged droughts and dwindling freshwater reserves.",
    synonyms: ["water saving", "water preservation", "water stewardship"],
    common_mistakes: ["conservation 表示合理使用的保护，不是 preservation (完全不使用)"],
    ielts_context: "Speaking Part 3: water resources; Reading: environmental management",
    pronunciation: "/ˈwɔː.tər ˌkɒn.səˈveɪ.ʃən/",
    collocations_cn: ["实行水资源保护", "水资源保护措施", "推广水资源保护", "水资源保护策略"],
    example_sentence_cn: "随着许多地区面临长期干旱和淡水储备减少，水资源保护变得越来越重要。",
    synonyms_cn: ["节约用水", "水资源保持", "水资源管理"],
  },
  {
    id: "env-059", word: "circular economy", translation: "循环经济", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["environment"], modules: ["writing", "reading"],
    collocations: ["transition to a circular economy", "circular economy model", "principles of circular economy", "circular economy initiatives"],
    example_sentence: "The circular economy aims to eliminate waste by designing products that can be reused, repaired, or recycled indefinitely.",
    synonyms: ["closed-loop economy", "regenerative economy", "zero-waste system"],
    common_mistakes: ["circular economy 不是 recycling 的同义词; 它是整个生产和消费系统的重设计"],
    ielts_context: "Writing Task 2: sustainability / business; Reading: environmental economics",
    pronunciation: "/ˈsɜː.kjʊ.lər iˈkɒn.ə.mi/",
    collocations_cn: ["向循环经济转型", "循环经济模式", "循环经济原则", "循环经济倡议"],
    example_sentence_cn: "循环经济旨在通过设计可无限重复使用、修复或回收的产品来消除废弃物。",
    synonyms_cn: ["闭环经济", "再生经济", "零废弃系统"],
  },
  {
    id: "env-060", word: "ecosystem services", translation: "生态系统服务", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 90, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["value ecosystem services", "degradation of ecosystem services", "ecosystem services assessment", "protect ecosystem services"],
    example_sentence: "Forests provide invaluable ecosystem services including carbon sequestration, water purification, and biodiversity habitat.",
    synonyms: ["natural capital", "environmental services", "ecological benefits"],
    common_mistakes: ["ecosystem 是一个词; eco-system 是较旧的非标准拼写"],
    ielts_context: "Reading: environmental science; Writing Task 2: conservation / economics",
    pronunciation: "/ˈiː.kəʊˌsɪs.təm ˈsɜː.vɪ.sɪz/",
    collocations_cn: ["重视生态系统服务", "生态系统服务的退化", "生态系统服务评估", "保护生态系统服务"],
    example_sentence_cn: "森林提供宝贵的生态系统服务，包括碳封存、水净化和生物多样性栖息地。",
    synonyms_cn: ["自然资本", "环境服务", "生态效益"],
  },
  {
    id: "env-061", word: "climate resilience", translation: "气候韧性", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 92, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["build climate resilience", "strengthen climate resilience", "climate resilience strategies", "enhance climate resilience"],
    example_sentence: "Developing countries need financial and technical support to build climate resilience in vulnerable communities.",
    synonyms: ["climate adaptation capacity", "environmental resilience", "climate robustness"],
    common_mistakes: ["resilience 表示恢复力; resistance 表示抵抗力，两者含义不同"],
    ielts_context: "Reading: climate adaptation reports; Writing Task 2: climate policy",
    pronunciation: "/ˈklaɪ.mət rɪˈzɪl.i.əns/",
    collocations_cn: ["建设气候韧性", "加强气候韧性", "气候韧性策略", "增强气候韧性"],
    example_sentence_cn: "发展中国家需要财政和技术支持来在脆弱社区建设气候韧性。",
    synonyms_cn: ["气候适应能力", "环境韧性", "气候抗逆力"],
  },
  {
    id: "env-062", word: "natural capital", translation: "自然资本", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 90, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["invest in natural capital", "deplete natural capital", "value natural capital", "natural capital accounting"],
    example_sentence: "Natural capital accounting helps governments understand the economic value of forests, wetlands, and other ecosystems.",
    synonyms: ["environmental assets", "ecological capital", "nature's wealth"],
    common_mistakes: ["natural capital 是经济学概念; natural resources 是具体资源"],
    ielts_context: "Reading: environmental economics; Writing Task 2: sustainable development",
    pronunciation: "/ˈnætʃ.ər.əl ˈkæp.ɪ.təl/",
    collocations_cn: ["投资自然资本", "消耗自然资本", "为自然资本估值", "自然资本核算"],
    example_sentence_cn: "自然资本核算有助于政府了解森林、湿地和其他生态系统的经济价值。",
    synonyms_cn: ["环境资产", "生态资本", "自然财富"],
  },
  {
    id: "env-063", word: "air quality index", translation: "空气质量指数", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["environment"], modules: ["listening", "reading"],
    collocations: ["check the air quality index", "hazardous air quality index", "daily air quality index", "air quality index reading"],
    example_sentence: "Residents are advised to stay indoors when the air quality index exceeds 150, indicating unhealthy pollution levels.",
    synonyms: ["AQI", "pollution index", "air pollution scale"],
    common_mistakes: ["AQI 是 Air Quality Index 的缩写; 口语中可说 smog level 但非正式"],
    ielts_context: "Listening Section 2: weather / health reports; Reading: environmental data",
    pronunciation: "/eə ˈkwɒl.ɪ.ti ˈɪn.deks/",
    collocations_cn: ["查看空气质量指数", "有害的空气质量指数", "每日空气质量指数", "空气质量指数读数"],
    example_sentence_cn: "当空气质量指数超过150时，表明污染水平不健康，建议居民待在室内。",
    synonyms_cn: ["空气质量指数", "污染指数", "空气污染等级"],
  },
  {
    id: "env-064", word: "environmental governance", translation: "环境治理", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 91, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["strengthen environmental governance", "global environmental governance", "environmental governance framework", "effective environmental governance"],
    example_sentence: "Effective environmental governance requires coordinated action across local, national, and international levels.",
    synonyms: ["environmental management", "ecological governance", "green governance"],
    common_mistakes: ["governance 不单指政府 (government)，也包括企业、NGO等多方参与"],
    ielts_context: "Reading: policy / international relations; Writing Task 2: global cooperation",
    pronunciation: "/ɪnˌvaɪ.rənˈmen.təl ˈɡʌv.ən.əns/",
    collocations_cn: ["加强环境治理", "全球环境治理", "环境治理框架", "有效的环境治理"],
    example_sentence_cn: "有效的环境治理需要在地方、国家和国际层面采取协调行动。",
    synonyms_cn: ["环境管理", "生态治理", "绿色治理"],
  },
  {
    id: "env-065", word: "zero-emission vehicle", translation: "零排放车辆", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 93, topics: ["environment"], modules: ["speaking", "reading"],
    collocations: ["promote zero-emission vehicles", "switch to zero-emission vehicles", "zero-emission vehicle mandate", "zero-emission vehicle adoption"],
    example_sentence: "Several European countries plan to ban the sale of new petrol and diesel cars by 2035, accelerating the transition to zero-emission vehicles.",
    synonyms: ["electric vehicle", "clean-energy car", "emission-free vehicle"],
    common_mistakes: ["zero-emission 有连字符; 注意 electric vehicle 是 ZEV 的一种但不完全相同"],
    ielts_context: "Speaking Part 3: transport / technology; Reading: automotive industry news",
    pronunciation: "/ˈzɪə.rəʊ ɪˈmɪʃ.ən ˈviː.ɪ.kəl/",
    collocations_cn: ["推广零排放车辆", "转向零排放车辆", "零排放车辆要求", "零排放车辆采用"],
    example_sentence_cn: "多个欧洲国家计划到2035年禁售新的汽油和柴油车，加速向零排放车辆过渡。",
    synonyms_cn: ["电动汽车", "清洁能源汽车", "无排放车辆"],
  },
  {
    id: "env-066", word: "low-carbon economy", translation: "低碳经济", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 94, topics: ["environment"], modules: ["writing", "reading"],
    collocations: ["transition to a low-carbon economy", "build a low-carbon economy", "low-carbon economy transition", "low-carbon economy strategy"],
    example_sentence: "The transition to a low-carbon economy presents both significant challenges and enormous economic opportunities.",
    synonyms: ["decarbonized economy", "green economy", "sustainable economy"],
    common_mistakes: ["low-carbon 指减少碳排放; zero-carbon 是完全零碳，二者程度不同"],
    ielts_context: "Writing Task 2: economy / environment; Reading: business / sustainability",
    pronunciation: "/ləʊ ˈkɑː.bən iˈkɒn.ə.mi/",
    collocations_cn: ["向低碳经济转型", "建设低碳经济", "低碳经济转型", "低碳经济战略"],
    example_sentence_cn: "向低碳经济转型既带来了重大挑战，也带来了巨大的经济机遇。",
    synonyms_cn: ["去碳化经济", "绿色经济", "可持续经济"],
  },
  {
    id: "env-067", word: "environmental activist", translation: "环保活动人士", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["environment"], modules: ["speaking", "reading"],
    collocations: ["young environmental activist", "leading environmental activist", "environmental activist group", "inspiring environmental activist"],
    example_sentence: "Environmental activists have played a crucial role in raising public awareness about the urgency of climate action.",
    synonyms: ["eco-activist", "climate campaigner", "green advocate"],
    common_mistakes: ["activist 指积极采取行动促变的人; campaigner 侧重宣传活动"],
    ielts_context: "Speaking Part 2: an inspiring person; Reading: news / profiles",
    pronunciation: "/ɪnˌvaɪ.rənˈmen.təl ˈæk.tɪ.vɪst/",
    collocations_cn: ["年轻的环保活动人士", "知名环保活动人士", "环保活动团体", "鼓舞人心的环保活动人士"],
    example_sentence_cn: "环保活动人士在提高公众对气候行动紧迫性的认识方面发挥了关键作用。",
    synonyms_cn: ["生态活动家", "气候运动者", "绿色倡导者"],
  },
  {
    id: "env-068", word: "renewable capacity", translation: "可再生能源装机容量", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["expand renewable capacity", "installed renewable capacity", "renewable capacity growth", "add renewable capacity"],
    example_sentence: "China continues to lead the world in installed renewable capacity, accounting for over 40% of global wind and solar power.",
    synonyms: ["clean energy capacity", "green power capacity", "sustainable energy output"],
    common_mistakes: ["capacity 指装机容量/发电能力，不只指规模 scale"],
    ielts_context: "Reading: energy reports; Writing Task 2: renewable energy",
    pronunciation: "/rɪˈnjuː.ə.bəl kəˈpæs.ɪ.ti/",
    collocations_cn: ["扩大可再生能源装机容量", "已安装的可再生能源装机容量", "可再生能源装机容量增长", "增加可再生能源装机容量"],
    example_sentence_cn: "中国在可再生能源装机容量方面继续领先世界，占全球风电和太阳能发电的40%以上。",
    synonyms_cn: ["清洁能源产能", "绿电装机容量", "可持续能源输出"],
  },
  {
    id: "env-069", word: "carbon offset", translation: "碳抵消", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 92, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["purchase carbon offsets", "carbon offset program", "carbon offset market", "voluntary carbon offset"],
    example_sentence: "Many airlines now offer passengers the option to purchase carbon offsets to compensate for the emissions from their flights.",
    synonyms: ["emission offset", "carbon compensation", "climate offset credit"],
    common_mistakes: ["carbon offset 是补偿已经排放的碳，不是减少排放 itself"],
    ielts_context: "Reading: business / sustainability; Writing Task 2: corporate responsibility",
    pronunciation: "/ˈkɑː.bən ˈɒf.set/",
    collocations_cn: ["购买碳抵消", "碳抵消项目", "碳抵消市场", "自愿性碳抵消"],
    example_sentence_cn: "许多航空公司现在为乘客提供购买碳抵消的选项，以补偿其航班的排放。",
    synonyms_cn: ["排放抵消", "碳补偿", "气候抵消信用"],
  },
  {
    id: "env-070", word: "ecological degradation", translation: "生态退化", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 95, topics: ["environment"], modules: ["writing", "reading"],
    collocations: ["reverse environmental degradation", "contribute to environmental degradation", "widespread environmental degradation", "prevent environmental degradation"],
    example_sentence: "Industrial expansion in developing nations has often come at the cost of severe environmental degradation.",
    synonyms: ["ecological decline", "environmental deterioration", "habitat impairment"],
    common_mistakes: ["degradation 强调质量下降的过程; damage 强调损害结果"],
    ielts_context: "Writing Task 2: industry / development; Reading: environmental studies",
    pronunciation: "/ˌiː.kəˈlɒdʒ.ɪ.kəl ˌdeɡ.rəˈdeɪ.ʃən/",
    collocations_cn: ["扭转生态退化", "导致生态退化", "广泛的生态退化", "防止生态退化"],
    example_sentence_cn: "发展中国家的工业扩张往往以严重的环境退化为代价。",
    synonyms_cn: ["生态衰退", "环境恶化", "栖息地损害"],
  },
  // ═══ 高頻 70-89 (18 个) ═══
  {
    id: "env-071", word: "environmental impact assessment", translation: "环境影响评估", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 88, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["conduct an environmental impact assessment", "environmental impact assessment report", "require an environmental impact assessment", "comprehensive environmental impact assessment"],
    example_sentence: "An environmental impact assessment must be completed before any major construction project can receive government approval.",
    synonyms: ["EIA", "ecological assessment", "environmental review"],
    common_mistakes: ["EIA 是 Environmental Impact Assessment 的缩写; 不可与 EA (Environmental Audit) 混淆"],
    ielts_context: "Reading: environmental law / planning; Writing Task 2: development / environment",
    pronunciation: "/ɪnˌvaɪ.rənˈmen.təl ˈɪm.pækt əˈses.mənt/",
    collocations_cn: ["进行环境影响评估", "环境影响评估报告", "要求进行环境影响评估", "全面环境影响评估"],
    example_sentence_cn: "任何重大建设项目在获得政府批准之前都必须完成环境影响评估。",
    synonyms_cn: ["环境影响评价", "生态评估", "环境审查"],
  },
  {
    id: "env-072", word: "greenwashing", translation: "洗绿/漂绿", part_of_speech: "noun", band_level: "7.0", frequency_score: 82, topics: ["environment"], modules: ["reading", "speaking"],
    collocations: ["corporate greenwashing", "accused of greenwashing", "greenwashing practices", "combat greenwashing"],
    example_sentence: "Regulators are introducing stricter guidelines to prevent companies from engaging in greenwashing and misleading consumers about their environmental credentials.",
    synonyms: ["green sheen", "eco-whitewashing", "false environmental claims"],
    common_mistakes: ["greenwashing 来自 whitewash (粉饰) + green; 是一个词，不要分开写"],
    ielts_context: "Reading: business ethics; Speaking Part 3: consumer awareness",
    pronunciation: "/ˈɡriːn.wɒʃ.ɪŋ/",
    collocations_cn: ["企业洗绿", "被指控洗绿", "洗绿行为", "打击洗绿"],
    example_sentence_cn: "监管机构正在出台更严格的指导方针，防止公司进行洗绿并误导消费者其环保资质。",
    synonyms_cn: ["漂绿", "假环保宣传", "虚假环保声称"],
  },
  {
    id: "env-073", word: "microplastics", translation: "微塑料", part_of_speech: "noun (plural)", band_level: "6.5", frequency_score: 85, topics: ["environment"], modules: ["reading", "speaking"],
    collocations: ["microplastics pollution", "ingest microplastics", "presence of microplastics", "microplastics in the ocean"],
    example_sentence: "Scientists have discovered microplastics in human blood, raising serious concerns about the long-term health implications.",
    synonyms: ["plastic microparticles", "microscopic plastic debris", "nano-plastics"],
    common_mistakes: ["microplastics 通常用复数; 指直径小于5mm的塑料颗粒"],
    ielts_context: "Reading: environmental health / ocean pollution; Speaking Part 3: pollution issues",
    pronunciation: "/ˈmaɪ.krəʊˌplæs.tɪks/",
    collocations_cn: ["微塑料污染", "摄入微塑料", "微塑料的存在", "海洋中的微塑料"],
    example_sentence_cn: "科学家已在人体血液中发现微塑料，引发了对长期健康影响的严重关切。",
    synonyms_cn: ["塑料微粒", "微观塑料碎片", "纳米塑料"],
  },
  {
    id: "env-074", word: "sea level rise", translation: "海平面上升", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 87, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["accelerating sea level rise", "sea level rise projections", "threatened by sea level rise", "adapt to sea level rise"],
    example_sentence: "Low-lying island nations are among the most vulnerable to the effects of sea level rise caused by global warming.",
    synonyms: ["coastal inundation", "ocean level increase", "rising sea levels"],
    common_mistakes: ["sea level rise 是持续性的过程; sea level 本身单指海平面"],
    ielts_context: "Reading: climate science; Writing Task 2: climate impacts / migration",
    pronunciation: "/siː ˈlev.əl raɪz/",
    collocations_cn: ["加速的海平面上升", "海平面上升预测", "受海平面上升威胁", "适应海平面上升"],
    example_sentence_cn: "低洼岛屿国家尤其容易受到全球变暖导致的海平面上升的影响。",
    synonyms_cn: ["沿海淹没", "海面升高", "海平面升高"],
  },
  {
    id: "env-075", word: "ecological ethics", translation: "生态伦理", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 75, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["principles of environmental ethics", "apply environmental ethics", "environmental ethics framework", "debate in environmental ethics"],
    example_sentence: "Environmental ethics challenges us to reconsider our moral obligations towards non-human species and future generations.",
    synonyms: ["ecological ethics", "green philosophy", "environmental moral philosophy"],
    common_mistakes: ["ethics 作学科名时是单数; 指具体道德准则时常用复数"],
    ielts_context: "Reading: philosophy / environment; Writing Task 2: moral responsibility",
    pronunciation: "/ˌiː.kəˈlɒdʒ.ɪ.kəl ˈeθ.ɪks/",
    collocations_cn: ["生态伦理原则", "应用生态伦理", "生态伦理框架", "生态伦理辩论"],
    example_sentence_cn: "环境伦理挑战我们重新思考对非人类物种和后代所负有的道德义务。",
    synonyms_cn: ["生态伦理", "绿色哲学", "环境道德哲学"],
  },
  {
    id: "env-076", word: "desertification", translation: "荒漠化", part_of_speech: "noun", band_level: "6.5", frequency_score: 78, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["combat desertification", "land desertification", "prone to desertification", "prevent desertification"],
    example_sentence: "Unsustainable farming practices and climate change are accelerating desertification in many arid and semi-arid regions.",
    synonyms: ["land degradation", "soil desertification", "aridification"],
    common_mistakes: ["desertification 特指土地退化变成沙漠的过程，不是指沙漠扩张"],
    ielts_context: "Reading: geography / agriculture; Writing Task 2: land management",
    pronunciation: "/dɪˌzɜː.tɪ.fɪˈkeɪ.ʃən/",
    collocations_cn: ["防治荒漠化", "土地荒漠化", "易荒漠化", "防止荒漠化"],
    example_sentence_cn: "不可持续的耕作方式和气候变化正在加速许多干旱和半干旱地区的荒漠化。",
    synonyms_cn: ["土地退化", "土壤沙化", "干旱化"],
  },
  {
    id: "env-077", word: "carbon tax", translation: "碳税", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 84, topics: ["environment"], modules: ["writing", "reading"],
    collocations: ["introduce a carbon tax", "impose a carbon tax", "carbon tax revenue", "carbon tax policy"],
    example_sentence: "A carbon tax is widely regarded by economists as one of the most cost-effective ways to reduce greenhouse gas emissions.",
    synonyms: ["carbon levy", "emissions tax", "carbon pricing"],
    common_mistakes: ["carbon tax 针对碳排放征税; cap-and-trade 是另一种碳定价机制"],
    ielts_context: "Writing Task 2: government policy / environment; Reading: economics",
    pronunciation: "/ˈkɑː.bən tæks/",
    collocations_cn: ["引入碳税", "征收碳税", "碳税收入", "碳税政策"],
    example_sentence_cn: "碳税被经济学家广泛认为是减少温室气体排放最具成本效益的方法之一。",
    synonyms_cn: ["碳排放税", "排放税", "碳定价"],
  },
  {
    id: "env-078", word: "overfishing", translation: "过度捕捞", part_of_speech: "noun", band_level: "6.0", frequency_score: 83, topics: ["environment"], modules: ["reading", "speaking"],
    collocations: ["combat overfishing", "illegal overfishing", "consequences of overfishing", "prevent overfishing"],
    example_sentence: "Overfishing has depleted many of the world's fish stocks, threatening both marine biodiversity and the livelihoods of coastal communities.",
    synonyms: ["excessive fishing", "fish stock depletion", "unsustainable harvesting"],
    common_mistakes: ["overfishing 是一个词; 不要分开写成 over fishing"],
    ielts_context: "Reading: marine biology / economics; Speaking Part 3: food / environment",
    pronunciation: "/ˌəʊ.vəˈfɪʃ.ɪŋ/",
    collocations_cn: ["打击过度捕捞", "非法过度捕捞", "过度捕捞的后果", "防止过度捕捞"],
    example_sentence_cn: "过度捕捞已耗尽世界许多鱼类资源，威胁着海洋生物多样性和沿海社区的生计。",
    synonyms_cn: ["过度捕鱼", "鱼类资源枯竭", "不可持续捕捞"],
  },
  {
    id: "env-079", word: "green building", translation: "绿色建筑", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 80, topics: ["environment"], modules: ["speaking", "reading"],
    collocations: ["design green buildings", "green building certification", "green building materials", "green building standard"],
    example_sentence: "Green building design incorporates energy-efficient systems, sustainable materials, and natural lighting to reduce environmental impact.",
    synonyms: ["sustainable construction", "eco-friendly building", "low-impact architecture"],
    common_mistakes: ["green building 不限于建筑颜色; 指环保节能的建筑设计和施工方式"],
    ielts_context: "Speaking Part 3: urban design / housing; Reading: architecture / sustainability",
    pronunciation: "/ɡriːn ˈbɪl.dɪŋ/",
    collocations_cn: ["设计绿色建筑", "绿色建筑认证", "绿色建筑材料", "绿色建筑标准"],
    example_sentence_cn: "绿色建筑设计整合了节能系统、可持续材料和自然采光，以减少环境影响。",
    synonyms_cn: ["可持续建筑", "环保建筑", "低影响建筑"],
  },
  {
    id: "env-080", word: "ecological restoration", translation: "生态恢复", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 79, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["undertake ecological restoration", "large-scale ecological restoration", "ecological restoration projects", "ecological restoration techniques"],
    example_sentence: "Ecological restoration of degraded wetlands has proven effective in improving water quality and reviving wildlife populations.",
    synonyms: ["ecosystem rehabilitation", "habitat recovery", "environmental remediation"],
    common_mistakes: ["restoration 指恢复到接近原始状态; restoration 比 remediation 更全面"],
    ielts_context: "Reading: conservation biology; Writing Task 2: environmental management",
    pronunciation: "/ˌiː.kəˈlɒdʒ.ɪ.kəl ˌres.tərˈeɪ.ʃən/",
    collocations_cn: ["进行生态恢复", "大规模生态恢复", "生态恢复项目", "生态恢复技术"],
    example_sentence_cn: "退化湿地的生态恢复已被证明能有效改善水质并恢复野生动物种群。",
    synonyms_cn: ["生态系统修复", "栖息地恢复", "环境修复"],
  },
  {
    id: "env-081", word: "biodegradable material", translation: "可生物降解材料", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 81, topics: ["environment"], modules: ["reading", "speaking"],
    collocations: ["use biodegradable materials", "develop biodegradable materials", "biodegradable packaging material", "fully biodegradable material"],
    example_sentence: "Researchers are developing biodegradable materials from plant fibers to replace conventional plastics in food packaging.",
    synonyms: ["compostable material", "decomposable substance", "organic-based material"],
    common_mistakes: ["biodegradable 表示能被生物分解; degradable 仅表示能降解（可能产生微塑料）"],
    ielts_context: "Reading: materials science / waste management; Speaking Part 3: consumer products",
    pronunciation: "/ˌbaɪ.əʊ.dɪˈɡreɪ.də.bəl məˈtɪə.ri.əl/",
    collocations_cn: ["使用可生物降解材料", "开发可生物降解材料", "可生物降解包装材料", "完全可生物降解材料"],
    example_sentence_cn: "研究人员正在从植物纤维中开发可生物降解材料，以替代传统塑料用于食品包装。",
    synonyms_cn: ["可堆肥材料", "可分解物质", "有机基材料"],
  },
  {
    id: "env-082", word: "water treatment", translation: "水处理", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 80, topics: ["environment"], modules: ["reading", "listening"],
    collocations: ["wastewater treatment plant", "advanced water treatment", "water treatment technology", "water treatment facility"],
    example_sentence: "Modern water treatment plants use a combination of physical, chemical, and biological processes to make water safe for consumption.",
    synonyms: ["water purification", "sewage treatment", "water sanitation"],
    common_mistakes: ["water treatment 指对所有类型的水进行处理; wastewater treatment 特指废水处理"],
    ielts_context: "Reading: infrastructure / public health; Listening: facility tours",
    pronunciation: "/ˈwɔː.tər ˈtriːt.mənt/",
    collocations_cn: ["污水处理厂", "先进水处理技术", "水处理技术", "水处理设施"],
    example_sentence_cn: "现代水处理厂综合运用物理、化学和生物过程，使水变得安全可饮用。",
    synonyms_cn: ["水净化", "污水处理", "水卫生处理"],
  },
  {
    id: "env-083", word: "climate adaptation", translation: "气候适应", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 86, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["invest in climate adaptation", "climate adaptation measures", "national climate adaptation plan", "climate adaptation funding"],
    example_sentence: "Climate adaptation strategies, such as building flood defenses and developing drought-resistant crops, are becoming increasingly urgent.",
    synonyms: ["climate adjustment", "adaptive capacity building", "climate preparedness"],
    common_mistakes: ["adaptation (适应) 和 mitigation (减缓排放) 是气候行动的两个不同维度"],
    ielts_context: "Reading: climate policy; Writing Task 2: government planning / environment",
    pronunciation: "/ˈklaɪ.mət ˌæd.æpˈteɪ.ʃən/",
    collocations_cn: ["投资气候适应", "气候适应措施", "国家气候适应计划", "气候适应资金"],
    example_sentence_cn: "气候适应策略，如建设防洪设施和开发抗旱作物，正变得越来越紧迫。",
    synonyms_cn: ["气候调整", "适应能力建设", "气候准备"],
  },
  {
    id: "env-084", word: "sustainable consumption", translation: "可持续消费", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 83, topics: ["environment"], modules: ["writing", "speaking"],
    collocations: ["encourage sustainable consumption", "sustainable consumption patterns", "promote sustainable consumption", "shift towards sustainable consumption"],
    example_sentence: "Sustainable consumption requires individuals to make conscious choices about the environmental impact of the products they buy.",
    synonyms: ["responsible consumption", "green purchasing", "eco-conscious consumption"],
    common_mistakes: ["sustainable consumption 不仅指买少，还指买对——选择环保产品"],
    ielts_context: "Writing Task 2: consumer behavior / environment; Speaking Part 3: lifestyle",
    pronunciation: "/səˈsteɪ.nə.bəl kənˈsʌmp.ʃən/",
    collocations_cn: ["鼓励可持续消费", "可持续消费模式", "推广可持续消费", "转向可持续消费"],
    example_sentence_cn: "可持续消费要求个人对其所购产品的环境影响做出有意识的选择。",
    synonyms_cn: ["负责任消费", "绿色购买", "环保意识消费"],
  },
  {
    id: "env-085", word: "pollution control", translation: "污染控制", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 82, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["implement pollution control measures", "stringent pollution control", "pollution control technology", "pollution control regulations"],
    example_sentence: "Effective pollution control requires a combination of government regulation, technological innovation, and public cooperation.",
    synonyms: ["pollution management", "emission control", "contamination prevention"],
    common_mistakes: ["pollution control 指控制污染源; pollution cleanup 指清理已发生的污染"],
    ielts_context: "Reading: environmental engineering; Writing Task 2: industry / regulation",
    pronunciation: "/pəˈluː.ʃən kənˈtrəʊl/",
    collocations_cn: ["实施污染控制措施", "严格的污染控制", "污染控制技术", "污染控制法规"],
    example_sentence_cn: "有效的污染控制需要政府监管、技术创新和公众合作的结合。",
    synonyms_cn: ["污染管理", "排放控制", "污染预防"],
  },
  {
    id: "env-086", word: "climate summit", translation: "气候峰会", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 84, topics: ["environment"], modules: ["reading", "speaking"],
    collocations: ["attend a climate summit", "UN climate summit", "global climate summit", "host a climate summit"],
    example_sentence: "World leaders gathered at the annual climate summit to negotiate binding commitments on reducing carbon emissions.",
    synonyms: ["climate conference", "environmental summit", "COP meeting"],
    common_mistakes: ["COP 代表 Conference of the Parties; 如 COP28 指第28届缔约方会议"],
    ielts_context: "Reading: international news; Speaking Part 3: global cooperation",
    pronunciation: "/ˈklaɪ.mət ˈsʌm.ɪt/",
    collocations_cn: ["参加气候峰会", "联合国气候峰会", "全球气候峰会", "主办气候峰会"],
    example_sentence_cn: "世界领导人齐聚年度气候峰会，就减少碳排放的有约束力承诺进行谈判。",
    synonyms_cn: ["气候大会", "环境峰会", "缔约方会议"],
  },
  {
    id: "env-087", word: "environmental monitoring", translation: "环境监测", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 77, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["conduct environmental monitoring", "environmental monitoring system", "continuous environmental monitoring", "satellite environmental monitoring"],
    example_sentence: "Satellite-based environmental monitoring provides crucial data on deforestation, ice cap melting, and air pollution on a global scale.",
    synonyms: ["ecological surveillance", "environmental observation", "eco-monitoring"],
    common_mistakes: ["monitoring 指持续观察记录; inspection 指一次性检查"],
    ielts_context: "Reading: technology / environment; Writing Task 2: data-driven policy",
    pronunciation: "/ɪnˌvaɪ.rənˈmen.təl ˈmɒn.ɪ.tər.ɪŋ/",
    collocations_cn: ["进行环境监测", "环境监测系统", "持续环境监测", "卫星环境监测"],
    example_sentence_cn: "基于卫星的环境监测为全球范围内的森林砍伐、冰盖融化和空气污染提供了关键数据。",
    synonyms_cn: ["生态监测", "环境观测", "环境监测"],
  },
  {
    id: "env-088", word: "food waste", translation: "食物浪费", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 82, topics: ["environment"], modules: ["speaking", "reading"],
    collocations: ["reduce food waste", "household food waste", "food waste crisis", "compost food waste"],
    example_sentence: "Approximately one-third of all food produced globally is lost or wasted, contributing significantly to greenhouse gas emissions.",
    synonyms: ["food loss", "kitchen waste", "edible waste"],
    common_mistakes: ["food waste (食物浪费) 不同于 food loss (食物损耗，发生在生产环节)"],
    ielts_context: "Speaking Part 3: food / environment; Reading: sustainability reports",
    pronunciation: "/fuːd weɪst/",
    collocations_cn: ["减少食物浪费", "家庭食物浪费", "食物浪费危机", "堆肥处理食物浪费"],
    example_sentence_cn: "全球约三分之一的粮食被损失或浪费，对温室气体排放贡献显著。",
    synonyms_cn: ["粮食损失", "厨房废弃物", "可食用废弃物"],
  },
  // ═══ 中頻 50-69 (12 个) ═══
  {
    id: "env-089", word: "eco-tourism", translation: "生态旅游", part_of_speech: "noun", band_level: "6.0", frequency_score: 68, topics: ["environment"], modules: ["reading", "speaking"],
    collocations: ["promote eco-tourism", "eco-tourism destination", "responsible eco-tourism", "eco-tourism initiatives"],
    example_sentence: "Eco-tourism provides economic incentives for local communities to conserve rather than exploit their natural resources.",
    synonyms: ["sustainable tourism", "green travel", "nature-based tourism"],
    common_mistakes: ["eco-tourism 强调保护自然和支持当地社区; 不仅仅是自然旅游"],
    ielts_context: "Speaking Part 2: travel experience; Reading: travel / sustainability",
    pronunciation: "/ˈiː.kəʊˌtʊə.rɪ.zəm/",
    collocations_cn: ["推广生态旅游", "生态旅游目的地", "负责任的生态旅游", "生态旅游倡议"],
    example_sentence_cn: "生态旅游为当地社区保护而非开发其自然资源提供了经济激励。",
    synonyms_cn: ["可持续旅游", "绿色旅行", "自然旅游"],
  },
  {
    id: "env-090", word: "reforestation", translation: "重新造林", part_of_speech: "noun", band_level: "6.0", frequency_score: 67, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["large-scale reforestation", "reforestation projects", "promote reforestation", "reforestation efforts"],
    example_sentence: "Reforestation programs in China have successfully increased forest coverage from 12% to over 23% in just a few decades.",
    synonyms: ["afforestation", "tree planting", "forest regeneration"],
    common_mistakes: ["reforestation 是指在曾经有森林的地方重新造林; afforestation 是指在从未有过森林的地方造林"],
    ielts_context: "Reading: conservation / geography; Writing Task 2: environmental solutions",
    pronunciation: "/ˌriː.fɒr.ɪˈsteɪ.ʃən/",
    collocations_cn: ["大规模重新造林", "重新造林项目", "促进重新造林", "重新造林工作"],
    example_sentence_cn: "中国的重新造林计划在短短几十年内成功将森林覆盖率从12%提高到23%以上。",
    synonyms_cn: ["造林", "植树造林", "森林再生"],
  },
  {
    id: "env-091", word: "chemical fertilizer", translation: "化肥", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 65, topics: ["environment"], modules: ["reading", "speaking"],
    collocations: ["apply chemical fertilizers", "overuse of chemical fertilizers", "synthetic chemical fertilizers", "reduce chemical fertilizer use"],
    example_sentence: "Excessive use of chemical fertilizers has led to soil degradation and water pollution through agricultural runoff.",
    synonyms: ["synthetic fertilizer", "inorganic fertilizer", "artificial plant nutrient"],
    common_mistakes: ["fertilizer 是肥料; pesticide 是杀虫剂; herbicide 是除草剂，不要混淆"],
    ielts_context: "Reading: agriculture / environment; Speaking Part 3: farming practices",
    pronunciation: "/ˈkem.ɪ.kəl ˈfɜː.tɪ.laɪ.zər/",
    collocations_cn: ["施用化肥", "过度使用化肥", "合成化肥", "减少化肥使用"],
    example_sentence_cn: "过度使用化肥已通过农业径流导致土壤退化和水污染。",
    synonyms_cn: ["合成肥料", "无机肥料", "人造植物营养素"],
  },
  {
    id: "env-092", word: "green energy subsidy", translation: "绿色能源补贴", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 64, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["provide green energy subsidies", "green energy subsidy program", "cut green energy subsidies", "expand green energy subsidies"],
    example_sentence: "Government green energy subsidies have been instrumental in making solar and wind power cost-competitive with fossil fuels.",
    synonyms: ["renewable energy incentive", "clean power subsidy", "alternative energy grant"],
    common_mistakes: ["subsidy 通常用复数 subsidies 表示多项补贴措施"],
    ielts_context: "Reading: energy policy / economics; Writing Task 2: government intervention",
    pronunciation: "/ɡriːn ˈen.ə.dʒi ˈsʌb.sɪ.di/",
    collocations_cn: ["提供绿色能源补贴", "绿色能源补贴计划", "削减绿色能源补贴", "扩大绿色能源补贴"],
    example_sentence_cn: "政府的绿色能源补贴在使太阳能和风能与化石燃料成本竞争力相当方面发挥了关键作用。",
    synonyms_cn: ["可再生能源激励", "清洁能源补贴", "替代能源补助"],
  },
  {
    id: "env-093", word: "marine protected area", translation: "海洋保护区", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 66, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["establish marine protected areas", "expand marine protected areas", "marine protected area network", "designate marine protected areas"],
    example_sentence: "Marine protected areas serve as sanctuaries where fish populations can recover and marine ecosystems can thrive undisturbed.",
    synonyms: ["ocean sanctuary", "marine reserve", "no-take zone"],
    common_mistakes: ["MPA 是 Marine Protected Area 的缩写; 程度不同，从限制到完全禁止"],
    ielts_context: "Reading: ocean conservation; Writing Task 2: environmental policy",
    pronunciation: "/məˈriːn prəˈtek.tɪd ˈeə.ri.ə/",
    collocations_cn: ["建立海洋保护区", "扩大海洋保护区", "海洋保护区网络", "指定海洋保护区"],
    example_sentence_cn: "海洋保护区作为庇护所，让鱼类种群得以恢复，海洋生态系统得以不受干扰地繁荣。",
    synonyms_cn: ["海洋庇护区", "海洋禁捕区", "禁渔区"],
  },
  {
    id: "env-094", word: "sustainable forestry", translation: "可持续林业", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 63, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["practice sustainable forestry", "promote sustainable forestry", "sustainable forestry management", "certified sustainable forestry"],
    example_sentence: "Sustainable forestry ensures that timber harvesting does not compromise the long-term health and biodiversity of forest ecosystems.",
    synonyms: ["responsible logging", "eco-forestry", "sustainable timber management"],
    common_mistakes: ["sustainable forestry 不等于停止伐木，而是管理性采伐不损害森林再生能力"],
    ielts_context: "Reading: resource management; Writing Task 2: industry / environment",
    pronunciation: "/səˈsteɪ.nə.bəl ˈfɒr.ɪ.stri/",
    collocations_cn: ["实行可持续林业", "推广可持续林业", "可持续林业管理", "认证的可持续林业"],
    example_sentence_cn: "可持续林业确保木材采伐不损害森林生态系统的长期健康和生物多样性。",
    synonyms_cn: ["负责任伐木", "生态林业", "可持续木材管理"],
  },
  {
    id: "env-095", word: "environmental compliance", translation: "环境合规", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 62, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["ensure environmental compliance", "environmental compliance audit", "verify environmental compliance", "environmental compliance standards"],
    example_sentence: "Companies must undergo regular environmental compliance audits to demonstrate adherence to pollution limits and waste disposal regulations.",
    synonyms: ["regulatory adherence", "ecological compliance", "green certification"],
    common_mistakes: ["compliance 后接 with; in compliance with environmental regulations"],
    ielts_context: "Reading: corporate governance / law; Writing Task 2: business regulation",
    pronunciation: "/ɪnˌvaɪ.rənˈmen.təl kəmˈplaɪ.əns/",
    collocations_cn: ["确保环境合规", "环境合规审计", "验证环境合规", "环境合规标准"],
    example_sentence_cn: "公司必须接受定期的环境合规审计，以证明遵守了污染限值和废物处理法规。",
    synonyms_cn: ["合规监管", "生态合规", "绿色认证"],
  },
  {
    id: "env-096", word: "oil spill", translation: "原油泄漏", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 67, topics: ["environment"], modules: ["reading", "speaking"],
    collocations: ["clean up an oil spill", "devastating oil spill", "major oil spill", "oil spill disaster"],
    example_sentence: "The devastating oil spill destroyed local fisheries, contaminated coastlines, and killed thousands of marine animals.",
    synonyms: ["petroleum leak", "crude oil discharge", "marine oil accident"],
    common_mistakes: ["oil spill 指意外泄漏; oil leakage 指缓慢渗漏"],
    ielts_context: "Reading: environmental disasters; Speaking Part 3: industrial accidents",
    pronunciation: "/ɔɪl spɪl/",
    collocations_cn: ["清理原油泄漏", "灾难性的原油泄漏", "重大原油泄漏", "原油泄漏灾难"],
    example_sentence_cn: "灾难性的原油泄漏摧毁了当地渔业，污染了海岸线，并导致数千只海洋动物死亡。",
    synonyms_cn: ["石油泄漏", "原油泄漏", "海洋油污事故"],
  },
  {
    id: "env-097", word: "wetland conservation", translation: "湿地保护", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 64, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["prioritize wetland conservation", "wetland conservation efforts", "international wetland conservation", "wetland conservation area"],
    example_sentence: "Wetland conservation is critical for maintaining water quality, preventing floods, and preserving biodiversity hotspots.",
    synonyms: ["marshland preservation", "wetland protection", "swamp ecosystem conservation"],
    common_mistakes: ["wetland 可以统称沼泽、泥潭、泥炭地等多种湿地类型"],
    ielts_context: "Reading: ecology / geography; Writing Task 2: environmental protection",
    pronunciation: "/ˈwet.lənd ˌkɒn.səˈveɪ.ʃən/",
    collocations_cn: ["优先保护湿地", "湿地保护工作", "国际湿地保护", "湿地保护区"],
    example_sentence_cn: "湿地保护对于维持水质、防止洪水和保护生物多样性热点地区至关重要。",
    synonyms_cn: ["沼泽保护", "湿地保护", "沼泽生态系统保护"],
  },
  {
    id: "env-098", word: "solar panel installation", translation: "太阳能板安装", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 66, topics: ["environment"], modules: ["speaking", "listening"],
    collocations: ["residential solar panel installation", "solar panel installation cost", "large-scale solar panel installation", "rooftop solar panel installation"],
    example_sentence: "Government incentives have significantly boosted rooftop solar panel installation among homeowners in recent years.",
    synonyms: ["PV system setup", "solar array deployment", "photovoltaic installation"],
    common_mistakes: ["solar panel 光伏板; solar thermal 太阳能热水器，是不同的技术"],
    ielts_context: "Speaking Part 3: renewable energy / home; Listening Section 2: home improvement",
    pronunciation: "/ˈsəʊ.lər ˈpæn.əl ˌɪn.stəˈleɪ.ʃən/",
    collocations_cn: ["住宅太阳能板安装", "太阳能板安装成本", "大规模太阳能板安装", "屋顶太阳能板安装"],
    example_sentence_cn: "政府激励措施近年来显著推动了房主安装屋顶太阳能板。",
    synonyms_cn: ["光伏系统安装", "太阳能阵列部署", "光伏安装"],
  },
  {
    id: "env-099", word: "urban green space", translation: "城市绿地空间", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 65, topics: ["environment"], modules: ["speaking", "reading"],
    collocations: ["preserve green spaces", "urban green space", "access to green spaces", "lack of green spaces"],
    example_sentence: "Access to green spaces in urban areas has been linked to improved mental health and reduced stress levels among residents.",
    synonyms: ["public parks", "natural area", "recreational greenery"],
    common_mistakes: ["green space 既指公园也指森林、草地等自然区域; 不限于城市"],
    ielts_context: "Speaking Part 3: city living / well-being; Reading: urban planning",
    pronunciation: "/ˈɜː.bən ɡriːn speɪs/",
    collocations_cn: ["保护城市绿地空间", "城市绿地空间", "获得城市绿地空间", "缺乏城市绿地空间"],
    example_sentence_cn: "城市地区获得城市绿地空间已被证明与居民心理健康改善和压力水平降低有关。",
    synonyms_cn: ["公共公园", "自然区域", "休闲绿地"],
  },
  {
    id: "env-100", word: "climate refugee", translation: "气候难民", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 69, topics: ["environment"], modules: ["reading", "writing"],
    collocations: ["displaced climate refugees", "growing number of climate refugees", "climate refugee crisis", "protect climate refugees"],
    example_sentence: "Rising sea levels and extreme weather events are expected to create millions of climate refugees in the coming decades.",
    synonyms: ["environmental migrant", "climate-displaced person", "ecological refugee"],
    common_mistakes: ["climate refugee 目前不被国际法正式承认，不是 legal status; 更准确的说法是 environmental migrant"],
    ielts_context: "Reading: migration / climate; Writing Task 2: global issues / humanitarian",
    pronunciation: "/ˈklaɪ.mət ˌref.juˈdʒiː/",
    collocations_cn: ["流离失所的气候难民", "日益增多的气候难民", "气候难民危机", "保护气候难民"],
    example_sentence_cn: "预计在未来几十年，海平面上升和极端天气事件将产生数百万气候难民。",
    synonyms_cn: ["环境移民", "气候流离失所者", "生态难民"],
  },
];
