// scripts/expand-technology.ts
// Phase 2: Technology 话题扩展 — tech-051 ~ tech-100（50 个新词块）
// 频次分布: 超高(90-99)×20 + 高(70-89)×18 + 中(50-69)×12

import type { Chunk } from "../types/chunk";

export const TECH_EXPANSION: Chunk[] = [
  // ═══ 超高頻 90-99 (20 个) ═══
  {
    id: "tech-051", word: "machine learning", translation: "机器学习", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 97, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["machine learning algorithms", "apply machine learning", "powered by machine learning", "advances in machine learning"],
    example_sentence: "Machine learning algorithms are being deployed across industries to analyze vast datasets and make predictive decisions.",
    synonyms: ["ML", "computational learning", "statistical learning"],
    common_mistakes: ["machine learning 是 AI 的一个子集; 重点在从数据中学习而非显式编程"],
    ielts_context: "Reading: technology / business; Writing Task 2: automation / jobs",
    pronunciation: "/məˈʃiːn ˈlɜː.nɪŋ/",
    collocations_cn: ["机器学习算法", "应用机器学习", "由机器学习驱动", "机器学习的进展"],
    example_sentence_cn: "机器学习算法正被部署到各行各业，以分析海量数据集并做出预测性决策。",
    synonyms_cn: ["机器学习", "计算学习", "统计学习"],
  },
  {
    id: "tech-052", word: "autonomous vehicle", translation: "自动驾驶汽车", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 95, topics: ["technology"], modules: ["reading", "speaking"],
    collocations: ["develop autonomous vehicles", "autonomous vehicle technology", "test autonomous vehicles", "deploy autonomous vehicles"],
    example_sentence: "Autonomous vehicles have the potential to dramatically reduce traffic accidents caused by human error.",
    synonyms: ["self-driving car", "driverless vehicle", "automated transport"],
    common_mistakes: ["autonomous 表示完全自主; automated 表示自动化程度更高但可能仍需人工"],
    ielts_context: "Reading: transport / technology; Speaking Part 3: future of transport",
    pronunciation: "/ɔːˈtɒn.ə.məs ˈviː.ɪ.kəl/",
    collocations_cn: ["开发自动驾驶汽车", "自动驾驶汽车技术", "测试自动驾驶汽车", "部署自动驾驶汽车"],
    example_sentence_cn: "自动驾驶汽车有潜力大幅减少由人为失误造成的交通事故。",
    synonyms_cn: ["自动驾驶汽车", "无人驾驶车辆", "自动运输"],
  },
  {
    id: "tech-053", word: "data encryption", translation: "数据加密", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 93, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["use data encryption", "end-to-end data encryption", "strong data encryption", "data encryption standard"],
    example_sentence: "Data encryption is essential for protecting sensitive information transmitted over public networks.",
    synonyms: ["cryptographic protection", "data scrambling", "information encoding"],
    common_mistakes: ["encryption (加密) 不同于 encoding (编码); encoding 不提供安全性"],
    ielts_context: "Reading: cybersecurity / IT; Writing Task 2: privacy / security",
    pronunciation: "/ˈdeɪ.tə ɪnˈkrɪp.ʃən/",
    collocations_cn: ["使用数据加密", "端到端数据加密", "强大的数据加密", "数据加密标准"],
    example_sentence_cn: "数据加密对于保护通过公共网络传输的敏感信息至关重要。",
    synonyms_cn: ["密码保护", "数据加扰", "信息编码"],
  },
  {
    id: "tech-054", word: "cloud storage", translation: "云存储", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 94, topics: ["technology"], modules: ["speaking", "reading"],
    collocations: ["store files in cloud storage", "cloud storage service", "cloud storage provider", "cloud storage capacity"],
    example_sentence: "Cloud storage allows users to access their files from any device with an internet connection, offering convenience and flexibility.",
    synonyms: ["online storage", "remote data storage", "web-based storage"],
    common_mistakes: ["cloud storage 的数据存储在远程服务器上; local storage 是本地存储"],
    ielts_context: "Speaking Part 3: digital life / work; Reading: IT infrastructure",
    pronunciation: "/klaʊd ˈstɔː.rɪdʒ/",
    collocations_cn: ["将文件存储在云存储中", "云存储服务", "云存储提供商", "云存储容量"],
    example_sentence_cn: "云存储使用户能够通过任何有互联网连接的设备访问其文件，提供便利性和灵活性。",
    synonyms_cn: ["在线存储", "远程数据存储", "网络存储"],
  },
  {
    id: "tech-055", word: "5G network", translation: "5G网络", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 94, topics: ["technology"], modules: ["speaking", "reading"],
    collocations: ["roll out 5G networks", "5G network infrastructure", "5G network coverage", "upgrade to 5G networks"],
    example_sentence: "The rollout of 5G networks promises faster download speeds and lower latency, enabling new applications such as remote surgery and smart cities.",
    synonyms: ["fifth-generation mobile network", "next-gen connectivity", "ultra-fast mobile broadband"],
    common_mistakes: ["5G 不代表 5 GHz WiFi; 5G 是第五代移动通信技术"],
    ielts_context: "Speaking Part 3: technology / communication; Reading: telecom industry",
    pronunciation: "/ˌfaɪv ˈdʒiː ˈnet.wɜːk/",
    collocations_cn: ["推出5G网络", "5G网络基础设施", "5G网络覆盖", "升级到5G网络"],
    example_sentence_cn: "5G网络的推出承诺更快的下载速度和更低的延迟，为远程手术和智能城市等新应用铺平道路。",
    synonyms_cn: ["第五代移动网络", "下一代连接", "超快移动宽带"],
  },
  {
    id: "tech-056", word: "blockchain technology", translation: "区块链技术", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 92, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["adopt blockchain technology", "powered by blockchain technology", "applications of blockchain technology", "decentralized blockchain technology"],
    example_sentence: "Blockchain technology offers a secure and transparent way to record transactions without the need for a central authority.",
    synonyms: ["distributed ledger technology", "cryptographic chain", "decentralized database"],
    common_mistakes: ["blockchain 不一定等于 cryptocurrency; 区块链是一种基础设施技术"],
    ielts_context: "Reading: fintech / business; Writing Task 2: digital security",
    pronunciation: "/ˈblɒk.tʃeɪn tekˈnɒl.ə.dʒi/",
    collocations_cn: ["采用区块链技术", "由区块链技术驱动", "区块链技术的应用", "去中心化区块链技术"],
    example_sentence_cn: "区块链技术提供了一种安全透明的方式来记录交易，无需中央机构。",
    synonyms_cn: ["分布式账本技术", "密码链", "去中心化数据库"],
  },
  {
    id: "tech-057", word: "smart home device", translation: "智能家居设备", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 91, topics: ["technology"], modules: ["speaking", "listening"],
    collocations: ["install smart home devices", "control smart home devices", "smart home device market", "connected smart home devices"],
    example_sentence: "Smart home devices such as thermostats, lights, and security cameras can be controlled remotely via smartphone apps.",
    synonyms: ["home automation device", "connected appliance", "IoT home product"],
    common_mistakes: ["smart home device 不限于 voice assistant; 还包括智能温控、照明等"],
    ielts_context: "Speaking Part 2: useful device; Listening: technology / home",
    pronunciation: "/smɑːt həʊm dɪˈvaɪs/",
    collocations_cn: ["安装智能家居设备", "控制智能家居设备", "智能家居设备市场", "互联智能家居设备"],
    example_sentence_cn: "智能家居设备如恒温器、灯具和安全摄像头可以通过智能手机应用远程控制。",
    synonyms_cn: ["家庭自动化设备", "互联家电", "物联网家居产品"],
  },
  {
    id: "tech-058", word: "software development", translation: "软件开发", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 95, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["software development process", "agile software development", "software development team", "custom software development"],
    example_sentence: "Agile software development methodologies prioritize iterative progress, collaboration, and rapid response to changing requirements.",
    synonyms: ["programming", "software engineering", "application development"],
    common_mistakes: ["software development 包含完整生命周期; coding 只是编程环节"],
    ielts_context: "Reading: IT industry / career; Writing Task 2: technology sector",
    pronunciation: "/ˈsɒft.weə dɪˈvel.əp.mənt/",
    collocations_cn: ["软件开发流程", "敏捷软件开发", "软件开发团队", "定制软件开发"],
    example_sentence_cn: "敏捷软件开发方法论优先考虑迭代式进展、协作和对需求变化的快速响应。",
    synonyms_cn: ["编程", "软件工程", "应用开发"],
  },
  {
    id: "tech-059", word: "deep learning", translation: "深度学习", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 90, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["deep learning models", "train deep learning systems", "deep learning algorithms", "applications of deep learning"],
    example_sentence: "Deep learning has revolutionized fields such as image recognition, natural language processing, and medical diagnosis.",
    synonyms: ["deep neural networks", "hierarchical learning", "multi-layered AI"],
    common_mistakes: ["deep learning 是 machine learning 的子集; 使用多层神经网络"],
    ielts_context: "Reading: AI research / technology; Writing Task 2: technology impact",
    pronunciation: "/diːp ˈlɜː.nɪŋ/",
    collocations_cn: ["深度学习模型", "训练深度学习系统", "深度学习算法", "深度学习的应用"],
    example_sentence_cn: "深度学习已彻底改变了图像识别、自然语言处理和医疗诊断等领域。",
    synonyms_cn: ["深度神经网络", "层次学习", "多层人工智能"],
  },
  {
    id: "tech-060", word: "mobile application", translation: "移动应用", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 96, topics: ["technology"], modules: ["speaking", "listening"],
    collocations: ["download a mobile application", "develop a mobile application", "mobile application interface", "popular mobile application"],
    example_sentence: "Mobile applications have transformed how people bank, shop, and communicate on a daily basis.",
    synonyms: ["app", "mobile software", "smartphone application"],
    common_mistakes: ["mobile application 正式; app 口语化，日常使用没有问题"],
    ielts_context: "Speaking Part 2: useful technology; Listening Section 1: everyday tech",
    pronunciation: "/ˈməʊ.baɪl ˌæp.lɪˈkeɪ.ʃən/",
    collocations_cn: ["下载移动应用", "开发移动应用", "移动应用界面", "热门的移动应用"],
    example_sentence_cn: "移动应用已经改变了人们日常银行、购物和沟通的方式。",
    synonyms_cn: ["应用程序", "手机软件", "智能手机应用"],
  },
  {
    id: "tech-061", word: "cybersecurity", translation: "网络安全", part_of_speech: "noun", band_level: "6.5", frequency_score: 94, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["strengthen cybersecurity", "cybersecurity threats", "cybersecurity measures", "invest in cybersecurity"],
    example_sentence: "As businesses become more digital, the importance of robust cybersecurity measures cannot be overstated.",
    synonyms: ["information security", "digital protection", "online safety infrastructure"],
    common_mistakes: ["cybersecurity 是一个词; cyber security 也可接受但一个词更常见"],
    ielts_context: "Reading: IT / business; Writing Task 2: digital security",
    pronunciation: "/ˌsaɪ.bə.sɪˈkjʊə.rə.ti/",
    collocations_cn: ["加强网络安全", "网络安全威胁", "网络安全措施", "投资网络安全"],
    example_sentence_cn: "随着企业变得越来越数字化，强大的网络安全措施的重要性不容低估。",
    synonyms_cn: ["信息安全", "数字保护", "在线安全基础设施"],
  },
  {
    id: "tech-062", word: "search engine", translation: "搜索引擎", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 93, topics: ["technology"], modules: ["speaking", "reading"],
    collocations: ["use a search engine", "search engine results", "search engine optimization", "popular search engine"],
    example_sentence: "Search engines have become the primary gateway through which people access information on the internet.",
    synonyms: ["web search tool", "online search platform", "information retrieval system"],
    common_mistakes: ["search engine 不是一个 browser; browser 是浏览网页的软件"],
    ielts_context: "Speaking Part 3: information access; Reading: digital literacy",
    pronunciation: "/sɜːtʃ ˈen.dʒɪn/",
    collocations_cn: ["使用搜索引擎", "搜索引擎结果", "搜索引擎优化", "热门搜索引擎"],
    example_sentence_cn: "搜索引擎已成为人们通过互联网获取信息的主要入口。",
    synonyms_cn: ["网络搜索工具", "在线搜索平台", "信息检索系统"],
  },
  {
    id: "tech-063", word: "digital transformation", translation: "数字化转型", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 92, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["undergo digital transformation", "drive digital transformation", "digital transformation strategy", "embrace digital transformation"],
    example_sentence: "Digital transformation is reshaping traditional industries by integrating digital technologies into every aspect of operations.",
    synonyms: ["digitisation drive", "tech modernisation", "digital overhaul"],
    common_mistakes: ["digital transformation 不仅仅是把纸质文件变成PDF; 是整个业务流程的数字化重构"],
    ielts_context: "Reading: business / technology; Writing Task 2: industry trends",
    pronunciation: "/ˈdɪdʒ.ɪ.təl ˌtræns.fəˈmeɪ.ʃən/",
    collocations_cn: ["经历数字化转型", "推动数字化转型", "数字化转型战略", "拥抱数字化转型"],
    example_sentence_cn: "数字化转型正在通过将数字技术融入运营的各个方面来重塑传统行业。",
    synonyms_cn: ["数字化浪潮", "技术现代化", "数字变革"],
  },
  {
    id: "tech-064", word: "biometric authentication", translation: "生物识别认证", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["technology"], modules: ["reading", "speaking"],
    collocations: ["use biometric authentication", "biometric authentication systems", "secure biometric authentication", "biometric authentication technology"],
    example_sentence: "Biometric authentication methods, such as fingerprint and facial recognition, have become standard features on most smartphones.",
    synonyms: ["biometric verification", "biological identification", "physiological authentication"],
    common_mistakes: ["biometric 指通过生理特征识别; 与 password-based authentication 不同"],
    ielts_context: "Reading: security technology; Speaking Part 3: privacy / security",
    pronunciation: "/ˌbaɪ.əʊˈmet.rɪk ɔːˌθen.tɪˈkeɪ.ʃən/",
    collocations_cn: ["使用生物识别认证", "生物识别认证系统", "安全的生物识别认证", "生物识别认证技术"],
    example_sentence_cn: "指纹识别和面部识别等生物识别认证方法已成为大多数智能手机的标准功能。",
    synonyms_cn: ["生物特征验证", "生物身份识别", "生理认证"],
  },
  {
    id: "tech-065", word: "data privacy regulation", translation: "数据隐私法规", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["comply with data privacy regulations", "enforce data privacy regulations", "stricter data privacy regulations", "data privacy regulation framework"],
    example_sentence: "The introduction of comprehensive data privacy regulations has forced companies to fundamentally rethink their data collection practices.",
    synonyms: ["data protection law", "privacy legislation", "information privacy rules"],
    common_mistakes: ["GDPR 是欧盟通用数据保护条例; 不同国家有不同的法规体系"],
    ielts_context: "Reading: law / technology; Writing Task 2: government regulation",
    pronunciation: "/ˈdeɪ.tə ˈprɪv.ə.si ˌreɡ.jʊˈleɪ.ʃən/",
    collocations_cn: ["遵守数据隐私法规", "执行数据隐私法规", "更严格的数据隐私法规", "数据隐私法规框架"],
    example_sentence_cn: "全面的数据隐私法规的出台迫使公司从根本上重新思考其数据收集做法。",
    synonyms_cn: ["数据保护法", "隐私立法", "信息隐私规则"],
  },
  {
    id: "tech-066", word: "artificial intelligence ethics", translation: "人工智能伦理", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 90, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["AI ethics guidelines", "artificial intelligence ethics framework", "address artificial intelligence ethics", "artificial intelligence ethics committee"],
    example_sentence: "As AI systems become more autonomous, the field of artificial intelligence ethics has gained unprecedented importance in technology policy.",
    synonyms: ["AI morality", "machine ethics", "algorithmic fairness"],
    common_mistakes: ["AI ethics 不仅关心机器人权利，更关注算法偏见、隐私和问责等实际问题"],
    ielts_context: "Reading: tech policy / philosophy; Writing Task 2: technology regulation",
    pronunciation: "/ˌɑː.tɪˈfɪʃ.əl ɪnˈtel.ɪ.dʒəns ˈeθ.ɪks/",
    collocations_cn: ["人工智能伦理指南", "人工智能伦理框架", "应对人工智能伦理", "人工智能伦理委员会"],
    example_sentence_cn: "随着AI系统变得更加自主，人工智能伦理领域在技术政策中获得了空前的重要性。",
    synonyms_cn: ["AI道德", "机器伦理", "算法公平"],
  },
  {
    id: "tech-067", word: "tech support", translation: "技术支持", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["technology"], modules: ["listening", "speaking"],
    collocations: ["contact tech support", "24/7 tech support", "tech support team", "remote tech support"],
    example_sentence: "Efficient tech support is essential for businesses that rely heavily on IT infrastructure for their daily operations.",
    synonyms: ["IT support", "technical assistance", "help desk service"],
    common_mistakes: ["tech support 口语化; 正式写作用 technical support"],
    ielts_context: "Listening Section 1: customer service; Speaking Part 1: technology problems",
    pronunciation: "/tek səˈpɔːt/",
    collocations_cn: ["联系技术支持", "全天候技术支持", "技术支持团队", "远程技术支持"],
    example_sentence_cn: "高效的技术支持对于日常运营严重依赖IT基础设施的企业至关重要。",
    synonyms_cn: ["IT支持", "技术援助", "客服支持"],
  },
  {
    id: "tech-068", word: "data mining", translation: "数据挖掘", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["use data mining techniques", "data mining tools", "perform data mining", "data mining analysis"],
    example_sentence: "Retailers use data mining to analyze customer purchasing patterns and tailor their marketing strategies accordingly.",
    synonyms: ["data extraction", "pattern discovery", "knowledge discovery"],
    common_mistakes: ["data mining 是发现模式和洞察的过程; data collection 只是收集数据"],
    ielts_context: "Reading: business analytics / technology; Writing Task 2: consumer data",
    pronunciation: "/ˈdeɪ.tə ˈmaɪ.nɪŋ/",
    collocations_cn: ["使用数据挖掘技术", "数据挖掘工具", "进行数据挖掘", "数据挖掘分析"],
    example_sentence_cn: "零售商使用数据挖掘来分析客户购买模式并相应调整其营销策略。",
    synonyms_cn: ["数据提取", "模式发现", "知识发现"],
  },
  {
    id: "tech-069", word: "high-speed internet", translation: "高速互联网", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 95, topics: ["technology"], modules: ["speaking", "writing"],
    collocations: ["access to high-speed internet", "reliable high-speed internet", "high-speed internet connection", "expand high-speed internet"],
    example_sentence: "Access to high-speed internet is increasingly viewed as essential infrastructure for economic participation in the digital age.",
    synonyms: ["broadband", "fast internet", "fiber-optic connection"],
    common_mistakes: ["broadband (宽带) 就是 high-speed internet; 不要与 Wi-Fi (无线局域网) 混淆"],
    ielts_context: "Writing Task 2: infrastructure / digital divide; Speaking Part 3: rural development",
    pronunciation: "/haɪ spiːd ˈɪn.tə.net/",
    collocations_cn: ["获取高速互联网", "可靠的高速互联网", "高速互联网连接", "扩展高速互联网"],
    example_sentence_cn: "高速互联网的接入越来越被视为数字时代经济参与的必要基础设施。",
    synonyms_cn: ["宽带", "高速网络", "光纤连接"],
  },
  {
    id: "tech-070", word: "digital ecosystem", translation: "数字生态系统", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["build a digital ecosystem", "digital ecosystem platform", "thriving digital ecosystem", "integrated digital ecosystem"],
    example_sentence: "Apple's success is largely attributed to its tightly integrated digital ecosystem of devices, software, and services.",
    synonyms: ["tech ecosystem", "digital platform environment", "online ecosystem"],
    common_mistakes: ["digital ecosystem 是一个比喻，不是真正的生物生态系统"],
    ielts_context: "Reading: business / technology; Writing Task 2: digital economy",
    pronunciation: "/ˈdɪdʒ.ɪ.təl ˈiː.kəʊˌsɪs.təm/",
    collocations_cn: ["构建数字生态系统", "数字生态系统平台", "繁荣的数字生态系统", "一体化的数字生态系统"],
    example_sentence_cn: "苹果的成功很大程度上归功于其紧密集成的设备、软件和服务的数字生态系统。",
    synonyms_cn: ["技术生态系统", "数字平台环境", "在线生态系统"],
  },
  // ═══ 高頻 70-89 (18 个) ═══
  {
    id: "tech-071", word: "robot automation", translation: "机器人自动化", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 88, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["implement robot automation", "robot automation systems", "industrial robot automation", "robot automation technology"],
    example_sentence: "Robot automation has significantly increased production efficiency in manufacturing while reducing the risk of workplace injuries.",
    synonyms: ["robotic process automation", "automated robotics", "mechanical automation"],
    common_mistakes: ["RPA (Robotic Process Automation) 特指软件机器人，不是物理机器人"],
    ielts_context: "Reading: manufacturing / industry; Writing Task 2: automation / employment",
    pronunciation: "/ˈrəʊ.bɒt ˌɔː.təˈmeɪ.ʃən/",
    collocations_cn: ["实施机器人自动化", "机器人自动化系统", "工业机器人自动化", "机器人自动化技术"],
    example_sentence_cn: "机器人自动化显著提高了制造业的生产效率，同时减少了工伤风险。",
    synonyms_cn: ["机器人流程自动化", "自动化机器人", "机械自动化"],
  },
  {
    id: "tech-072", word: "online privacy", translation: "网络隐私", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 87, topics: ["technology"], modules: ["speaking", "writing"],
    collocations: ["protect online privacy", "concerns about online privacy", "violation of online privacy", "online privacy settings"],
    example_sentence: "As social media platforms collect ever more personal data, online privacy has become a growing public concern.",
    synonyms: ["digital privacy", "internet privacy", "web privacy"],
    common_mistakes: ["online privacy 不仅指密码安全，也包括数据收集、追踪等"],
    ielts_context: "Speaking Part 3: internet use; Writing Task 2: digital rights",
    pronunciation: "/ˈɒn.laɪn ˈprɪv.ə.si/",
    collocations_cn: ["保护网络隐私", "对网络隐私的担忧", "侵犯网络隐私", "网络隐私设置"],
    example_sentence_cn: "随着社交媒体平台收集越来越多的个人数据，网络隐私已成为日益增长的公众关切。",
    synonyms_cn: ["数字隐私", "互联网隐私", "网络隐私"],
  },
  {
    id: "tech-073", word: "user interface design", translation: "用户界面设计", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 84, topics: ["technology"], modules: ["reading", "speaking"],
    collocations: ["intuitive user interface design", "user interface design principles", "modern user interface design", "user interface design process"],
    example_sentence: "Good user interface design makes complex technology accessible and intuitive for non-technical users.",
    synonyms: ["UI design", "interface engineering", "human-computer interaction design"],
    common_mistakes: ["UI (用户界面) 和 UX (用户体验) 不同; UI 是 UX 的一部分"],
    ielts_context: "Reading: web development / design; Speaking Part 3: product design",
    pronunciation: "/ˈjuː.zər ˈɪn.tə.feɪs dɪˈzaɪn/",
    collocations_cn: ["直观的用户界面设计", "用户界面设计原则", "现代用户界面设计", "用户界面设计流程"],
    example_sentence_cn: "好的用户界面设计让复杂技术对非技术用户来说变得直观易用。",
    synonyms_cn: ["UI设计", "界面工程", "人机交互设计"],
  },
  {
    id: "tech-074", word: "technology startup", translation: "科技创业公司", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 83, topics: ["technology"], modules: ["speaking", "reading"],
    collocations: ["launch a tech startup", "venture-backed tech startup", "tech startup ecosystem", "early-stage tech startup"],
    example_sentence: "Silicon Valley remains the world's most influential hub for tech startups seeking venture capital investment.",
    synonyms: ["technology venture", "software startup", "innovation company"],
    common_mistakes: ["startup (创业公司) 和 small business (小企业) 不同; startup 追求快速扩张"],
    ielts_context: "Speaking Part 3: entrepreneurship; Reading: business / technology",
    pronunciation: "/tekˈnɒl.ə.dʒi ˈstɑːt.ʌp/",
    collocations_cn: ["创办科技创业公司", "风投支持的科技创业公司", "科技创业生态系统", "早期科技创业公司"],
    example_sentence_cn: "硅谷仍然是寻求风险投资的科技创业公司全球最具影响力的中心。",
    synonyms_cn: ["科技企业", "软件创业公司", "创新公司"],
  },
  {
    id: "tech-075", word: "semiconductor chip", translation: "半导体芯片", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 85, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["manufacture semiconductor chips", "semiconductor chip shortage", "advanced semiconductor chips", "semiconductor chip industry"],
    example_sentence: "The global semiconductor chip shortage has highlighted the strategic importance of domestic chip manufacturing capacity.",
    synonyms: ["microchip", "integrated circuit", "silicon chip"],
    common_mistakes: ["semiconductor 指导电性介于导体和绝缘体之间的材料; 是芯片的基础"],
    ielts_context: "Reading: technology / manufacturing; Writing Task 2: supply chain",
    pronunciation: "/ˌsem.i.kənˈdʌk.tər tʃɪp/",
    collocations_cn: ["制造半导体芯片", "半导体芯片短缺", "先进的半导体芯片", "半导体芯片行业"],
    example_sentence_cn: "全球半导体芯片短缺凸显了国内芯片制造能力的战略重要性。",
    synonyms_cn: ["微芯片", "集成电路", "硅片"],
  },
  {
    id: "tech-076", word: "digital payment system", translation: "数字支付系统", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 86, topics: ["technology"], modules: ["speaking", "reading"],
    collocations: ["use digital payment systems", "digital payment system platform", "secure digital payment systems", "adopt digital payment systems"],
    example_sentence: "Digital payment systems have transformed commerce by enabling instant, cashless transactions across borders.",
    synonyms: ["electronic payment", "mobile payment system", "cashless transaction platform"],
    common_mistakes: ["digital payment 广泛涵盖所有电子支付; mobile payment 特指手机支付"],
    ielts_context: "Speaking Part 3: shopping / finance; Reading: fintech / e-commerce",
    pronunciation: "/ˈdɪdʒ.ɪ.təl ˈpeɪ.mənt ˈsɪs.təm/",
    collocations_cn: ["使用数字支付系统", "数字支付系统平台", "安全的数字支付系统", "采用数字支付系统"],
    example_sentence_cn: "数字支付系统通过实现即时无现金的跨境交易，改变了商业。",
    synonyms_cn: ["电子支付", "移动支付系统", "无现金交易平台"],
  },
  {
    id: "tech-077", word: "data center", translation: "数据中心", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 82, topics: ["technology"], modules: ["reading", "listening"],
    collocations: ["build a data center", "cloud data center", "data center facility", "energy-efficient data center"],
    example_sentence: "The exponential growth of cloud computing has driven massive investment in data center construction worldwide.",
    synonyms: ["server farm", "computing facility", "IT infrastructure hub"],
    common_mistakes: ["data center 是物理设施; cloud 是虚拟服务，依赖数据中心运行"],
    ielts_context: "Reading: IT infrastructure; Listening: technology / business",
    pronunciation: "/ˈdeɪ.tə ˈsen.tər/",
    collocations_cn: ["建设数据中心", "云数据中心", "数据中心设施", "节能数据中心"],
    example_sentence_cn: "云计算的指数级增长推动了全球范围内数据中心建设的大规模投资。",
    synonyms_cn: ["服务器群", "计算设施", "IT基础设施中心"],
  },
  {
    id: "tech-078", word: "drone delivery", translation: "无人机配送", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 78, topics: ["technology"], modules: ["speaking", "reading"],
    collocations: ["pilot drone delivery", "drone delivery service", "commercial drone delivery", "autonomous drone delivery"],
    example_sentence: "Drone delivery services are being trialed in several cities to transport medical supplies and small packages efficiently.",
    synonyms: ["UAV delivery", "aerial delivery", "unmanned aerial logistics"],
    common_mistakes: ["drone 可以指军用无人机或民用四轴飞行器; 此处指民用配送"],
    ielts_context: "Speaking Part 3: future technology; Reading: logistics / innovation",
    pronunciation: "/drəʊn dɪˈlɪv.ər.i/",
    collocations_cn: ["试行无人机配送", "无人机配送服务", "商业无人机配送", "自主无人机配送"],
    example_sentence_cn: "无人机配送服务正在多个城市进行试点，以高效运输医疗用品和小型包裹。",
    synonyms_cn: ["无人飞行器配送", "空中配送", "无人航空物流"],
  },
  {
    id: "tech-079", word: "computer virus", translation: "计算机病毒", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 80, topics: ["technology"], modules: ["reading", "listening"],
    collocations: ["detect a computer virus", "infected with a computer virus", "protect against computer viruses", "computer virus attack"],
    example_sentence: "Ransomware, a particularly destructive type of computer virus, encrypts victims' files and demands payment for their release.",
    synonyms: ["malware", "malicious software", "digital contagion"],
    common_mistakes: ["computer virus 特指自我复制的恶意软件; malware 是更广义的恶意软件总称"],
    ielts_context: "Reading: cybersecurity; Listening Section 2: IT security briefing",
    pronunciation: "/kəmˈpjuː.tər ˈvaɪə.rəs/",
    collocations_cn: ["检测计算机病毒", "感染计算机病毒", "防范计算机病毒", "计算机病毒攻击"],
    example_sentence_cn: "勒索病毒是一种特别具有破坏性的计算机病毒类型，它加密受害者的文件并索要赎金才能释放。",
    synonyms_cn: ["恶意软件", "恶意软件", "数字传染病"],
  },
  {
    id: "tech-080", word: "speech recognition", translation: "语音识别", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 82, topics: ["technology"], modules: ["reading", "speaking"],
    collocations: ["speech recognition technology", "automatic speech recognition", "speech recognition system", "accuracy of speech recognition"],
    example_sentence: "Advances in speech recognition have made voice-controlled virtual assistants like Siri and Alexa a part of everyday life.",
    synonyms: ["voice recognition", "audio recognition", "spoken language processing"],
    common_mistakes: ["speech recognition 识别说话内容; voice recognition 识别说话者身份"],
    ielts_context: "Reading: AI / technology; Speaking Part 3: human-computer interaction",
    pronunciation: "/spiːtʃ ˌrek.əɡˈnɪʃ.ən/",
    collocations_cn: ["语音识别技术", "自动语音识别", "语音识别系统", "语音识别的准确度"],
    example_sentence_cn: "语音识别的进步使Siri和Alexa等声控虚拟助手成为日常生活的一部分。",
    synonyms_cn: ["声音识别", "音频识别", "口语处理"],
  },
  {
    id: "tech-081", word: "digital archive", translation: "数字档案", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 75, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["create a digital archive", "preserve in a digital archive", "online digital archive", "digital archive system"],
    example_sentence: "Libraries and museums are investing in digital archives to preserve historical documents and make them accessible worldwide.",
    synonyms: ["electronic repository", "digital library", "online collection"],
    common_mistakes: ["digital archive 不仅指扫描文件; 还包括原生数字内容的保存"],
    ielts_context: "Reading: cultural heritage / technology; Writing Task 2: preservation",
    pronunciation: "/ˈdɪdʒ.ɪ.təl ˈɑː.kaɪv/",
    collocations_cn: ["创建数字档案", "保存在数字档案中", "在线数字档案", "数字档案系统"],
    example_sentence_cn: "图书馆和博物馆正在投资数字档案，以保存历史文献并使其可供全球访问。",
    synonyms_cn: ["电子储存库", "数字图书馆", "在线收藏"],
  },
  {
    id: "tech-082", word: "operating system", translation: "操作系统", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 81, topics: ["technology"], modules: ["reading", "speaking"],
    collocations: ["install an operating system", "operating system update", "mobile operating system", "desktop operating system"],
    example_sentence: "The operating system manages all the hardware and software resources of a computer, serving as the foundation for all other programs.",
    synonyms: ["OS", "system software", "core platform"],
    common_mistakes: ["常见的操作系统有 Windows, macOS, Linux, iOS, Android"],
    ielts_context: "Reading: IT / technology; Speaking Part 1: computer use",
    pronunciation: "/ˈɒp.ər.eɪ.tɪŋ ˈsɪs.təm/",
    collocations_cn: ["安装操作系统", "操作系统更新", "移动操作系统", "桌面操作系统"],
    example_sentence_cn: "操作系统管理计算机的所有硬件和软件资源，是所有其他程序运行的基础。",
    synonyms_cn: ["系统软件", "核心平台", "OS"],
  },
  {
    id: "tech-083", word: "battery technology", translation: "电池技术", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 80, topics: ["technology"], modules: ["reading", "speaking"],
    collocations: ["advance battery technology", "lithium-ion battery technology", "next-generation battery technology", "battery technology breakthrough"],
    example_sentence: "Breakthroughs in battery technology are crucial for the widespread adoption of electric vehicles and renewable energy storage.",
    synonyms: ["energy storage technology", "power cell innovation", "rechargeable technology"],
    common_mistakes: ["battery 单指电池单元; battery pack 指由多个电池组成的电池组"],
    ielts_context: "Reading: energy / technology; Speaking Part 3: electric vehicles",
    pronunciation: "/ˈbæt.ər.i tekˈnɒl.ə.dʒi/",
    collocations_cn: ["推进电池技术", "锂离子电池技术", "下一代电池技术", "电池技术突破"],
    example_sentence_cn: "电池技术的突破对于电动汽车和可再生能源存储的广泛采用至关重要。",
    synonyms_cn: ["能源存储技术", "电力电池创新", "可充电技术"],
  },
  {
    id: "tech-084", word: "satellite navigation", translation: "卫星导航", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 80, topics: ["technology"], modules: ["speaking", "listening"],
    collocations: ["rely on satellite navigation", "satellite navigation system", "satellite navigation device", "satellite navigation signal"],
    example_sentence: "Modern logistics and transportation networks depend heavily on satellite navigation for route optimization and real-time tracking.",
    synonyms: ["GPS", "global positioning system", "satellite positioning"],
    common_mistakes: ["GPS 仅仅是卫星导航的一种 (美国); 还有 GLONASS (俄国)、北斗 (中国)、Galileo (欧盟)"],
    ielts_context: "Speaking Part 2: travel technology; Listening Section 2: transport / travel",
    pronunciation: "/ˈsæt.əl.aɪt ˌnæv.ɪˈɡeɪ.ʃən/",
    collocations_cn: ["依赖卫星导航", "卫星导航系统", "卫星导航设备", "卫星导航信号"],
    example_sentence_cn: "现代物流和运输网络严重依赖卫星导航进行路线优化和实时追踪。",
    synonyms_cn: ["全球定位系统", "卫星定位", "GPS"],
  },
  {
    id: "tech-085", word: "wireless charging", translation: "无线充电", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 79, topics: ["technology"], modules: ["speaking", "reading"],
    collocations: ["support wireless charging", "wireless charging pad", "fast wireless charging", "built-in wireless charging"],
    example_sentence: "Wireless charging technology eliminates the need for cables, allowing devices to charge simply by being placed on a compatible surface.",
    synonyms: ["inductive charging", "cordless charging", "contact-free power"],
    common_mistakes: ["wireless charging 仍需设备放在充电板上（近距离）; true wireless power (远程) 尚未商业化"],
    ielts_context: "Speaking Part 2: useful gadget; Reading: consumer electronics",
    pronunciation: "/ˈwaɪə.ləs ˈtʃɑː.dʒɪŋ/",
    collocations_cn: ["支持无线充电", "无线充电板", "快速无线充电", "内置无线充电"],
    example_sentence_cn: "无线充电技术消除了对线缆的需求，设备只需放在兼容表面上即可充电。",
    synonyms_cn: ["感应充电", "无绳充电", "免接触充电"],
  },
  {
    id: "tech-086", word: "virtual reality headset", translation: "虚拟现实头显", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 83, topics: ["technology"], modules: ["speaking", "reading"],
    collocations: ["put on a virtual reality headset", "immersive virtual reality headset", "virtual reality headset experience", "wireless virtual reality headset"],
    example_sentence: "Virtual reality headsets are increasingly used in education to create immersive learning experiences, from exploring ancient civilizations to conducting virtual science experiments.",
    synonyms: ["VR headset", "HMD (head-mounted display)", "immersive display device"],
    common_mistakes: ["VR headset 是完全沉浸式的; AR glasses 是在现实世界上叠加数字信息"],
    ielts_context: "Speaking Part 2: future technology; Reading: EdTech / entertainment",
    pronunciation: "/ˈvɜː.tʃu.əl riˈæl.ə.ti ˈhed.set/",
    collocations_cn: ["戴上虚拟现实头显", "沉浸式虚拟现实头显", "虚拟现实体验", "无线虚拟现实头显"],
    example_sentence_cn: "虚拟现实头显越来越多地用于教育中，创造沉浸式学习体验，从探索古代文明到进行虚拟科学实验。",
    synonyms_cn: ["VR头显", "头戴显示器", "沉浸式显示设备"],
  },
  {
    id: "tech-087", word: "coding education", translation: "编程教育", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 77, topics: ["technology"], modules: ["speaking", "writing"],
    collocations: ["promote coding education", "early coding education", "coding education programs", "accessible coding education"],
    example_sentence: "Many countries have incorporated coding education into their national curriculum to prepare students for a technology-driven future.",
    synonyms: ["programming instruction", "computer science education", "software development training"],
    common_mistakes: ["coding 是 writing code; computer science 范围更广，包括算法和理论"],
    ielts_context: "Speaking Part 3: education / technology; Writing Task 2: future skills",
    pronunciation: "/ˈkəʊ.dɪŋ ˌedʒ.ʊˈkeɪ.ʃən/",
    collocations_cn: ["推广编程教育", "早期编程教育", "编程教育项目", "可及的编程教育"],
    example_sentence_cn: "许多国家已将编程教育纳入国家课程体系，为学生在技术驱动的未来做好准备。",
    synonyms_cn: ["编程教学", "计算机科学教育", "软件开发培训"],
  },
  {
    id: "tech-088", word: "technology cluster", translation: "科技产业集群", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 76, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["form a technology cluster", "thriving technology cluster", "global technology cluster", "technology cluster development"],
    example_sentence: "Successful technology clusters like Silicon Valley thrive on the concentration of talent, capital, and knowledge-sharing networks.",
    synonyms: ["tech hub", "innovation cluster", "technology park"],
    common_mistakes: ["technology cluster 不仅仅是地理集中; 还包括人才、投资者、研究机构的生态系统"],
    ielts_context: "Reading: economics / innovation; Writing Task 2: regional development",
    pronunciation: "/tekˈnɒl.ə.dʒi ˈklʌs.tər/",
    collocations_cn: ["形成科技产业集群", "繁荣的科技产业集群", "全球科技产业集群", "科技产业集群发展"],
    example_sentence_cn: "像硅谷这样成功的科技产业集群依靠人才、资本和知识共享网络的集中而蓬勃发展。",
    synonyms_cn: ["科技中心", "创新集群", "科技园区"],
  },
  // ═══ 中頻 50-69 (12 个) ═══
  {
    id: "tech-089", word: "smart sensor", translation: "智能传感器", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 68, topics: ["technology"], modules: ["reading", "listening"],
    collocations: ["deploy smart sensors", "smart sensor technology", "network of smart sensors", "smart sensor data"],
    example_sentence: "Smart sensors embedded in bridges and buildings can monitor structural integrity and provide early warnings of potential failures.",
    synonyms: ["intelligent detector", "connected sensor", "IoT sensor"],
    common_mistakes: ["smart sensor 不仅能感知，还具有数据处理和通信能力"],
    ielts_context: "Reading: IoT / smart infrastructure; Listening: technology presentations",
    pronunciation: "/smɑːt ˈsen.sər/",
    collocations_cn: ["部署智能传感器", "智能传感器技术", "智能传感器网络", "智能传感器数据"],
    example_sentence_cn: "嵌入桥梁和建筑中的智能传感器可以监测结构完整性，并提供潜在故障的早期预警。",
    synonyms_cn: ["智能检测器", "互联传感器", "物联网传感器"],
  },
  {
    id: "tech-090", word: "dark web", translation: "暗网", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 65, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["access the dark web", "dark web marketplace", "dark web activity", "hidden on the dark web"],
    example_sentence: "While the dark web is often associated with illegal activities, it also serves as a platform for whistleblowers and journalists in repressive regimes.",
    synonyms: ["hidden internet", "encrypted network", "anonymous web"],
    common_mistakes: ["dark web 不等于 deep web; deep web 指未被搜索引擎索引的所有内容（如私人邮件）"],
    ielts_context: "Reading: cybersecurity / digital society; Writing Task 2: internet regulation",
    pronunciation: "/dɑːk web/",
    collocations_cn: ["访问暗网", "暗网市场", "暗网活动", "隐藏在暗网上"],
    example_sentence_cn: "虽然暗网通常与非法活动联系在一起，但它也为压制性政权下的举报人和记者提供了平台。",
    synonyms_cn: ["隐藏互联网", "加密网络", "匿名网络"],
  },
  {
    id: "tech-091", word: "interactive media", translation: "互动媒体", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 64, topics: ["technology"], modules: ["reading", "speaking"],
    collocations: ["create interactive media", "interactive media content", "digital interactive media", "interactive media platform"],
    example_sentence: "Interactive media engages users as active participants rather than passive consumers, transforming the way stories are told.",
    synonyms: ["participatory media", "digital interactive content", "responsive media"],
    common_mistakes: ["interactive media 让用户参与互动; social media 侧重社交网络"],
    ielts_context: "Reading: digital entertainment / education; Speaking Part 3: media",
    pronunciation: "/ˌɪn.tərˈæk.tɪv ˈmiː.di.ə/",
    collocations_cn: ["创作互动媒体", "互动媒体内容", "数字互动媒体", "互动媒体平台"],
    example_sentence_cn: "互动媒体让用户成为主动参与者而非被动消费者，改变了故事的讲述方式。",
    synonyms_cn: ["参与式媒体", "数字互动内容", "响应式媒体"],
  },
  {
    id: "tech-092", word: "data visualization", translation: "数据可视化", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 67, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["create data visualizations", "data visualization tool", "interactive data visualization", "data visualization dashboard"],
    example_sentence: "Data visualization transforms complex datasets into accessible charts and graphs, enabling better decision-making.",
    synonyms: ["information graphics", "visual analytics", "graphical data representation"],
    common_mistakes: ["data visualization 不仅仅是画图; 重点在于让数据易于理解并有洞察力"],
    ielts_context: "Reading: data science / business; Writing Task 1: describing graphs",
    pronunciation: "/ˈdeɪ.tə ˌvɪʒ.u.əl.aɪˈzeɪ.ʃən/",
    collocations_cn: ["创建数据可视化", "数据可视化工具", "交互式数据可视化", "数据可视化仪表板"],
    example_sentence_cn: "数据可视化将复杂的数据集转化为易于理解的图表和图形，有助于更好的决策。",
    synonyms_cn: ["信息图形", "可视化分析", "图形化数据展示"],
  },
  {
    id: "tech-093", word: "tech incubator", translation: "科技孵化器", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 62, topics: ["technology"], modules: ["reading", "speaking"],
    collocations: ["join a tech incubator", "university tech incubator", "tech incubator program", "supported by a tech incubator"],
    example_sentence: "Tech incubators provide early-stage startups with mentorship, office space, and access to investors in exchange for equity.",
    synonyms: ["startup accelerator", "innovation lab", "venture nursery"],
    common_mistakes: ["incubator 提供长期支持; accelerator 通常是固定期限的集中项目"],
    ielts_context: "Reading: entrepreneurship / business; Speaking Part 3: startups",
    pronunciation: "/tek ˈɪŋ.kjʊ.beɪ.tər/",
    collocations_cn: ["加入科技孵化器", "大学科技孵化器", "科技孵化器项目", "获得科技孵化器支持"],
    example_sentence_cn: "科技孵化器为早期创业公司提供导师指导、办公空间和投资者对接机会，换取股权。",
    synonyms_cn: ["创业加速器", "创新实验室", "创业苗圃"],
  },
  {
    id: "tech-094", word: "technology transfer", translation: "技术转让", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 65, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["facilitate technology transfer", "technology transfer agreement", "international technology transfer", "technology transfer office"],
    example_sentence: "University-industry technology transfer plays a vital role in turning academic research into commercially viable products.",
    synonyms: ["tech dissemination", "knowledge transfer", "innovation diffusion"],
    common_mistakes: ["technology transfer 不仅是卖技术，还包括专有知识 (know-how) 的转移"],
    ielts_context: "Reading: innovation policy / R&D; Writing Task 2: development / cooperation",
    pronunciation: "/tekˈnɒl.ə.dʒi ˈtræns.fɜːr/",
    collocations_cn: ["促进技术转让", "技术转让协议", "国际技术转让", "技术转让办公室"],
    example_sentence_cn: "大学与产业之间的技术转让在将学术研究转化为商业可行产品方面发挥着关键作用。",
    synonyms_cn: ["技术推广", "知识转移", "创新扩散"],
  },
  {
    id: "tech-095", word: "network latency", translation: "网络延迟", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 63, topics: ["technology"], modules: ["reading", "listening"],
    collocations: ["reduce network latency", "high network latency", "network latency issues", "low network latency"],
    example_sentence: "Online gamers and remote surgeons alike require low network latency to ensure real-time responsiveness.",
    synonyms: ["transmission delay", "ping time", "network lag"],
    common_mistakes: ["latency (延迟) 不同于 bandwidth (带宽); 带宽高不一定延迟低"],
    ielts_context: "Reading: internet infrastructure; Listening: IT / tech support",
    pronunciation: "/ˈnet.wɜːk ˈleɪ.tən.si/",
    collocations_cn: ["降低网络延迟", "高网络延迟", "网络延迟问题", "低网络延迟"],
    example_sentence_cn: "在线游戏玩家和远程外科医生都需要低网络延迟来确保实时响应。",
    synonyms_cn: ["传输延迟", "响应时间", "网络滞后"],
  },
  {
    id: "tech-096", word: "fiber optic cable", translation: "光纤电缆", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 64, topics: ["technology"], modules: ["reading", "listening"],
    collocations: ["install fiber optic cables", "fiber optic cable network", "undersea fiber optic cable", "fiber optic cable infrastructure"],
    example_sentence: "Fiber optic cables form the backbone of the global internet, transmitting data at the speed of light across continents.",
    synonyms: ["optical fiber", "light-guide cable", "photonic conduit"],
    common_mistakes: ["fiber optic 使用光信号; 传统铜缆使用电信号，速度和容量都更低"],
    ielts_context: "Reading: telecom / infrastructure; Listening Section 4: technology lecture",
    pronunciation: "/ˈfaɪ.bər ˈɒp.tɪk ˈkeɪ.bəl/",
    collocations_cn: ["安装光纤电缆", "光纤电缆网络", "海底光纤电缆", "光纤电缆基础设施"],
    example_sentence_cn: "光纤电缆构成了全球互联网的骨干，以光速跨洲传输数据。",
    synonyms_cn: ["光导纤维", "光缆", "光子导管"],
  },
  {
    id: "tech-097", word: "technology gap", translation: "技术差距", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 66, topics: ["technology"], modules: ["writing", "reading"],
    collocations: ["bridge the technology gap", "widen the technology gap", "technology gap between nations", "close the technology gap"],
    example_sentence: "The technology gap between urban and rural schools has widened despite efforts to expand digital access nationwide.",
    synonyms: ["tech disparity", "digital technology gap", "technological divide"],
    common_mistakes: ["technology gap (技术差距) 不完全等同于 digital divide (数字鸿沟，侧重接入)"],
    ielts_context: "Writing Task 2: inequality / development; Reading: global technology",
    pronunciation: "/tekˈnɒl.ə.dʒi ɡæp/",
    collocations_cn: ["弥合技术差距", "扩大技术差距", "国家间的技术差距", "缩小技术差距"],
    example_sentence_cn: "尽管全国努力扩大数字接入，但城乡学校之间的技术差距仍在扩大。",
    synonyms_cn: ["技术差距", "数字技术差距", "技术鸿沟"],
  },
  {
    id: "tech-098", word: "biometric identification", translation: "生物识别身份验证", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 63, topics: ["technology"], modules: ["reading", "speaking"],
    collocations: ["use biometric identification", "biometric identification system", "mandatory biometric identification", "secure biometric identification"],
    example_sentence: "Airports around the world are increasingly adopting biometric identification to streamline passenger processing and enhance security.",
    synonyms: ["biometric screening", "biological identity verification", "physiological identification"],
    common_mistakes: ["biometric identification 识别身份; biometric authentication 验证身份声明"],
    ielts_context: "Reading: security / travel; Speaking Part 3: privacy / technology",
    pronunciation: "/ˌbaɪ.əʊˈmet.rɪk aɪˌden.tɪ.fɪˈkeɪ.ʃən/",
    collocations_cn: ["使用生物识别身份验证", "生物识别身份验证系统", "强制性生物识别身份验证", "安全的生物识别身份验证"],
    example_sentence_cn: "世界各地的机场越来越多地采用生物识别身份验证来简化旅客处理流程并加强安全。",
    synonyms_cn: ["生物识别筛查", "生物身份验证", "生理特征识别"],
  },
  {
    id: "tech-099", word: "screen addiction", translation: "屏幕成瘾", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 67, topics: ["technology"], modules: ["speaking", "writing"],
    collocations: ["child screen addiction", "overcome screen addiction", "signs of screen addiction", "digital screen addiction"],
    example_sentence: "Health experts warn that screen addiction among children is linked to sleep disorders, reduced physical activity, and social isolation.",
    synonyms: ["digital dependency", "device overuse", "technology compulsion"],
    common_mistakes: ["addiction 是临床术语，表示无法控制的成瘾行为; excessive use 是过度使用"],
    ielts_context: "Speaking Part 3: technology / health; Writing Task 2: technology impact",
    pronunciation: "/skriːn əˈdɪk.ʃən/",
    collocations_cn: ["儿童屏幕成瘾", "克服屏幕成瘾", "屏幕成瘾的迹象", "数字屏幕成瘾"],
    example_sentence_cn: "健康专家警告说，儿童屏幕成瘾与睡眠障碍、体育活动减少和社交孤立有关。",
    synonyms_cn: ["数字依赖", "设备过度使用", "技术强迫症"],
  },
  {
    id: "tech-100", word: "green tech innovation", translation: "绿色科技创新", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 68, topics: ["technology"], modules: ["reading", "writing"],
    collocations: ["invest in green tech innovation", "drive green tech innovation", "green tech innovation hub", "accelerate green tech innovation"],
    example_sentence: "Green tech innovation is essential for decoupling economic growth from environmental degradation and resource depletion.",
    synonyms: ["sustainable technology innovation", "clean-tech development", "eco-friendly technical advancement"],
    common_mistakes: ["green tech 包括可再生能源、能源效率、水处理等等广泛领域"],
    ielts_context: "Reading: sustainable development / business; Writing Task 2: environment / technology",
    pronunciation: "/ɡriːn tek ˌɪn.əˈveɪ.ʃən/",
    collocations_cn: ["投资绿色科技创新", "推动绿色科技创新", "绿色科技创新中心", "加速绿色科技创新"],
    example_sentence_cn: "绿色科技创新对于将经济增长与环境退化和资源消耗脱钩至关重要。",
    synonyms_cn: ["可持续技术创新", "清洁技术开发", "环保技术进步"],
  },
];
