// scripts/expand-work.ts
// Phase 2: Work 话题扩展 — work-051 ~ work-100（50 个新词块）
// 频次分布: 超高(90-99)×20 + 高(70-89)×18 + 中(50-69)×12

import type { Chunk } from "../types/chunk";

export const WORK_EXPANSION: Chunk[] = [
  // ═══ 超高頻 90-99 (20 个) ═══
  {
    id: "work-051", word: "paid leave", translation: "带薪休假", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 93, topics: ["work"], modules: ["speaking", "reading"],
    collocations: ["entitled to paid leave", "annual paid leave", "paid sick leave", "take paid leave"],
    example_sentence: "Workers in many countries are legally entitled to a minimum amount of paid leave each year to rest and recharge.",
    synonyms: ["annual leave", "holiday pay", "paid time off"],
    common_mistakes: ["paid leave 是带薪休假; unpaid leave 是无薪休假"],
    ielts_context: "Speaking Part 3: work benefits; Reading: labor law / HR",
    pronunciation: "/peɪd liːv/",
    collocations_cn: ["享有带薪休假", "年假", "带薪病假", "休带薪休假"],
    example_sentence_cn: "许多国家的工人每年依法享有最低天数的带薪休假以休息和充电。",
    synonyms_cn: ["年假", "休假工资", "带薪时间"],
  },
  {
    id: "work-052", word: "gender pay gap", translation: "性别薪酬差距", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 96, topics: ["work"], modules: ["writing", "reading"],
    collocations: ["close the gender pay gap", "persistent gender pay gap", "address the gender pay gap", "gender pay gap report"],
    example_sentence: "Despite decades of progress, a significant gender pay gap persists in most industries around the world.",
    synonyms: ["wage disparity", "gender earnings divide", "salary inequality"],
    common_mistakes: ["gender pay gap 是指男女平均收入差距，不必然等于同工不同酬"],
    ielts_context: "Writing Task 2: equality / workplace; Reading: economics / sociology",
    pronunciation: "/ˈdʒen.dər peɪ ɡæp/",
    collocations_cn: ["缩小性别薪酬差距", "持续的性别薪酬差距", "解决性别薪酬差距", "性别薪酬差距报告"],
    example_sentence_cn: "尽管取得了数十年的进展，大多数行业在全球范围内仍然存在显著的性别薪酬差距。",
    synonyms_cn: ["工资差距", "性别收入差距", "薪酬不平等"],
  },
  {
    id: "work-053", word: "overtime pay", translation: "加班费", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["work"], modules: ["listening", "speaking"],
    collocations: ["receive overtime pay", "entitled to overtime pay", "overtime pay rate", "claim overtime pay"],
    example_sentence: "Many workers rely on overtime pay to supplement their regular income and make ends meet.",
    synonyms: ["overtime compensation", "extra hours payment", "time-and-a-half pay"],
    common_mistakes: ["overtime 指超出正常工时的工作; overtime pay 通常高于正常时薪"],
    ielts_context: "Listening Section 3: workplace discussion; Speaking Part 3: work conditions",
    pronunciation: "/ˈəʊ.və.taɪm peɪ/",
    collocations_cn: ["领取加班费", "有权获得加班费", "加班费率", "申报加班费"],
    example_sentence_cn: "许多工人依靠加班费来补充正常收入并维持生计。",
    synonyms_cn: ["加班补偿", "超时工资", "1.5倍工资"],
  },
  {
    id: "work-054", word: "professional networking", translation: "职业社交", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 92, topics: ["work"], modules: ["speaking", "reading"],
    collocations: ["engage in professional networking", "professional networking event", "online professional networking", "professional networking platform"],
    example_sentence: "Professional networking has become essential for career growth, with many job opportunities filled through personal connections.",
    synonyms: ["career networking", "business networking", "professional relationship building"],
    common_mistakes: ["networking 不是社交; 它是建立职业关系以交换信息和建议"],
    ielts_context: "Speaking Part 2: career development; Reading: business / career",
    pronunciation: "/prəˈfeʃ.ən.əl ˈnet.wɜː.kɪŋ/",
    collocations_cn: ["参与职业社交", "职业社交活动", "在线职业社交", "职业社交平台"],
    example_sentence_cn: "职业社交对职业发展已变得至关重要，许多工作机会是通过个人关系获得的。",
    synonyms_cn: ["职业社交", "商业社交", "职业关系建设"],
  },
  {
    id: "work-055", word: "job placement", translation: "就业安置", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["assist with job placement", "job placement services", "successful job placement", "job placement rate"],
    example_sentence: "Vocational schools often provide job placement services to help graduates transition smoothly into the workforce.",
    synonyms: ["employment placement", "career placement", "work placement"],
    common_mistakes: ["job placement 指帮助找到工作; internship placement 特指实习安置"],
    ielts_context: "Reading: education / career services; Listening: employment agency",
    pronunciation: "/dʒɒb ˈpleɪs.mənt/",
    collocations_cn: ["协助就业安置", "就业安置服务", "成功的就业安置", "就业安置率"],
    example_sentence_cn: "职业学校通常提供就业安置服务，帮助毕业生顺利过渡到职场。",
    synonyms_cn: ["就业介绍", "职业安置", "工作安置"],
  },
  {
    id: "work-056", word: "retirement plan", translation: "退休计划", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 91, topics: ["work"], modules: ["reading", "speaking"],
    collocations: ["contribute to a retirement plan", "employer-sponsored retirement plan", "retirement plan options", "set up a retirement plan"],
    example_sentence: "Many employers offer retirement plans with matching contributions as part of their employee benefits package.",
    synonyms: ["pension scheme", "retirement savings account", "superannuation fund"],
    common_mistakes: ["retirement plan 不是 single savings account; 是长期财务规划方案"],
    ielts_context: "Reading: personal finance / HR; Speaking Part 3: work benefits",
    pronunciation: "/rɪˈtaɪə.mənt plæn/",
    collocations_cn: ["向退休计划缴费", "雇主提供的退休计划", "退休计划选项", "设立退休计划"],
    example_sentence_cn: "许多雇主提供退休计划，配以匹配缴费作为员工福利方案的一部分。",
    synonyms_cn: ["养老金计划", "退休储蓄账户", "公积金"],
  },
  {
    id: "work-057", word: "collective bargaining", translation: "集体谈判", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 92, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["engage in collective bargaining", "collective bargaining power", "collective bargaining agreement", "right to collective bargaining"],
    example_sentence: "Collective bargaining gives workers greater leverage to negotiate better wages and working conditions with their employers.",
    synonyms: ["labor negotiation", "union bargaining", "joint negotiation"],
    common_mistakes: ["collective bargaining 是由工会代表全体工人进行的; individual negotiation 是个人协商"],
    ielts_context: "Reading: labor relations / law; Writing Task 2: workers' rights",
    pronunciation: "/kəˈlek.tɪv ˈbɑː.ɡɪ.nɪŋ/",
    collocations_cn: ["进行集体谈判", "集体谈判力量", "集体谈判协议", "集体谈判权"],
    example_sentence_cn: "集体谈判赋予工人更大的议价能力来与雇主协商更好的工资和工作条件。",
    synonyms_cn: ["劳工谈判", "工会协商", "联合谈判"],
  },
  {
    id: "work-058", word: "workplace harassment", translation: "职场骚扰", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 93, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["prevent workplace harassment", "report workplace harassment", "victim of workplace harassment", "zero tolerance for workplace harassment"],
    example_sentence: "Companies must implement clear policies and reporting mechanisms to prevent and address workplace harassment.",
    synonyms: ["workplace bullying", "occupational harassment", "on-the-job mistreatment"],
    common_mistakes: ["harassment 指重复的、不受欢迎的冒犯行为; 单一事件可能不构成 harassment"],
    ielts_context: "Reading: HR policy / law; Writing Task 2: workplace culture",
    pronunciation: "/ˈwɜːk.pleɪs ˈhær.əs.mənt/",
    collocations_cn: ["防止职场骚扰", "举报职场骚扰", "职场骚扰受害者", "对职场骚扰零容忍"],
    example_sentence_cn: "公司必须实施明确的政策和报告机制来防止和处理职场骚扰。",
    synonyms_cn: ["职场欺凌", "职业骚扰", "工作场所不当对待"],
  },
  {
    id: "work-059", word: "remote collaboration", translation: "远程协作", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 95, topics: ["work"], modules: ["speaking", "writing"],
    collocations: ["facilitate remote collaboration", "remote collaboration tools", "effective remote collaboration", "remote collaboration platform"],
    example_sentence: "Remote collaboration tools like Slack and Zoom have become indispensable for distributed teams working across different time zones.",
    synonyms: ["virtual collaboration", "distributed teamwork", "online cooperation"],
    common_mistakes: ["remote collaboration 不仅需要视频会议; 还包括文档共享、项目管理、即时通讯等"],
    ielts_context: "Writing Task 2: remote work / technology; Speaking Part 3: workplace trends",
    pronunciation: "/rɪˈməʊt kəˌlæb.əˈreɪ.ʃən/",
    collocations_cn: ["促进远程协作", "远程协作工具", "有效的远程协作", "远程协作平台"],
    example_sentence_cn: "像Slack和Zoom这样的远程协作工具已成为跨不同时区工作的分布式团队不可或缺的工具。",
    synonyms_cn: ["虚拟协作", "分布式团队合作", "在线协作"],
  },
  {
    id: "work-060", word: "time management", translation: "时间管理", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 94, topics: ["work"], modules: ["speaking", "listening"],
    collocations: ["improve time management", "effective time management", "time management skills", "poor time management"],
    example_sentence: "Strong time management skills enable employees to prioritize tasks, meet deadlines, and maintain a healthy work-life balance.",
    synonyms: ["scheduling proficiency", "productivity management", "work prioritization"],
    common_mistakes: ["time management 的关键是 prioritization，而不是试图做更多事情"],
    ielts_context: "Speaking Part 2: study / work habits; Listening Section 3: student skills",
    pronunciation: "/taɪm ˈmæn.ɪdʒ.mənt/",
    collocations_cn: ["改善时间管理", "有效的时间管理", "时间管理技能", "糟糕的时间管理"],
    example_sentence_cn: "良好的时间管理技能使员工能够确定任务优先级、满足最后期限并维持健康的工作与生活平衡。",
    synonyms_cn: ["日程安排能力", "生产力管理", "工作优先排序"],
  },
  {
    id: "work-061", word: "glass ceiling", translation: "玻璃天花板", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["break the glass ceiling", "invisible glass ceiling", "glass ceiling effect", "shatter the glass ceiling"],
    example_sentence: "Despite decades of progress, women continue to face a glass ceiling that prevents them from reaching the highest leadership positions.",
    synonyms: ["invisible barrier", "promotion ceiling", "career advancement limit"],
    common_mistakes: ["glass ceiling 特指女性、少数族裔等群体遇到的隐性晋升障碍"],
    ielts_context: "Reading: gender studies / business; Writing Task 2: workplace equality",
    pronunciation: "/ɡlɑːs ˈsiː.lɪŋ/",
    collocations_cn: ["打破玻璃天花板", "隐形的玻璃天花板", "玻璃天花板效应", "击碎玻璃天花板"],
    example_sentence_cn: "尽管取得了数十年的进步，女性仍然面临着阻止她们达到最高领导职位的玻璃天花板。",
    synonyms_cn: ["隐形障碍", "晋升天花板", "职业晋升限制"],
  },
  {
    id: "work-062", word: "employee engagement", translation: "员工敬业度", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["boost employee engagement", "measure employee engagement", "high employee engagement", "employee engagement survey"],
    example_sentence: "Companies with high employee engagement tend to have lower turnover rates and higher overall productivity.",
    synonyms: ["staff engagement", "workforce commitment", "employee involvement"],
    common_mistakes: ["engagement 不仅仅是 satisfaction (满意); 还包含情感投入和主动贡献的意愿"],
    ielts_context: "Reading: HR / management; Writing Task 2: workplace culture",
    pronunciation: "/ɪmˈplɔɪ.iː ɪnˈɡeɪdʒ.mənt/",
    collocations_cn: ["提升员工敬业度", "衡量员工敬业度", "高员工敬业度", "员工敬业度调查"],
    example_sentence_cn: "员工敬业度高的公司往往拥有更低的离职率和更高的整体生产力。",
    synonyms_cn: ["员工敬业", "劳动力承诺", "员工参与"],
  },
  {
    id: "work-063", word: "severance package", translation: "解雇补偿方案", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["negotiate a severance package", "generous severance package", "receive a severance package", "severance package terms"],
    example_sentence: "When the company downsized, affected employees were offered a severance package including salary continuation and career counseling.",
    synonyms: ["redundancy pay", "termination benefit", "layoff compensation"],
    common_mistakes: ["severance 特指被解雇时的补偿; notice period 是通知期内继续工作"],
    ielts_context: "Reading: HR / employment law; Listening: business news",
    pronunciation: "/ˈsev.ər.əns ˈpæk.ɪdʒ/",
    collocations_cn: ["协商解雇补偿方案", "丰厚的解雇补偿方案", "获得解雇补偿方案", "解雇补偿方案条款"],
    example_sentence_cn: "当公司裁员时，受影响的员工获得了包括薪资延续和职业咨询在内的解雇补偿方案。",
    synonyms_cn: ["遣散费", "解雇津贴", "裁员补偿"],
  },
  {
    id: "work-064", word: "human resources department", translation: "人力资源部门", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 91, topics: ["work"], modules: ["listening", "reading"],
    collocations: ["contact the human resources department", "human resources department policies", "managed by the human resources department", "consult the human resources department"],
    example_sentence: "The human resources department is responsible for recruitment, employee relations, and ensuring compliance with labor laws.",
    synonyms: ["HR department", "personnel department", "people operations"],
    common_mistakes: ["human resources 常缩写为 HR; 不要写成 Human Resource (单数)"],
    ielts_context: "Listening Section 3: workplace orientation; Reading: company structure",
    pronunciation: "/ˈhjuː.mən rɪˈzɔː.sɪz dɪˈpɑːt.mənt/",
    collocations_cn: ["联系人力资源部门", "人力资源部门政策", "由人力资源部门管理", "咨询人力资源部门"],
    example_sentence_cn: "人力资源部门负责招聘、员工关系以及确保遵守劳动法。",
    synonyms_cn: ["人事部", "员工管理部门", "人才运营"],
  },
  {
    id: "work-065", word: "cover letter", translation: "求职信", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 95, topics: ["work"], modules: ["writing", "reading"],
    collocations: ["write a cover letter", "tailor a cover letter", "compelling cover letter", "submit a cover letter"],
    example_sentence: "A well-crafted cover letter can set a candidate apart by showcasing their personality and genuine interest in the role.",
    synonyms: ["application letter", "letter of interest", "job application letter"],
    common_mistakes: ["cover letter 不是重复简历; 它补充说明你为什么适合这个职位"],
    ielts_context: "Writing Task 1: formal letter (General Training); Reading: career advice",
    pronunciation: "/ˈkʌv.ər ˈlet.ər/",
    collocations_cn: ["撰写求职信", "量身定制求职信", "有说服力的求职信", "提交求职信"],
    example_sentence_cn: "一份精心编写的求职信可以通过展示个性和对职位的真实兴趣使候选人脱颖而出。",
    synonyms_cn: ["求职信函", "意向书", "工作应聘信"],
  },
  {
    id: "work-066", word: "talent acquisition", translation: "人才招聘", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["talent acquisition strategy", "talent acquisition team", "improve talent acquisition", "talent acquisition process"],
    example_sentence: "Effective talent acquisition goes beyond filling vacancies to building a long-term pipeline of qualified candidates.",
    synonyms: ["recruitment", "talent sourcing", "workforce recruitment"],
    common_mistakes: ["talent acquisition 是战略性长期招聘; recruitment 是填补当前空缺"],
    ielts_context: "Reading: HR / business; Writing Task 2: workforce development",
    pronunciation: "/ˈtæl.ənt ˌæk.wɪˈzɪʃ.ən/",
    collocations_cn: ["人才招聘策略", "人才招聘团队", "改善人才招聘", "人才招聘流程"],
    example_sentence_cn: "有效的人才招聘超越了填补空缺，致力于建立长期的合格候选人管道。",
    synonyms_cn: ["招聘", "人才搜寻", "劳动力招聘"],
  },
  {
    id: "work-067", word: "workplace safety", translation: "工作场所安全", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 92, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["ensure workplace safety", "workplace safety regulations", "violate workplace safety", "workplace safety training"],
    example_sentence: "Employers have a legal obligation to provide a work environment that meets minimum workplace safety standards.",
    synonyms: ["occupational safety", "job site security", "worker protection"],
    common_mistakes: ["workplace safety 不仅是防止身体伤害; 也包括心理健康和人为因素"],
    ielts_context: "Reading: labor law / industry; Listening: safety training",
    pronunciation: "/ˈwɜːk.pleɪs ˈseɪf.ti/",
    collocations_cn: ["确保工作场所安全", "工作场所安全规定", "违反工作场所安全", "工作场所安全培训"],
    example_sentence_cn: "雇主有法律义务提供满足最低工作场所安全标准的工作环境。",
    synonyms_cn: ["职业安全", "工地安全", "工人保护"],
  },
  {
    id: "work-068", word: "onboarding process", translation: "入职流程", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 90, topics: ["work"], modules: ["listening", "reading"],
    collocations: ["streamline the onboarding process", "new hire onboarding process", "effective onboarding process", "complete the onboarding process"],
    example_sentence: "A well-designed onboarding process helps new employees integrate into the company culture and become productive more quickly.",
    synonyms: ["induction program", "orientation process", "new employee integration"],
    common_mistakes: ["onboarding (入职) 和 training (培训) 不同; onboarding 更全面，包含文化融入"],
    ielts_context: "Listening Section 3: new job / workplace; Reading: HR management",
    pronunciation: "/ˈɒn.bɔː.dɪŋ ˈprəʊ.ses/",
    collocations_cn: ["简化入职流程", "新员工入职流程", "有效的入职流程", "完成入职流程"],
    example_sentence_cn: "精心设计的入职流程有助于新员工融入公司文化并更快地提高生产力。",
    synonyms_cn: ["入职引导", "入职培训", "新员工融合"],
  },
  {
    id: "work-069", word: "workforce diversity", translation: "劳动力多元化", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 91, topics: ["work"], modules: ["writing", "reading"],
    collocations: ["promote workforce diversity", "increase workforce diversity", "benefits of workforce diversity", "lack of workforce diversity"],
    example_sentence: "Workforce diversity brings a wider range of perspectives and experiences, driving innovation and better decision-making.",
    synonyms: ["workplace diversity", "employee diversification", "inclusive workforce"],
    common_mistakes: ["diversity 不仅指种族性别; 还包括年龄、背景、思维方式的多样性"],
    ielts_context: "Writing Task 2: equality / business; Reading: diversity reports",
    pronunciation: "/ˈwɜːk.fɔːs daɪˈvɜː.sə.ti/",
    collocations_cn: ["促进劳动力多元化", "提高劳动力多元化", "劳动力多元化的好处", "缺乏劳动力多元化"],
    example_sentence_cn: "劳动力多元化带来了更广泛的视角和经验，推动创新和更好的决策。",
    synonyms_cn: ["职场多元化", "员工多样化", "包容性劳动力"],
  },
  {
    id: "work-070", word: "equal employment opportunity", translation: "平等就业机会", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["ensure equal employment opportunity", "equal employment opportunity policy", "violate equal employment opportunity", "promote equal employment opportunity"],
    example_sentence: "Equal employment opportunity laws prohibit discrimination based on race, gender, age, religion, or disability in the workplace.",
    synonyms: ["EEO", "fair employment practices", "non-discriminatory hiring"],
    common_mistakes: ["EEO 指机会平等; affirmative action 指积极纠正历史不平等的措施"],
    ielts_context: "Reading: employment law; Writing Task 2: social equality",
    pronunciation: "/ˈiː.kwəl ɪmˈplɔɪ.mənt ˌɒp.əˈtjuː.nə.ti/",
    collocations_cn: ["确保平等就业机会", "平等就业机会政策", "违反平等就业机会", "促进平等就业机会"],
    example_sentence_cn: "平等就业机会法律禁止基于种族、性别、年龄、宗教或残疾的职场歧视。",
    synonyms_cn: ["就业机会均等", "公平就业实践", "非歧视性雇佣"],
  },
  // ═══ 高頻 70-89 (18 个) ═══
  {
    id: "work-071", word: "maternity leave", translation: "产假", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 88, topics: ["work"], modules: ["reading", "speaking"],
    collocations: ["take maternity leave", "paid maternity leave", "maternity leave policy", "extend maternity leave"],
    example_sentence: "Generous maternity leave policies are associated with better health outcomes for both mothers and infants.",
    synonyms: ["parental leave", "pregnancy leave", "childbirth leave"],
    common_mistakes: ["maternity leave (产假) 通常指母亲; paternity leave (陪产假) 指父亲; parental leave 是统称"],
    ielts_context: "Reading: labor rights / family policy; Speaking Part 3: work-life balance",
    pronunciation: "/məˈtɜː.nə.ti liːv/",
    collocations_cn: ["休产假", "带薪产假", "产假政策", "延长产假"],
    example_sentence_cn: "慷慨的产假政策与母婴双方更好的健康结果相关。",
    synonyms_cn: ["育儿假", "孕期假", "生育假"],
  },
  {
    id: "work-072", word: "work-related stress", translation: "工作压力", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 87, topics: ["work"], modules: ["reading", "speaking"],
    collocations: ["suffer from work-related stress", "manage work-related stress", "causes of work-related stress", "reduce work-related stress"],
    example_sentence: "Work-related stress has become a leading cause of long-term absence from the workplace across many industries.",
    synonyms: ["occupational stress", "job pressure", "professional burnout risk"],
    common_mistakes: ["stress 不同于 burnout; burnout 是长期压力导致的极度疲惫和失去动力"],
    ielts_context: "Reading: occupational health; Speaking Part 3: well-being at work",
    pronunciation: "/wɜːk rɪˈleɪ.tɪd stres/",
    collocations_cn: ["承受工作压力", "管理工作压力", "工作压力的原因", "减轻工作压力"],
    example_sentence_cn: "工作压力已成为许多行业长期缺勤的主要原因。",
    synonyms_cn: ["职业压力", "工作负担", "职业倦怠风险"],
  },
  {
    id: "work-073", word: "career counseling", translation: "职业咨询", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 80, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["seek career counseling", "provide career counseling", "career counseling services", "benefit from career counseling"],
    example_sentence: "Career counseling helps individuals identify their strengths and interests to make informed decisions about their professional paths.",
    synonyms: ["career guidance", "vocational counseling", "job advisory service"],
    common_mistakes: ["career counseling 侧重长期职业规划; job coaching 侧重当下求职技能"],
    ielts_context: "Reading: student services / HR; Listening: career center appointment",
    pronunciation: "/kəˈrɪə ˈkaʊn.səl.ɪŋ/",
    collocations_cn: ["寻求职业咨询", "提供职业咨询", "职业咨询服务", "受益于职业咨询"],
    example_sentence_cn: "职业咨询帮助个人识别自身优势和兴趣，就其职业道路做出明智决定。",
    synonyms_cn: ["职业指导", "就业咨询", "求职顾问服务"],
  },
  {
    id: "work-074", word: "employment agency", translation: "职业介绍所", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 79, topics: ["work"], modules: ["listening", "reading"],
    collocations: ["register with an employment agency", "use an employment agency", "private employment agency", "reputable employment agency"],
    example_sentence: "Employment agencies match job seekers with suitable vacancies and often provide temporary staffing solutions for businesses.",
    synonyms: ["recruitment agency", "staffing firm", "job center"],
    common_mistakes: ["employment agency 通常免费对求职者，向雇主收费; 也有收费的咨询机构"],
    ielts_context: "Listening Section 1: job search; Reading: HR / recruitment",
    pronunciation: "/ɪmˈplɔɪ.mənt ˈeɪ.dʒən.si/",
    collocations_cn: ["在职业介绍所登记", "利用职业介绍所", "私营职业介绍所", "信誉良好的职业介绍所"],
    example_sentence_cn: "职业介绍所为求职者匹配合适的空缺职位，并通常为企业提供临时用工解决方案。",
    synonyms_cn: ["招聘机构", "人才派遣公司", "就业中心"],
  },
  {
    id: "work-075", word: "flexitime arrangement", translation: "弹性工时安排", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 82, topics: ["work"], modules: ["speaking", "reading"],
    collocations: ["offer flexitime arrangements", "adopt flexitime arrangements", "benefit from flexitime arrangements", "flexitime arrangement policy"],
    example_sentence: "Flexitime arrangements allow employees to choose their start and end times within agreed limits, improving work-life integration.",
    synonyms: ["flexible schedule", "flextime system", "adjustable working hours"],
    common_mistakes: ["flexitime (弹性工时) 不同于 remote working (远程工作); 前者关注时间，后者关注地点"],
    ielts_context: "Speaking Part 3: work flexibility; Reading: HR policies / workplace trends",
    pronunciation: "/ˈflek.si.taɪm əˈreɪndʒ.mənt/",
    collocations_cn: ["提供弹性工时安排", "采用弹性工时安排", "受益于弹性工时安排", "弹性工时安排政策"],
    example_sentence_cn: "弹性工时安排允许员工在约定范围内选择上下班时间，改善工作与生活的融合。",
    synonyms_cn: ["灵活排班", "弹性时间制", "可调节工作时间"],
  },
  {
    id: "work-076", word: "annual performance review", translation: "年度绩效评估", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 84, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["undergo an annual performance review", "annual performance review meeting", "prepare for an annual performance review", "annual performance review process"],
    example_sentence: "The annual performance review provides a structured opportunity for employees and managers to discuss achievements and set future goals.",
    synonyms: ["yearly appraisal", "annual evaluation", "year-end review"],
    common_mistakes: ["performance review 关注过去表现和未来目标; 不光是批评会议"],
    ielts_context: "Reading: HR / management; Listening: workplace scenario",
    pronunciation: "/ˈæn.ju.əl pəˈfɔː.məns rɪˈvjuː/",
    collocations_cn: ["接受年度绩效评估", "年度绩效评估会议", "准备年度绩效评估", "年度绩效评估流程"],
    example_sentence_cn: "年度绩效评估为员工和管理者提供了一个结构化机会来讨论成就并设定未来目标。",
    synonyms_cn: ["年度考核", "年度评价", "年终评估"],
  },
  {
    id: "work-077", word: "strike action", translation: "罢工行动", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 83, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["take strike action", "threaten strike action", "call for strike action", "organize strike action"],
    example_sentence: "Workers voted overwhelmingly to take strike action after negotiations over pay and conditions broke down.",
    synonyms: ["industrial action", "work stoppage", "labor walkout"],
    common_mistakes: ["strike 是 organized refusal to work; strike action 通常由工会组织"],
    ielts_context: "Reading: labor relations / news; Writing Task 2: workers' rights",
    pronunciation: "/straɪk ˈæk.ʃən/",
    collocations_cn: ["采取罢工行动", "威胁罢工行动", "呼吁罢工行动", "组织罢工行动"],
    example_sentence_cn: "在薪酬和条件谈判破裂后，工人以压倒性多数投票决定采取罢工行动。",
    synonyms_cn: ["产业行动", "停工抗议", "工人罢工"],
  },
  {
    id: "work-078", word: "job description", translation: "职位描述", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 82, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["read the job description", "detailed job description", "match the job description", "write a job description"],
    example_sentence: "Before applying, candidates should carefully review the job description to ensure their qualifications align with the role requirements.",
    synonyms: ["role description", "position specification", "job requirements"],
    common_mistakes: ["job description 列出职位职责; person specification 列出候选人需要具备的特质"],
    ielts_context: "Reading: job advertisements; Listening Section 1: job inquiry",
    pronunciation: "/dʒɒb dɪˈskrɪp.ʃən/",
    collocations_cn: ["阅读职位描述", "详细的职位描述", "符合职位描述", "撰写职位描述"],
    example_sentence_cn: "在申请之前，候选人应仔细阅读职位描述，确保其资质与职位要求相符。",
    synonyms_cn: ["职位说明", "岗位规格", "工作要求"],
  },
  {
    id: "work-079", word: "work-life integration", translation: "工作生活一体化", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 80, topics: ["work"], modules: ["writing", "speaking"],
    collocations: ["achieve work-life integration", "promote work-life integration", "work-life integration strategy", "work-life integration approach"],
    example_sentence: "Unlike the strict separation of work and personal life, work-life integration acknowledges that the two spheres naturally overlap in the modern world.",
    synonyms: ["work-life blending", "holistic work approach", "life-work fusion"],
    common_mistakes: ["work-life integration (融合) 不同于 work-life balance (平衡); 前者接受重叠，后者追求分离"],
    ielts_context: "Writing Task 2: modern work / lifestyle; Speaking Part 3: work trends",
    pronunciation: "/wɜːk laɪf ˌɪn.tɪˈɡreɪ.ʃən/",
    collocations_cn: ["实现工作生活一体化", "促进工作生活一体化", "工作生活一体化策略", "工作生活一体化方法"],
    example_sentence_cn: "与工作与个人生活的严格分离不同，工作生活一体化承认这两个领域在现代世界中自然会重叠。",
    synonyms_cn: ["工作生活融合", "整体工作方式", "生活-工作融合"],
  },
  {
    id: "work-080", word: "labor shortage", translation: "劳动力短缺", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 86, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["face a labor shortage", "chronic labor shortage", "address the labor shortage", "labor shortage crisis"],
    example_sentence: "Many developed countries are experiencing acute labor shortages in sectors such as healthcare, construction, and technology.",
    synonyms: ["workforce deficit", "talent gap", "manpower shortage"],
    common_mistakes: ["labor shortage 指缺少劳动力; skills gap 指缺少特定技能"],
    ielts_context: "Reading: economics / immigration; Writing Task 2: workforce / economy",
    pronunciation: "/ˈleɪ.bər ˈʃɔː.tɪdʒ/",
    collocations_cn: ["面临劳动力短缺", "长期劳动力短缺", "解决劳动力短缺问题", "劳动力短缺危机"],
    example_sentence_cn: "许多发达国家在医疗保健、建筑和科技等行业正经历严重的劳动力短缺。",
    synonyms_cn: ["劳动力不足", "人才缺口", "人力短缺"],
  },
  {
    id: "work-081", word: "unpaid internship", translation: "无薪实习", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 81, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["offer an unpaid internship", "complete an unpaid internship", "unpaid internship programme", "accept an unpaid internship"],
    example_sentence: "Unpaid internships have been criticized for perpetuating inequality by favoring candidates from wealthy backgrounds who can afford to work for free.",
    synonyms: ["voluntary placement", "non-remunerative training", "gratis traineeship"],
    common_mistakes: ["unpaid internship 在某些国家/地区可能是非法的; 取决于法律规定"],
    ielts_context: "Reading: employment / education; Writing Task 2: social mobility",
    pronunciation: "/ʌnˈpeɪd ˈɪn.tɜːn.ʃɪp/",
    collocations_cn: ["提供无薪实习", "完成无薪实习", "无薪实习项目", "接受无薪实习"],
    example_sentence_cn: "无薪实习因倾向于来自富裕背景能够无偿工作的候选人而受到延续不平等的批评。",
    synonyms_cn: ["志愿实习", "无偿培训", "免费学徒"],
  },
  {
    id: "work-082", word: "dismissal procedure", translation: "解雇程序", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 78, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["follow the dismissal procedure", "unfair dismissal procedure", "formal dismissal procedure", "initiate the dismissal procedure"],
    example_sentence: "Employers must follow a fair dismissal procedure to avoid claims of wrongful termination.",
    synonyms: ["termination process", "redundancy procedure", "employee discharge process"],
    common_mistakes: ["dismissal 因员工行为或能力不足; redundancy 因职位不再需要"],
    ielts_context: "Reading: employment law / HR; Listening: workplace meeting",
    pronunciation: "/dɪsˈmɪs.əl prəˈsiː.dʒər/",
    collocations_cn: ["遵循解雇程序", "不公平的解雇程序", "正式解雇程序", "启动解雇程序"],
    example_sentence_cn: "雇主必须遵循公平的解雇程序，以避免不当解雇的索赔。",
    synonyms_cn: ["终止流程", "裁员程序", "员工解职流程"],
  },
  {
    id: "work-083", word: "workplace morale", translation: "职场士气", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 80, topics: ["work"], modules: ["reading", "speaking"],
    collocations: ["boost workplace morale", "low workplace morale", "improve workplace morale", "maintain high workplace morale"],
    example_sentence: "Recognizing employees' achievements regularly is one of the simplest and most effective ways to boost workplace morale.",
    synonyms: ["staff spirit", "employee morale", "team motivation"],
    common_mistakes: ["morale (士气) 不同于 moral (道德的); 拼写只有一个字母之差"],
    ielts_context: "Reading: management / HR; Speaking Part 3: work environment",
    pronunciation: "/ˈwɜːk.pleɪs məˈrɑːl/",
    collocations_cn: ["提升职场士气", "低落的职场士气", "改善职场士气", "保持高昂的职场士气"],
    example_sentence_cn: "定期表彰员工的成就是提升职场士气最简单且最有效的方法之一。",
    synonyms_cn: ["员工精神", "团体动力", "团队激励"],
  },
  {
    id: "work-084", word: "probation period", translation: "试用期", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 79, topics: ["work"], modules: ["listening", "reading"],
    collocations: ["complete a probation period", "probation period of three months", "extend a probation period", "during the probation period"],
    example_sentence: "Most new employees are required to successfully complete a probation period before their position becomes permanent.",
    synonyms: ["trial period", "probationary term", "initial assessment period"],
    common_mistakes: ["probation 在此指工作的试用期，不是法律上的缓刑"],
    ielts_context: "Listening Section 3: job offer discussion; Reading: employment contracts",
    pronunciation: "/prəˈbeɪ.ʃən ˈpɪə.ri.əd/",
    collocations_cn: ["完成试用期", "三个月试用期", "延长试用期", "在试用期内"],
    example_sentence_cn: "大多数新员工需要成功完成试用期，其职位才能转为永久职位。",
    synonyms_cn: ["试用阶段", "试用评估期", "初始评估期"],
  },
  {
    id: "work-085", word: "side hustle", translation: "副业", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 77, topics: ["work"], modules: ["speaking", "reading"],
    collocations: ["start a side hustle", "profitable side hustle", "freelance side hustle", "online side hustle"],
    example_sentence: "Many workers have turned to side hustles not just for extra income, but also to pursue passions that their main job doesn't satisfy.",
    synonyms: ["second job", "moonlighting", "supplemental gig"],
    common_mistakes: ["side hustle 是非正式说法; 正式写作中使用 secondary employment 或 supplementary income"],
    ielts_context: "Speaking Part 2: ways to earn money; Reading: gig economy / career trends",
    pronunciation: "/saɪd ˈhʌs.əl/",
    collocations_cn: ["开始副业", "能赚钱的副业", "自由职业副业", "在线副业"],
    example_sentence_cn: "许多工人转向副业不仅为了额外收入，也为了追求主要工作无法满足的热情所在。",
    synonyms_cn: ["第二职业", "兼职", "补充收入"],
  },
  {
    id: "work-086", word: "merit bonus", translation: "绩效奖金", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 80, topics: ["work"], modules: ["listening", "reading"],
    collocations: ["award a performance bonus", "annual performance bonus", "qualify for a performance bonus", "performance bonus scheme"],
    example_sentence: "The company replaced individual performance bonuses with a team-based profit-sharing scheme to encourage collaboration.",
    synonyms: ["merit-based bonus", "achievement bonus", "incentive payment"],
    common_mistakes: ["bonus 是可数名词; 可以说 annual bonus 或 bonuses"],
    ielts_context: "Listening Section 3: compensation discussion; Reading: HR / compensation",
    pronunciation: "/ˈmer.ɪt ˈbəʊ.nəs/",
    collocations_cn: ["发放绩效奖金", "年度绩效奖金", "获得绩效奖金资格", "绩效奖金方案"],
    example_sentence_cn: "该公司用基于团队的利润分享方案取代了个人绩效奖金，以鼓励协作。",
    synonyms_cn: ["功绩奖金", "成就奖金", "激励性报酬"],
  },
  {
    id: "work-087", word: "occupational disease", translation: "职业病", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 76, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["prevent occupational diseases", "diagnosed with an occupational disease", "occupational disease compensation", "common occupational disease"],
    example_sentence: "Construction workers are at high risk of developing occupational diseases such as silicosis from prolonged exposure to dust and chemicals.",
    synonyms: ["work-related illness", "industrial disease", "professional ailment"],
    common_mistakes: ["occupational disease 特指因工作环境或工作性质导致的疾病"],
    ielts_context: "Reading: occupational health / safety; Writing Task 2: worker protection",
    pronunciation: "/ˌɒk.jʊˈpeɪ.ʃən.əl dɪˈziːz/",
    collocations_cn: ["预防职业病", "被诊断患有职业病", "职业病赔偿", "常见职业病"],
    example_sentence_cn: "建筑工人因长期接触粉尘和化学品而患矽肺等职业病的风险很高。",
    synonyms_cn: ["工作相关疾病", "工业病", "职业性疾病"],
  },
  {
    id: "work-088", word: "labour legislation", translation: "劳动立法", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 78, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["enforce labour legislation", "strengthen labour legislation", "comply with labour legislation", "violate labour legislation"],
    example_sentence: "Comprehensive labour legislation protects workers from exploitation by establishing minimum standards for wages, hours, and safety.",
    synonyms: ["employment law", "workplace regulation", "labour protection laws"],
    common_mistakes: ["labour legislation 是国家法律; company policy 是公司内部政策"],
    ielts_context: "Reading: law / workers' rights; Writing Task 2: government regulation",
    pronunciation: "/ˈleɪ.bər ˌledʒ.ɪˈsleɪ.ʃən/",
    collocations_cn: ["执行劳动立法", "加强劳动立法", "遵守劳动立法", "违反劳动立法"],
    example_sentence_cn: "全面的劳动立法通过建立工资、工时和安全的最低标准来保护工人免受剥削。",
    synonyms_cn: ["就业法", "工作场所法规", "劳动保护法"],
  },
  // ═══ 中頻 50-69 (12 个) ═══
  {
    id: "work-089", word: "reference check", translation: "背景调查", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 66, topics: ["work"], modules: ["listening", "reading"],
    collocations: ["conduct a reference check", "pass a reference check", "reference check process", "employment reference check"],
    example_sentence: "Employers typically conduct reference checks to verify a candidate's employment history and character before making a job offer.",
    synonyms: ["background verification", "credential check", "previous employer inquiry"],
    common_mistakes: ["reference check (核实前雇主评价) 不同于 background check (背景调查可包括犯罪记录等)"],
    ielts_context: "Listening Section 3: job application; Reading: HR / recruitment",
    pronunciation: "/ˈref.ər.əns tʃek/",
    collocations_cn: ["进行背景调查", "通过背景调查", "背景调查流程", "就业背景调查"],
    example_sentence_cn: "雇主通常在发出录用通知前进行背景调查，以核实候选人的工作经历和品行。",
    synonyms_cn: ["背景核查", "资历审核", "前雇主调查"],
  },
  {
    id: "work-090", word: "wage stagnation", translation: "工资停滞", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 68, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["experience wage stagnation", "persistent wage stagnation", "contribute to wage stagnation", "address wage stagnation"],
    example_sentence: "Despite rising productivity and corporate profits, wage stagnation has left many workers struggling to keep up with the cost of living.",
    synonyms: ["pay stagnation", "income plateau", "earnings freeze"],
    common_mistakes: ["wage stagnation 指实际工资 (经通胀调整后) 不增长; 名义工资也许在涨"],
    ielts_context: "Reading: economics / labor market; Writing Task 2: income inequality",
    pronunciation: "/weɪdʒ stæɡˈneɪ.ʃən/",
    collocations_cn: ["经历工资停滞", "持续的工资停滞", "导致工资停滞", "解决工资停滞"],
    example_sentence_cn: "尽管生产率和企业利润不断增长，工资停滞让许多工人难以跟上生活成本的步伐。",
    synonyms_cn: ["薪酬停滞", "收入停滞", "薪资冻结"],
  },
  {
    id: "work-091", word: "job rotation", translation: "岗位轮换", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 63, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["implement job rotation", "participate in job rotation", "job rotation programme", "job rotation benefits"],
    example_sentence: "Job rotation allows employees to develop a broader skill set and gain a better understanding of how different departments operate.",
    synonyms: ["role rotation", "cross-functional assignment", "task diversification"],
    common_mistakes: ["job rotation 是组织安排的轮岗; job hopping 是个人主动频繁跳槽"],
    ielts_context: "Reading: HR development / management; Listening: workplace training",
    pronunciation: "/dʒɒb rəʊˈteɪ.ʃən/",
    collocations_cn: ["实施岗位轮换", "参与岗位轮换", "岗位轮换项目", "岗位轮换的好处"],
    example_sentence_cn: "岗位轮换使员工能够培养更广泛的技能，并更好地了解不同部门的运作方式。",
    synonyms_cn: ["轮岗", "跨职能任务", "任务多样化"],
  },
  {
    id: "work-092", word: "employment tribunal", translation: "就业法庭", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 62, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["take a case to an employment tribunal", "employment tribunal claim", "employment tribunal hearing", "file at an employment tribunal"],
    example_sentence: "Workers who believe they have been unfairly dismissed can bring their case to an employment tribunal for resolution.",
    synonyms: ["labour court", "industrial tribunal", "workplace dispute board"],
    common_mistakes: ["employment tribunal 处理劳资纠纷; 不是普通法院"],
    ielts_context: "Reading: law / workers' rights; Writing Task 2: dispute resolution",
    pronunciation: "/ɪmˈplɔɪ.mənt traɪˈbjuː.nəl/",
    collocations_cn: ["向就业法庭提起诉讼", "就业法庭申诉", "就业法庭听证", "向就业法庭提交"],
    example_sentence_cn: "认为自己被不当解雇的工人可以向就业法庭提起诉讼以求解决。",
    synonyms_cn: ["劳动法庭", "产业法庭", "工作场所争议委员会"],
  },
  {
    id: "work-093", word: "career plateau", translation: "职业瓶颈期", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 61, topics: ["work"], modules: ["reading", "speaking"],
    collocations: ["reach a career plateau", "stuck at a career plateau", "overcome a career plateau", "career plateau phase"],
    example_sentence: "Professionals who feel they have reached a career plateau may benefit from additional training or a lateral move to re-energize their career.",
    synonyms: ["career stagnation", "professional standstill", "promotion ceiling"],
    common_mistakes: ["career plateau 是暂时的停滞阶段; 不等于职业生涯失败"],
    ielts_context: "Reading: career development / psychology; Speaking Part 3: job satisfaction",
    pronunciation: "/kəˈrɪə ˈplæt.əʊ/",
    collocations_cn: ["遇到职业瓶颈期", "困于职业瓶颈期", "突破职业瓶颈期", "职业瓶颈阶段"],
    example_sentence_cn: "感觉自己遇到职业瓶颈期的专业人士可能通过额外培训或横向调动来重新激发职业活力。",
    synonyms_cn: ["职业停滞", "专业停滞", "晋升天花板"],
  },
  {
    id: "work-094", word: "hostile work environment", translation: "敌对工作环境", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 65, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["create a hostile work environment", "complain of a hostile work environment", "hostile work environment claim", "address a hostile work environment"],
    example_sentence: "A hostile work environment can lead to increased absenteeism, reduced productivity, and costly legal claims against employers.",
    synonyms: ["toxic workplace", "intimidating work setting", "adverse employment climate"],
    common_mistakes: ["hostile work environment 是法律术语，指基于受保护类别的歧视性或骚扰行为"],
    ielts_context: "Reading: employment law / HR; Writing Task 2: workplace well-being",
    pronunciation: "/ˈhɒs.taɪl wɜːk ɪnˈvaɪ.rən.mənt/",
    collocations_cn: ["创造敌对工作环境", "投诉敌对工作环境", "敌对工作环境索赔", "处理敌对工作环境"],
    example_sentence_cn: "敌对工作环境可能导致缺勤增加、生产力下降和针对雇主的昂贵法律索赔。",
    synonyms_cn: ["有毒职场", "恐吓性工作环境", "恶劣就业环境"],
  },
  {
    id: "work-095", word: "payroll system", translation: "薪资管理系统", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 64, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["manage the payroll system", "automated payroll system", "update the payroll system", "payroll system software"],
    example_sentence: "Modern payroll systems automatically calculate taxes, pension contributions, and other deductions from employee paychecks.",
    synonyms: ["salary management system", "wage processing platform", "compensation administration"],
    common_mistakes: ["payroll 指公司员工工资的总名单/系统; 不要和 salary (个人工资) 混淆"],
    ielts_context: "Reading: business / HR; Listening: office administration",
    pronunciation: "/ˈpeɪ.rəʊl ˈsɪs.təm/",
    collocations_cn: ["管理薪资管理系统", "自动化薪资管理系统", "更新薪资管理系统", "薪资管理软件"],
    example_sentence_cn: "现代薪资管理系统自动计算员工工资单中的税金、养老金和其他扣款项。",
    synonyms_cn: ["工资管理系统", "薪酬处理平台", "薪酬管理"],
  },
  {
    id: "work-096", word: "career development plan", translation: "职业发展规划", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 67, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["create a career development plan", "follow a career development plan", "individual career development plan", "review a career development plan"],
    example_sentence: "A personalized career development plan outlines specific steps and milestones for achieving long-term professional goals.",
    synonyms: ["professional growth plan", "career roadmap", "vocational advancement scheme"],
    common_mistakes: ["career development plan 是一个持续更新的动态文件，不是在入职时写一次就放一边的"],
    ielts_context: "Reading: HR / career resources; Listening: performance review meeting",
    pronunciation: "/kəˈrɪə dɪˈvel.əp.mənt plæn/",
    collocations_cn: ["制定职业发展规划", "遵循职业发展规划", "个人职业发展规划", "审查职业发展规划"],
    example_sentence_cn: "个性化的职业发展规划概述了实现长期职业目标的具体步骤和里程碑。",
    synonyms_cn: ["专业成长计划", "职业路线图", "职业晋升方案"],
  },
  {
    id: "work-097", word: "work permit", translation: "工作许可", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 66, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["apply for a work permit", "obtain a work permit", "work permit holder", "renew a work permit"],
    example_sentence: "Foreign nationals typically need to secure a valid work permit before they can legally take up employment in another country.",
    synonyms: ["employment authorization", "work visa", "labour permit"],
    common_mistakes: ["work permit 是政府发放的工作许可; work visa 是入境签证，两者不同但相关"],
    ielts_context: "Reading: immigration / employment; Listening Section 1: visa applications",
    pronunciation: "/wɜːk ˈpɜː.mɪt/",
    collocations_cn: ["申请工作许可", "获得工作许可", "工作许可持有人", "续期工作许可"],
    example_sentence_cn: "外国公民通常需要在获得有效工作许可后才能在其他国家合法就业。",
    synonyms_cn: ["就业许可", "工作签证", "劳工许可证"],
  },
  {
    id: "work-098", word: "zero-hour contract", translation: "零时工合同", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 60, topics: ["work"], modules: ["reading", "writing"],
    collocations: ["on a zero-hour contract", "ban zero-hour contracts", "zero-hour contract worker", "issue zero-hour contracts"],
    example_sentence: "Zero-hour contracts offer flexibility to both employers and workers, but critics argue they create financial insecurity for employees.",
    synonyms: ["casual contract", "on-call employment", "precarious work arrangement"],
    common_mistakes: ["zero-hour 表示不保证最低工时; 工人只在被叫时才工作"],
    ielts_context: "Reading: labor market / employment law; Writing Task 2: workers' rights",
    pronunciation: "/ˈzɪə.rəʊ aʊə ˈkɒn.trækt/",
    collocations_cn: ["持有零时工合同", "禁止零时工合同", "零时工合同工人", "发放零时工合同"],
    example_sentence_cn: "零时工合同为雇主和工人提供了灵活性，但批评者认为它们给员工带来了财务不安全感。",
    synonyms_cn: ["临时合同", "随叫随到雇佣", "不稳定工作安排"],
  },
  {
    id: "work-099", word: "grievance procedure", translation: "申诉程序", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 63, topics: ["work"], modules: ["reading", "listening"],
    collocations: ["file a grievance procedure", "follow the grievance procedure", "formal grievance procedure", "internal grievance procedure"],
    example_sentence: "Every organization should have a clear grievance procedure that allows employees to raise concerns without fear of retaliation.",
    synonyms: ["complaint procedure", "dispute resolution process", "formal appeal mechanism"],
    common_mistakes: ["grievance 是正式申诉; complaint 是普通投诉，程度不同"],
    ielts_context: "Reading: HR policy / worker rights; Listening: workplace meeting",
    pronunciation: "/ˈɡriː.vəns prəˈsiː.dʒər/",
    collocations_cn: ["提起申诉程序", "遵循申诉程序", "正式申诉程序", "内部申诉程序"],
    example_sentence_cn: "每个组织都应有一个明确的申诉程序，允许员工在不用担心报复的情况下提出关切。",
    synonyms_cn: ["投诉程序", "争议解决流程", "正式上诉机制"],
  },
  {
    id: "work-100", word: "equal pay for equal work", translation: "同工同酬", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 69, topics: ["work"], modules: ["writing", "reading"],
    collocations: ["demand equal pay for equal work", "principle of equal pay for equal work", "ensure equal pay for equal work", "advocate equal pay for equal work"],
    example_sentence: "The principle of equal pay for equal work is enshrined in law in most countries, yet enforcement remains a significant challenge.",
    synonyms: ["pay equity", "wage parity", "comparable worth"],
    common_mistakes: ["equal pay for equal work 指完全相同的职位; equal pay for work of equal value 是更广泛的概念"],
    ielts_context: "Writing Task 2: gender equality / workers' rights; Reading: labor law / economics",
    pronunciation: "/ˈiː.kwəl peɪ fɔːr ˈiː.kwəl wɜːk/",
    collocations_cn: ["要求同工同酬", "同工同酬原则", "确保同工同酬", "倡导同工同酬"],
    example_sentence_cn: "同工同酬原则已在大多数国家写入法律，但执法仍然是一个重大挑战。",
    synonyms_cn: ["薪酬公平", "工资平等", "可比价值"],
  },
];
