// scripts/expand-education.ts
// Phase 2: Education 话题扩展 — edu-051 ~ edu-100（50 个新词块）
// 包含完整 17 字段 + 双语数据
// 频次分布: 超高(90-99)×20 + 高(70-89)×18 + 中(50-69)×12

import type { Chunk } from "../types/chunk";

export const EDU_EXPANSION: Chunk[] = [
  // ═══ 超高頻 90-99 (20 个) ═══
  {
    id: "edu-051", word: "academic rigor", translation: "学术严谨性", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 91, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["maintain academic rigor", "lack of academic rigor", "ensure academic rigor", "academic rigor and standards"],
    example_sentence: "The university has a long-standing reputation for academic rigor and high standards.",
    synonyms: ["scholarly strictness", "intellectual discipline", "academic thoroughness"],
    common_mistakes: ["rigor 不要拼成 rigour (英式) 或 rigger"],
    ielts_context: "Writing Task 2: education quality; Reading: university profiles",
    pronunciation: "/ˌæk.əˈdem.ɪk ˈrɪɡ.ər/",
    collocations_cn: ["保持学术严谨", "缺乏学术严谨性", "确保学术严谨", "学术严谨与标准"],
    example_sentence_cn: "该大学长期以来以学术严谨性和高标准著称。",
    synonyms_cn: ["学术严格", "知识纪律", "学术周密"],
  },
  {
    id: "edu-052", word: "admissions process", translation: "招生流程", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["education"], modules: ["listening", "reading"],
    collocations: ["competitive admissions process", "streamline the admissions process", "holistic admissions process", "university admissions process"],
    example_sentence: "The admissions process at top universities has become increasingly competitive in recent years.",
    synonyms: ["enrollment procedure", "selection process", "application procedure"],
    common_mistakes: ["admission (单数) 指入学概念；admissions (复数) 指招生部门/流程"],
    ielts_context: "Listening Section 3: campus conversation; Reading: university guides",
    pronunciation: "/ədˈmɪʃ.ənz ˈprəʊ.ses/",
    collocations_cn: ["竞争激烈的招生流程", "简化招生流程", "全面招生流程", "大学招生流程"],
    example_sentence_cn: "顶尖大学的招生流程近年来变得越来越有竞争性。",
    synonyms_cn: ["录取程序", "选拔过程", "申请程序"],
  },
  {
    id: "edu-053", word: "knowledge acquisition", translation: "知识获取", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 93, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["facilitate knowledge acquisition", "rapid knowledge acquisition", "lifelong knowledge acquisition", "process of knowledge acquisition"],
    example_sentence: "Technology has dramatically accelerated the process of knowledge acquisition for learners of all ages.",
    synonyms: ["learning process", "information uptake", "cognitive assimilation"],
    common_mistakes: ["acquisition 拼写注意 c 和 q 的位置；不要说 knowledge learn"],
    ielts_context: "Writing Task 2: technology / education; Reading: cognitive science",
    pronunciation: "/ˈnɒl.ɪdʒ ˌæk.wɪˈzɪʃ.ən/",
    collocations_cn: ["促进知识获取", "快速知识获取", "终身知识获取", "知识获取过程"],
    example_sentence_cn: "技术极大地加速了各个年龄段学习者的知识获取过程。",
    synonyms_cn: ["学习过程", "信息吸收", "认知同化"],
  },
  {
    id: "edu-054", word: "curriculum design", translation: "课程设计", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 92, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["innovative curriculum design", "curriculum design principles", "participate in curriculum design", "effective curriculum design"],
    example_sentence: "Effective curriculum design must balance theoretical knowledge with practical application.",
    synonyms: ["course planning", "syllabus development", "program design"],
    common_mistakes: ["curriculum 的复数形式是 curricula 或 curriculums"],
    ielts_context: "Writing Task 2: education reform; Reading: pedagogy journals",
    pronunciation: "/kəˈrɪk.jʊ.ləm dɪˈzaɪn/",
    collocations_cn: ["创新的课程设计", "课程设计原则", "参与课程设计", "有效的课程设计"],
    example_sentence_cn: "有效的课程设计必须在理论知识和实际应用之间取得平衡。",
    synonyms_cn: ["课程规划", "教学大纲制定", "项目设计"],
  },
  {
    id: "edu-055", word: "assessment criteria", translation: "评估标准", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 94, topics: ["education"], modules: ["reading", "writing"],
    collocations: ["clear assessment criteria", "meet assessment criteria", "define assessment criteria", "based on assessment criteria"],
    example_sentence: "Students perform better when they understand the assessment criteria before starting their assignments.",
    synonyms: ["evaluation standards", "grading rubric", "marking guidelines"],
    common_mistakes: ["criteria 是复数形式 (单数 criterion)；说 assessment criteria 不用 criterias"],
    ielts_context: "Reading: academic guidelines; Writing Task 2: education assessment",
    pronunciation: "/əˈses.mənt kraɪˈtɪə.ri.ə/",
    collocations_cn: ["明确的评估标准", "达到评估标准", "定义评估标准", "基于评估标准"],
    example_sentence_cn: "当学生在开始作业前了解评估标准时，他们的表现会更好。",
    synonyms_cn: ["评价标准", "评分标准", "评分指南"],
  },
  {
    id: "edu-056", word: "blended learning", translation: "混合式学习", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 95, topics: ["education"], modules: ["speaking", "writing"],
    collocations: ["adopt blended learning", "blended learning approach", "blended learning environment", "benefits of blended learning"],
    example_sentence: "Blended learning combines face-to-face instruction with online resources to create a more flexible educational experience.",
    synonyms: ["hybrid learning", "mixed-mode instruction", "integrated learning"],
    common_mistakes: ["blended learning 不是 blended studying；learning 是固定搭配"],
    ielts_context: "Speaking Part 3: technology in education; Writing Task 2: modern education",
    pronunciation: "/ˈblen.dɪd ˈlɜː.nɪŋ/",
    collocations_cn: ["采用混合式学习", "混合式学习方法", "混合式学习环境", "混合式学习的好处"],
    example_sentence_cn: "混合式学习将面对面教学与在线资源相结合，创造了更灵活的教育体验。",
    synonyms_cn: ["混合学习", "混合模式教学", "整合学习"],
  },
  {
    id: "edu-057", word: "early childhood education", translation: "早期儿童教育", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 97, topics: ["education"], modules: ["writing", "speaking"],
    collocations: ["invest in early childhood education", "access to early childhood education", "quality early childhood education", "importance of early childhood education"],
    example_sentence: "Research consistently shows that investment in early childhood education yields significant long-term social and economic returns.",
    synonyms: ["preschool education", "early years education", "nursery education"],
    common_mistakes: ["childhood 是一个词，不要分开写；early child education 少了 hood"],
    ielts_context: "Writing Task 2: government spending / education; Speaking Part 3: child development",
    pronunciation: "/ˈɜː.li ˈtʃaɪld.hʊd ˌedʒ.ʊˈkeɪ.ʃən/",
    collocations_cn: ["投资早期儿童教育", "获得早期儿童教育", "优质早期儿童教育", "早期儿童教育的重要性"],
    example_sentence_cn: "研究一致表明，投资早期儿童教育能产生显著的长期社会和经济效益。",
    synonyms_cn: ["学前教育", "早期教育", "幼儿教育"],
  },
  {
    id: "edu-058", word: "scholastic probation", translation: "学业警告", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 90, topics: ["education"], modules: ["reading", "listening"],
    collocations: ["placed on academic probation", "academic probation policy", "face academic probation", "avoid academic probation"],
    example_sentence: "Students who fail to maintain a minimum GPA may be placed on academic probation or face dismissal.",
    synonyms: ["academic warning", "scholastic probation", "academic suspension warning"],
    common_mistakes: ["probation 不是 problem；指观察期/试读期"],
    ielts_context: "Listening Section 3: academic counseling; Reading: university policies",
    pronunciation: "/skəˈlæs.tɪk prəˈbeɪ.ʃən/",
    collocations_cn: ["被列入学业警告", "学业警告政策", "面临学业警告", "避免学业警告"],
    example_sentence_cn: "未能保持最低平均绩点的学生可能会被列入学业警告或面临开除。",
    synonyms_cn: ["学业警告", "学业观察期", "停学警告"],
  },
  {
    id: "edu-059", word: "interactive whiteboard", translation: "交互式白板", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["education"], modules: ["listening", "speaking"],
    collocations: ["use an interactive whiteboard", "interactive whiteboard technology", "equipped with interactive whiteboards", "interactive whiteboard software"],
    example_sentence: "Interactive whiteboards have replaced traditional chalkboards in many modern classrooms around the world.",
    synonyms: ["smart board", "digital whiteboard", "electronic display board"],
    common_mistakes: ["whiteboard 是一个词，不要分开写 white board"],
    ielts_context: "Listening Section 3: classroom technology; Speaking Part 2: describe a classroom",
    pronunciation: "/ˌɪn.təˈræk.tɪv ˈwaɪt.bɔːd/",
    collocations_cn: ["使用交互式白板", "交互式白板技术", "配备交互式白板", "交互式白板软件"],
    example_sentence_cn: "交互式白板已在全球许多现代教室中取代了传统黑板。",
    synonyms_cn: ["智能白板", "数字白板", "电子显示板"],
  },
  {
    id: "edu-060", word: "teacher training", translation: "教师培训", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 96, topics: ["education"], modules: ["writing", "speaking"],
    collocations: ["invest in teacher training", "quality teacher training", "ongoing teacher training", "teacher training programmes"],
    example_sentence: "Improving the quality of teacher training is one of the most effective ways to raise educational standards.",
    synonyms: ["teacher education", "instructor development", "faculty training"],
    common_mistakes: ["teacher training 强调实践培训；teacher education 更强调理论"],
    ielts_context: "Writing Task 2: education policy; Speaking Part 3: teaching profession",
    pronunciation: "/ˈtiː.tʃər ˈtreɪ.nɪŋ/",
    collocations_cn: ["投资教师培训", "优质教师培训", "持续的教师培训", "教师培训计划"],
    example_sentence_cn: "提高教师培训质量是提升教育标准最有效的方法之一。",
    synonyms_cn: ["师范教育", "教师发展", "师资培训"],
  },
  {
    id: "edu-061", word: "special needs education", translation: "特殊需求教育", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 92, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["provide special needs education", "access to special needs education", "inclusive special needs education", "funding for special needs education"],
    example_sentence: "Every child has the right to receive appropriate special needs education tailored to their unique learning requirements.",
    synonyms: ["special education", "SEN provision", "inclusive education"],
    common_mistakes: ["special needs 作形容词时常用连字符 special-needs education"],
    ielts_context: "Writing Task 2: education equality; Reading: education policy",
    pronunciation: "/ˈspeʃ.əl niːdz ˌedʒ.ʊˈkeɪ.ʃən/",
    collocations_cn: ["提供特殊需求教育", "获得特殊需求教育", "包容性特殊需求教育", "特殊需求教育资金"],
    example_sentence_cn: "每个孩子都有权接受适合其独特学习需求的适当的特殊需求教育。",
    synonyms_cn: ["特殊教育", "特殊教育需求保障", "包容性教育"],
  },
  {
    id: "edu-062", word: "degree program", translation: "学位课程", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 95, topics: ["education"], modules: ["listening", "reading"],
    collocations: ["enroll in a degree program", "complete a degree program", "four-year degree program", "online degree program"],
    example_sentence: "The university offers over 200 degree programs across a wide range of academic disciplines.",
    synonyms: ["degree course", "academic program", "university program"],
    common_mistakes: ["degree programme 是英式拼写；美式为 degree program"],
    ielts_context: "Listening Section 3: course selection; Reading: university catalogues",
    pronunciation: "/dɪˈɡriː ˈprəʊ.ɡræm/",
    collocations_cn: ["攻读学位课程", "完成学位课程", "四年制学位课程", "在线学位课程"],
    example_sentence_cn: "该大学提供超过200个学位课程，涵盖广泛的学科领域。",
    synonyms_cn: ["学位项目", "学术课程", "大学课程"],
  },
  {
    id: "edu-063", word: "academic calendar", translation: "校历", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 90, topics: ["education"], modules: ["listening", "reading"],
    collocations: ["follow the academic calendar", "check the academic calendar", "academic calendar dates", "according to the academic calendar"],
    example_sentence: "Students should consult the academic calendar for important dates such as exam periods and holiday breaks.",
    synonyms: ["school calendar", "university calendar", "term schedule"],
    common_mistakes: ["calendar 拼写注意：结尾是 -dar 不是 -der"],
    ielts_context: "Listening Section 1: orientation; Reading: university websites",
    pronunciation: "/ˌæk.əˈdem.ɪk ˈkæl.ɪn.dər/",
    collocations_cn: ["遵循校历", "查看校历", "校历日期", "根据校历"],
    example_sentence_cn: "学生应查阅校历以了解考试周和假期等重要日期。",
    synonyms_cn: ["学校日历", "大学日历", "学期安排"],
  },
  {
    id: "edu-064", word: "study skills", translation: "学习技巧", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 93, topics: ["education"], modules: ["speaking", "listening"],
    collocations: ["develop study skills", "effective study skills", "improve study skills", "study skills workshop"],
    example_sentence: "Many universities offer workshops to help first-year students develop effective study skills and time management strategies.",
    synonyms: ["learning techniques", "academic skills", "revision strategies"],
    common_mistakes: ["study skills 不是 studying skills；study 此处是名词作定语"],
    ielts_context: "Speaking Part 2: learning experience; Listening Section 3: student support",
    pronunciation: "/ˈstʌd.i skɪlz/",
    collocations_cn: ["培养学习技巧", "有效的学习技巧", "提高学习技巧", "学习技巧工作坊"],
    example_sentence_cn: "许多大学提供工作坊帮助新生发展有效的学习技巧和时间管理策略。",
    synonyms_cn: ["学习方法", "学术技能", "复习策略"],
  },
  {
    id: "edu-065", word: "faculty advisor", translation: "院系导师", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 91, topics: ["education"], modules: ["listening", "speaking"],
    collocations: ["meet with an academic advisor", "seek advice from an academic advisor", "assigned academic advisor", "academic advisor appointment"],
    example_sentence: "Students should regularly meet with their academic advisor to discuss course selection and career plans.",
    synonyms: ["faculty advisor", "tutor", "academic counselor", "academic mentor"],
    common_mistakes: ["advisor 美式拼写；英式为 adviser，IELTS 两种都接受"],
    ielts_context: "Listening Section 3: campus services; Speaking Part 1: university life",
    pronunciation: "/ˈfæk.əl.ti ədˈvaɪ.zər/",
    collocations_cn: ["与院系导师会面", "向院系导师寻求建议", "指派的院系导师", "院系导师约见"],
    example_sentence_cn: "学生应定期与学业导师会面，讨论课程选择和职业规划。",
    synonyms_cn: ["院系导师", "辅导教师", "学术顾问", "学业指导"],
  },
  {
    id: "edu-066", word: "remedial class", translation: "补习班", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 92, topics: ["education"], modules: ["reading", "listening"],
    collocations: ["attend remedial classes", "offer remedial classes", "remedial class instruction", "require remedial classes"],
    example_sentence: "Students who fall behind in core subjects may be required to attend remedial classes after school.",
    synonyms: ["catch-up class", "supplementary class", "extra-help session"],
    common_mistakes: ["remedial 表示补救性的，不要和 remedy (治疗方案) 混淆"],
    ielts_context: "Reading: education reports; Listening Section 3: student support discussions",
    pronunciation: "/rɪˈmiː.di.əl klɑːs/",
    collocations_cn: ["参加补习班", "提供补习班", "补习班教学", "需要补习班"],
    example_sentence_cn: "在核心科目上落后的学生可能被要求放学后参加补习班。",
    synonyms_cn: ["补课班", "补充课程", "额外辅导课"],
  },
  {
    id: "edu-067", word: "group project", translation: "小组项目", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 94, topics: ["education"], modules: ["speaking", "listening"],
    collocations: ["work on a group project", "complete a group project", "group project collaboration", "assess group projects"],
    example_sentence: "Group projects help students develop essential collaboration and communication skills needed in the workplace.",
    synonyms: ["team assignment", "collaborative project", "group assignment"],
    common_mistakes: ["group project 指小组形式完成的项目；teamwork 指团队合作能力"],
    ielts_context: "Speaking Part 2: school experience; Listening Section 3: student discussion",
    pronunciation: "/ɡruːp ˈprɒdʒ.ekt/",
    collocations_cn: ["参与小组项目", "完成小组项目", "小组项目合作", "评估小组项目"],
    example_sentence_cn: "小组项目帮助学生培养职场所需的必要协作和沟通技能。",
    synonyms_cn: ["团队作业", "合作项目", "小组作业"],
  },
  {
    id: "edu-068", word: "exam-oriented education", translation: "应试教育", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 96, topics: ["education"], modules: ["writing", "speaking"],
    collocations: ["criticize exam-oriented education", "move away from exam-oriented education", "exam-oriented education system", "limitations of exam-oriented education"],
    example_sentence: "Many educators argue that exam-oriented education stifles creativity and fails to develop critical thinking skills.",
    synonyms: ["test-focused education", "examination-driven learning", "score-oriented schooling"],
    common_mistakes: ["exam-oriented 有连字符；oriented 不是 orientated (尽管 orientated 也正确但较少用)"],
    ielts_context: "Writing Task 2: education reform; Speaking Part 3: education systems",
    pronunciation: "/ɪɡˈzæm ˈɔː.ri.en.tɪd ˌedʒ.ʊˈkeɪ.ʃən/",
    collocations_cn: ["批评应试教育", "摆脱应试教育", "应试教育体系", "应试教育的局限"],
    example_sentence_cn: "许多教育工作者认为应试教育扼杀了创造力，未能培养批判性思维能力。",
    synonyms_cn: ["考试导向教育", "考试驱动学习", "分数导向教育"],
  },
  {
    id: "edu-069", word: "university application", translation: "大学申请", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 94, topics: ["education"], modules: ["reading", "listening"],
    collocations: ["submit a university application", "university application process", "university application deadline", "successful university application"],
    example_sentence: "Writing a compelling personal statement is a crucial part of any university application.",
    synonyms: ["college application", "university admission application", "tertiary education application"],
    common_mistakes: ["application 后接 for + 机构/课程；application for university admission"],
    ielts_context: "Reading: university guides; Listening Section 3: student planning",
    pronunciation: "/ˌjuː.nɪˈvɜː.sə.ti ˌæp.lɪˈkeɪ.ʃən/",
    collocations_cn: ["提交大学申请", "大学申请流程", "大学申请截止日期", "成功的大学申请"],
    example_sentence_cn: "撰写有说服力的个人陈述是任何大学申请的关键部分。",
    synonyms_cn: ["大学入学申请", "本科申请", "高等教育申请"],
  },
  {
    id: "edu-070", word: "academic writing", translation: "学术写作", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 97, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["improve academic writing", "academic writing skills", "features of academic writing", "academic writing style"],
    example_sentence: "Academic writing requires clarity, precision, and proper citation of sources to support arguments.",
    synonyms: ["scholarly writing", "research writing", "formal academic prose"],
    common_mistakes: ["academic writing 要求客观、正式，不要用口语化表达和缩写"],
    ielts_context: "Writing Task 2: academic skills; Reading: academic journals",
    pronunciation: "/ˌæk.əˈdem.ɪk ˈraɪ.tɪŋ/",
    collocations_cn: ["提高学术写作", "学术写作技能", "学术写作的特点", "学术写作风格"],
    example_sentence_cn: "学术写作要求清晰、精确，并正确引用来源以支持论点。",
    synonyms_cn: ["学术写作", "研究写作", "正式学术文章"],
  },
  // ═══ 高頻 70-89 (18 个) ═══
  {
    id: "edu-071", word: "student loan", translation: "学生贷款", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 88, topics: ["education"], modules: ["writing", "speaking"],
    collocations: ["repay student loans", "take out a student loan", "student loan debt", "student loan forgiveness"],
    example_sentence: "Rising student loan debt has become a major socio-economic issue in many developed countries.",
    synonyms: ["education loan", "tuition loan", "study loan"],
    common_mistakes: ["loan 是可数名词，可以说 a student loan"],
    ielts_context: "Writing Task 2: education funding; Speaking Part 3: university costs",
    pronunciation: "/ˈstjuː.dənt ləʊn/",
    collocations_cn: ["偿还学生贷款", "申请学生贷款", "学生贷款债务", "学生贷款减免"],
    example_sentence_cn: "不断增长的学生贷款债务已成为许多发达国家的重要社会经济问题。",
    synonyms_cn: ["教育贷款", "学费贷款", "学习贷款"],
  },
  {
    id: "edu-072", word: "educational inequality", translation: "教育不平等", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 87, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["address educational inequality", "perpetuate educational inequality", "reduce educational inequality", "root causes of educational inequality"],
    example_sentence: "Educational inequality remains a persistent challenge, with students from disadvantaged backgrounds consistently underperforming.",
    synonyms: ["education disparity", "learning gap", "achievement gap"],
    common_mistakes: ["inequality 是不可数名词，说的是状况而非某个具体不平等的实例"],
    ielts_context: "Writing Task 2: social justice / education; Reading: sociology",
    pronunciation: "/ˌedʒ.ʊˈkeɪ.ʃən.əl ˌɪn.ɪˈkwɒl.ə.ti/",
    collocations_cn: ["解决教育不平等", "延续教育不平等", "减少教育不平等", "教育不平等的根本原因"],
    example_sentence_cn: "教育不平等仍然是一个持续的挑战，来自弱势背景的学生始终表现不佳。",
    synonyms_cn: ["教育差距", "学习差距", "成绩差距"],
  },
  {
    id: "edu-073", word: "flipped classroom", translation: "翻转课堂", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 82, topics: ["education"], modules: ["writing", "speaking"],
    collocations: ["implement a flipped classroom", "flipped classroom model", "flipped classroom approach", "benefits of the flipped classroom"],
    example_sentence: "In a flipped classroom, students watch lecture videos at home and use class time for interactive problem-solving activities.",
    synonyms: ["inverted classroom", "reverse instruction", "student-centered classroom"],
    common_mistakes: ["flipped 是 flip 的过去分词；不要说 flip classroom"],
    ielts_context: "Writing Task 2: innovative teaching; Speaking Part 3: education methods",
    pronunciation: "/flɪpt ˈklɑːs.ruːm/",
    collocations_cn: ["实施翻转课堂", "翻转课堂模式", "翻转课堂方法", "翻转课堂的好处"],
    example_sentence_cn: "在翻转课堂中，学生在家里观看讲座视频，利用课堂时间进行互动式问题解决活动。",
    synonyms_cn: ["颠倒课堂", "反向教学", "以学生为中心的课堂"],
  },
  {
    id: "edu-074", word: "inclusive education", translation: "包容性教育", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 84, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["promote inclusive education", "inclusive education policy", "implement inclusive education", "barriers to inclusive education"],
    example_sentence: "Inclusive education ensures that all students, regardless of their abilities or backgrounds, learn together in the same environment.",
    synonyms: ["mainstream education", "integrated education", "education for all"],
    common_mistakes: ["inclusive 表示包容各类学生的；不要和 comprehensive (综合性的) 混淆"],
    ielts_context: "Writing Task 2: education equality; Reading: special education policy",
    pronunciation: "/ɪnˈkluː.sɪv ˌedʒ.ʊˈkeɪ.ʃən/",
    collocations_cn: ["促进包容性教育", "包容性教育政策", "实施包容性教育", "包容性教育的障碍"],
    example_sentence_cn: "包容性教育确保所有学生，无论其能力或背景如何，都能在同一环境中共同学习。",
    synonyms_cn: ["主流教育", "融合教育", "全民教育"],
  },
  {
    id: "edu-075", word: "subject specialist", translation: "学科专家", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 78, topics: ["education"], modules: ["reading", "listening"],
    collocations: ["consult a subject specialist", "subject specialist teacher", "become a subject specialist", "subject specialist knowledge"],
    example_sentence: "Secondary schools need to recruit more subject specialists to improve the quality of teaching in STEM disciplines.",
    synonyms: ["subject matter expert", "discipline expert", "specialized teacher"],
    common_mistakes: ["specialist (专家) 不是 special (特别的)"],
    ielts_context: "Reading: education recruitment; Listening Section 3: staff discussion",
    pronunciation: "/ˈsʌb.dʒɪkt ˈspeʃ.əl.ɪst/",
    collocations_cn: ["咨询学科专家", "学科专家教师", "成为学科专家", "学科专业知识"],
    example_sentence_cn: "中学需要招聘更多学科专家来提高STEM学科的教学质量。",
    synonyms_cn: ["学科领域专家", "专业领域专家", "专业教师"],
  },
  {
    id: "edu-076", word: "language acquisition", translation: "语言习得", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 85, topics: ["education"], modules: ["reading", "writing"],
    collocations: ["second language acquisition", "facilitate language acquisition", "language acquisition theory", "stages of language acquisition"],
    example_sentence: "Immersion programs have been shown to accelerate language acquisition compared to traditional classroom instruction.",
    synonyms: ["language learning", "linguistic development", "language development"],
    common_mistakes: ["acquisition 强调自然习得；learning 强调有意识的学习过程"],
    ielts_context: "Reading: linguistics / education; Writing Task 2: language education",
    pronunciation: "/ˈlæŋ.ɡwɪdʒ ˌæk.wɪˈzɪʃ.ən/",
    collocations_cn: ["第二语言习得", "促进语言习得", "语言习得理论", "语言习得阶段"],
    example_sentence_cn: "沉浸式课程已被证明比传统课堂教学更能加速语言习得。",
    synonyms_cn: ["语言学习", "语言发展", "语言能力发展"],
  },
  {
    id: "edu-077", word: "parental involvement", translation: "家长参与", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 86, topics: ["education"], modules: ["writing", "speaking"],
    collocations: ["encourage parental involvement", "lack of parental involvement", "positive parental involvement", "level of parental involvement"],
    example_sentence: "Research consistently shows a strong correlation between parental involvement and children's academic success.",
    synonyms: ["parent engagement", "family participation", "guardian involvement"],
    common_mistakes: ["parental 是形容词 (父母的)；parent 是名词，parental involvement 是正确说法"],
    ielts_context: "Writing Task 2: education / parenting; Speaking Part 3: child development",
    pronunciation: "/pəˈren.təl ɪnˈvɒlv.mənt/",
    collocations_cn: ["鼓励家长参与", "缺乏家长参与", "积极的家长参与", "家长参与度"],
    example_sentence_cn: "研究一致显示，家长参与与孩子的学业成功之间存在很强的相关性。",
    synonyms_cn: ["家长参与", "家庭参与", "监护人参与"],
  },
  {
    id: "edu-078", word: "vocational school", translation: "职业学校", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 79, topics: ["education"], modules: ["reading", "speaking"],
    collocations: ["attend a vocational school", "vocational school graduate", "vocational school training", "enroll in a vocational school"],
    example_sentence: "Vocational schools provide students with practical skills that are directly applicable to specific trades and industries.",
    synonyms: ["trade school", "technical college", "career academy"],
    common_mistakes: ["vocational 来自 vocation (职业)，不要和 vacation (假期) 混淆"],
    ielts_context: "Reading: education alternatives; Speaking Part 3: career preparation",
    pronunciation: "/vəʊˈkeɪ.ʃən.əl skuːl/",
    collocations_cn: ["就读职业学校", "职业学校毕业生", "职业学校培训", "入读职业学校"],
    example_sentence_cn: "职业学校为学生提供直接适用于特定行业和产业的实用技能。",
    synonyms_cn: ["技工学校", "技术学院", "职业院校"],
  },
  {
    id: "edu-079", word: "digital textbook", translation: "数字教科书", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 81, topics: ["education"], modules: ["speaking", "reading"],
    collocations: ["adopt digital textbooks", "digital textbook platform", "interactive digital textbook", "switch to digital textbooks"],
    example_sentence: "Digital textbooks offer interactive features such as embedded videos and quizzes that enhance the learning experience.",
    synonyms: ["e-textbook", "electronic textbook", "online textbook"],
    common_mistakes: ["digital textbook 也可说 e-textbook，但 digital 更正式"],
    ielts_context: "Speaking Part 3: technology in education; Reading: EdTech articles",
    pronunciation: "/ˈdɪdʒ.ɪ.təl ˈtekst.bʊk/",
    collocations_cn: ["采用数字教科书", "数字教科书平台", "互动式数字教科书", "转向数字教科书"],
    example_sentence_cn: "数字教科书提供嵌入式视频和测验等互动功能，增强了学习体验。",
    synonyms_cn: ["电子教科书", "电子教材", "在线教科书"],
  },
  {
    id: "edu-080", word: "research methodology", translation: "研究方法论", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 83, topics: ["education"], modules: ["reading", "writing"],
    collocations: ["apply research methodology", "qualitative research methodology", "rigorous research methodology", "research methodology course"],
    example_sentence: "Understanding research methodology is essential for conducting credible and reliable academic studies.",
    synonyms: ["research methods", "investigative approach", "scientific methodology"],
    common_mistakes: ["methodology 指方法体系；method 指具体方法，两者不可混用"],
    ielts_context: "Reading: academic papers; Writing Task 2: research / science",
    pronunciation: "/rɪˈsɜːtʃ ˌmeθ.əˈdɒl.ə.dʒi/",
    collocations_cn: ["应用研究方法论", "定性研究方法论", "严谨的研究方法论", "研究方法论课程"],
    example_sentence_cn: "理解研究方法论对于开展可信可靠的学术研究至关重要。",
    synonyms_cn: ["研究方法", "调查方法", "科学方法论"],
  },
  {
    id: "edu-081", word: "online assessment", translation: "在线评估", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 80, topics: ["education"], modules: ["speaking", "reading"],
    collocations: ["conduct online assessments", "online assessment tool", "online assessment platform", "secure online assessment"],
    example_sentence: "The shift to remote learning has accelerated the adoption of online assessment tools in educational institutions worldwide.",
    synonyms: ["digital assessment", "e-assessment", "web-based testing"],
    common_mistakes: ["assessment 和 evaluation 不同：assessment 更关注学习过程，evaluation 更关注结果"],
    ielts_context: "Speaking Part 3: education technology; Reading: EdTech reports",
    pronunciation: "/ˈɒn.laɪn əˈses.mənt/",
    collocations_cn: ["进行在线评估", "在线评估工具", "在线评估平台", "安全的在线评估"],
    example_sentence_cn: "向远程学习的转变加速了全球教育机构对在线评估工具的采用。",
    synonyms_cn: ["数字评估", "电子评估", "网络测试"],
  },
  {
    id: "edu-082", word: "academic support", translation: "学术支持", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 82, topics: ["education"], modules: ["listening", "speaking"],
    collocations: ["provide academic support", "seek academic support", "academic support services", "access academic support"],
    example_sentence: "Universities offer a range of academic support services including tutoring, writing centers, and study skills workshops.",
    synonyms: ["learning support", "educational assistance", "scholastic support"],
    common_mistakes: ["support 是不可数名词，不说 an academic support"],
    ielts_context: "Listening Section 3: student services; Speaking Part 1: university experience",
    pronunciation: "/ˌæk.əˈdem.ɪk səˈpɔːt/",
    collocations_cn: ["提供学术支持", "寻求学术支持", "学术支持服务", "获取学术支持"],
    example_sentence_cn: "大学提供一系列学术支持服务，包括辅导、写作中心和学习技巧工作坊。",
    synonyms_cn: ["学习支持", "教育辅助", "学业支持"],
  },
  {
    id: "edu-083", word: "critical pedagogy", translation: "批判教育学", part_of_speech: "noun phrase", band_level: "7.0", frequency_score: 75, topics: ["education"], modules: ["reading", "writing"],
    collocations: ["apply critical pedagogy", "principles of critical pedagogy", "critical pedagogy approach", "influenced by critical pedagogy"],
    example_sentence: "Critical pedagogy encourages students to question and challenge existing power structures and social norms within education.",
    synonyms: ["emancipatory education", "transformative pedagogy", "radical education theory"],
    common_mistakes: ["pedagogy 发音 /ˈped.ə.ɡɒdʒ.i/，重音在第一个音节"],
    ielts_context: "Reading: education theory; Writing Task 2: education philosophy",
    pronunciation: "/ˈkrɪt.ɪ.kəl ˈped.ə.ɡɒdʒ.i/",
    collocations_cn: ["应用批判教育学", "批判教育学原则", "批判教育学方法", "受批判教育学影响"],
    example_sentence_cn: "批判教育学鼓励学生质疑和挑战教育中现有的权力结构和社会规范。",
    synonyms_cn: ["解放教育", "转化教育学", "激进教育理论"],
  },
  {
    id: "edu-084", word: "graduation thesis", translation: "毕业论文", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 84, topics: ["education"], modules: ["reading", "writing"],
    collocations: ["write a graduation thesis", "submit a graduation thesis", "defend a graduation thesis", "graduation thesis supervisor"],
    example_sentence: "Completing a graduation thesis requires extensive research, critical analysis, and clear academic writing.",
    synonyms: ["senior thesis", "capstone project", "dissertation"],
    common_mistakes: ["thesis 的复数是 theses /ˈθiː.siːz/，不是 thesises"],
    ielts_context: "Reading: university requirements; Writing Task 2: higher education",
    pronunciation: "/ˌɡrædʒ.uˈeɪ.ʃən ˈθiː.sɪs/",
    collocations_cn: ["撰写毕业论文", "提交毕业论文", "答辩毕业论文", "毕业论文导师"],
    example_sentence_cn: "完成毕业论文需要广泛的研究、批判性分析和清晰的学术写作。",
    synonyms_cn: ["学士论文", "毕业设计", "学位论文"],
  },
  {
    id: "edu-085", word: "multilingual education", translation: "多语言教育", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 73, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["promote multilingual education", "multilingual education policy", "benefits of multilingual education", "implement multilingual education"],
    example_sentence: "Multilingual education not only preserves cultural heritage but also enhances cognitive flexibility and academic performance.",
    synonyms: ["bilingual education", "plurilingual instruction", "linguistically diverse education"],
    common_mistakes: ["multilingual 形容词；multi-language 也可但不如 multilingual 正式"],
    ielts_context: "Writing Task 2: language policy; Reading: linguistics / education",
    pronunciation: "/ˌmʌl.tiˈlɪŋ.ɡwəl ˌedʒ.ʊˈkeɪ.ʃən/",
    collocations_cn: ["推广多语言教育", "多语言教育政策", "多语言教育的好处", "实施多语言教育"],
    example_sentence_cn: "多语言教育不仅保护文化遗产，还能增强认知灵活性和学业表现。",
    synonyms_cn: ["双语教育", "多语种教学", "语言多样化教育"],
  },
  {
    id: "edu-086", word: "peer tutoring", translation: "同伴辅导", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 77, topics: ["education"], modules: ["speaking", "listening"],
    collocations: ["participate in peer tutoring", "peer tutoring program", "offer peer tutoring", "peer tutoring session"],
    example_sentence: "Peer tutoring benefits both the tutor and the tutee by reinforcing understanding and building confidence.",
    synonyms: ["student mentoring", "peer-assisted learning", "buddy teaching"],
    common_mistakes: ["tutoring (辅导) 和 mentoring (指导) 不同：前者侧重学业，后者侧重职业发展"],
    ielts_context: "Speaking Part 2: helping others; Listening Section 3: student collaboration",
    pronunciation: "/pɪə ˈtjuː.tər.ɪŋ/",
    collocations_cn: ["参与同伴辅导", "同伴辅导计划", "提供同伴辅导", "同伴辅导课程"],
    example_sentence_cn: "同伴辅导通过加强理解和建立信心，对辅导者和被辅导者都有益。",
    synonyms_cn: ["学生指导", "同伴互助学习", "伙伴教学"],
  },
  {
    id: "edu-087", word: "educational technology", translation: "教育技术", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 86, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["integrate educational technology", "advances in educational technology", "educational technology tools", "use of educational technology"],
    example_sentence: "The integration of educational technology in classrooms has transformed traditional teaching and learning methods.",
    synonyms: ["EdTech", "instructional technology", "learning technology"],
    common_mistakes: ["EdTech 在正式写作中首次提用全称 Educational Technology"],
    ielts_context: "Writing Task 2: technology / education; Reading: EdTech journals",
    pronunciation: "/ˌedʒ.ʊˈkeɪ.ʃən.əl tekˈnɒl.ə.dʒi/",
    collocations_cn: ["整合教育技术", "教育技术的进步", "教育技术工具", "教育技术的使用"],
    example_sentence_cn: "教育技术在课堂中的整合已改变了传统的教学和学习方法。",
    synonyms_cn: ["教育科技", "教学技术", "学习技术"],
  },
  {
    id: "edu-088", word: "school curriculum", translation: "学校课程", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 85, topics: ["education"], modules: ["writing", "speaking"],
    collocations: ["review the school curriculum", "national school curriculum", "broaden the school curriculum", "school curriculum reform"],
    example_sentence: "There is ongoing debate about whether the school curriculum should focus more on practical life skills.",
    synonyms: ["educational program", "course of study", "academic syllabus"],
    common_mistakes: ["school curriculum 前常用 the；curriculum 的复数形式是 curricula 或 curriculums"],
    ielts_context: "Writing Task 2: education policy; Speaking Part 3: school experience",
    pronunciation: "/skuːl kəˈrɪk.jʊ.ləm/",
    collocations_cn: ["审查学校课程", "国家学校课程", "拓宽学校课程", "学校课程改革"],
    example_sentence_cn: "关于学校课程是否应更多地关注实用生活技能，一直存在争议。",
    synonyms_cn: ["教育计划", "课程体系", "教学大纲"],
  },
  // ═══ 中頻 50-69 (12 个) ═══
  {
    id: "edu-089", word: "summative assessment", translation: "终结性评价", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 68, topics: ["education"], modules: ["reading", "writing"],
    collocations: ["conduct summative assessment", "summative assessment results", "summative vs formative assessment", "end-of-term summative assessment"],
    example_sentence: "Summative assessment at the end of a course measures what students have learned against established standards.",
    synonyms: ["final evaluation", "end-point assessment", "cumulative assessment"],
    common_mistakes: ["summative (总结性的) 不是 summer (夏天)；与 formative assessment (形成性评价) 相对"],
    ielts_context: "Reading: education assessment; Writing Task 2: evaluation methods",
    pronunciation: "/səˈmeɪ.tɪv əˈses.mənt/",
    collocations_cn: ["进行终结性评价", "终结性评价结果", "终结性与形成性评价", "期末终结性评价"],
    example_sentence_cn: "课程结束时的终结性评价衡量学生对已学内容的掌握程度是否符合既定标准。",
    synonyms_cn: ["最终评价", "终点评测", "累积性评估"],
  },
  {
    id: "edu-090", word: "plagiarism detection", translation: "抄袭检测", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 65, topics: ["education"], modules: ["reading", "listening"],
    collocations: ["use plagiarism detection software", "plagiarism detection tools", "plagiarism detection system", "automated plagiarism detection"],
    example_sentence: "Most universities now employ sophisticated plagiarism detection software to uphold academic integrity standards.",
    synonyms: ["similarity checking", "originality verification", "academic integrity screening"],
    common_mistakes: ["plagiarism 拼写注意 ia 的顺序；不要说 copy detection"],
    ielts_context: "Reading: university policies; Listening Section 3: academic integrity discussion",
    pronunciation: "/ˈpleɪ.dʒər.ɪ.zəm dɪˈtek.ʃən/",
    collocations_cn: ["使用抄袭检测软件", "抄袭检测工具", "抄袭检测系统", "自动抄袭检测"],
    example_sentence_cn: "大多数大学现在使用先进的抄袭检测软件来维护学术诚信标准。",
    synonyms_cn: ["相似度检查", "原创性验证", "学术诚信筛查"],
  },
  {
    id: "edu-091", word: "extracurricular involvement", translation: "课外活动参与", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 62, topics: ["education"], modules: ["speaking", "writing"],
    collocations: ["encourage extracurricular involvement", "benefits of extracurricular involvement", "level of extracurricular involvement", "active extracurricular involvement"],
    example_sentence: "Employers increasingly value candidates who demonstrate meaningful extracurricular involvement alongside academic qualifications.",
    synonyms: ["co-curricular participation", "after-school engagement", "non-academic involvement"],
    common_mistakes: ["extracurricular 拼写注意：extra + curricular，两个 r"],
    ielts_context: "Speaking Part 2: hobbies / activities; Writing Task 2: holistic education",
    pronunciation: "/ˌek.strə.kəˈrɪk.jʊ.lər ɪnˈvɒlv.mənt/",
    collocations_cn: ["鼓励课外活动参与", "课外活动参与的好处", "课外活动参与度", "积极参与课外活动"],
    example_sentence_cn: "雇主越来越重视那些在学历之外展现出有意义的课外活动参与的候选人。",
    synonyms_cn: ["课外参与", "课后参与", "非学术参与"],
  },
  {
    id: "edu-092", word: "education funding", translation: "教育经费", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 69, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["increase education funding", "cuts to education funding", "public education funding", "allocate education funding"],
    example_sentence: "Adequate education funding is essential for maintaining school facilities, attracting quality teachers, and reducing class sizes.",
    synonyms: ["educational expenditure", "school funding", "education budget"],
    common_mistakes: ["funding 是不可数名词，不说 an education funding"],
    ielts_context: "Writing Task 2: government spending; Reading: education policy",
    pronunciation: "/ˌedʒ.ʊˈkeɪ.ʃən ˈfʌn.dɪŋ/",
    collocations_cn: ["增加教育经费", "削减教育经费", "公共教育经费", "分配教育经费"],
    example_sentence_cn: "充足的教育经费对于维护学校设施、吸引优秀教师和缩小班级规模至关重要。",
    synonyms_cn: ["教育支出", "学校经费", "教育预算"],
  },
  {
    id: "edu-093", word: "academic probation", translation: "学术观察期", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 61, topics: ["education"], modules: ["reading", "listening"],
    collocations: ["academic probation period", "face academic probation", "placed on academic probation", "academic probation warning"],
    example_sentence: "Students who fail to meet the minimum GPA requirement for two consecutive semesters may be placed on academic probation.",
    synonyms: ["scholastic warning", "academic review status", "conditional enrollment"],
    common_mistakes: ["probation 不要拼成 prohbition；此处不是禁止的意思"],
    ielts_context: "Reading: university regulations; Listening Section 3: academic counseling",
    pronunciation: "/ˌæk.əˈdem.ɪk prəˈbeɪ.ʃən/",
    collocations_cn: ["学术观察期", "面临学术观察", "被列入学术观察", "学术观察警告"],
    example_sentence_cn: "连续两个学期未能达到最低绩点要求的学生可能会被列入学术观察期。",
    synonyms_cn: ["学业警告", "学术审查状态", "有条件入学"],
  },
  {
    id: "edu-094", word: "school readiness", translation: "入学准备", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 64, topics: ["education"], modules: ["reading", "speaking"],
    collocations: ["assess school readiness", "promote school readiness", "school readiness skills", "lack of school readiness"],
    example_sentence: "Early childhood programs play a crucial role in developing school readiness skills such as basic literacy and social interaction.",
    synonyms: ["kindergarten readiness", "learning preparedness", "educational readiness"],
    common_mistakes: ["readiness 是 ready 的名词形式，表示准备就绪的状态"],
    ielts_context: "Reading: child development; Speaking Part 3: early education",
    pronunciation: "/skuːl ˈred.i.nəs/",
    collocations_cn: ["评估入学准备", "促进入学准备", "入学准备技能", "缺乏入学准备"],
    example_sentence_cn: "早期儿童项目在培养基本读写能力和社交互动等入学准备技能方面发挥着关键作用。",
    synonyms_cn: ["入学准备度", "学习准备", "教育准备"],
  },
  {
    id: "edu-095", word: "tuition waiver", translation: "学费减免", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 63, topics: ["education"], modules: ["reading", "listening"],
    collocations: ["receive a tuition waiver", "full tuition waiver", "partial tuition waiver", "apply for a tuition waiver"],
    example_sentence: "The university offers full tuition waivers to outstanding students from low-income families.",
    synonyms: ["fee exemption", "tuition remission", "scholarship grant"],
    common_mistakes: ["waiver 表示免除/放弃；不要拼成 waver (摇摆)"],
    ielts_context: "Reading: university financial aid; Listening Section 3: scholarship information",
    pronunciation: "/tjuːˈɪʃ.ən ˈweɪ.vər/",
    collocations_cn: ["获得学费减免", "全额学费减免", "部分学费减免", "申请学费减免"],
    example_sentence_cn: "该大学为来自低收入家庭的优秀学生提供全额学费减免。",
    synonyms_cn: ["费用免除", "学费减免", "奖学金资助"],
  },
  {
    id: "edu-096", word: "field trip", translation: "实地考察", part_of_speech: "noun phrase", band_level: "5.0", frequency_score: 66, topics: ["education"], modules: ["speaking", "listening"],
    collocations: ["go on a field trip", "organize a field trip", "educational field trip", "school field trip"],
    example_sentence: "Field trips to museums and historical sites bring classroom learning to life and deepen students' understanding.",
    synonyms: ["educational excursion", "study tour", "school outing"],
    common_mistakes: ["field trip 两个词分开写，通常指短途教育性质的外出"],
    ielts_context: "Speaking Part 2: memorable school experience; Listening Section 1: school notices",
    pronunciation: "/fiːld trɪp/",
    collocations_cn: ["去实地考察", "组织实地考察", "教育性质的实地考察", "学校实地考察"],
    example_sentence_cn: "参观博物馆和历史遗址的实地考察让课堂学习变得生动，加深了学生的理解。",
    synonyms_cn: ["教育远足", "学习参观", "学校出游"],
  },
  {
    id: "edu-097", word: "homework load", translation: "作业负担", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 67, topics: ["education"], modules: ["speaking", "writing"],
    collocations: ["excessive homework load", "manage homework load", "reduce homework load", "heavy homework load"],
    example_sentence: "Many students complain that an excessive homework load leaves little time for extracurricular activities and family life.",
    synonyms: ["assignment burden", "study workload", "take-home task volume"],
    common_mistakes: ["homework 是不可数名词，不说 homeworks；homework load 是正确表达"],
    ielts_context: "Speaking Part 1: school life; Writing Task 2: education / student well-being",
    pronunciation: "/ˈhəʊm.wɜːk ləʊd/",
    collocations_cn: ["过重的作业负担", "管理作业负担", "减轻作业负担", "沉重的作业负担"],
    example_sentence_cn: "许多学生抱怨过重的作业负担让他们几乎没有时间参加课外活动和享受家庭生活。",
    synonyms_cn: ["作业量", "学习负担", "家庭作业量"],
  },
  {
    id: "edu-098", word: "gap year", translation: "间隔年", part_of_speech: "noun phrase", band_level: "5.5", frequency_score: 68, topics: ["education"], modules: ["speaking", "writing"],
    collocations: ["take a gap year", "gap year experience", "gap year travel", "gap year before university"],
    example_sentence: "Taking a gap year before starting university can provide valuable life experience and clarity about one's career goals.",
    synonyms: ["deferred entry year", "sabbatical year", "bridge year"],
    common_mistakes: ["gap year 特指高中毕业后大学前的一年；sabbatical 指职业生涯中的休假"],
    ielts_context: "Speaking Part 2: life experience; Writing Task 2: education / personal development",
    pronunciation: "/ɡæp jɪər/",
    collocations_cn: ["选择间隔年", "间隔年经历", "间隔年旅行", "上大学前的间隔年"],
    example_sentence_cn: "在开始大学之前选择间隔年可以提供宝贵的生活经历和对职业目标的清晰认识。",
    synonyms_cn: ["延迟入学年", "休假年", "过渡年"],
  },
  {
    id: "edu-099", word: "classroom management", translation: "课堂管理", part_of_speech: "noun phrase", band_level: "6.0", frequency_score: 66, topics: ["education"], modules: ["reading", "writing"],
    collocations: ["effective classroom management", "classroom management strategies", "classroom management skills", "struggle with classroom management"],
    example_sentence: "Effective classroom management is one of the most challenging yet essential skills for new teachers to develop.",
    synonyms: ["classroom discipline", "behavior management", "instructional management"],
    common_mistakes: ["classroom management 不仅指纪律管理，还包括时间管理、教学组织等"],
    ielts_context: "Reading: teaching methodology; Writing Task 2: teacher training",
    pronunciation: "/ˈklɑːs.ruːm ˈmæn.ɪdʒ.mənt/",
    collocations_cn: ["有效的课堂管理", "课堂管理策略", "课堂管理技能", "课堂管理困难"],
    example_sentence_cn: "有效的课堂管理是新教师最具挑战性但也是最需要培养的核心技能之一。",
    synonyms_cn: ["课堂纪律", "行为管理", "教学管理"],
  },
  {
    id: "edu-100", word: "student-centered learning", translation: "以学生为中心的学习", part_of_speech: "noun phrase", band_level: "6.5", frequency_score: 69, topics: ["education"], modules: ["writing", "reading"],
    collocations: ["adopt student-centered learning", "student-centered learning approach", "principles of student-centered learning", "promote student-centered learning"],
    example_sentence: "Student-centered learning shifts the focus from the teacher delivering content to students actively constructing their own understanding.",
    synonyms: ["learner-centered education", "active learning", "personalized instruction"],
    common_mistakes: ["student-centered 有连字符；centered 美式，centred 英式"],
    ielts_context: "Writing Task 2: education methods; Reading: pedagogy research",
    pronunciation: "/ˈstjuː.dənt ˈsen.təd ˈlɜː.nɪŋ/",
    collocations_cn: ["采用以学生为中心的学习", "以学生为中心的学习方法", "以学生为中心的学习原则", "促进以学生为中心的学习"],
    example_sentence_cn: "以学生为中心的学习将焦点从教师传递内容转变为学生主动建构自己的理解。",
    synonyms_cn: ["以学习者为中心的教育", "主动学习", "个性化教学"],
  },
];
