const fs = require("fs");
const path = require("path");

// ── Quality helpers ──────────────────────────────────────────────
function n(id, word, translation, pos, band, freq, modules, collocations, example, synonyms, mistakes, ctx) {
  return { id, word, translation, part_of_speech: pos, band_level: band, frequency_score: freq, modules, collocations, example_sentence: example, synonyms, common_mistakes: mistakes, ielts_context: ctx };
}

// ── Existing 6 chunks (keep exactly as-is) ──────────────────────
const existing = [
  {
    "id": "edu-001",
    "word": "academic performance",
    "translation": "学业表现",
    "part_of_speech": "noun phrase",
    "band_level": "6.0",
    "frequency_score": 95,
    "topics": ["education"],
    "modules": ["writing", "speaking"],
    "collocations": [
      "improve academic performance",
      "outstanding academic performance",
      "decline in academic performance"
    ],
    "example_sentence": "Extracurricular activities can positively influence students' academic performance.",
    "synonyms": ["educational achievement", "scholastic attainment"],
    "common_mistakes": ["不能说 study performance，固定搭配是 academic performance"],
    "ielts_context": "Writing Task 2: education / parenting topics"
  },
  {
    "id": "env-001",
    "word": "environmental protection",
    "translation": "环境保护",
    "part_of_speech": "noun phrase",
    "band_level": "6.0",
    "frequency_score": 96,
    "topics": ["environment"],
    "modules": ["writing", "speaking"],
    "collocations": [
      "environmental protection measures",
      "environmental protection agency",
      "prioritize environmental protection"
    ],
    "example_sentence": "Governments should invest more in environmental protection to combat climate change.",
    "synonyms": ["conservation", "eco-protection", "environmental conservation"],
    "common_mistakes": ["不能说 protect environment，要加 the → protect the environment"],
    "ielts_context": "Writing Task 2: government / environment topics"
  },
  {
    "id": "tech-001",
    "word": "technological advancement",
    "translation": "科技进步",
    "part_of_speech": "noun phrase",
    "band_level": "6.5",
    "frequency_score": 87,
    "topics": ["technology"],
    "modules": ["writing", "speaking"],
    "collocations": [
      "rapid technological advancement",
      "driven by technological advancement",
      "keep pace with technological advancements"
    ],
    "example_sentence": "Technological advancement has transformed the way people communicate and access information.",
    "synonyms": ["technological progress", "technological development"],
    "common_mistakes": ["technology advancement 不如 technological advancement 正式"],
    "ielts_context": "Writing Task 2: technology / society topics"
  },
  {
    "id": "work-001",
    "word": "work-life balance",
    "translation": "工作生活平衡",
    "part_of_speech": "noun phrase",
    "band_level": "6.5",
    "frequency_score": 85,
    "topics": ["work"],
    "modules": ["writing", "speaking"],
    "collocations": [
      "maintain a healthy work-life balance",
      "struggle with work-life balance",
      "achieve better work-life balance"
    ],
    "example_sentence": "Many employees today prioritize work-life balance over higher salaries.",
    "synonyms": ["life-work balance", "work-life equilibrium"],
    "common_mistakes": ["不是 life-work balance，固定语序是 work-life balance"],
    "ielts_context": "Speaking Part 3: work / lifestyle topics; Writing Task 2: employment"
  },
  {
    "id": "health-001",
    "word": "mental well-being",
    "translation": "心理健康",
    "part_of_speech": "noun phrase",
    "band_level": "6.0",
    "frequency_score": 90,
    "topics": ["health"],
    "modules": ["writing", "reading"],
    "collocations": [
      "promote mental well-being",
      "impact on mental well-being",
      "prioritize mental well-being"
    ],
    "example_sentence": "Regular exercise has a significant impact on both physical health and mental well-being.",
    "synonyms": ["psychological well-being", "mental health", "emotional well-being"],
    "common_mistakes": ["mental health 更常用；well-being 注意连字符"],
    "ielts_context": "Writing Task 2: health / lifestyle topics; Reading: health articles"
  },
  {
    "id": "city-001",
    "word": "public transport",
    "translation": "公共交通",
    "part_of_speech": "noun phrase",
    "band_level": "5.5",
    "frequency_score": 89,
    "topics": ["city"],
    "modules": ["speaking", "listening"],
    "collocations": [
      "reliable public transport",
      "invest in public transport",
      "accessible public transport"
    ],
    "example_sentence": "Improving public transport is key to reducing traffic congestion in urban areas.",
    "synonyms": ["public transportation", "mass transit", "public transit"],
    "common_mistakes": ["可数/不可数均可：public transport (UK) = public transportation (US)"],
    "ielts_context": "Speaking Part 1: hometown / transport; Listening Section 1: travel"
  }
];

// ── Education chunks (edu-002 ~ edu-050) ─────────────────────────
const eduChunks = [
  // ═══ 超高頻 90-99 (20 chunks including edu-001) ═══
  n("edu-002","higher education","高等教育","noun phrase","6.0",98,["writing","speaking"],
    ["pursue higher education","access to higher education","higher education institution","cost of higher education"],
    "Higher education plays a crucial role in preparing individuals for the competitive job market.",
    ["tertiary education","university education","post-secondary education"],
    ["higher education 泛指时前面不加 the"],
    "Writing Task 2: education / government spending; Speaking Part 3: education"),
  n("edu-003","critical thinking","批判性思维","noun phrase","6.5",97,["writing","speaking"],
    ["develop critical thinking","foster critical thinking","critical thinking skills","lack of critical thinking"],
    "Schools should focus on developing students' critical thinking rather than encouraging rote memorization.",
    ["analytical thinking","logical reasoning","higher-order thinking"],
    ["不说 criticize thinking，critical thinking 是固定搭配"],
    "Writing Task 2: education methods / curriculum reform"),
  n("edu-004","lifelong learning","终身学习","noun phrase","6.0",95,["writing","speaking"],
    ["promote lifelong learning","embrace lifelong learning","lifelong learning habits","culture of lifelong learning"],
    "In today's rapidly changing job market, lifelong learning has become essential for career advancement.",
    ["continuous learning","ongoing education","lifelong education"],
    ["lifelong 是一个词，不要分开写成 life long"],
    "Writing Task 2: education / employment; Speaking Part 3: career development"),
  n("edu-005","tuition fees","学费","noun phrase","5.5",94,["writing","speaking"],
    ["rising tuition fees","afford tuition fees","tuition fees waiver","cover tuition fees"],
    "Rising tuition fees have made higher education increasingly unaffordable for students from low-income families.",
    ["tuition costs","school fees","educational expenses"],
    ["tuition 本身就有学费的意思，不要说 tuition fee costs"],
    "Writing Task 2: education funding / government policy; Speaking Part 3"),
  n("edu-006","vocational training","职业培训","noun phrase","6.0",93,["writing","speaking"],
    ["provide vocational training","vocational training program","vocational training center","undergo vocational training"],
    "Vocational training equips young people with practical skills that are directly applicable in the workplace.",
    ["career training","technical education","professional training"],
    ["vocational 发音 /vəʊˈkeɪʃənl/，重音在第二个音节"],
    "Writing Task 2: employment / education policy; Speaking Part 3"),
  n("edu-007","compulsory education","义务教育","noun phrase","6.0",92,["writing","speaking"],
    ["compulsory education law","nine-year compulsory education","complete compulsory education","beyond compulsory education"],
    "In most countries, children are legally required to complete at least nine years of compulsory education.",
    ["mandatory education","obligatory schooling","statutory schooling"],
    ["compulsory 是法律强制的，mandatory 更口语化但可互换"],
    "Writing Task 2: government policy / education"),
  n("edu-008","study abroad","留学","verb phrase","5.5",98,["speaking","writing"],
    ["choose to study abroad","study abroad experience","study abroad program","opportunity to study abroad"],
    "Studying abroad exposes students to different cultures and broadens their horizons.",
    ["pursue overseas education","attend foreign universities","international study"],
    ["study abroad 中间没有 in/at，不要说 study in abroad"],
    "Speaking Part 1/2: personal experience; Writing Task 2: education / culture"),
  n("edu-009","extracurricular activities","课外活动","noun phrase","6.0",91,["speaking","writing"],
    ["participate in extracurricular activities","extracurricular activities program","engage in extracurricular activities","variety of extracurricular activities"],
    "Participating in extracurricular activities helps students develop teamwork and leadership skills.",
    ["after-school activities","co-curricular activities","enrichment activities"],
    ["extracurricular 拼写注意：extra + curricular，两个 r"],
    "Writing Task 2: holistic education; Speaking Part 1: school life"),
  n("edu-010","educational system","教育体系","noun phrase","6.0",96,["writing","speaking"],
    ["reform the educational system","educational system faces challenges","flaws in the educational system","outdated educational system"],
    "The educational system should be reformed to meet the demands of the 21st-century economy.",
    ["education system","school system","schooling system"],
    ["educational system 和 education system 可互换，后者更常用"],
    "Writing Task 2: education policy; Speaking Part 3: education"),
  n("edu-011","formal education","正规教育","noun phrase","6.0",99,["writing","speaking"],
    ["complete formal education","access to formal education","formal education system","beyond formal education"],
    "Many successful entrepreneurs achieved remarkable success without completing formal education.",
    ["mainstream education","structured education","institutional education"],
    ["formal education 前面通常不加 the"],
    "Writing Task 2: education / career success; Speaking Part 3"),
  n("edu-012","teaching methodology","教学方法","noun phrase","6.5",92,["writing","reading"],
    ["innovative teaching methodology","traditional teaching methodology","adopt new teaching methodology","effective teaching methodology"],
    "Modern teaching methodology emphasizes student-centered learning over teacher-centered instruction.",
    ["teaching approach","pedagogical method","instructional strategy"],
    ["methodology 强调整套体系，method 指具体方法，不可混用"],
    "Writing Task 2: education reform; Reading: pedagogy articles"),
  n("edu-013","student engagement","学生参与度","noun phrase","6.5",90,["writing","reading"],
    ["increase student engagement","level of student engagement","promote student engagement","measure student engagement"],
    "Interactive teaching methods have been shown to significantly improve student engagement in the classroom.",
    ["student participation","student involvement","learner engagement"],
    ["engagement 是参与/投入，不要说 student engagement rate"],
    "Reading: educational research; Writing Task 2: teaching methods"),
  n("edu-014","learning outcome","学习成果","noun phrase","6.5",93,["writing","reading"],
    ["improve learning outcomes","measure learning outcomes","desired learning outcomes","assess learning outcomes"],
    "Technology in the classroom can enhance learning outcomes when integrated effectively.",
    ["educational outcome","learning result","academic outcome"],
    ["outcome 常用复数 outcomes 更自然"],
    "Writing Task 2: education technology; Reading: academic journals"),
  n("edu-015","academic qualification","学历","noun phrase","6.0",90,["writing","reading"],
    ["obtain academic qualifications","recognized academic qualification","minimum academic qualification","academic qualification requirement"],
    "While academic qualifications are important, employers increasingly value practical experience and soft skills.",
    ["educational credentials","academic degree","formal qualification"],
    ["qualification 表示学历时可数，常用复数 qualifications"],
    "Writing Task 2: job market; Reading: employment / education articles"),
  n("edu-016","education reform","教育改革","noun phrase","6.0",91,["writing","speaking"],
    ["implement education reform","comprehensive education reform","education reform policy","call for education reform"],
    "Education reform is urgently needed to equip students with 21st-century skills such as digital literacy.",
    ["educational reform","school reform","curriculum reform"],
    ["reform 作不可数名词指改革过程；reforms (复数) 指具体改革措施"],
    "Writing Task 2: government policy / education"),
  n("edu-017","peer pressure","同侪压力","noun phrase","6.0",90,["speaking","writing"],
    ["succumb to peer pressure","negative peer pressure","cope with peer pressure","influence of peer pressure"],
    "Teenagers often engage in risky behaviors due to intense peer pressure from their social circles.",
    ["peer influence","social pressure","group pressure"],
    ["peer 指同龄人，不要说 peer's pressure"],
    "Speaking Part 2/3: teenage issues; Writing Task 2: education / parenting"),
  n("edu-018","learning environment","学习环境","noun phrase","6.0",91,["writing","reading"],
    ["conducive learning environment","supportive learning environment","create a positive learning environment","inclusive learning environment"],
    "A supportive learning environment is essential for students to reach their full potential.",
    ["educational environment","study environment","academic setting"],
    ["conducive to learning 固定搭配，介词用 to 不用 for"],
    "Writing Task 2: school infrastructure; Reading: educational psychology"),
  n("edu-019","academic achievement","学业成就","noun phrase","6.0",94,["writing","reading"],
    ["measure academic achievement","improve academic achievement","academic achievement gap","outstanding academic achievement"],
    "Parental involvement plays a crucial role in shaping children's academic achievement.",
    ["educational attainment","scholastic achievement","academic success"],
    ["achievement 作成就时可数也可不可数，看语境"],
    "Writing Task 2: education / parenting; Reading: education studies"),
  n("edu-020","educational opportunity","教育机会","noun phrase","6.0",94,["writing","speaking"],
    ["equal educational opportunity","expand educational opportunities","access to educational opportunities","limited educational opportunity"],
    "Online learning platforms have expanded educational opportunities for students in remote regions.",
    ["learning opportunity","access to education","educational access"],
    ["opportunity 后接 for + noun 或 to + verb，不要混淆"],
    "Writing Task 2: education equality; Speaking Part 3"),
  // ═══ 高頻 70-89 (18 chunks) ═══
  n("edu-021","cognitive development","认知发展","noun phrase","6.5",85,["reading","writing"],
    ["promote cognitive development","cognitive development theory","early cognitive development","stage of cognitive development"],
    "Reading to children from an early age significantly promotes their cognitive development and language skills.",
    ["intellectual development","mental development","cognitive growth"],
    ["cognitive 发音 /ˈkɒɡnɪtɪv/，g 不发音"],
    "Reading: child development articles; Writing Task 2: early education"),
  n("edu-022","rote memorization","死记硬背","noun phrase","6.0",82,["writing","speaking"],
    ["rely on rote memorization","discourage rote memorization","rote memorization approach","beyond rote memorization"],
    "Traditional exam-oriented education often places too much emphasis on rote memorization rather than understanding.",
    ["rote learning","mechanical memorization","learning by heart"],
    ["rote 拼写注意不是 wrote；rote 指机械重复"],
    "Writing Task 2: exam-oriented education; Speaking Part 3: learning styles"),
  n("edu-023","scholarship program","奖学金项目","noun phrase","5.5",80,["reading","listening"],
    ["apply for a scholarship program","award a scholarship program","merit-based scholarship program","fully-funded scholarship program"],
    "The university offers a range of scholarship programs to attract talented international students.",
    ["financial aid program","bursary scheme","grant program","fellowship"],
    ["scholarship 指奖学金，bursary 更多指助学金，不要混淆"],
    "Listening Section 3: campus conversation; Reading: university brochures"),
  n("edu-024","literacy rate","识字率","noun phrase","6.0",83,["writing","reading"],
    ["improve literacy rate","adult literacy rate","high literacy rate","national literacy rate"],
    "Developing countries have made significant progress in improving literacy rates over the past few decades.",
    ["reading proficiency","literate population rate","educational attainment indicator"],
    ["literacy 是不可数名词；表示识字率用 literacy rate"],
    "Writing Task 1/2: development indicators; Reading: social science"),
  n("edu-025","academic integrity","学术诚信","noun phrase","6.5",78,["reading","writing"],
    ["uphold academic integrity","violation of academic integrity","academic integrity policy","maintain academic integrity"],
    "Universities must enforce strict policies to uphold academic integrity and prevent plagiarism.",
    ["intellectual honesty","scholarly integrity","academic honesty"],
    ["integrity 是不可数名词，不用复数形式"],
    "Reading: university policies; Writing Task 2: education standards"),
  n("edu-026","dropout rate","辍学率","noun phrase","5.5",81,["writing","speaking"],
    ["high dropout rate","reduce dropout rate","school dropout rate","college dropout rate"],
    "The high dropout rate in rural areas is primarily caused by poverty and lack of educational resources.",
    ["attrition rate","non-completion rate","withdrawal rate"],
    ["dropout 可以连写也可以写 drop-out，但 drop out 是动词"],
    "Writing Task 1/2: education data; Speaking Part 3: social issues"),
  n("edu-027","educational resources","教育资源","noun phrase","6.0",84,["writing","speaking"],
    ["allocate educational resources","lack of educational resources","equal distribution of educational resources","digital educational resources"],
    "The unequal distribution of educational resources between urban and rural areas remains a pressing issue.",
    ["learning resources","teaching resources","academic resources"],
    ["resources 表示资源时通常用复数"],
    "Writing Task 2: education equality; Speaking Part 3"),
  n("edu-028","classroom interaction","课堂互动","noun phrase","5.5",77,["listening","speaking"],
    ["encourage classroom interaction","facilitate classroom interaction","meaningful classroom interaction","classroom interaction patterns"],
    "Teachers should encourage more classroom interaction to help students develop communication skills.",
    ["classroom participation","student-teacher interaction","class engagement"],
    ["interaction 后可跟 between 或 with，根据语境选择"],
    "Listening Section 3: academic discussion; Speaking Part 2: school experience"),
  n("edu-029","hands-on experience","实践经验","noun phrase","6.0",79,["speaking","writing"],
    ["gain hands-on experience","valuable hands-on experience","provide hands-on experience","practical hands-on experience"],
    "Internships provide students with valuable hands-on experience that cannot be gained in the classroom.",
    ["practical experience","real-world experience","experiential learning"],
    ["hands-on 是形容词，注意连字符；没有连字符的 hands on 是动词短语"],
    "Speaking Part 2: work/study experience; Writing Task 2: education"),
  n("edu-030","standardized testing","标准化考试","noun phrase","6.0",80,["writing","reading"],
    ["rely on standardized testing","criticism of standardized testing","standardized testing system","performance on standardized tests"],
    "Critics argue that standardized testing fails to measure creativity and critical thinking abilities.",
    ["standardized assessment","uniform testing","norm-referenced testing"],
    ["standardized 是美式拼写，英式为 standardised"],
    "Writing Task 2: education assessment; Reading: education policy"),
  n("edu-031","academic research","学术研究","noun phrase","6.0",82,["reading","writing"],
    ["conduct academic research","peer-reviewed academic research","academic research paper","academic research findings"],
    "Government funding for academic research is essential for scientific and technological progress.",
    ["scholarly research","scientific investigation","academic inquiry"],
    ["research 是不可数名词，不说 a research，可说 a piece of research"],
    "Reading: academic journals; Writing Task 2: science / education"),
  n("edu-032","educational background","教育背景","noun phrase","5.5",76,["speaking","listening"],
    ["academic and educational background","diverse educational background","educational background information","regardless of educational background"],
    "Applicants from diverse educational backgrounds bring unique perspectives to the program.",
    ["academic background","educational history","academic upbringing"],
    ["background 在此语境下为可数名词，可以说 different backgrounds"],
    "Speaking Part 2: self-introduction; Listening Section 1: application forms"),
  n("edu-033","tertiary education","高等教育","noun phrase","6.5",84,["writing","reading"],
    ["enroll in tertiary education","access to tertiary education","tertiary education sector","tertiary education institution"],
    "Investing in tertiary education is crucial for a nation's long-term economic competitiveness.",
    ["higher education","post-secondary education","college education"],
    ["tertiary 是正式用词，IELTS Writing 中比 higher education 更正式"],
    "Writing Task 2: education policy; Reading: academic reports"),
  n("edu-034","academic excellence","学术卓越","noun phrase","6.5",75,["reading","writing"],
    ["strive for academic excellence","pursue academic excellence","academic excellence award","standard of academic excellence"],
    "The school has built a reputation for academic excellence over the past three decades.",
    ["scholastic excellence","educational excellence","academic distinction"],
    ["excellence 是不可数名词，不说 an excellence"],
    "Reading: school profiles; Writing Task 2: education quality"),
  n("edu-035","student enrollment","入学人数","noun phrase","5.5",78,["listening","reading"],
    ["increase in student enrollment","declining student enrollment","student enrollment figures","total student enrollment"],
    "The university has seen a steady increase in student enrollment since introducing its online programs.",
    ["student admission","registration numbers","pupil intake"],
    ["enrollment 美式拼写；英式是 enrolment"],
    "Listening Section 3: campus statistics; Reading: university reports"),
  n("edu-036","intellectual development","智力发展","noun phrase","6.5",73,["reading","listening"],
    ["support intellectual development","intellectual development of children","stimulate intellectual development","intellectual development theories"],
    "Play-based learning has been proven to support the intellectual development of young children.",
    ["cognitive development","mental growth","intellectual growth"],
    ["intellectual 作形容词时重音在第三音节 /ˌɪntɪˈlektʃuəl/"],
    "Reading: child psychology; Listening Section 4: education lecture"),
  n("edu-037","academic discipline","学科","noun phrase","6.0",74,["reading","writing"],
    ["core academic discipline","across academic disciplines","various academic disciplines","traditional academic discipline"],
    "Interdisciplinary research that bridges multiple academic disciplines is becoming increasingly common.",
    ["field of study","subject area","scholarly discipline"],
    ["discipline 表示学科；也表示纪律，根据语境区分"],
    "Reading: curriculum documents; Writing Task 2: higher education"),
  n("edu-038","educational attainment","教育程度","noun phrase","6.5",71,["writing","reading"],
    ["level of educational attainment","high educational attainment","educational attainment gap","measure educational attainment"],
    "There is a strong correlation between educational attainment and lifetime earnings.",
    ["educational achievement","academic attainment","education level"],
    ["attainment 常作不可数名词，偶尔可数"],
    "Writing Task 1/2: social data; Reading: sociology articles"),
  // ═══ 中頻 50-69 (12 chunks) ═══
  n("edu-039","learning curve","学习曲线","noun phrase","6.0",68,["speaking","listening"],
    ["steep learning curve","manageable learning curve","learning curve theory","overcome the learning curve"],
    "Learning a new language has a steep learning curve at first, but it becomes easier with consistent practice.",
    ["learning trajectory","skill acquisition rate","adaptation period"],
    ["steep learning curve 表示初始很难学，不是曲线本身陡峭"],
    "Speaking Part 2: learning experience; Listening Section 3: student discussion"),
  n("edu-040","formative assessment","形成性评价","noun phrase","6.5",65,["reading","writing"],
    ["conduct formative assessment","formative assessment strategies","formative vs summative assessment","ongoing formative assessment"],
    "Formative assessment provides continuous feedback that helps students improve throughout the learning process.",
    ["continuous assessment","ongoing evaluation","diagnostic assessment"],
    ["formative 与 summative 相对，前者关注过程，后者关注结果"],
    "Reading: education methodology; Writing Task 2: assessment methods"),
  n("edu-041","educational equity","教育公平","noun phrase","6.5",66,["writing","speaking"],
    ["promote educational equity","ensure educational equity","educational equity policy","issue of educational equity"],
    "Ensuring educational equity remains one of the biggest challenges facing developing nations.",
    ["education equality","equal access to education","fairness in education"],
    ["equity（公平/公正）与 equality（平等）不同；equity 关注结果公平"],
    "Writing Task 2: social justice / education; Speaking Part 3"),
  n("edu-042","boarding school","寄宿学校","noun phrase","5.5",64,["listening","speaking"],
    ["attend a boarding school","boarding school education","traditional boarding school","boarding school experience"],
    "Some parents believe that boarding school education fosters independence and self-discipline in children.",
    ["residential school","dormitory school","live-in school"],
    ["boarding school 是寄宿制学校；boarding pass 是登机牌，不要混淆"],
    "Listening Section 3: student discussion; Speaking Part 1: school life"),
  n("edu-043","self-directed learning","自主学习","noun phrase","6.0",69,["reading","speaking"],
    ["encourage self-directed learning","self-directed learning skills","independent and self-directed learning","promote self-directed learning"],
    "Online courses require strong self-directed learning skills as there is minimal teacher supervision.",
    ["autonomous learning","self-paced study","independent learning"],
    ["self-directed 有连字符，不要写成 self directed"],
    "Reading: education technology; Speaking Part 2: study habits"),
  n("edu-044","intellectual curiosity","求知欲","noun phrase","6.5",62,["reading","speaking"],
    ["spark intellectual curiosity","nurture intellectual curiosity","intellectual curiosity and creativity","natural intellectual curiosity"],
    "Great teachers know how to spark intellectual curiosity in their students through engaging lessons.",
    ["inquisitiveness","thirst for knowledge","curiosity to learn"],
    ["curiosity 是不可数名词，不说 a curiosity（除非表示奇物）"],
    "Reading: education philosophy; Speaking Part 2: teachers"),
  n("edu-045","mixed-ability class","混合能力班","noun phrase","6.0",58,["reading","listening"],
    ["teach a mixed-ability class","mixed-ability class challenges","in a mixed-ability class","manage mixed-ability classes"],
    "Teaching a mixed-ability class requires differentiated instruction to meet every student's needs.",
    ["heterogeneous class","multi-level class","mixed-level group"],
    ["mixed-ability 有连字符；ability 不要拼成 abilty"],
    "Reading: teaching methodology; Listening Section 3: teacher discussion"),
  n("edu-046","academic pressure","学业压力","noun phrase","5.5",67,["speaking","writing"],
    ["intense academic pressure","cope with academic pressure","under academic pressure","mounting academic pressure"],
    "Many students suffer from anxiety and depression due to intense academic pressure from parents and schools.",
    ["study pressure","educational stress","examination pressure"],
    ["pressure 是不可数名词，不说 a pressure"],
    "Speaking Part 2/3: student life; Writing Task 2: education / mental health"),
  n("edu-047","learning disability","学习障碍","noun phrase","6.0",55,["reading","listening"],
    ["diagnosed with a learning disability","students with learning disabilities","specific learning disability","overcome learning disabilities"],
    "Students with learning disabilities require tailored support to succeed in mainstream education.",
    ["learning difficulty","learning disorder","special educational needs"],
    ["disability 可数；learning disability 比 learning difficulty 更正式/医学"],
    "Reading: special education; Listening Section 4: psychology lecture"),
  n("edu-048","educational philosophy","教育理念","noun phrase","6.5",60,["reading","writing"],
    ["educational philosophy emphasizes","progressive educational philosophy","adopt an educational philosophy","traditional educational philosophy"],
    "Montessori's educational philosophy emphasizes hands-on learning and self-directed activity.",
    ["teaching philosophy","pedagogical approach","educational ideology"],
    ["philosophy 在此语境中是可数的，可以说 a philosophy of education"],
    "Reading: education theory; Writing Task 2: education approaches"),
  n("edu-049","academic advisor","学业导师","noun phrase","5.5",63,["listening","speaking"],
    ["meet with an academic advisor","seek advice from an academic advisor","assigned academic advisor","academic advisor appointment"],
    "Students should regularly meet with their academic advisor to discuss their course selection and career plans.",
    ["faculty advisor","tutor","academic counselor","academic mentor"],
    ["advisor 美式拼写；英式为 adviser，IELTS 两种都接受"],
    "Listening Section 3: campus services; Speaking Part 1: university life"),
  n("edu-050","educational subsidy","教育补贴","noun phrase","6.0",57,["writing","reading"],
    ["government educational subsidy","receive an educational subsidy","educational subsidy program","provide educational subsidies"],
    "Government educational subsidies can help bridge the gap between rich and poor students.",
    ["education grant","tuition subsidy","financial aid"],
    ["subsidy 可数，复数 subsidies；注意拼写不是 subside"],
    "Writing Task 2: government spending; Reading: policy reports"),
];

// ── Environment chunks (env-002 ~ env-050) ──────────────────────
const envChunks = [
  // ═══ 超高頻 90-99 (20 chunks including env-001) ═══
  n("env-002","climate change","气候变化","noun phrase","6.0",99,["writing","speaking"],
    ["combat climate change","tackle climate change","impact of climate change","climate change adaptation"],
    "Climate change poses an unprecedented threat to ecosystems and human societies around the world.",
    ["global warming","climatic change","climate crisis"],
    ["climate change 是更综合的说法，global warming 是其中一个方面"],
    "Writing Task 2: environment; Speaking Part 3: global issues"),
  n("env-003","carbon footprint","碳足迹","noun phrase","6.5",96,["writing","speaking"],
    ["reduce carbon footprint","measure carbon footprint","carbon footprint reduction","individual carbon footprint"],
    "Switching to renewable energy sources is one of the most effective ways to reduce our carbon footprint.",
    ["carbon emissions","greenhouse gas emissions","environmental footprint"],
    ["footprint 此处是比喻义，不说 carbon footmark"],
    "Writing Task 2: environment / lifestyle; Speaking Part 3"),
  n("env-004","renewable energy","可再生能源","noun phrase","6.0",97,["writing","speaking"],
    ["invest in renewable energy","renewable energy sources","shift to renewable energy","renewable energy technology"],
    "Governments should provide incentives for businesses to invest in renewable energy sources such as solar and wind power.",
    ["clean energy","green energy","sustainable energy","alternative energy"],
    ["renewable 发音 /rɪˈnjuːəbəl/，注意重音在第二个音节"],
    "Writing Task 2: energy / environment; Speaking Part 3"),
  n("env-005","sustainable development","可持续发展","noun phrase","6.5",98,["writing","speaking"],
    ["achieve sustainable development","promote sustainable development","sustainable development goals","path to sustainable development"],
    "Balancing economic growth with environmental protection is at the heart of sustainable development.",
    ["sustainability","balanced development","green growth"],
    ["sustainable 形容词形式，sustainability 是名词形式，用法不同"],
    "Writing Task 2: economy vs environment; Speaking Part 3"),
  n("env-006","fossil fuels","化石燃料","noun phrase","6.0",95,["writing","speaking"],
    ["dependence on fossil fuels","burning fossil fuels","phase out fossil fuels","reliance on fossil fuels"],
    "Our heavy dependence on fossil fuels is the primary driver of global carbon emissions.",
    ["non-renewable fuels","conventional fuels","hydrocarbon fuels"],
    ["fossil 拼写注意两个 s；fuels 通常用复数"],
    "Writing Task 2: energy policy; Speaking Part 3: environment"),
  n("env-007","greenhouse gas","温室气体","noun phrase","6.0",94,["writing","reading"],
    ["emit greenhouse gases","reduce greenhouse gas emissions","greenhouse gas effect","major greenhouse gas"],
    "Carbon dioxide is the most significant greenhouse gas contributing to global warming.",
    ["heat-trapping gas","atmospheric pollutant","CO2 equivalent"],
    ["greenhouse 是一个词，不要分开写 green house"],
    "Writing Task 2: climate change; Reading: science articles"),
  n("env-008","natural resources","自然资源","noun phrase","6.0",93,["writing","speaking"],
    ["deplete natural resources","conserve natural resources","abundant natural resources","exploit natural resources"],
    "Rapid industrialization has led to the depletion of natural resources at an alarming rate.",
    ["raw materials","natural capital","environmental resources"],
    ["resources 在此语境中总是用复数"],
    "Writing Task 2: development / environment; Speaking Part 3"),
  n("env-009","environmental degradation","环境退化","noun phrase","6.5",91,["writing","reading"],
    ["cause environmental degradation","prevent environmental degradation","severe environmental degradation","combat environmental degradation"],
    "Uncontrolled industrial expansion has resulted in severe environmental degradation in many regions.",
    ["environmental damage","ecological deterioration","environmental deterioration"],
    ["degradation 是不可数名词；恶劣程度用 severe/serious 修饰"],
    "Writing Task 2: industry / environment; Reading: environmental reports"),
  n("env-010","global warming","全球变暖","noun phrase","6.0",97,["writing","speaking"],
    ["contribute to global warming","address global warming","impact of global warming","combat global warming"],
    "The scientific consensus is clear: human activities are the primary cause of global warming.",
    ["climate heating","planetary warming","temperature rise"],
    ["global warming 多用于口语/一般写作；climate change 更学术"],
    "Writing Task 2: environment; Speaking Part 3: climate topics"),
  n("env-011","conservation efforts","保护工作","noun phrase","6.0",90,["writing","speaking"],
    ["support conservation efforts","wildlife conservation efforts","conservation efforts aim to","strengthen conservation efforts"],
    "International cooperation is essential for effective wildlife conservation efforts across national borders.",
    ["preservation initiatives","protection measures","conservation programs"],
    ["conservation 主要指保护自然资源；preservation 侧重维持原始状态"],
    "Writing Task 2: wildlife / environment; Speaking Part 3"),
  n("env-012","ecological balance","生态平衡","noun phrase","6.5",92,["writing","reading"],
    ["maintain ecological balance","disrupt ecological balance","restore ecological balance","delicate ecological balance"],
    "The introduction of invasive species can severely disrupt the ecological balance of an entire ecosystem.",
    ["environmental equilibrium","ecosystem balance","natural balance"],
    ["ecological 是形容词，注意拼写 eco + logical"],
    "Writing Task 2: biodiversity; Reading: ecology articles"),
  n("env-013","deforestation rate","森林砍伐率","noun phrase","6.0",90,["writing","reading"],
    ["alarming deforestation rate","reduce deforestation rate","rapid deforestation rate","slow the deforestation rate"],
    "The alarming deforestation rate in the Amazon rainforest has raised serious concerns worldwide.",
    ["forest clearing rate","rate of forest loss","tree cover loss"],
    ["deforestation 是不可数名词；deforest 是动词形式"],
    "Writing Task 1/2: environmental data; Reading: environmental news"),
  n("env-014","environmental awareness","环保意识","noun phrase","6.0",92,["writing","speaking"],
    ["raise environmental awareness","growing environmental awareness","promote environmental awareness","lack of environmental awareness"],
    "Schools play a vital role in raising environmental awareness among the younger generation.",
    ["eco-consciousness","environmental consciousness","green awareness"],
    ["awareness 是不可数名词，不用复数形式"],
    "Writing Task 2: education / environment; Speaking Part 3"),
  n("env-015","air pollution","空气污染","noun phrase","5.5",94,["speaking","listening"],
    ["combat air pollution","reduce air pollution","severe air pollution","indoor air pollution"],
    "Air pollution in major cities has reached hazardous levels, posing serious health risks to residents.",
    ["atmospheric pollution","smog","air contamination"],
    ["pollution 是不可数名词；specific types 用 air/water/noise pollution"],
    "Speaking Part 3: city life; Listening Section 2: public health announcements"),
  n("env-016","energy consumption","能源消耗","noun phrase","6.0",94,["writing","reading"],
    ["reduce energy consumption","excessive energy consumption","household energy consumption","energy consumption patterns"],
    "Installing smart meters can help households monitor and reduce their energy consumption.",
    ["energy use","power consumption","energy expenditure"],
    ["consumption 是不可数名词；consumer 是消费者，不要混淆"],
    "Writing Task 1/2: energy data; Reading: energy reports"),
  n("env-017","waste disposal","废物处理","noun phrase","5.5",93,["listening","speaking"],
    ["improper waste disposal","waste disposal system","household waste disposal","safe waste disposal"],
    "Improper waste disposal has led to widespread contamination of soil and groundwater in the area.",
    ["garbage disposal","refuse management","waste management"],
    ["disposal 是不可数名词；dispose of 是动词短语"],
    "Listening Section 2: community services; Speaking Part 3"),
  n("env-018","biodiversity loss","生物多样性丧失","noun phrase","6.5",95,["writing","reading"],
    ["halt biodiversity loss","rapid biodiversity loss","cause biodiversity loss","consequences of biodiversity loss"],
    "Habitat destruction is the leading cause of biodiversity loss in tropical regions worldwide.",
    ["species extinction","loss of biodiversity","ecological decline"],
    ["biodiversity 是 bio+ diversity 合成词，不可数"],
    "Writing Task 2: environment / wildlife; Reading: biology articles"),
  n("env-019","eco-friendly","环保的","adjective","5.5",93,["speaking","listening"],
    ["eco-friendly product","eco-friendly alternative","eco-friendly lifestyle","eco-friendly packaging"],
    "Consumers are increasingly choosing eco-friendly products to minimize their environmental impact.",
    ["environmentally friendly","green","sustainable","earth-friendly"],
    ["eco-friendly 有连字符；不要写成 eco friendly"],
    "Speaking Part 3: consumer habits; Listening Section 2: product descriptions"),
  n("env-020","environmental impact","环境影响","noun phrase","6.0",92,["writing","reading"],
    ["assess environmental impact","minimize environmental impact","environmental impact assessment","negative environmental impact"],
    "Companies are now required to conduct environmental impact assessments before starting major projects.",
    ["ecological impact","environmental consequence","environmental effect"],
    ["impact 后接 on；environmental impact on local communities"],
    "Writing Task 2: business / environment; Reading: environmental reports"),
  // ═══ 高頻 70-89 (18 chunks) ═══
  n("env-021","carbon emissions","碳排放","noun phrase","6.0",85,["writing","reading"],
    ["cut carbon emissions","reduce carbon emissions","carbon emissions trading","net-zero carbon emissions"],
    "Many countries have pledged to achieve net-zero carbon emissions by 2050.",
    ["CO2 emissions","greenhouse gas output","carbon output"],
    ["emissions 表示排放物时总是用复数；emission 单数指排放过程"],
    "Writing Task 1/2: climate data; Reading: climate science"),
  n("env-022","water scarcity","水资源短缺","noun phrase","6.0",82,["writing","reading"],
    ["face water scarcity","severe water scarcity","water scarcity issue","address water scarcity"],
    "Water scarcity affects over two billion people worldwide and is expected to worsen with climate change.",
    ["water shortage","water stress","water deficit"],
    ["scarcity 是不可数名词；scarce 是形容词形式"],
    "Writing Task 2: resource management; Reading: global issues"),
  n("env-023","endangered species","濒危物种","noun phrase","6.0",84,["writing","speaking"],
    ["protect endangered species","critically endangered species","endangered species list","habitat of endangered species"],
    "Poaching and habitat loss continue to threaten endangered species such as the giant panda and the snow leopard.",
    ["threatened species","vulnerable species","at-risk species"],
    ["endangered 不用于 very 修饰；说 critically endangered"],
    "Writing Task 2: wildlife conservation; Speaking Part 3: animals"),
  n("env-024","marine ecosystem","海洋生态系统","noun phrase","6.5",76,["reading","listening"],
    ["protect marine ecosystems","threat to marine ecosystems","marine ecosystem health","fragile marine ecosystem"],
    "Plastic pollution poses a growing threat to marine ecosystems and the countless species that depend on them.",
    ["ocean ecosystem","aquatic ecosystem","marine environment"],
    ["marine 发音 /məˈriːn/，注意重音在第二个音节"],
    "Reading: environmental science; Listening Section 4: marine biology"),
  n("env-025","ozone layer","臭氧层","noun phrase","6.0",80,["reading","listening"],
    ["deplete the ozone layer","protect the ozone layer","ozone layer depletion","hole in the ozone layer"],
    "The successful recovery of the ozone layer demonstrates that international cooperation can solve environmental problems.",
    ["ozone shield","stratospheric ozone","atmospheric ozone layer"],
    ["ozone layer 前通常加 the；deplete 表示消耗/枯竭"],
    "Reading: environmental science; Listening Section 4: science lecture"),
  n("env-026","solar energy","太阳能","noun phrase","5.5",86,["speaking","writing"],
    ["harness solar energy","solar energy system","install solar energy panels","solar energy potential"],
    "Solar energy is becoming increasingly affordable and accessible for households in sun-rich regions.",
    ["solar power","sunlight energy","photovoltaic energy"],
    ["solar 表示太阳的；lunar 表示月亮的，不要混淆"],
    "Speaking Part 3: energy / technology; Writing Task 2: renewable energy"),
  n("env-027","environmental policy","环保政策","noun phrase","6.5",78,["writing","reading"],
    ["implement environmental policy","stringent environmental policy","government environmental policy","formulate environmental policy"],
    "Stringent environmental policies have proven effective in reducing industrial pollution in developed nations.",
    ["green policy","environmental regulation","eco-policy"],
    ["policy 可数，复数 policies；表示政策的集合时也可用单数"],
    "Writing Task 2: government; Reading: policy documents"),
  n("env-028","urban sprawl","城市扩张","noun phrase","6.5",74,["writing","reading"],
    ["uncontrolled urban sprawl","limit urban sprawl","urban sprawl contributes to","consequences of urban sprawl"],
    "Uncontrolled urban sprawl has led to the loss of valuable farmland and green spaces around many cities.",
    ["suburban expansion","urban expansion","city sprawl"],
    ["sprawl 是不可数名词；注意拼写不是 sprawl"],
    "Writing Task 2: urbanization; Reading: urban planning articles"),
  n("env-029","ecological footprint","生态足迹","noun phrase","6.5",72,["writing","reading"],
    ["reduce ecological footprint","measure ecological footprint","humanity's ecological footprint","exceed the ecological footprint"],
    "If everyone lived like the average American, we would need five Earths to sustain our ecological footprint.",
    ["environmental footprint","biocapacity demand","earth footprint"],
    ["ecological footprint 是科学术语，和 carbon footprint 不同"],
    "Writing Task 2: sustainability; Reading: environmental economics"),
  n("env-030","industrial pollution","工业污染","noun phrase","5.5",81,["writing","listening"],
    ["reduce industrial pollution","control industrial pollution","sources of industrial pollution","tackle industrial pollution"],
    "Strict regulations have been introduced to control industrial pollution and protect local communities.",
    ["factory emissions","industrial contamination","manufacturing pollution"],
    ["industrial 是形容词 (工业的)；industrious 是勤劳的，完全不同"],
    "Writing Task 2: industry regulation; Listening Section 2: community issues"),
  n("env-031","recycling program","回收计划","noun phrase","5.5",79,["listening","speaking"],
    ["implement a recycling program","participate in recycling programs","community recycling program","effective recycling program"],
    "The city council launched a comprehensive recycling program to reduce the amount of waste sent to landfills.",
    ["waste recovery scheme","reuse initiative","circular economy program"],
    ["recycling 拼写注意，中间有 c 不是 k"],
    "Listening Section 2: community announcements; Speaking Part 1: daily habits"),
  n("env-032","natural habitat","自然栖息地","noun phrase","6.0",83,["reading","writing"],
    ["destroy natural habitats","preserve natural habitats","loss of natural habitat","threatened natural habitat"],
    "Urban expansion continues to encroach upon the natural habitats of many wildlife species.",
    ["native habitat","wildlife habitat","ecological habitat","natural environment"],
    ["habitat 可数，复数 habitats；注意重音在第一个音节"],
    "Reading: wildlife articles; Writing Task 2: conservation"),
  n("env-033","wind power","风力发电","noun phrase","5.5",75,["listening","reading"],
    ["generate wind power","offshore wind power","harness wind power","wind power capacity"],
    "Offshore wind power has emerged as one of the most promising sources of clean energy in Europe.",
    ["wind energy","aeolian energy","wind-generated electricity"],
    ["wind 发音 /wɪnd/，不是 /waɪnd/ (那个是动词缠绕)"],
    "Listening Section 4: renewable energy; Reading: energy technology"),
  n("env-034","greenhouse effect","温室效应","noun phrase","5.5",84,["reading","listening"],
    ["the greenhouse effect causes","enhanced greenhouse effect","natural greenhouse effect","trap heat in the greenhouse effect"],
    "The greenhouse effect is a natural phenomenon, but human activities have intensified it to dangerous levels.",
    ["heat-trapping phenomenon","atmospheric warming process"],
    ["greenhouse 一个词，重音在前面"],
    "Reading: basic science; Listening Section 4: environmental lecture"),
  n("env-035","natural disaster","自然灾害","noun phrase","5.5",77,["speaking","listening"],
    ["devastating natural disaster","prone to natural disasters","cope with natural disasters","frequency of natural disasters"],
    "Climate change has been linked to the increasing frequency and intensity of natural disasters worldwide.",
    ["catastrophic event","environmental disaster","act of nature"],
    ["disaster 可数；natural disaster 前可加 a/an"],
    "Speaking Part 2/3: natural disasters; Listening Section 2: news reports"),
  n("env-036","pollutant emission","污染物排放","noun phrase","6.5",70,["reading","writing"],
    ["reduce pollutant emissions","vehicle pollutant emissions","industrial pollutant emissions","regulate pollutant emissions"],
    "The government has introduced stricter standards to regulate pollutant emissions from factories and vehicles.",
    ["toxic discharge","contaminant release","harmful emission"],
    ["emission 可用单数表示排放过程，复数表示排放物"],
    "Reading: environmental regulations; Writing Task 2: pollution control"),
  n("env-037","environmental sustainability","环境可持续性","noun phrase","6.5",73,["writing","reading"],
    ["achieve environmental sustainability","promote environmental sustainability","ensure environmental sustainability","commitment to environmental sustainability"],
    "Achieving environmental sustainability requires a fundamental shift in how we produce and consume goods.",
    ["ecological sustainability","green sustainability","planetary sustainability"],
    ["sustainability 不可数；sustainable 是形容词，用法不同"],
    "Writing Task 2: sustainability / development; Reading: policy documents"),
  n("env-038","habitat destruction","栖息地破坏","noun phrase","6.0",71,["writing","reading"],
    ["cause habitat destruction","widespread habitat destruction","prevent habitat destruction","rate of habitat destruction"],
    "Habitat destruction due to agriculture and urbanization is the single greatest threat to biodiversity.",
    ["habitat loss","ecosystem destruction","habitat degradation"],
    ["destruction 不可数；动词是 destroy"],
    "Writing Task 2: conservation; Reading: ecology articles"),
  // ═══ 中頻 50-69 (12 chunks) ═══
  n("env-039","carbon neutral","碳中和","adjective","6.5",68,["writing","reading"],
    ["become carbon neutral","carbon neutral by 2050","achieve carbon neutral status","pledge to be carbon neutral"],
    "Several major corporations have pledged to become carbon neutral by 2030 to combat climate change.",
    ["net-zero emissions","climate neutral","carbon zero"],
    ["carbon neutral 是复合形容词，不需要连字符；carbon-neutral 也接受"],
    "Writing Task 2: climate policy; Reading: business news"),
  n("env-040","plastic waste","塑料垃圾","noun phrase","5.5",69,["speaking","listening"],
    ["reduce plastic waste","plastic waste pollution","dispose of plastic waste","plastic waste problem"],
    "Single-use plastic waste has become one of the most visible and pressing environmental issues today.",
    ["plastic pollution","plastic debris","synthetic waste"],
    ["waste 是不可数名词；plastic waste 无复数形式"],
    "Speaking Part 3: environment; Listening Section 2: public campaigns"),
  n("env-041","emission standards","排放标准","noun phrase","6.5",64,["reading","writing"],
    ["meet emission standards","strict emission standards","vehicle emission standards","tighten emission standards"],
    "The government plans to tighten emission standards for all newly registered vehicles from next year.",
    ["pollution limits","discharge regulations","emission limits"],
    ["standards 通常用复数，因为涉及多项标准"],
    "Reading: regulatory documents; Writing Task 2: government policy"),
  n("env-042","organic farming","有机农业","noun phrase","6.0",67,["speaking","reading"],
    ["practice organic farming","organic farming methods","promote organic farming","shift to organic farming"],
    "Organic farming avoids the use of synthetic pesticides and fertilizers, making it more environmentally friendly.",
    ["sustainable agriculture","chemical-free farming","natural farming"],
    ["organic 在不同语境有不同含义，这里指有机/无化学合成"],
    "Speaking Part 3: food / agriculture; Reading: food industry"),
  n("env-043","soil erosion","土壤侵蚀","noun phrase","6.0",61,["reading","listening"],
    ["prevent soil erosion","cause soil erosion","severe soil erosion","soil erosion control"],
    "Deforestation on steep slopes has accelerated soil erosion, reducing the land's agricultural productivity.",
    ["land erosion","topsoil loss","soil degradation"],
    ["erosion 不可数；动词是 erode"],
    "Reading: agriculture / geography; Listening Section 4: environmental lecture"),
  n("env-044","overpopulation","人口过剩","noun phrase","6.0",66,["writing","speaking"],
    ["problem of overpopulation","overpopulation leads to","address overpopulation","burden of overpopulation"],
    "Overpopulation puts tremendous strain on natural resources, infrastructure, and the environment.",
    ["population explosion","overcrowding","excessive population growth"],
    ["overpopulation 不可数；通常不加 the"],
    "Writing Task 2: global issues; Speaking Part 3: social problems"),
  n("env-045","energy efficiency","能源效率","noun phrase","6.0",65,["writing","reading"],
    ["improve energy efficiency","promote energy efficiency","energy efficiency standards","invest in energy efficiency"],
    "Improving energy efficiency in buildings is one of the most cost-effective ways to reduce carbon emissions.",
    ["energy conservation","fuel efficiency","power efficiency"],
    ["efficiency 不可数；efficient 是形容词"],
    "Writing Task 2: energy policy; Reading: technology reports"),
  n("env-046","acid rain","酸雨","noun phrase","5.5",62,["reading","listening"],
    ["caused by acid rain","damage from acid rain","acid rain pollution","effects of acid rain"],
    "Acid rain, primarily caused by industrial emissions, has severely damaged forests and lakes across the region.",
    ["acid precipitation","acid deposition","atmospheric acid"],
    ["acid rain 不可数，前面不用加 an"],
    "Reading: environmental science; Listening Section 4: environmental issues"),
  n("env-047","wildlife corridor","野生动物走廊","noun phrase","6.5",54,["reading","listening"],
    ["establish wildlife corridors","create wildlife corridors","wildlife corridor network","protect wildlife corridors"],
    "Wildlife corridors allow animals to move safely between fragmented habitats, helping maintain genetic diversity.",
    ["ecological corridor","habitat corridor","conservation corridor","green corridor"],
    ["corridor 表示走廊/通道；wildlife corridor 是生态学术语"],
    "Reading: conservation biology; Listening Section 4: ecology lecture"),
  n("env-048","afforestation","植树造林","noun phrase","6.5",56,["reading","writing"],
    ["promote afforestation","afforestation project","afforestation efforts","large-scale afforestation"],
    "Large-scale afforestation projects have been launched to combat desertification in arid regions.",
    ["tree planting","reforestation","forest restoration"],
    ["afforestation 是在无林地上造林；reforestation 是在毁林地上再造林"],
    "Reading: environmental science; Writing Task 2: land management"),
  n("env-049","tidal energy","潮汐能","noun phrase","6.5",52,["reading","listening"],
    ["harness tidal energy","tidal energy project","tidal energy potential","generate tidal energy"],
    "Tidal energy offers a predictable and reliable source of renewable power compared to wind and solar.",
    ["tidal power","wave energy","ocean energy"],
    ["tidal 来自 tide (潮汐)，注意拼写 tidal 不是 tidle"],
    "Reading: renewable energy; Listening Section 4: technology lecture"),
  n("env-050","environmental ethics","环境伦理","noun phrase","6.5",58,["reading","writing"],
    ["principles of environmental ethics","environmental ethics argues","apply environmental ethics","field of environmental ethics"],
    "Environmental ethics challenges the anthropocentric view that nature exists solely for human exploitation.",
    ["ecological ethics","conservation philosophy","green ethics"],
    ["ethics 以 -s 结尾但是单数概念，视为单数"],
    "Reading: philosophy / environment; Writing Task 2: environmental values"),
];

// ── Technology chunks (tech-002 ~ tech-050) ─────────────────────
const techChunks = [
  // ═══ 超高頻 90-99 (20 chunks including tech-001) ═══
  n("tech-002","artificial intelligence","人工智能","noun phrase","6.5",99,["writing","reading"],
    ["develop artificial intelligence","application of artificial intelligence","powered by artificial intelligence","artificial intelligence algorithm"],
    "Artificial intelligence is transforming industries ranging from healthcare to transportation.",
    ["AI","machine intelligence","cognitive computing"],
    ["artificial 拼写注意，两个 i (art + i + ficial)"],
    "Writing Task 2: technology / employment; Reading: technology articles"),
  n("tech-003","social media","社交媒体","noun phrase","5.5",98,["speaking","writing"],
    ["addicted to social media","social media platform","social media influencer","impact of social media"],
    "Social media has fundamentally changed the way people interact and share information.",
    ["social networking sites","online platforms","digital networks"],
    ["media 是复数形式 (单数 medium)，但 social media 后常跟单数动词"],
    "Speaking Part 1/3: technology use; Writing Task 2: society"),
  n("tech-004","digital technology","数字技术","noun phrase","6.0",95,["writing","speaking"],
    ["embrace digital technology","advancement of digital technology","digital technology adoption","impact of digital technology"],
    "Digital technology has revolutionized the way businesses operate and deliver services to customers.",
    ["information technology","digital tools","electronic technology"],
    ["digital 是形容词，digit 是名词 (数字/手指)，不要混淆"],
    "Writing Task 2: technology / business; Speaking Part 3: technology"),
  n("tech-005","online learning","在线学习","noun phrase","5.5",94,["speaking","writing"],
    ["online learning platform","shift to online learning","online learning environment","benefits of online learning"],
    "Online learning has democratized access to education, enabling anyone with internet access to study.",
    ["e-learning","distance education","virtual learning","web-based learning"],
    ["online learning 和 e-learning 可互换，前者更日常，后者更技术化"],
    "Speaking Part 3: education technology; Writing Task 2: education"),
  n("tech-006","information technology","信息技术","noun phrase","6.0",93,["writing","reading"],
    ["information technology sector","develop information technology","information technology infrastructure","information technology specialist"],
    "The information technology sector has been the driving force behind economic growth in many countries.",
    ["IT","computing technology","information systems","digital technology"],
    ["information technology 在正式写作中第一次提用全称，之后可用 IT"],
    "Writing Task 2: economy / technology; Reading: business articles"),
  n("tech-007","screen time","屏幕时间","noun phrase","5.5",90,["speaking","writing"],
    ["limit screen time","excessive screen time","reduce screen time","manage screen time"],
    "Parents are increasingly concerned about the effects of excessive screen time on children's development.",
    ["device usage time","digital exposure","electronic device use"],
    ["screen time 是名词短语，不分开使用；通常作不可数名词"],
    "Speaking Part 3: parenting / technology; Writing Task 2: children"),
  n("tech-008","data privacy","数据隐私","noun phrase","6.5",92,["writing","reading"],
    ["protect data privacy","data privacy concern","data privacy regulation","violation of data privacy"],
    "Stricter data privacy regulations are needed to protect individuals in the digital age.",
    ["information privacy","digital privacy","personal data protection"],
    ["privacy 不可数；private 是形容词，不要写成 data private"],
    "Writing Task 2: technology / law; Reading: technology news"),
  n("tech-009","cutting-edge technology","尖端技术","noun phrase","6.5",90,["writing","reading"],
    ["adopt cutting-edge technology","cutting-edge technology company","access to cutting-edge technology","invest in cutting-edge technology"],
    "The hospital invested in cutting-edge technology to improve patient diagnosis and treatment outcomes.",
    ["state-of-the-art technology","advanced technology","frontier technology","leading-edge technology"],
    ["cutting-edge 带连字符，是复合形容词"],
    "Writing Task 2: innovation / business; Reading: technology reviews"),
  n("tech-010","digital literacy","数字素养","noun phrase","6.5",91,["writing","reading"],
    ["improve digital literacy","digital literacy skills","promote digital literacy","lack of digital literacy"],
    "Digital literacy is now considered as essential as traditional literacy in the modern workforce.",
    ["technological literacy","computer literacy","IT skills","tech proficiency"],
    ["literacy 是不可数名词；表示读写能力或素养"],
    "Writing Task 2: education / technology; Reading: education policy"),
  n("tech-011","technological innovation","技术创新","noun phrase","6.5",91,["writing","reading"],
    ["drive technological innovation","pace of technological innovation","foster technological innovation","technological innovation leads to"],
    "Technological innovation has accelerated at an unprecedented pace over the past two decades.",
    ["tech innovation","scientific advancement","technological breakthrough"],
    ["innovation 可以是可数 (一项创新 innovation) 或不可数 (创新概念)"],
    "Writing Task 2: technology / progress; Reading: technology news"),
  n("tech-012","automation technology","自动化技术","noun phrase","6.0",93,["writing","reading"],
    ["introduce automation technology","displaced by automation technology","industrial automation technology","invest in automation technology"],
    "Automation technology is reshaping the manufacturing sector, boosting efficiency while reducing labor costs.",
    ["robotic technology","mechanized systems","automated technology"],
    ["automation 不可数；automate 是动词，automatic 是形容词"],
    "Writing Task 2: employment / industry; Reading: industry reports"),
  n("tech-013","internet access","互联网接入","noun phrase","5.5",90,["speaking","writing"],
    ["provide internet access","broadband internet access","universal internet access","lack of internet access"],
    "Bridging the digital divide requires providing affordable internet access to underserved communities.",
    ["web access","online access","network connectivity"],
    ["access 是不可数名词，access to the internet 介词用 to"],
    "Speaking Part 3: technology; Writing Task 2: digital divide"),
  n("tech-014","cybersecurity threat","网络安全威胁","noun phrase","6.5",95,["reading","writing"],
    ["protect against cybersecurity threats","growing cybersecurity threat","cybersecurity threat landscape","address cybersecurity threats"],
    "The growing number of cybersecurity threats has forced organizations to invest heavily in digital defenses.",
    ["cyber threat","digital security risk","online security threat"],
    ["cybersecurity 可以连写也可以 cyber security；两种拼写都接受"],
    "Reading: technology security; Writing Task 2: technology risks"),
  n("tech-015","tech giant","科技巨头","noun phrase","5.5",94,["reading","speaking"],
    ["global tech giant","tech giant faces scrutiny","dominated by tech giants","regulate tech giants"],
    "Tech giants such as Google and Apple have accumulated unprecedented market power and influence.",
    ["technology conglomerate","big tech company","tech behemoth"],
    ["giant 此处是名词；也可作形容词 (giant corporation)"],
    "Reading: business news; Speaking Part 3: companies"),
  n("tech-016","digital revolution","数字革命","noun phrase","6.5",92,["writing","reading"],
    ["sparked a digital revolution","digital revolution has transformed","era of digital revolution","impact of the digital revolution"],
    "The digital revolution has fundamentally changed how we work, communicate, and access information.",
    ["information revolution","tech revolution","digital transformation"],
    ["revolution 前可加冠词 a/the，根据语境选择"],
    "Writing Task 2: technology / society; Reading: technology history"),
  n("tech-017","big data analytics","大数据分析","noun phrase","6.5",96,["reading","writing"],
    ["leverage big data analytics","big data analytics tools","apply big data analytics","big data analytics platform"],
    "Big data analytics enables companies to understand customer behavior and make data-driven decisions.",
    ["large-scale data analysis","data mining","predictive analytics"],
    ["data 严格来说是复数 (datum 的复数)，但现代英语常用作不可数单数"],
    "Reading: business technology; Writing Task 2: data / business"),
  n("tech-018","the internet of things","物联网","noun phrase","6.5",80,["reading","listening"],
    ["the internet of things enables","internet of things devices","internet of things technology","rise of the internet of things"],
    "The Internet of Things connects everyday devices to the internet, enabling smarter homes and cities.",
    ["IoT","connected devices","smart network","ambient computing"],
    ["此短语前面通常有 the；正式写作首次提用全称后可用 IoT"],
    "Reading: technology trends; Listening Section 4: technology lectures"),
  n("tech-019","remote working","远程办公","noun phrase","6.0",94,["speaking","writing"],
    ["embrace remote working","remote working arrangement","shift to remote working","remote working technology"],
    "Remote working has become a permanent fixture in many industries following the global pandemic.",
    ["telecommuting","working from home","distributed work","flexible working"],
    ["remote working 和 working remotely 都正确，前者是名词短语"],
    "Speaking Part 3: work / technology; Writing Task 2: employment"),
  n("tech-020","wearable device","可穿戴设备","noun phrase","5.5",78,["reading","listening"],
    ["wearable device market","smart wearable device","health-related wearable device","adopt wearable devices"],
    "Wearable devices such as smartwatches can monitor health indicators like heart rate and sleep patterns.",
    ["wearable technology","smart accessory","body-borne device"],
    ["wearable 是形容词，也可作名词 (复数 wearables)"],
    "Reading: technology reviews; Listening Section 2: product descriptions"),
  // ═══ 高頻 70-89 (18 chunks) ═══
  n("tech-021","digital divide","数字鸿沟","noun phrase","6.5",79,["writing","speaking"],
    ["bridge the digital divide","widen the digital divide","digital divide between","narrow the digital divide"],
    "Governments must take steps to bridge the digital divide between urban and rural communities.",
    ["technological gap","information gap","digital inequality","connectivity divide"],
    ["divide 在此是名词 (鸿沟)，不是动词"],
    "Writing Task 2: technology / inequality; Speaking Part 3: society"),
  n("tech-022","electronic commerce","电子商务","noun phrase","6.0",77,["reading","writing"],
    ["electronic commerce platform","growth of electronic commerce","electronic commerce sector","cross-border electronic commerce"],
    "Electronic commerce has reshaped the retail industry by allowing businesses to reach global markets.",
    ["e-commerce","online retail","digital commerce","internet shopping"],
    ["electronic commerce 在正式写作中用全称，日常写作可用 e-commerce"],
    "Reading: business articles; Writing Task 2: economy / technology"),
  n("tech-023","genetic engineering","基因工程","noun phrase","6.5",76,["reading","writing"],
    ["advancements in genetic engineering","genetic engineering technology","concerns about genetic engineering","field of genetic engineering"],
    "Genetic engineering has opened up new possibilities in medicine, but it also raises ethical concerns.",
    ["gene modification","genetic modification","biotechnology intervention"],
    ["genetic 是形容词 (基因的)；generic 是通用的/一般的，完全不同"],
    "Reading: science articles; Writing Task 2: science ethics"),
  n("tech-024","smartphone addiction","手机沉迷","noun phrase","5.5",91,["speaking","writing"],
    ["suffer from smartphone addiction","combat smartphone addiction","overcome smartphone addiction","signs of smartphone addiction"],
    "Smartphone addiction among teenagers has become a growing concern for parents and educators worldwide.",
    ["phone dependency","mobile device addiction","digital dependency"],
    ["addiction 后接 to；addiction to smartphones"],
    "Speaking Part 3: technology / health; Writing Task 2: technology / society"),
  n("tech-025","algorithm recommendation","算法推荐","noun phrase","6.5",74,["reading","writing"],
    ["powered by algorithm recommendation","algorithm recommendation system","personalized algorithm recommendation","algorithm recommendation engine"],
    "Algorithm recommendation systems have raised concerns about echo chambers and information bias.",
    ["algorithmic suggestions","automated recommendation","machine-learning recommendations"],
    ["algorithm 发音 /ˈælɡərɪðəm/，注意和 logarithm (对数) 区分"],
    "Reading: technology analysis; Writing Task 2: AI / social media"),
  n("tech-026","cloud computing","云计算","noun phrase","6.0",91,["reading","writing"],
    ["adopt cloud computing","cloud computing services","cloud computing platform","shift to cloud computing"],
    "Cloud computing allows businesses to access powerful computing resources without investing in expensive hardware.",
    ["cloud services","distributed computing","remote server technology"],
    ["cloud 在这里是比喻义，不是气象学意义上的云"],
    "Reading: technology news; Writing Task 2: business technology"),
  n("tech-027","video conferencing","视频会议","noun phrase","5.5",92,["speaking","listening"],
    ["participate in video conferencing","video conferencing tool","video conferencing software","via video conferencing"],
    "Video conferencing has become an indispensable tool for remote collaboration in the modern workplace.",
    ["video call","virtual meeting","online conferencing","teleconferencing"],
    ["conferencing 不可数；注意重音在第一个音节"],
    "Speaking Part 3: work; Listening Section 1/2: business context"),
  n("tech-028","quantum computing","量子计算","noun phrase","6.5",70,["reading","listening"],
    ["develop quantum computing","quantum computing technology","potential of quantum computing","quantum computing breakthroughs"],
    "Quantum computing has the potential to solve complex problems that are beyond the reach of conventional computers.",
    ["quantum computation","quantum information processing","quantum technology"],
    ["quantum 发音 /ˈkwɒntəm/，复数 quanta，但在 computing 前不变"],
    "Reading: advanced technology; Listening Section 4: science lecture"),
  n("tech-029","gig economy","零工经济","noun phrase","6.0",75,["speaking","writing"],
    ["participate in the gig economy","rise of the gig economy","gig economy worker","platform-based gig economy"],
    "The gig economy offers flexibility but often lacks the job security and benefits of traditional employment.",
    ["freelance economy","on-demand economy","sharing economy","platform economy"],
    ["gig 原意是演出，现引申为零工；the gig economy 前通常加 the"],
    "Speaking Part 3: work trends; Writing Task 2: employment"),
  n("tech-030","patent protection","专利保护","noun phrase","6.5",68,["reading","writing"],
    ["seek patent protection","intellectual property and patent protection","patent protection laws","adequate patent protection"],
    "Strong patent protection is essential for encouraging innovation and rewarding research and development.",
    ["intellectual property right","patent safeguard","invention protection"],
    ["patent 发音 /ˈpeɪtənt/ 或 /ˈpætənt/，两种英式发音均接受"],
    "Reading: business law; Writing Task 2: innovation policy"),
  n("tech-031","data breach","数据泄露","noun phrase","6.0",72,["reading","listening"],
    ["suffer a data breach","major data breach","prevent data breaches","data breach incident"],
    "The company faced severe criticism and legal action following the massive data breach affecting millions of users.",
    ["data leak","security breach","information leak","privacy violation"],
    ["breach 不是 beach (海滩)；breach 表示违反/突破/泄露"],
    "Reading: cybersecurity news; Listening Section 3: business discussion"),
  n("tech-032","social networking","社交网络","noun phrase","5.5",78,["speaking","writing"],
    ["social networking site","online social networking","social networking platform","impact of social networking"],
    "Social networking has fundamentally altered patterns of human interaction and community formation.",
    ["social media networking","online networking","digital socializing"],
    ["networking 是动名词形式；network 是名词/动词形式"],
    "Speaking Part 3: social media; Writing Task 2: technology / relationships"),
  n("tech-033","telemedicine service","远程医疗服务","noun phrase","6.5",70,["reading","listening"],
    ["access telemedicine services","telemedicine service platform","provide telemedicine services","telemedicine service delivery"],
    "Telemedicine services have greatly improved healthcare access for patients in rural and remote areas.",
    ["remote healthcare","virtual consultation","e-health service","digital healthcare"],
    ["telemedicine 前缀 tele- 表示远距离，和 television/telescope 一样"],
    "Reading: healthcare technology; Listening Section 3: healthcare discussion"),
  n("tech-034","virtual reality","虚拟现实","noun phrase","6.0",73,["reading","listening"],
    ["virtual reality technology","immersive virtual reality","virtual reality application","virtual reality headset"],
    "Virtual reality is being used increasingly in education to create immersive learning experiences.",
    ["VR","immersive technology","simulated environment","artificial reality"],
    ["virtual 表示虚拟的/模拟的，和 actual 相对，不是美德的意思"],
    "Reading: technology reviews; Listening Section 4: technology trends"),
  n("tech-035","digital payment","数字支付","noun phrase","5.5",76,["speaking","listening"],
    ["digital payment system","adopt digital payments","digital payment platform","convenience of digital payments"],
    "Digital payment systems have made financial transactions faster, safer, and more convenient than cash.",
    ["electronic payment","mobile payment","cashless payment","online transaction"],
    ["payment 是可数名词 (一笔支付) 也能作不可数 (支付概念)"],
    "Speaking Part 1/2: daily life; Listening Section 1: transactions"),
  n("tech-036","innovation hub","创新中心","noun phrase","6.0",67,["reading","listening"],
    ["global innovation hub","establish an innovation hub","technology and innovation hub","serve as an innovation hub"],
    "Silicon Valley remains the world's most prominent innovation hub for technology startups.",
    ["tech hub","innovation center","technology cluster","startup ecosystem"],
    ["hub 原意是轮毂，引申为中心/枢纽"],
    "Reading: business articles; Listening Section 3: business discussion"),
  n("tech-037","technology sector","科技行业","noun phrase","6.0",71,["writing","reading"],
    ["booming technology sector","work in the technology sector","technology sector growth","dominate the technology sector"],
    "The technology sector continues to attract the largest share of venture capital investment globally.",
    ["tech industry","IT sector","high-tech sector","technology industry"],
    ["sector 可数；注意和 section (部分/章节) 区分"],
    "Writing Task 2: employment / economy; Reading: business news"),
  n("tech-038","scientific breakthrough","科学突破","noun phrase","6.0",74,["writing","reading"],
    ["major scientific breakthrough","achieve a scientific breakthrough","transformative scientific breakthrough","announce a scientific breakthrough"],
    "The discovery of the CRISPR gene-editing tool is considered one of the most significant scientific breakthroughs of this century.",
    ["research breakthrough","technological breakthrough","major advance","scientific discovery"],
    ["breakthrough 可数；through 不是 though"],
    "Writing Task 2: science / progress; Reading: science journals"),
  // ═══ 中頻 50-69 (12 chunks) ═══
  n("tech-039","cryptocurrency","加密货币","noun phrase","6.5",72,["reading","listening"],
    ["invest in cryptocurrency","cryptocurrency market","cryptocurrency exchange","rise of cryptocurrency"],
    "Cryptocurrency has sparked debate about the future of money and the role of central banks.",
    ["digital currency","virtual currency","decentralized currency","crypto"],
    ["cryptocurrency 可数/不可数均可；crypto- 前缀表示隐藏/加密"],
    "Reading: finance technology; Listening Section 3: finance discussion"),
  n("tech-040","intellectual property","知识产权","noun phrase","6.5",66,["writing","reading"],
    ["protect intellectual property","intellectual property rights","intellectual property law","violate intellectual property"],
    "Protecting intellectual property is essential for encouraging creativity and innovation in the digital age.",
    ["IP","creative rights","proprietary knowledge","copyright and patent"],
    ["property 不可数；intellectual property 也不可数"],
    "Writing Task 2: law / innovation; Reading: legal documents"),
  n("tech-041","tech startup","科技创业公司","noun phrase","5.5",64,["reading","speaking"],
    ["found a tech startup","tech startup ecosystem","promising tech startup","invest in tech startups"],
    "The city has become a thriving hub for tech startups thanks to its supportive regulatory environment.",
    ["technology startup","tech venture","emerging tech company"],
    ["startup 可连写也可 start-up，tech startup 更常用连写形式"],
    "Reading: business news; Speaking Part 2: career"),
  n("tech-042","algorithmic bias","算法偏见","noun phrase","6.5",58,["reading","writing"],
    ["address algorithmic bias","algorithmic bias in AI","detect algorithmic bias","concerns about algorithmic bias"],
    "Algorithmic bias in hiring tools can perpetuate discrimination against certain demographic groups.",
    ["AI bias","machine bias","data-driven discrimination","computational bias"],
    ["bias 可数/不可数均可；algorithmic 是 algorithm 的形容词形式"],
    "Reading: AI ethics; Writing Task 2: technology / ethics"),
  n("tech-043","digital infrastructure","数字基础设施","noun phrase","6.5",62,["writing","reading"],
    ["build digital infrastructure","lack of digital infrastructure","invest in digital infrastructure","robust digital infrastructure"],
    "Developing countries need to invest in digital infrastructure to participate fully in the global economy.",
    ["technological infrastructure","IT infrastructure","network infrastructure","cyber infrastructure"],
    ["infrastructure 不可数；通常用单数形式"],
    "Writing Task 2: development / technology; Reading: policy documents"),
  n("tech-044","space exploration","太空探索","noun phrase","6.0",60,["reading","listening"],
    ["advance space exploration","fund space exploration","space exploration mission","future of space exploration"],
    "Private companies are now playing an increasingly important role in space exploration.",
    ["cosmic exploration","interstellar exploration","space research","astronautics"],
    ["exploration 不可数；explore 是动词，explorer 是探索者"],
    "Reading: science articles; Listening Section 4: astronomy lecture"),
  n("tech-045","technology addiction","科技成瘾","noun phrase","5.5",71,["speaking","writing"],
    ["suffer from technology addiction","overcome technology addiction","technology addiction among youth","impact of technology addiction"],
    "Technology addiction is increasingly recognized as a legitimate mental health concern requiring treatment.",
    ["digital addiction","tech dependency","internet addiction","screen addiction"],
    ["addiction to technology，介词用 to 不是 of"],
    "Speaking Part 3: technology / health; Writing Task 2: technology / society"),
  n("tech-046","facial recognition","面部识别","noun phrase","6.5",63,["reading","writing"],
    ["facial recognition technology","use facial recognition","facial recognition system","deploy facial recognition"],
    "The use of facial recognition technology in public spaces has sparked intense debate about privacy and civil liberties.",
    ["face recognition","biometric identification","face detection technology"],
    ["facial 是 face 的形容词形式，不是 familiar 的缩写"],
    "Reading: technology / privacy; Writing Task 2: surveillance / privacy"),
  n("tech-047","open source software","开源软件","noun phrase","6.0",57,["reading","listening"],
    ["develop open source software","open source software community","contribute to open source software","adopt open source software"],
    "Open source software has driven innovation by allowing developers worldwide to collaborate and build upon existing code.",
    ["free software","community-developed software","public-source software","OSS"],
    ["open source 作为形容词有连字符 open-source；作名词无连字符"],
    "Reading: technology development; Listening Section 3: IT discussion"),
  n("tech-048","hybrid work model","混合办公模式","noun phrase","6.0",61,["speaking","writing"],
    ["adopt a hybrid work model","hybrid work model benefits","implement a hybrid work model","shift to hybrid work models"],
    "Many companies have adopted a hybrid work model that combines remote and in-office work.",
    ["flexible work arrangement","blended work model","mixed-mode working","hybrid workplace model"],
    ["hybrid 发音 /ˈhaɪbrɪd/，不是 high-brid"],
    "Speaking Part 3: work trends; Writing Task 2: future of work"),
  n("tech-049","3D printing technology","3D打印技术","noun phrase","6.0",55,["reading","listening"],
    ["advance 3D printing technology","3D printing technology enables","adopt 3D printing technology","applications of 3D printing technology"],
    "3D printing technology is revolutionizing manufacturing by enabling rapid prototyping and customized production.",
    ["additive manufacturing","three-dimensional printing","rapid prototyping technology"],
    ["3D 中的 D 大写；发音 three-dimensional"],
    "Reading: manufacturing technology; Listening Section 4: engineering lecture"),
  n("tech-050","information overload","信息过载","noun phrase","6.0",59,["writing","speaking"],
    ["suffer from information overload","cope with information overload","digital age information overload","impact of information overload"],
    "Information overload in the digital age can lead to reduced productivity and increased stress levels.",
    ["data deluge","information glut","cognitive overload","content saturation"],
    ["overload 不可数；是 over + load 复合词"],
    "Writing Task 2: technology / society; Speaking Part 3: modern life"),
];

// ── Assemble and write ───────────────────────────────────────────

const allChunks = [
  // Education section
  ...existing.filter(c => c.id === "edu-001").map(c => ({ ...c, topics: ["education"] })),
  ...eduChunks.map(c => ({ ...c, topics: ["education"] })),

  // Environment section
  ...existing.filter(c => c.id === "env-001").map(c => ({ ...c, topics: ["environment"] })),
  ...envChunks.map(c => ({ ...c, topics: ["environment"] })),

  // Technology section
  ...existing.filter(c => c.id === "tech-001").map(c => ({ ...c, topics: ["technology"] })),
  ...techChunks.map(c => ({ ...c, topics: ["technology"] })),

  // Legacy chunks kept at the end
  ...existing.filter(c => !["edu-001","env-001","tech-001"].includes(c.id)),
];

// ── Validation ───────────────────────────────────────────────────
function validate(chunks) {
  const errors = [];
  const ids = chunks.map(c => c.id);

  // Check total count
  const expected = 153;
  if (chunks.length !== expected) {
    errors.push(`Expected ${expected} chunks, got ${chunks.length}`);
  }

  // Check unique IDs
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length > 0) {
    errors.push(`Duplicate IDs: ${[...new Set(dupes)].join(", ")}`);
  }

  // Check ID format
  for (const c of chunks) {
    if (!/^(edu|env|tech|work|health|city)-\d{3}$/.test(c.id)) {
      errors.push(`Invalid ID format: ${c.id}`);
    }
  }

  // Check required fields
  const required = ["id","word","translation","part_of_speech","band_level","frequency_score","topics","modules","collocations","example_sentence","synonyms","common_mistakes","ielts_context"];
  for (const c of chunks) {
    for (const f of required) {
      if (!(f in c)) errors.push(`Missing field "${f}" in ${c.id}`);
    }
  }

  // Frequency distribution per topic
  for (const topic of ["education","environment","technology"]) {
    const topicChunks = chunks.filter(c => c.topics.includes(topic));
    if (topicChunks.length !== 50) {
      errors.push(`${topic}: expected 50 chunks, got ${topicChunks.length}`);
    }
    const ultra = topicChunks.filter(c => c.frequency_score >= 90).length;
    const high = topicChunks.filter(c => c.frequency_score >= 70 && c.frequency_score < 90).length;
    const mid = topicChunks.filter(c => c.frequency_score >= 50 && c.frequency_score < 70).length;
    if (ultra !== 20) errors.push(`${topic}: expected 20 ultra-high (90-99), got ${ultra}`);
    if (high !== 18) errors.push(`${topic}: expected 18 high (70-89), got ${high}`);
    if (mid !== 12) errors.push(`${topic}: expected 12 medium (50-69), got ${mid}`);
  }

  // Collocations count
  for (const c of chunks) {
    if (c.collocations.length < 3) {
      errors.push(`${c.id}: need at least 3 collocations, got ${c.collocations.length}`);
    }
  }

  // Synonyms count
  for (const c of chunks) {
    if (c.synonyms.length < 2) {
      errors.push(`${c.id}: need at least 2 synonyms, got ${c.synonyms.length}`);
    }
  }

  return errors;
}

// ── Write ────────────────────────────────────────────────────────
const errors = validate(allChunks);
if (errors.length > 0) {
  console.error("VALIDATION ERRORS:");
  for (const e of errors) console.error("  - " + e);
  process.exit(1);
}

const outPath = path.join(__dirname, "..", "data", "chunks.json");
fs.writeFileSync(outPath, JSON.stringify(allChunks, null, 2), "utf-8");
console.log(`Written ${allChunks.length} chunks to ${outPath}`);
console.log("Validation passed!");

// Distribution summary
for (const topic of ["education","environment","technology"]) {
  const tc = allChunks.filter(c => c.topics.includes(topic));
  const ultra = tc.filter(c => c.frequency_score >= 90).length;
  const high = tc.filter(c => c.frequency_score >= 70 && c.frequency_score < 90).length;
  const mid = tc.filter(c => c.frequency_score >= 50 && c.frequency_score < 70).length;
  console.log(`${topic}: ${tc.length} chunks | ultra=${ultra} high=${high} mid=${mid}`);
}
